/* C-backed EVM memory for the evm-sail model.
 *
 * Sail forbids recursive types, so an in-model balanced tree is impossible and a
 * list-backed memory is O(n) per access (O(n^2) over a fill/copy loop). Following
 * revm's SharedMemory, memory lives in C as ONE arena with per-frame
 * checkpoints: frame d owns arena[f_base[d] ..), and a sub-call's frame begins
 * where the (suspended) caller's ESTABLISHED extent ends. Offsets -- never
 * pointers -- identify bytes, so arena growth cannot dangle, and any suspended
 * frame's range is addressable as a plain (base + off) slice.
 *
 * Establishment discipline (no zeroing on frame exit): f_len[d] is the extent
 * the frame has WRITTEN OR ZEROED. Reads beyond it return 0; any write or
 * region grant that extends it first zero-fills the gap, so a dead child's
 * bytes (which live above the parent's extent) can never be observed.
 * mem_frame_leave just pops the checkpoint. The canonical generated-C ABI
 * carries mathematical byte quantities; the production ABI represents the
 * protocol-bounded values directly as uint64_t. */
#include "sail.h"
#include "value_convert.h"
#include "byte_slice_glue.h"
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

#define MEMORY_MAXDEPTH 1100 /* DEPTH_LIMIT(1024) + tx frame + slack */

static uint8_t *arena;
static size_t arena_cap;
static size_t f_base[MEMORY_MAXDEPTH];
static size_t f_len[MEMORY_MAXDEPTH]; /* established (written-or-zeroed) extent */
static int h_top = 0;

static void arena_reserve(size_t need) {
  if (need <= arena_cap) return;
  size_t ncap = arena_cap ? arena_cap : 4096;
  while (ncap < need) {
    if (ncap > SIZE_MAX / 2) {
      ncap = need;
      break;
    }
    ncap <<= 1;
  }
  uint8_t *nb = (uint8_t *)realloc(arena, ncap);
  if (!nb) abort();
  arena = nb;
  arena_cap = ncap;
}

/* extend the current frame's established extent to `end` (frame-relative),
 * zero-filling the gap. Sail has already established and charged the range;
 * a failure here is a host-contract violation rather than EVM OutOfGas. */
static void f_establish(uint64_t end) {
  if (end <= f_len[h_top]) return;
  size_t base = f_base[h_top];
  if (end > SIZE_MAX || base > SIZE_MAX - (size_t)end) abort();
  arena_reserve(base + (size_t)end);
  memset(arena + base + f_len[h_top], 0, (size_t)end - f_len[h_top]);
  f_len[h_top] = (size_t)end;
}

static uint8_t *frame_write_region(uint64_t off, uint64_t len);

/* clear back to a single empty top-level frame (called per tx); the arena
 * allocation is kept for reuse across transactions */
unit mem_clear(const unit u) {
  (void)u;
  h_top = 0;
  f_base[0] = 0;
  f_len[0] = 0;
  return UNIT;
}

/* Enter a sub-call and return the fresh frame's absolute arena base. Sail
 * stores that base in the active frame's EvmMemorySource ByteSlice. */
static uint64_t mem_frame_enter_value(void) {
  /* The EVM call-depth rule makes this host-capacity failure unreachable. */
  if (h_top + 1 >= MEMORY_MAXDEPTH) abort();
  h_top++;
  f_base[h_top] = f_base[h_top - 1] + f_len[h_top - 1];
  f_len[h_top] = 0;
  return (uint64_t)f_base[h_top];
}

#ifdef EVMSAIL_STANDARD_ABI
void mem_frame_enter(sail_int *out, const unit u) {
  (void)u;
  evmsail_byte_quantity_set(out, mem_frame_enter_value());
}
#else
uint64_t mem_frame_enter(const unit u) {
  (void)u;
  return mem_frame_enter_value();
}
#endif

/* leave a sub-call: pop the checkpoint. The dead frame's bytes sit above the
 * parent's established extent, so establishment zero-fills over them before
 * the parent could ever read them. */
unit mem_frame_leave(const unit u) {
  (void)u;
  if (h_top > 0) h_top--;
  return UNIT;
}

/* byte-quantity offset -> bits(8) byte (0 beyond the established extent) */
uint64_t mem_read_byte(EVMSAIL_BYTE_QUANTITY_PARAM(off)) {
  uint64_t offset = evmsail_byte_quantity_value(off);
  return (offset < f_len[h_top])
             ? (uint64_t)arena[f_base[h_top] + offset]
             : 0;
}

/* Current call-frame depth. */
uint64_t hm_depth(const unit u) { (void)u; return (uint64_t)h_top; }

/* Materialize the logical extent whose affordability Sail already proved and
 * return its absolute arena base. byte_slice_glue.c packages this span in the
 * generated ByteSlice representation. */
uint64_t evm_memory_expand(uint64_t len) {
  f_establish(len);
  return (uint64_t)f_base[h_top];
}

/* establish + a WRITE pointer to [off, off+len) of the current frame (the
 * gas-side watermark is raised by charge_expansion before any copy opcode
 * writes) */
static uint8_t *frame_write_region(uint64_t off, uint64_t len) {
  if (len == 0) return NULL;
  if (off > UINT64_MAX - len) abort();
  f_establish(off + len);
  return arena + f_base[h_top] + off;
}

/* MLOAD: the 32-byte big-endian word at off. No establishment -- reads past
 * the extent are zeros, and charge_expansion precedes every MLOAD so the
 * gas-side watermark already covers the range. */
EVMSAIL_WORD_RETURN mem_load_word(EVMSAIL_WORD_RESULT(result)
                                  EVMSAIL_BYTE_QUANTITY_PARAM(off)) {
  uint64_t offset = evmsail_byte_quantity_value(off);
  uint8_t buf[32];
  for (int i = 0; i < 32; i++) {
    uint64_t o = offset + (uint64_t)i;
    buf[i] = (o >= offset && o < f_len[h_top])
                 ? arena[f_base[h_top] + o]
                 : 0;
  }
  EVMSAIL_RETURN_WORD(result, be_bytes_to_sail_word(buf));
}

/* MSTORE: the 32-byte big-endian word at off (establish + one memcpy) */
unit mem_store_word(EVMSAIL_BYTE_QUANTITY_PARAM(off), EVMSAIL_WORD_PARAM(w)) {
  uint8_t buf[32];
  sail_word_to_be_bytes(buf, EVMSAIL_WORD_VALUE(w));
  uint8_t *d = frame_write_region(evmsail_byte_quantity_value(off), 32);
  memcpy(d, buf, 32);
  return UNIT;
}

/* MCOPY: overlapping-safe copy within the current frame. Both ranges are
 * established BEFORE either pointer is taken (a second establishment could
 * realloc the arena from under the first pointer). */
unit mem_move(EVMSAIL_BYTE_QUANTITY_PARAM(dst),
              EVMSAIL_BYTE_QUANTITY_PARAM(src),
              EVMSAIL_BYTE_QUANTITY_PARAM(len)) {
  uint64_t dst_value = evmsail_byte_quantity_value(dst);
  uint64_t src_value = evmsail_byte_quantity_value(src);
  uint64_t len_value = evmsail_byte_quantity_value(len);
  if (!len_value) return UNIT;
  if (src_value > UINT64_MAX - len_value ||
      dst_value > UINT64_MAX - len_value)
    abort();
  f_establish(src_value + len_value);
  f_establish(dst_value + len_value);
  memmove(arena + f_base[h_top] + dst_value,
          arena + f_base[h_top] + src_value, len_value);
  return UNIT;
}

/* (byte-quantity offset, bits(8) value) -> unit */
unit mem_write_byte(EVMSAIL_BYTE_QUANTITY_PARAM(off), uint64_t v) {
  uint64_t offset = evmsail_byte_quantity_value(off);
  if (offset == UINT64_MAX) abort();
  f_establish(offset + 1);
  arena[f_base[h_top] + offset] = (uint8_t)(v & 0xff);
  return UNIT;
}

/* ---- generic ByteSlice reads (calldata and executable frame code) ------- */

/* Read an absolute span minted by subslicing an active or suspended Sail
 * EVM-memory frame pointer. Well-formed slices never exceed an established
 * frame; the capacity check keeps malformed host inputs fail-closed. */
const uint8_t *evm_memory_region(uint64_t off, uint64_t len) {
  if (len == 0 || off > arena_cap || len > arena_cap - off) return NULL;
  return arena + off;
}

/* one byte at slice offset i, zero past the slice's end */
uint64_t slice_byte_at_source(uint64_t kind, uint64_t off, uint64_t len,
                              uint64_t i) {
  if (i >= len) return 0;
  const uint8_t *p = NULL;
  uint64_t resolved_len = 0;
  return evmsail_resolve_byte_source(kind, off + i, 1, &p, &resolved_len) &&
         p && resolved_len == 1 ? *p : 0;
}

/* Count nonzero bytes without materializing the slice in Sail. */
uint64_t slice_count_nonzero_source(uint64_t kind, uint64_t off, uint64_t len) {
  if (len == 0) return 0;
  const uint8_t *p = NULL;
  uint64_t resolved_len = 0;
  if (!evmsail_resolve_byte_source(kind, off, len, &p, &resolved_len) ||
      !p || resolved_len != len)
    return 0;
  uint64_t count = 0;
  for (uint64_t i = 0; i < len; i++) count += p[i] != 0;
  return count;
}

/* True when each width-byte region at start + i*stride is zero. Resolving the
 * source once keeps regular-layout validation (notably padded BLS fields) at
 * one host crossing while Sail remains explicit about the checked layout. */
bool slice_strided_zero_source(uint64_t kind, uint64_t off, uint64_t len,
                               uint64_t start, uint64_t stride, uint64_t width,
                               uint64_t count) {
  if (count == 0 || width == 0) return true;
  if (start > len || width > len - start) return false;
  if (count > 1 && (stride == 0 || count - 1 > (UINT64_MAX - start) / stride))
    return false;
  uint64_t last = start + (count - 1) * stride;
  if (last > len || width > len - last) return false;

  const uint8_t *p = NULL;
  uint64_t resolved_len = 0;
  if (!evmsail_resolve_byte_source(kind, off, len, &p, &resolved_len) ||
      !p || resolved_len != len)
    return false;
  for (uint64_t i = 0; i < count; i++) {
    const uint8_t *field = p + start + i * stride;
    for (uint64_t j = 0; j < width; j++)
      if (field[j] != 0) return false;
  }
  return true;
}

/* the 32-byte word at slice offset i, zero-padded past the slice's end */
sail_word slice_load_word_source(uint64_t kind, uint64_t off, uint64_t len,
                                 uint64_t i) {
  uint8_t b[32] = {0};
  if (i < len) {
    uint64_t n = len - i;
    if (n > 32) n = 32;
    const uint8_t *p = NULL;
    uint64_t rl = 0;
    if (evmsail_resolve_byte_source(kind, off + i, n, &p, &rl) && rl == n) memcpy(b, p, n);
  }
  return be_bytes_to_sail_word(b);
}

/* the n-byte big-endian word at slice offset i, right-aligned and zero-padded
 * past the slice's end (PUSH0..PUSH32) */
sail_word slice_load_n_word_source(uint64_t kind, uint64_t off, uint64_t len,
                                   uint64_t i, uint64_t n) {
  uint8_t b[32] = {0};
  uint64_t cnt = n < 32 ? n : 32;
  if (i < len) {
    uint64_t m = len - i;
    if (m > cnt) m = cnt;
    const uint8_t *p = NULL;
    uint64_t resolved_len = 0;
    if (evmsail_resolve_byte_source(kind, off + i, m, &p, &resolved_len) &&
        p && resolved_len == m)
      memcpy(b + 32 - cnt, p, m);
  }
  return be_bytes_to_sail_word(b);
}

/* slice[i, i+n) into memory at dst, zero-filling past the slice's end. The
 * destination is established FIRST (it may realloc the arena); the source
 * pointer is taken after and used immediately. */
unit slice_copy_to_memory_source(uint64_t kind, uint64_t off, uint64_t len,
                                 uint64_t dst, uint64_t i, uint64_t n) {
  if (!n) return UNIT;
  uint8_t *d = frame_write_region(dst, n);
  if (!d) return UNIT;
  uint64_t m = 0;
  if (i < len) {
    m = len - i;
    if (m > n) m = n;
    const uint8_t *p = NULL;
    uint64_t rl = 0;
    if (evmsail_resolve_byte_source(kind, off + i, m, &p, &rl) && rl == m) memmove(d, p, m);
    else m = 0;
  }
  memset(d + m, 0, n - m);
  return UNIT;
}
