/* Optimized interpreter access to the C-private operand-stack rows.
 *
 * These helpers are not Sail host axioms. They are used only by the optimized
 * C interpreter, which already operates on the generated by-value sail_u256
 * representation. The standard Sail opcode bodies continue to use stack.h.
 */
#ifndef EVMSAIL_OPTIMIZED_STACK_H
#define EVMSAIL_OPTIMIZED_STACK_H

#include "sail_abi.h"

#include <stdint.h>

enum evmsail_stack_rewrite_status {
  EVMSAIL_STACK_REWRITE_OK = 0,
  EVMSAIL_STACK_REWRITE_UNDERFLOW,
  EVMSAIL_STACK_REWRITE_OVERFLOW,
};

/* Replace the top `inputs` rows with `outputs` rows and return a pointer to
 * the deepest input/output row. Old input rows remain readable until callers
 * overwrite them. */
enum evmsail_stack_rewrite_status evmsail_stack_rewrite(
    uint32_t inputs, uint32_t outputs, sail_u256 **rows);

/* Duplicate the one-based `depth` row onto the top of the stack. */
enum evmsail_stack_rewrite_status evmsail_stack_dup(uint32_t depth);

/* Exchange the top row with the zero-based `other_depth` row. */
enum evmsail_stack_rewrite_status evmsail_stack_swap(uint32_t other_depth);

/* Exchange two zero-based stack depths. */
enum evmsail_stack_rewrite_status evmsail_stack_exchange(uint32_t left_depth,
                                                         uint32_t right_depth);

#endif
