# Generated by Sail's Python backend. Do not edit by hand.
# Sail source: executor/block.sail
from __future__ import annotations

from .._runtime import (
    Bits,
    Bytes20,
    Bytes32,
    SailThrown,
    Uint,
    sail_ediv_int,
)
from copy import deepcopy
from dataclasses import replace
from typing import TypeAlias
from pydantic import ConfigDict, model_validator
from pydantic.dataclasses import dataclass as pydantic_dataclass
from typing_extensions import Self
from evm.HostContract import (
    bal_reset as _host_bal_reset,
)
from evm.prelude import (
    address,
    hash,
    alu_mul,
    ZERO_ADDRESS,
)
from evm.primitives.quantities import (
    blob_gas_used,
    word_of_withdrawal_amount,
)
from evm.primitives.gas import (
    gas,
    GAS_ZERO,
)
from evm.primitives.bytes import (
    StatelessInputSlice,
    stateless_input_slice_length,
    stateless_input_sub_slice,
    stateless_input_slice_suffix,
)
from evm.exceptions import (
    BlockError,
    InvalidBlock,
)
from evm.primitives.ssz import (
    TransactionListRef,
    WithdrawalListRef,
)
from evm.primitives.fork import (
    Paris,
    Shanghai,
    Cancun,
    Prague,
    Amsterdam,
)
from evm.primitives.system import (
    BEACON_ROOTS_ADDR,
    HISTORY_STORAGE_ADDR,
)
from evm.primitives.block import (
    BlockBody,
    ExecutionRequests,
    LogsBloom,
    EMPTY_EXECUTION_REQUESTS,
)
from evm.kernel.environment import k_coinbase
from evm.kernel.accounts import k_add_balance
from evm.kernel.lifecycle import k_tx_merge
from evm.evm.machine import conserved_gas_add
from evm.evm.gas import block_blob_gas_add
from evm.evm.transaction import (
    transaction_gas_allowance,
    process_transaction,
)
from evm.lib.ssz.stateless_input import (
    ssz_list_cursor,
    ssz_list_cursor_empty,
    ssz_list_pop,
    ssz_fixed_list_pop,
    decode_withdrawal,
    decode_transaction,
    WD_SIZE,
    PUBLIC_KEY_LENGTH,
)
from evm.executor.receipts import (
    receipt_accumulator_empty,
    receipt_accumulator_push,
    receipt_accumulator_root,
    receipt_accumulator_bloom,
)
from evm.executor.system_calls import (
    system_call,
    authenticate_deposit_logs,
    collect_execution_requests,
)
from evm.kernel import environment

_BlockExecutionResult_blob_gas_used_type: TypeAlias = blob_gas_used
@pydantic_dataclass(config=ConfigDict(strict=True, validate_assignment=True, revalidate_instances="always", arbitrary_types_allowed=True), slots=True, kw_only=True)
class BlockExecutionResult:
    header_gas_used: gas
    execution_gas_used: gas
    state_gas_used: gas
    blob_gas_used: _BlockExecutionResult_blob_gas_used_type
    first_tx_recipient: address
    receipts_root: hash
    logs_bloom: LogsBloom
    requests: ExecutionRequests

    @model_validator(mode="after")
    def validate(self) -> Self:
        if not ((len(self.logs_bloom) == 256)):
            raise ValueError("BlockExecutionResult.logs_bloom violates Sail type vector(256, bitvector(8))")
        return self

def remaining_block_gas(limit: int, used: int) -> Uint:
    if (int(used) <= int(limit)):
        return Uint((int(limit) - int(used)))
    else:
        raise SailThrown(InvalidBlock(BlockError.GasUsedExceedsLimit))

def run_block_start_system_calls() -> None:
    execution_profile = environment.k_execution_profile
    profile = execution_profile.protocol
    if (int(profile.fork) >= int(Cancun)):
        system_call(BEACON_ROOTS_ADDR, environment.k_header.parent_beacon_block_root)
    if (int(profile.fork) >= int(Prague)):
        return system_call(HISTORY_STORAGE_ADDR, environment.k_header.parent_hash)
    else:
        return None

def execute_block_transactions(transactions: TransactionListRef, public_keys: StatelessInputSlice, expected_deposits: StatelessInputSlice) -> BlockExecutionResult:
    execution_profile = environment.k_execution_profile
    profile = execution_profile.protocol
    gas_limits = execution_profile.gas
    public_keys_length = public_keys.len
    public_key_length = PUBLIC_KEY_LENGTH
    public_key_count_value = sail_ediv_int(public_keys_length, public_key_length)
    if ((((public_key_count_value) != (transactions.count))) | (((public_keys_length) != ((int(public_key_count_value) * int(public_key_length)))))):
        raise SailThrown(InvalidBlock(BlockError.WitnessDeficient))
    gas_limit = gas_limits.block_limit
    execution_gas_acc = GAS_ZERO
    state_gas_acc = GAS_ZERO
    blob_gas_acc = 0
    tx0_to = ZERO_ADDRESS
    receipts = receipt_accumulator_empty()
    remaining_deposits = expected_deposits
    cursor = ssz_list_cursor(transactions)
    keys = public_keys
    while True:
        if not ((not (ssz_list_cursor_empty(cursor)))):
            break
        i = cursor.index
        (transaction, next) = ssz_list_pop(cursor)
        cursor = next
        keys_fields = keys
        keys_length = keys_fields.len
        if (int(keys_length) < int(public_key_length)):
            raise SailThrown(InvalidBlock(BlockError.WitnessDeficient))
        public_key = stateless_input_sub_slice(keys_fields, 0, PUBLIC_KEY_LENGTH)
        keys = stateless_input_slice_suffix(keys_fields, public_key_length)
        tx = decode_transaction(transaction, public_key)
        environment.k_block_access_index = (int(i) + 1)
        if ((i) == (0)):
            tx0_to = Bytes20(tx.recipient)
        available_execution_gas = remaining_block_gas(gas_limit, execution_gas_acc)
        available_state_gas = remaining_block_gas(gas_limit, state_gas_acc)
        allowance = transaction_gas_allowance(tx.gas_limit, gas_limits.transaction_total_limit, gas_limits.transaction_regular_limit)
        if (int(profile.fork) >= int(Amsterdam)):
            transaction_fits = (((int(allowance.regular) <= int(available_execution_gas))) & ((int(allowance.total) <= int(available_state_gas))))
        else:
            transaction_fits = (int(allowance.total) <= int(available_execution_gas))
        if (not (transaction_fits)):
            raise SailThrown(InvalidBlock(BlockError.GasUsedExceedsLimit))
        else:
            tx_blob_gas = (int((1 << 17)) * int(tx.blob_hashes.count))
            if (int(profile.fork) < int(Cancun)):
                next_blob_gas = blob_gas_acc
            else:
                next_blob_gas = block_blob_gas_add(profile.blob_schedule.max, blob_gas_acc, tx_blob_gas)
            receipt = process_transaction(tx, allowance)
            execution_gas_acc = Uint(conserved_gas_add(execution_gas_acc, receipt.execution_gas))
            state_gas_acc = Uint(conserved_gas_add(state_gas_acc, receipt.state_gas))
            if (((int(gas_limit) < int(execution_gas_acc))) | ((int(gas_limit) < int(state_gas_acc)))):
                raise SailThrown(InvalidBlock(BlockError.GasUsedExceedsLimit))
            receipts = receipt_accumulator_push(receipts, receipt, next.index)
            if (int(profile.fork) >= int(Prague)):
                remaining_deposits = authenticate_deposit_logs(receipt.logs, remaining_deposits)
            blob_gas_acc = next_blob_gas
    if (((int(profile.fork) >= int(Prague))) & (((stateless_input_slice_length(remaining_deposits)) != (0)))):
        raise SailThrown(InvalidBlock(BlockError.InvalidExecutionRequests))
    if (((int(profile.fork) >= int(Amsterdam))) & ((int(execution_gas_acc) < int(state_gas_acc)))):
        header_gas_used = state_gas_acc
    else:
        header_gas_used = execution_gas_acc
    receipts_root = receipt_accumulator_root(receipts)
    return BlockExecutionResult(header_gas_used=Uint(header_gas_used), execution_gas_used=Uint(execution_gas_acc), state_gas_used=Uint(state_gas_acc), blob_gas_used=blob_gas_acc, first_tx_recipient=Bytes20(tx0_to), receipts_root=Bytes32(receipts_root), logs_bloom=receipt_accumulator_bloom(receipts), requests=EMPTY_EXECUTION_REQUESTS)

def apply_withdrawals(withdrawals: WithdrawalListRef) -> None:
    rest = withdrawals
    while True:
        if not (((rest.count) != (0))):
            break
        (withdrawal_ref, tail) = ssz_fixed_list_pop(rest, WD_SIZE)
        rest = tail
        withdrawal = decode_withdrawal(withdrawal_ref)
        k_add_balance(withdrawal.address, alu_mul(word_of_withdrawal_amount(withdrawal.amount), 1000000000))
    return None

def apply_block_end_state(body: BlockBody) -> None:
    execution_profile = environment.k_execution_profile
    profile = execution_profile.protocol
    if (int(profile.fork) >= int(Shanghai)):
        apply_withdrawals(body.withdrawals)
    if (int(profile.fork) < int(Paris)):
        k_add_balance(k_coinbase(), PRE_MERGE_BLOCK_REWARD)
    return k_tx_merge()

def execute_block_body(body: BlockBody, public_keys: StatelessInputSlice, expected_deposits: StatelessInputSlice) -> BlockExecutionResult:
    execution_profile = environment.k_execution_profile
    profile = execution_profile.protocol
    _host_bal_reset()
    environment.k_block_access_index = 0
    run_block_start_system_calls()
    result = execute_block_transactions(body.transactions, public_keys, expected_deposits)
    post_tx_index = (int(body.transactions.count) + 1)
    environment.k_block_access_index = post_tx_index
    apply_block_end_state(body)
    if (int(profile.fork) >= int(Prague)):
        requests = collect_execution_requests(expected_deposits)
    else:
        requests = EMPTY_EXECUTION_REQUESTS
    return replace(deepcopy(result), requests=requests)

PRE_MERGE_BLOCK_REWARD: int = int(Bits(64, 0b0001101111000001011011010110011101001110110010000000000000000000))
