# Generated by Sail's Python backend. Do not edit by hand.
# Sail source: host/debug_disabled.sail
from __future__ import annotations

from .._runtime import (
    Bytes32,
)
from src.prelude import (
    address,
    hash,
)
from src.exceptions import (
    FatalError,
    validation_stage,
)
from src.primitives.crypto import EMPTY_TRIE_ROOT

def validation_debug_reset() -> None:
    return None

def validation_debug_capture_block_gas(_actual: int, _expected: int, _execution: int, _state: int) -> None:
    return None

def validation_debug_record(_stage: validation_stage, _reason: FatalError) -> None:
    return None

def debug_account_storage_root(_a: address) -> hash:
    return Bytes32(EMPTY_TRIE_ROOT)
