# Generated by Sail's Python backend. Do not edit by hand.
# Sail source: host/journal.sail
from __future__ import annotations

from dataclasses import dataclass
from typing import TypeAlias
from src.prelude import (
    address,
    hash,
    word,
)
from src.primitives.quantities import (
    account_nonce,
    storage_generation,
)
from src.primitives.ssz import block_access_index
from src.primitives.account import StorageKey

_JournalTransientChange_address_type: TypeAlias = address
@dataclass(slots=True)
class JournalTransientChange:
    address: _JournalTransientChange_address_type
    slot: word
    prior: word

_JournalWarmAccountChange_address_type: TypeAlias = address
@dataclass(slots=True)
class JournalWarmAccountChange:
    address: _JournalWarmAccountChange_address_type
    prior_epoch: block_access_index

@dataclass(slots=True)
class JournalWarmStorageChange:
    key: StorageKey
    prior_epoch: block_access_index

_JournalAccountBalanceChange_address_type: TypeAlias = address
@dataclass(slots=True)
class JournalAccountBalanceChange:
    address: _JournalAccountBalanceChange_address_type
    prior: word

_JournalAccountNonceChange_address_type: TypeAlias = address
@dataclass(slots=True)
class JournalAccountNonceChange:
    address: _JournalAccountNonceChange_address_type
    prior: account_nonce

_JournalAccountCodeHashChange_address_type: TypeAlias = address
@dataclass(slots=True)
class JournalAccountCodeHashChange:
    address: _JournalAccountCodeHashChange_address_type
    prior: hash

_JournalAccountExistsChange_address_type: TypeAlias = address
@dataclass(slots=True)
class JournalAccountExistsChange:
    address: _JournalAccountExistsChange_address_type
    prior: bool

_JournalAccountCreatedChange_address_type: TypeAlias = address
@dataclass(slots=True)
class JournalAccountCreatedChange:
    address: _JournalAccountCreatedChange_address_type
    prior: bool

_JournalAccountSelfdestructedChange_address_type: TypeAlias = address
@dataclass(slots=True)
class JournalAccountSelfdestructedChange:
    address: _JournalAccountSelfdestructedChange_address_type
    prior: bool

@dataclass(slots=True)
class JournalStorageValueChange:
    key: StorageKey
    prior: word

@dataclass(slots=True)
class JournalStorageRowGenerationChange:
    key: StorageKey
    prior: storage_generation

_JournalAccountStorageGenerationChange_address_type: TypeAlias = address
@dataclass(slots=True)
class JournalAccountStorageGenerationChange:
    address: _JournalAccountStorageGenerationChange_address_type
    prior: storage_generation

class StateJournalEntry:
    pass

@dataclass(frozen=True, slots=True)
class JournalTransientChanged(StateJournalEntry):
    value: JournalTransientChange

@dataclass(frozen=True, slots=True)
class JournalWarmAccountChanged(StateJournalEntry):
    value: JournalWarmAccountChange

@dataclass(frozen=True, slots=True)
class JournalWarmStorageChanged(StateJournalEntry):
    value: JournalWarmStorageChange

@dataclass(frozen=True, slots=True)
class JournalAccountBalanceChanged(StateJournalEntry):
    value: JournalAccountBalanceChange

@dataclass(frozen=True, slots=True)
class JournalAccountNonceChanged(StateJournalEntry):
    value: JournalAccountNonceChange

@dataclass(frozen=True, slots=True)
class JournalAccountCodeHashChanged(StateJournalEntry):
    value: JournalAccountCodeHashChange

@dataclass(frozen=True, slots=True)
class JournalAccountExistsChanged(StateJournalEntry):
    value: JournalAccountExistsChange

@dataclass(frozen=True, slots=True)
class JournalAccountCreatedChanged(StateJournalEntry):
    value: JournalAccountCreatedChange

@dataclass(frozen=True, slots=True)
class JournalAccountSelfdestructedChanged(StateJournalEntry):
    value: JournalAccountSelfdestructedChange

@dataclass(frozen=True, slots=True)
class JournalTransactionAccountListed(StateJournalEntry):
    value: None = None

@dataclass(frozen=True, slots=True)
class JournalTransactionStorageListed(StateJournalEntry):
    value: address

@dataclass(frozen=True, slots=True)
class JournalLogAppended(StateJournalEntry):
    value: None = None

@dataclass(frozen=True, slots=True)
class JournalStorageValueChanged(StateJournalEntry):
    value: JournalStorageValueChange

@dataclass(frozen=True, slots=True)
class JournalStorageRowGenerationChanged(StateJournalEntry):
    value: JournalStorageRowGenerationChange

@dataclass(frozen=True, slots=True)
class JournalAccountStorageGenerationChanged(StateJournalEntry):
    value: JournalAccountStorageGenerationChange

@dataclass(frozen=True, slots=True)
class JournalFrameCheckpointed(StateJournalEntry):
    value: None = None

@dataclass(frozen=True, slots=True)
class JournalFrameCommitted(StateJournalEntry):
    value: None = None
