#!/usr/bin/env bash
# Restructure the extraction backends into a per-target layout:
#
#   ffi/                                -> extractions/c/
#   ffi/optimized/                      -> extractions/c/optimised/contract/   (z -> s, matching the
#   ffi/spec/                           -> extractions/c/spec/contract/         repo-wide spelling:
#                                                                                sail/optimised,
#                                                                                make c-optimised)
#   extractions/contracts/ExternBoundary.v   -> extractions/coq/contract/
#   extractions/contracts/HostAxioms.lean    -> extractions/lean/contract/
#   extractions/contracts/Specialization.lean-> extractions/lean/contract/  (companion Lean
#                                               contract file; travels with HostAxioms.lean)
#   extractions/contracts/HostContract.py    -> extractions/python/contract/
#
# The root platform contracts zkvm_accelerators.h / zkvm_io.h / zkvm_bigint.h
# move with the ffi root to extractions/c/.
#
# After the git mv steps the script rewrites every known path reference. The
# rewrite inventory below was generated with `rg -l 'ffi/'` (and
# `extractions/contracts`) over the tracked tree and is baked in explicitly;
# generated trees (build/, zkvm/*/.build*, book/docs/reference generated
# pages, zkvm/build-zisk) are intentionally NOT rewritten -- they are
# regenerated by their build steps. The generated-C staging directory name
# `<generated>/src/ffi` is an internal packaging name produced by
# devtools/optimised_c/package.py and the build scripts; it does not refer to the
# repository directory and is deliberately preserved.
#
# The .github/workflows/*.yml files are make-target-based and carry no ffi/
# path references; the verification pass at the end asserts that.
#
# PREPARED, NOT YET EXECUTED. Idempotent-safe: refuses to run if any target
# already exists or if the involved paths carry uncommitted changes.

set -euo pipefail

die() {
    echo "restructure: $*" >&2
    exit 1
}

# --- preconditions ---------------------------------------------------------

[ -f sail/evm.sail_project ] || die "run from the repository root"
[ -d ffi ] || die "ffi/ does not exist (already restructured?)"
[ ! -e extractions/c ] || die "target extractions/c already exists; refusing"
[ ! -e extractions/coq/contract ] || die "target extractions/coq/contract already exists; refusing"
[ ! -e extractions/lean/contract ] || die "target extractions/lean/contract already exists; refusing"
[ ! -e extractions/python/contract ] || die "target extractions/python/contract already exists; refusing"
[ -d ffi/optimized ] || die "ffi/optimized does not exist"
[ -d ffi/spec ] || die "ffi/spec does not exist"
[ -f extractions/contracts/ExternBoundary.v ] || die "extractions/contracts/ExternBoundary.v missing"
[ -f extractions/contracts/HostAxioms.lean ] || die "extractions/contracts/HostAxioms.lean missing"
[ -f extractions/contracts/Specialization.lean ] || die "extractions/contracts/Specialization.lean missing"
[ -f extractions/contracts/HostContract.py ] || die "extractions/contracts/HostContract.py missing"

if [ -n "$(git status --porcelain -- ffi extractions Makefile AGENTS.md README.md)" ]; then
    die "uncommitted changes under ffi/, extractions/, Makefile, AGENTS.md, or README.md; commit or stash first"
fi

# --- moves -----------------------------------------------------------------

echo "== moving directories and contract files =="

mkdir -p extractions/c
git mv ffi extractions/c
git mv extractions/c/optimized extractions/c/optimised/contract

mkdir -p extractions/coq/contract extractions/lean/contract extractions/python/contract
git mv extractions/contracts/ExternBoundary.v extractions/coq/contract/ExternBoundary.v
git mv extractions/contracts/HostAxioms.lean extractions/lean/contract/HostAxioms.lean
git mv extractions/contracts/Specialization.lean extractions/lean/contract/Specialization.lean
git mv extractions/contracts/HostContract.py extractions/python/contract/HostContract.py
rmdir extractions/contracts 2>/dev/null || true

# --- path-reference rewrites -----------------------------------------------

# Complete inventory of tracked files that reference the old layout.
# Post-move self-references inside the moved tree are listed at their NEW
# paths.
REWRITE_FILES=(
    # build entry points
    Makefile
    zkvm/build.sh
    zkvm/native-runner/build.sh
    zkvm/native-runner/build_lib.sh
    # repository tooling (devtools.optimised_c.package is handled separately below:
    # it also OWNS the package-internal staging names "src/ffi" and
    # f"ffi/{entry}", which must not be rewritten)
    devtools/optimised_c/ffi.py
    devtools/optimised_c/format.py
    devtools/optimised_c/lint.py
    # documentation
    AGENTS.md
    README.md
    book/docs/extractions.md
    zkvm/README.md
    # zkVM platform sources (comment references to the root contracts)
    zkvm/accel-host/Cargo.toml
    zkvm/accel-host/src/lib.rs
    zkvm/io-device/io_device.cc
    zkvm/io-device/io_mmio.h
    zkvm/runtime/accel_guest.c
    zkvm/runtime/bigint_portable.c
    zkvm/runtime/runtime.c
    zkvm/zisk/bigint.c
    zkvm/zkvm_accel_mmio.h
    # Sail doc comments
    sail/host/stack.sail
    sail/optimised/prelude.sail
    sail/primitives/crypto.sail
    # moved-tree self references (new paths)
    extractions/c/spec/contract/trie_node_db.h
    extractions/c/optimised/contract/src/prelude.c
    extractions/c/zkvm_bigint.h
)

echo "== rewriting path references (${#REWRITE_FILES[@]} files) =="

for f in "${REWRITE_FILES[@]}"; do
    [ -f "$f" ] || die "rewrite target missing: $f"
    perl -pi -e '
        # ordered: most specific first
        s{ffi/optimized}{extractions/c/optimised/contract}g;         # dir + inner rename
        s{ffi/spec}{extractions/c/spec/contract}g;
        s{\.\./ffi/}{../extractions/c/}g;                    # zkvm/README.md relative links
        s{-Iffi\b}{-Iextractions/c}g;                        # Makefile c-spec include path
        s{ROOT/ffi"}{ROOT/extractions/c"}g;                  # FFI_ROOT= / FFI= in zkvm scripts
        s{ROOT / "ffi"}{ROOT / "extractions/c"}g;            # package module default
        s{ROOT / \x27ffi\x27}{ROOT / \x27extractions/c\x27}g; # lint module -I root
        s{FFI_ROOT/optimized}{FFI_ROOT/optimised}g;                    # MODEL_FFI selection
        # generic prose/doc references: `ffi/` not preceded by a path or word
        # character. Preserves the generated staging name src/ffi.
        s{(^|[^/A-Za-z0-9_.])ffi/}{$1extractions/c/}g;
    ' "$f"
done

echo "== file-specific rewrites =="

# Makefile: the single CONTRACTS_DIR fans out into per-target contract dirs.
perl -pi -e '
    s{\$\(CONTRACTS_DIR\)/HostContract\.py}{extractions/python/contract/HostContract.py};
    s{\$\(CONTRACTS_DIR\)/HostAxioms\.lean}{extractions/lean/contract/HostAxioms.lean};
    s{\$\(CONTRACTS_DIR\)/Specialization\.lean}{extractions/lean/contract/Specialization.lean};
    s{\$\(CONTRACTS_DIR\)/ExternBoundary\.v}{extractions/coq/contract/ExternBoundary.v};
    s{find sail extractions/contracts }{find sail };
' Makefile
perl -ni -e 'print unless /^CONTRACTS_DIR\s+:= extractions\/contracts$/' Makefile

# devtools.optimised_c.package: only the repository-facing paths change. The
# package-internal staging layout it produces (generated/src/ffi, manifest
# entries prefixed f"ffi/{entry}", -Isrc/ffi in the emitted Makefile) is a
# self-consistent internal naming scheme and stays as-is.
perl -pi -e '
    s{ROOT / "ffi"}{ROOT / "extractions/c"}g;
    s{"optimized/sources\.list"}{"optimised/sources.list"}g;
    s{"optimized/src"}{"optimised/src"}g;
    s{"optimized/include"}{"optimised/include"}g;
' devtools/optimised_c/package.py

# AGENTS.md: the extern-contract pointer follows the Coq contract move.
perl -pi -e '
    s{extractions/contracts/ExternBoundary\.v}{extractions/coq/contract/ExternBoundary.v}g;
' AGENTS.md

# book/docs/extractions.md: the stub pointer fans out per target.
perl -pi -e '
    s{`extractions/contracts/`}{`extractions/{coq,lean,python}/contract/`}g;
' book/docs/extractions.md

# Moved-tree docs that name the optimized/ subdir relative to the ffi root.
perl -pi -e 's{optimized/}{optimised/}g' \
    extractions/c/README.md \
    extractions/c/spec/contract/state_db.h

# --- verification ----------------------------------------------------------

echo "== verifying no stale references remain =="

fail=0
for f in "${REWRITE_FILES[@]}" .github/workflows/book.yml .github/workflows/ci.yml; do
    [ -f "$f" ] || continue
    if perl -ne 'if (m{(^|[^/A-Za-z0-9_.])ffi/}) { print "$ARGV:$.: $_"; $bad = 1 } END { exit($bad ? 1 : 0) }' "$f"; then
        :
    else
        echo "stale ffi/ reference in $f" >&2
        fail=1
    fi
done
for f in Makefile AGENTS.md book/docs/extractions.md; do
    if grep -n 'extractions/contracts' "$f"; then
        echo "stale extractions/contracts reference in $f" >&2
        fail=1
    fi
done
# devtools.optimised_c.package: repo-facing paths must be gone, staging names kept.
if grep -n 'ROOT / "ffi"\|"optimized/' devtools/optimised_c/package.py; then
    echo "stale reference in devtools/optimised_c/package.py" >&2
    fail=1
fi
grep -q 'src/ffi' devtools/optimised_c/package.py \
    || { echo "package staging name src/ffi unexpectedly rewritten" >&2; fail=1; }
[ ! -e ffi ] || { echo "ffi/ still exists" >&2; fail=1; }
[ -f extractions/c/zkvm_accelerators.h ] || { echo "root contract header missing after move" >&2; fail=1; }
[ -f extractions/c/zkvm_io.h ] || { echo "root contract header missing after move" >&2; fail=1; }
[ -f extractions/c/zkvm_bigint.h ] || { echo "root contract header missing after move" >&2; fail=1; }
[ -f extractions/c/optimised/contract/sources.list ] || { echo "optimised manifest missing after move" >&2; fail=1; }
[ "$fail" -eq 0 ] || die "verification failed; inspect the findings above before committing"

# --- summary ---------------------------------------------------------------

echo
echo "== summary =="
echo "moved:"
echo "  ffi/                                 -> extractions/c/"
echo "  ffi/optimized/                       -> extractions/c/optimised/contract/"
echo "  ffi/spec/                            -> extractions/c/spec/contract/"
echo "  ffi/zkvm_{accelerators,io,bigint}.h  -> extractions/c/"
echo "  extractions/contracts/ExternBoundary.v    -> extractions/coq/contract/"
echo "  extractions/contracts/HostAxioms.lean     -> extractions/lean/contract/"
echo "  extractions/contracts/Specialization.lean -> extractions/lean/contract/"
echo "  extractions/contracts/HostContract.py     -> extractions/python/contract/"
echo "rewrote ${#REWRITE_FILES[@]} files (see REWRITE_FILES in this script)"
echo "preserved: generated staging name src/ffi (internal packaging layout)"
echo "note: book/docs/reference generated pages refresh on the next 'make docs-site'"
echo
echo "== validation commands to run now =="
echo "  make check"
echo "  make lint && make fmt-check"
echo "  make check-optimized-ffi"
echo "  make c-spec"
echo "  make c-optimised"
echo "  python3 -m devtools.harness.cli --rebuild --limit 1 --quiet \\"
echo "    zkvm/.fixtures/current-v062-full/blockchain_tests/for_amsterdam/shanghai/eip3855_push0/push0/push0_contracts.json"
echo "  python3 -m devtools.harness.cli --jobs 8 --quiet zkvm/.fixtures/current-v062-full   # full native gate"
echo "  make zisk-guest    # production ZisK ELF build"
echo "  make docs-site     # regenerates the book reference pages"
