version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "05:00"
      timezone: Etc/UTC
    open-pull-requests-limit: 5
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: cargo
    directories:
      - /zkvm/accel-host
      - /zkvm/zisk
    schedule:
      interval: weekly
      day: monday
      time: "05:15"
      timezone: Etc/UTC
    open-pull-requests-limit: 5
    groups:
      cargo-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: uv
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "05:30"
      timezone: Etc/UTC
    open-pull-requests-limit: 5
    groups:
      python-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: uv
    directory: /mkdocstrings-sail
    schedule:
      interval: weekly
      day: monday
      time: "05:45"
      timezone: Etc/UTC
    open-pull-requests-limit: 5
    groups:
      python-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
