# Generated by Sail's Python backend. Do not edit by hand.
# Sail source: host/accelerators.sail
from __future__ import annotations

from .._runtime import (
    Unsigned,
)

class pairing_check_result(Unsigned):
    LOWER = 0
    UPPER = 3

    def _in_range(self, value: int) -> bool:
        return self.LOWER <= value <= self.UPPER
