# Generated by Sail's Python backend. Do not edit by hand.
# Sail source: evm/machine.sail
from __future__ import annotations

from .._runtime import (
    BitWidth,
    Bits,
    SailError,
    SailThrown,
    Uint,
    sail_tmod_int,
)
from typing import Annotated
from evm.HostContract import (
    jumpdest_ref_contains as _host_jumpdest_ref_contains,
    mem_clear as _host_mem_clear,
    mem_expand as _host_mem_expand,
    mem_frame_enter as _host_mem_frame_enter,
    mem_frame_leave as _host_mem_frame_leave,
    mem_load_word as _host_mem_load_word,
    mem_move as _host_mem_move,
    mem_read_byte as _host_mem_read_byte,
    mem_store_word as _host_mem_store_word,
    mem_write_byte as _host_mem_write_byte,
    memory_keccak256 as _host_memory_keccak256,
    stack_depth as _host_stack_depth,
    stack_enter_frame as _host_stack_enter_frame,
    stack_leave_frame as _host_stack_leave_frame,
    stack_peek_word as _host_stack_peek_word,
    stack_pop_word as _host_stack_pop_word,
    stack_push_word as _host_stack_push_word,
    stack_set_word as _host_stack_set_word,
)
from evm.prelude import (
    word,
    sail_U256,
    hash_to_word,
    word_low_byte,
    ZERO_WORD,
    WORD_ZERO,
)
from evm.primitives.quantities import (
    MemoryRange,
    code_chunk_index,
    code_pointer,
    frame_depth,
    operand_stack_height,
    stack_index,
)
from evm.primitives.gas import (
    gas,
    gas_refund,
    receipt_cumulative_gas,
    state_gas_spill,
    transaction_state_gas_delta,
    STATE_GAS_SPILL_ZERO,
    GAS_ZERO,
    GAS_REFUND_ZERO,
)
from evm.primitives.bytes import (
    CalldataSlice,
    CodeRegionSliceFields,
    MemorySlice,
    MemorySliceFields,
    OutputSlice,
    memory_slice,
    memory_sub_slice,
    EMPTY_MEMORY_SLICE,
    EMPTY_OUTPUT_SLICE,
    EMPTY_CALLDATA,
)
from evm.exceptions import (
    BlockError,
    ExceptionKind,
    InvalidBlock,
)
from evm.evm.halt import (
    Exceptional,
    FrameStatus,
    Running,
)
from evm.primitives.code import (
    Code,
    EMPTY_CODE_SLICE,
    EMPTY_CODE,
)
from evm.host.region_access import (
    output_byte,
    code_slice_copy,
    output_slice_copy,
)
from evm.primitives.fork import Amsterdam
from evm.primitives.evm import (
    FrameCheckpoint,
    Message,
    DEFAULT_MESSAGE,
)
from evm.host.code import code_db_intern_memory
from evm.kernel.lifecycle import k_state_checkpoint
from evm.kernel import environment

def validated_refund_add(left: int, right: int) -> gas_refund:
    total = (int(left) + int(right))
    if (((int((-int((199 * int((int((1 << 64)) - 1)))))) <= int(total))) & ((int(total) <= int((199 * int((int((1 << 64)) - 1))))))):
        return total
    else:
        raise SailThrown(InvalidBlock(BlockError.ExecutionInvalid))

def record_refund(delta: int) -> None:
    global frame_refund
    frame_refund = validated_refund_add(frame_refund, delta)
    return None

def frame_code_len() -> code_chunk_index:
    code = frame_code.bytes
    length = code.len
    return Uint(length)

def frame_jumpdest_valid(dest: int) -> bool:
    code = frame_code.bytes
    length = code.len
    return _host_jumpdest_ref_contains(frame_code.jumpdests, length, dest)

def conserved_gas_add(left: int, right: int) -> receipt_cumulative_gas:
    return Uint((int(left) + int(right)))

def refill_frame_state_gas() -> None:
    global gas_remaining, state_gas_remaining, state_gas_spilled
    execution_profile = environment.k_execution_profile
    profile = execution_profile.protocol
    if (int(profile.fork) >= int(Amsterdam)):
        gas_remaining = Uint(conserved_gas_add(gas_remaining, state_gas_spilled))
        state_gas_remaining = Uint(message.state_gas_reservoir)
        state_gas_spilled = STATE_GAS_SPILL_ZERO
        return None
    else:
        return None

def frame_state_gas_used() -> transaction_state_gas_delta:
    entry = message.state_gas_reservoir
    remaining = state_gas_remaining
    spilled = state_gas_spilled
    return (int((int(entry) - int(remaining))) + int(spilled))

def exc_halt(k: ExceptionKind) -> None:
    global frame_status, gas_remaining
    refill_frame_state_gas()
    gas_remaining = GAS_ZERO
    frame_status = Exceptional(k)
    return None

def stack_height() -> operand_stack_height:
    height = _host_stack_depth()
    if not ((int(height) <= int(STACK_LIMIT))):
        raise SailError("sail/evm/machine.sail:129.32-129.33")
    return operand_stack_height(height)

def peek(n: stack_index) -> word:
    return word(_host_stack_peek_word(n))

def push_word(w: word) -> None:
    if (int(STACK_LIMIT) <= int(stack_height())):
        return exc_halt(ExceptionKind.StackOverflow)
    else:
        return _host_stack_push_word(w)

def push_gas(value: receipt_cumulative_gas) -> None:
    return push_word(sail_U256(sail_tmod_int(value, (1 << 256))))

def pop() -> word:
    if ((stack_height()) == (0)):
        exc_halt(ExceptionKind.StackUnderflow)
        return word(WORD_ZERO)
    else:
        return word(_host_stack_pop_word())

def stack_set(n: stack_index, w: word) -> None:
    return _host_stack_set_word(n, w)

def is_running() -> bool:
    match frame_status:
        case Running(None):
            return True
        case _:
            return False

def calldata_install(data: CalldataSlice) -> None:
    global calldata
    calldata = data
    return None

def returndata_clear() -> None:
    global returndata
    returndata = EMPTY_OUTPUT_SLICE
    return None

def returndata_size() -> code_chunk_index:
    data = returndata
    return Uint(data.len)

def returndata_byte(index: code_chunk_index) -> Annotated[Bits, BitWidth(8)]:
    return output_byte(returndata, index)

def returndata_copy(dst: int, off: int, sail_len: int) -> None:
    return output_slice_copy(returndata, dst, off, sail_len)

def returndata_copy_prefix(dst: code_chunk_index, want: code_chunk_index) -> None:
    wanted = want
    available = returndata_size()
    if (int(wanted) < int(available)):
        copy_length = wanted
    else:
        copy_length = available
    return output_slice_copy(returndata, dst, 0, copy_length)

def returndata_remaining(available: int, offset: int) -> Uint:
    return Uint((int(available) - int(offset)))

def validated_returndata_copy(dst: code_chunk_index, source_offset: int, length: int) -> None:
    available = returndata_size()
    if (int(source_offset) <= int(available)):
        remaining = returndata_remaining(available, source_offset)
        bounded_source_offset = source_offset
        if (int(length) <= int(remaining)):
            bounded_length = length
            return returndata_copy(dst, bounded_source_offset, bounded_length)
        else:
            return exc_halt(ExceptionKind.InvalidOpcode)
    else:
        return exc_halt(ExceptionKind.InvalidOpcode)

def returndata_copy_words(dst: code_chunk_index, source_offset: word, length: word) -> None:
    return validated_returndata_copy(dst, source_offset, length)

def evm_memory_high_water() -> code_chunk_index:
    memory = evm_memory
    length = memory.len
    return Uint(length)

def memory_reset() -> None:
    global evm_memory
    _host_mem_clear()
    evm_memory = EMPTY_MEMORY_SLICE
    return None

def memory_expand_to(new_size: int) -> MemorySliceFields:
    global evm_memory
    memory = evm_memory
    if (int(memory.len) < int(new_size)):
        expanded = _host_mem_expand(new_size)
        evm_memory = expanded
        return expanded
    else:
        return memory_sub_slice(memory, 0, new_size)

def active_memory_slice(off: int, sail_len: int) -> MemorySliceFields:
    if ((sail_len) == (0)):
        return EMPTY_MEMORY_SLICE
    else:
        return memory_sub_slice(memory_expand_to((int(off) + int(sail_len))), off, sail_len)

def memory_code_slice(off: int, sail_len: int) -> CodeRegionSliceFields:
    if ((sail_len) == (0)):
        return EMPTY_CODE_SLICE
    else:
        return code_db_intern_memory(memory_sub_slice(memory_expand_to((int(off) + int(sail_len))), off, sail_len))

def memory_frame_enter() -> MemorySlice:
    global evm_memory
    parent = evm_memory
    base = _host_mem_frame_enter()
    evm_memory = memory_slice(base, 0)
    return parent

def memory_frame_leave(parent: MemorySlice) -> None:
    global evm_memory
    _host_mem_frame_leave()
    evm_memory = parent
    return None

def suspend_frame() -> FrameCheckpoint:
    state = k_state_checkpoint()
    saved_pc = pc
    saved_gas = gas_remaining
    saved_state_gas = state_gas_remaining
    saved_state_spill = state_gas_spilled
    saved_refund = frame_refund
    saved_status = frame_status
    saved_message = message
    saved_depth = call_depth
    saved_code = frame_code
    saved_calldata = calldata
    _host_stack_enter_frame()
    saved_memory = memory_frame_enter()
    return FrameCheckpoint(state=Uint(state), pc=Uint(saved_pc), gas_remaining=Uint(saved_gas), state_gas_remaining=Uint(saved_state_gas), state_gas_spilled=state_gas_spill(saved_state_spill), refund=saved_refund, status=saved_status, message=saved_message, call_depth=frame_depth(saved_depth), code=saved_code, calldata=saved_calldata, memory=saved_memory)

def restore_frame(checkpoint: FrameCheckpoint) -> None:
    global call_depth, calldata, frame_code, frame_refund, frame_status, gas_remaining, message, pc, state_gas_remaining, state_gas_spilled
    _host_stack_leave_frame()
    memory_frame_leave(checkpoint.memory)
    pc = Uint(checkpoint.pc)
    gas_remaining = Uint(checkpoint.gas_remaining)
    state_gas_remaining = Uint(checkpoint.state_gas_remaining)
    state_gas_spilled = state_gas_spill(checkpoint.state_gas_spilled)
    frame_refund = checkpoint.refund
    frame_status = checkpoint.status
    message = checkpoint.message
    call_depth = operand_stack_height(checkpoint.call_depth)
    frame_code = checkpoint.code
    calldata = checkpoint.calldata
    return None

def mem_get_byte(off: code_chunk_index) -> Annotated[Bits, BitWidth(8)]:
    if is_running():
        return _host_mem_read_byte(off)
    else:
        return Bits(8, 0b00000000)

def mem_set_byte(off: code_chunk_index, v: Annotated[Bits, BitWidth(8)]) -> None:
    if is_running():
        return _host_mem_write_byte(off, v)
    else:
        return None

def mem_load(off: code_chunk_index) -> word:
    if is_running():
        return word(_host_mem_load_word(off))
    else:
        return word(ZERO_WORD)

def mem_store(off: code_chunk_index, w: word) -> None:
    if is_running():
        return _host_mem_store_word(off, w)
    else:
        return None

def mem_store_byte(off: code_chunk_index, w: word) -> None:
    return mem_set_byte(off, word_low_byte(w))

def mem_mcopy(dst: code_chunk_index, src: code_chunk_index, sail_len: code_chunk_index) -> None:
    if ((sail_len) != (0)):
        return _host_mem_move(dst, src, sail_len)
    else:
        return None

def mem_codecopy(dst: code_chunk_index, off: code_chunk_index, sail_len: code_chunk_index) -> None:
    return code_slice_copy(frame_code.bytes, dst, off, sail_len)

def mem_keccak(sail_range_: MemoryRange) -> word:
    return word(hash_to_word(_host_memory_keccak256(active_memory_slice(sail_range_.off, sail_range_.len))))

pc: code_pointer = 0

gas_remaining: gas = GAS_ZERO

state_gas_remaining: gas = GAS_ZERO

state_gas_spilled: state_gas_spill = STATE_GAS_SPILL_ZERO

frame_refund: gas_refund = GAS_REFUND_ZERO

frame_status: FrameStatus = Running(None)

message: Message = DEFAULT_MESSAGE

call_depth: frame_depth = 0

frame_code: Code = EMPTY_CODE

STACK_LIMIT: int = 1024

calldata: CalldataSlice = EMPTY_CALLDATA

returndata: OutputSlice = EMPTY_OUTPUT_SLICE

evm_memory: MemorySlice = EMPTY_MEMORY_SLICE

def _reset_registers() -> None:
    global pc, gas_remaining, state_gas_remaining, state_gas_spilled, frame_refund, frame_status, message, call_depth, frame_code, calldata, returndata, evm_memory
    pc = 0
    gas_remaining = GAS_ZERO
    state_gas_remaining = GAS_ZERO
    state_gas_spilled = STATE_GAS_SPILL_ZERO
    frame_refund = GAS_REFUND_ZERO
    frame_status = Running(None)
    message = DEFAULT_MESSAGE
    call_depth = 0
    frame_code = EMPTY_CODE
    calldata = EMPTY_CALLDATA
    returndata = EMPTY_OUTPUT_SLICE
    evm_memory = EMPTY_MEMORY_SLICE
    return None
