# Generated by Sail's Python backend. Do not edit by hand.
# Sail source: evm/precompiles.sail
from __future__ import annotations

from .._runtime import (
    Bits,
    Bytes20,
    Bytes32,
    IntegerRange,
    sail_ediv_int,
    sail_tmod_int,
    sail_vector_access,
    sail_vector_update,
)
from dataclasses import dataclass
from typing import Annotated
from evm.HostContract import (
    accelerator_blake2f as _host_accelerator_blake2f,
    accelerator_bls_g1_add as _host_accelerator_bls_g1_add,
    accelerator_bls_g1_msm as _host_accelerator_bls_g1_msm,
    accelerator_bls_g2_add as _host_accelerator_bls_g2_add,
    accelerator_bls_g2_msm as _host_accelerator_bls_g2_msm,
    accelerator_bls_map_fp2_to_g2 as _host_accelerator_bls_map_fp2_to_g2,
    accelerator_bls_map_fp_to_g1 as _host_accelerator_bls_map_fp_to_g1,
    accelerator_bls_pairing as _host_accelerator_bls_pairing,
    accelerator_bn254_add as _host_accelerator_bn254_add,
    accelerator_bn254_mul as _host_accelerator_bn254_mul,
    accelerator_bn254_pairing as _host_accelerator_bn254_pairing,
    accelerator_kzg_point_evaluation as _host_accelerator_kzg_point_evaluation,
    accelerator_modexp as _host_accelerator_modexp,
    accelerator_p256_verify as _host_accelerator_p256_verify,
    accelerator_ripemd160 as _host_accelerator_ripemd160,
)
from evm._sail.vector import neq_bits
from evm.prelude import (
    address,
    u256,
    hash_to_word,
    word_to_hash,
    word_to_address,
    address_to_word,
    WORD_ZERO,
    WORD_ONE,
)
from evm.primitives.quantities import (
    ancestor_hash_count,
    precompile_id,
)
from evm.primitives.bytes import (
    CalldataSlice,
    OutputSlice,
    calldata_slice_length,
    calldata_sub_slice,
    WORD_BYTE_LENGTH,
    DOUBLE_WORD_BYTE_LENGTH,
    EMPTY_OUTPUT_SLICE,
)
from evm.host.accelerators import pairing_check_result
from evm.host.region_access import (
    calldata_slice_byte,
    slice_strided_zero,
    calldata_slice_load,
)
from evm.primitives.crypto import (
    calldata_sha256,
    ecrecover_addr,
)
from evm.primitives.fork import (
    Byzantium,
    Istanbul,
    Cancun,
    Prague,
    Osaka,
)
from evm.host.output import (
    output_buffer_slice,
    freeze_calldata_output,
    output_buffer_word,
    output_buffer_words,
)
from evm.evm.gas import (
    pc_word,
    pc_blake2_rounds,
)
from evm.kernel import environment

@dataclass(slots=True)
class PrecompileResult:
    success: bool
    output: OutputSlice

def precompile_success(output: OutputSlice) -> PrecompileResult:
    return PrecompileResult(success=True, output=output)

def precompile_failure() -> PrecompileResult:
    return PrecompileResult(success=False, output=EMPTY_OUTPUT_SLICE)

def accelerator_result(success: bool, output_len: int) -> PrecompileResult:
    if success:
        return precompile_success(output_buffer_slice(output_len))
    else:
        return precompile_failure()

def copied_result(data: CalldataSlice) -> PrecompileResult:
    output = freeze_calldata_output(data)
    if ((output.len) == (calldata_slice_length(data))):
        return precompile_success(output)
    else:
        return precompile_failure()

def boolean_result(value: bool) -> PrecompileResult:
    return precompile_success(output_buffer_word((WORD_ONE if value else WORD_ZERO)))

def precompile_active_at_fork(n: precompile_id) -> bool:
    execution_profile = environment.k_execution_profile
    profile = execution_profile.protocol
    base = (int(n) <= 4)
    byzantium = (((5 <= int(n))) & ((((int(n) <= 8)) & ((int(profile.fork) >= int(Byzantium))))))
    istanbul = ((((n) == (9))) & ((int(profile.fork) >= int(Istanbul))))
    kzg = ((((n) == (10))) & ((int(profile.fork) >= int(Cancun))))
    bls = (((11 <= int(n))) & ((((int(n) <= 17)) & ((int(profile.fork) >= int(Prague))))))
    p256 = ((((n) == (256))) & ((int(profile.fork) >= int(Osaka))))
    return ((base) | (((byzantium) | (((istanbul) | (((kzg) | (((bls) | (p256))))))))))

def precompile_number(bytes: address) -> ancestor_hash_count:
    selector = (int((int(sail_vector_access(bytes, 18, False)) * 256)) + int(sail_vector_access(bytes, 19, False)))
    match selector:
        case 1:
            if ((bytes) == (PRECOMPILE_ADDRESS_1)):
                candidate = 1
            else:
                candidate = 0
        case 2:
            if ((bytes) == (PRECOMPILE_ADDRESS_2)):
                candidate = 2
            else:
                candidate = 0
        case 3:
            if ((bytes) == (PRECOMPILE_ADDRESS_3)):
                candidate = 3
            else:
                candidate = 0
        case 4:
            if ((bytes) == (PRECOMPILE_ADDRESS_4)):
                candidate = 4
            else:
                candidate = 0
        case 5:
            if ((bytes) == (PRECOMPILE_ADDRESS_5)):
                candidate = 5
            else:
                candidate = 0
        case 6:
            if ((bytes) == (PRECOMPILE_ADDRESS_6)):
                candidate = 6
            else:
                candidate = 0
        case 7:
            if ((bytes) == (PRECOMPILE_ADDRESS_7)):
                candidate = 7
            else:
                candidate = 0
        case 8:
            if ((bytes) == (PRECOMPILE_ADDRESS_8)):
                candidate = 8
            else:
                candidate = 0
        case 9:
            if ((bytes) == (PRECOMPILE_ADDRESS_9)):
                candidate = 9
            else:
                candidate = 0
        case 10:
            if ((bytes) == (PRECOMPILE_ADDRESS_10)):
                candidate = 10
            else:
                candidate = 0
        case 11:
            if ((bytes) == (PRECOMPILE_ADDRESS_11)):
                candidate = 11
            else:
                candidate = 0
        case 12:
            if ((bytes) == (PRECOMPILE_ADDRESS_12)):
                candidate = 12
            else:
                candidate = 0
        case 13:
            if ((bytes) == (PRECOMPILE_ADDRESS_13)):
                candidate = 13
            else:
                candidate = 0
        case 14:
            if ((bytes) == (PRECOMPILE_ADDRESS_14)):
                candidate = 14
            else:
                candidate = 0
        case 15:
            if ((bytes) == (PRECOMPILE_ADDRESS_15)):
                candidate = 15
            else:
                candidate = 0
        case 16:
            if ((bytes) == (PRECOMPILE_ADDRESS_16)):
                candidate = 16
            else:
                candidate = 0
        case 17:
            if ((bytes) == (PRECOMPILE_ADDRESS_17)):
                candidate = 17
            else:
                candidate = 0
        case 256:
            if ((bytes) == (PRECOMPILE_ADDRESS_256)):
                candidate = 256
            else:
                candidate = 0
        case _:
            candidate = 0
    if ((candidate) != (0)):
        id = candidate
        if precompile_active_at_fork(id):
            return ancestor_hash_count(id)
        else:
            return ancestor_hash_count(0)
    else:
        return ancestor_hash_count(0)

def run_ecrecover(input: CalldataSlice) -> PrecompileResult:
    v = calldata_slice_load(input, PRECOMPILE_WORD_OFFSET)
    valid_v = ((((v) == (u256(27)))) | (((v) == (u256(28)))))
    if valid_v:
        if ((v) == (u256(27))):
            parity = 0
        else:
            parity = 1
        (recovered, address) = ecrecover_addr(word_to_hash(calldata_slice_load(input, 0)), parity, calldata_slice_load(input, PRECOMPILE_DOUBLE_WORD_OFFSET), calldata_slice_load(input, ECRECOVER_S_OFFSET))
        if recovered:
            return precompile_success(output_buffer_word(address_to_word(address)))
        else:
            return precompile_success(EMPTY_OUTPUT_SLICE)
    else:
        return precompile_success(EMPTY_OUTPUT_SLICE)

def run_sha256(input: CalldataSlice) -> PrecompileResult:
    return precompile_success(output_buffer_word(hash_to_word(calldata_sha256(input))))

def run_ripemd160(input: CalldataSlice) -> PrecompileResult:
    return accelerator_result(_host_accelerator_ripemd160(input), PRECOMPILE_WORD_LENGTH)

def run_modexp(input: CalldataSlice) -> PrecompileResult:
    base_len = pc_word(input, 0, 32)
    exponent_len = pc_word(input, 32, 32)
    modulus_len = pc_word(input, 64, 32)
    if ((modulus_len) == (0)):
        return precompile_success(EMPTY_OUTPUT_SLICE)
    else:
        if (((int(ACCELERATOR_INPUT_MAX) < int(base_len))) | ((((int(ACCELERATOR_INPUT_MAX) < int(exponent_len))) | ((int(ACCELERATOR_INPUT_MAX) < int(modulus_len)))))):
            return precompile_failure()
        else:
            bounded_base = base_len
            bounded_exponent = exponent_len
            bounded_modulus = modulus_len
            input_end = (int((int((96 + int(bounded_base))) + int(bounded_exponent))) + int(bounded_modulus))
            if (int(ACCELERATOR_INPUT_MAX) < int(input_end)):
                return precompile_failure()
            else:
                return accelerator_result(_host_accelerator_modexp(input, bounded_base, bounded_exponent, bounded_modulus), bounded_modulus)

def pairing_result(result: pairing_check_result) -> PrecompileResult:
    if (int(result) < 2):
        return precompile_failure()
    else:
        return boolean_result(((sail_tmod_int(result, 2)) == (1)))

def run_blake2f(input: CalldataSlice) -> PrecompileResult:
    final_byte = calldata_slice_byte(input, BLAKE2F_FINAL_BLOCK_OFFSET)
    if ((((calldata_slice_length(input)) != (BLAKE2F_INPUT_LENGTH))) | (((neq_bits(final_byte, Bits(8, 0b00000000))) & (neq_bits(final_byte, Bits(8, 0b00000001)))))):
        return precompile_failure()
    else:
        if ((final_byte) == (Bits(8, 0b00000000))):
            final_block = 0
        else:
            final_block = 1
        return accelerator_result(_host_accelerator_blake2f(input, pc_blake2_rounds(input), final_block), BLAKE2F_OUTPUT_LENGTH)

def kzg_versioned_hash_matches(input: CalldataSlice) -> bool:
    commitment_hash = calldata_sha256(calldata_sub_slice(input, KZG_COMMITMENT_OFFSET, KZG_COMMITMENT_LENGTH))
    expected = commitment_hash
    expected = Bytes32(sail_vector_update(expected, 0, Bits(8, 0b00000001), False))
    return ((word_to_hash(calldata_slice_load(input, 0))) == (expected))

def run_kzg_point_evaluation(input: CalldataSlice) -> PrecompileResult:
    if ((calldata_slice_length(input)) != (KZG_INPUT_LENGTH)):
        return precompile_failure()
    else:
        if (not (kzg_versioned_hash_matches(input))):
            return precompile_failure()
        else:
            if _host_accelerator_kzg_point_evaluation(input):
                return precompile_success(output_buffer_words(FIELD_ELEMENTS_PER_BLOB, BLS_MODULUS))
            else:
                return precompile_failure()

def bls_g1_padding(input: CalldataSlice, base: int, stride: int, count: int) -> bool:
    return ((slice_strided_zero(input, base, stride, BLS_FIELD_PADDING_LENGTH, count)) & (slice_strided_zero(input, (int(base) + int(BLS_PADDED_FIELD_LENGTH)), stride, BLS_FIELD_PADDING_LENGTH, count)))

def bls_g2_padding(input: CalldataSlice, base: int, stride: int, count: int) -> bool:
    return ((slice_strided_zero(input, base, stride, BLS_FIELD_PADDING_LENGTH, count)) & (((slice_strided_zero(input, (int(base) + int(BLS_PADDED_FIELD_LENGTH)), stride, BLS_FIELD_PADDING_LENGTH, count)) & (((slice_strided_zero(input, (int(base) + int(BLS_G1_POINT_LENGTH)), stride, BLS_FIELD_PADDING_LENGTH, count)) & (slice_strided_zero(input, (int(base) + int(BLS_G2_FINAL_FIELD_OFFSET)), stride, BLS_FIELD_PADDING_LENGTH, count)))))))

def run_bls_g1_add(input: CalldataSlice) -> PrecompileResult:
    if ((calldata_slice_length(input)) != (BLS_G1_ADD_INPUT_LENGTH)):
        return precompile_failure()
    else:
        if (not (bls_g1_padding(input, 0, BLS_G1_POINT_LENGTH, TWO_COMPONENTS))):
            return precompile_failure()
        else:
            return accelerator_result(_host_accelerator_bls_g1_add(input), BLS_G1_POINT_LENGTH)

def run_bls_g1_msm(input: CalldataSlice) -> PrecompileResult:
    length = calldata_slice_length(input)
    item_length = BLS_G1_MSM_ITEM_LENGTH
    pairs = sail_ediv_int(length, item_length)
    if ((((length) == (0))) | (((length) != ((int(pairs) * int(item_length)))))):
        return precompile_failure()
    else:
        if (not (bls_g1_padding(input, 0, BLS_G1_MSM_ITEM_LENGTH, pairs))):
            return precompile_failure()
        else:
            return accelerator_result(_host_accelerator_bls_g1_msm(input), BLS_G1_POINT_LENGTH)

def run_bls_g2_add(input: CalldataSlice) -> PrecompileResult:
    if ((calldata_slice_length(input)) != (BLS_G2_ADD_INPUT_LENGTH)):
        return precompile_failure()
    else:
        if (not (bls_g2_padding(input, 0, BLS_G2_POINT_LENGTH, TWO_COMPONENTS))):
            return precompile_failure()
        else:
            return accelerator_result(_host_accelerator_bls_g2_add(input), BLS_G2_POINT_LENGTH)

def run_bls_g2_msm(input: CalldataSlice) -> PrecompileResult:
    length = calldata_slice_length(input)
    item_length = BLS_G2_MSM_ITEM_LENGTH
    pairs = sail_ediv_int(length, item_length)
    if ((((length) == (0))) | (((length) != ((int(pairs) * int(item_length)))))):
        return precompile_failure()
    else:
        if (not (bls_g2_padding(input, 0, BLS_G2_MSM_ITEM_LENGTH, pairs))):
            return precompile_failure()
        else:
            return accelerator_result(_host_accelerator_bls_g2_msm(input), BLS_G2_POINT_LENGTH)

def run_bls_pairing(input: CalldataSlice) -> PrecompileResult:
    length = calldata_slice_length(input)
    item_length = BLS_PAIRING_ITEM_LENGTH
    pairs = sail_ediv_int(length, item_length)
    if ((((length) == (0))) | (((length) != ((int(pairs) * int(item_length)))))):
        return precompile_failure()
    else:
        pair_count = pairs
        if ((bls_g1_padding(input, 0, BLS_PAIRING_ITEM_LENGTH, pair_count)) & (bls_g2_padding(input, BLS_G2_POINT_OFFSET, BLS_PAIRING_ITEM_LENGTH, pair_count))):
            return pairing_result(_host_accelerator_bls_pairing(input))
        else:
            return precompile_failure()

def run_bls_map_fp_to_g1(input: CalldataSlice) -> PrecompileResult:
    if ((calldata_slice_length(input)) != (BLS_PADDED_FIELD_LENGTH)):
        return precompile_failure()
    else:
        if (not (slice_strided_zero(input, 0, BLS_PADDED_FIELD_LENGTH, BLS_FIELD_PADDING_LENGTH, 1))):
            return precompile_failure()
        else:
            return accelerator_result(_host_accelerator_bls_map_fp_to_g1(input), BLS_G1_POINT_LENGTH)

def run_bls_map_fp2_to_g2(input: CalldataSlice) -> PrecompileResult:
    if ((calldata_slice_length(input)) != (BLS_G1_POINT_LENGTH)):
        return precompile_failure()
    else:
        if (not (slice_strided_zero(input, 0, BLS_PADDED_FIELD_LENGTH, BLS_FIELD_PADDING_LENGTH, TWO_COMPONENTS))):
            return precompile_failure()
        else:
            return accelerator_result(_host_accelerator_bls_map_fp2_to_g2(input), BLS_G2_POINT_LENGTH)

def run_p256_verify(input: CalldataSlice) -> PrecompileResult:
    if ((calldata_slice_length(input)) == (P256_INPUT_LENGTH)):
        verified = _host_accelerator_p256_verify(input)
    else:
        verified = False
    if verified:
        return precompile_success(output_buffer_word(WORD_ONE))
    else:
        return precompile_success(EMPTY_OUTPUT_SLICE)

def run_precompile_slice(num: precompile_id, input: CalldataSlice) -> PrecompileResult:
    match num:
        case 1:
            return run_ecrecover(input)
        case 2:
            return run_sha256(input)
        case 3:
            return run_ripemd160(input)
        case 4:
            return copied_result(input)
        case 5:
            return run_modexp(input)
        case 6:
            return accelerator_result(_host_accelerator_bn254_add(input), PRECOMPILE_DOUBLE_WORD_LENGTH)
        case 7:
            return accelerator_result(_host_accelerator_bn254_mul(input), PRECOMPILE_DOUBLE_WORD_LENGTH)
        case 8:
            input_length = calldata_slice_length(input)
            item_length = BN254_PAIRING_ITEM_LENGTH
            if ((input_length) == ((int(sail_ediv_int(input_length, item_length)) * int(item_length)))):
                return pairing_result(_host_accelerator_bn254_pairing(input))
            else:
                return precompile_failure()
        case 9:
            return run_blake2f(input)
        case 10:
            return run_kzg_point_evaluation(input)
        case 11:
            return run_bls_g1_add(input)
        case 12:
            return run_bls_g1_msm(input)
        case 13:
            return run_bls_g2_add(input)
        case 14:
            return run_bls_g2_msm(input)
        case 15:
            return run_bls_pairing(input)
        case 16:
            return run_bls_map_fp_to_g1(input)
        case 17:
            return run_bls_map_fp2_to_g2(input)
        case 256:
            return run_p256_verify(input)
        case _:
            return precompile_failure()

ACCELERATOR_INPUT_MAX: Annotated[int, IntegerRange(2097152, 2097152)] = 2097152

FIELD_ELEMENTS_PER_BLOB: int = u256(int(Bits(256, 0b0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001000000000000)))

BLS_MODULUS: int = u256(int(Bits(256, 0b0111001111101101101001110101001100101001100111010111110101001000001100110011100111011000000010000000100110100001110110000000010101010011101111011010010000000010111111111111111001011011111111101111111111111111111111111111111100000000000000000000000000000001)))

BLAKE2F_INPUT_LENGTH: Annotated[int, IntegerRange(213, 213)] = 213

BLAKE2F_FINAL_BLOCK_OFFSET: Annotated[int, IntegerRange(212, 212)] = 212

BLAKE2F_OUTPUT_LENGTH: Annotated[int, IntegerRange(64, 64)] = DOUBLE_WORD_BYTE_LENGTH

KZG_INPUT_LENGTH: Annotated[int, IntegerRange(192, 192)] = 192

KZG_COMMITMENT_OFFSET: Annotated[int, IntegerRange(96, 96)] = 96

KZG_COMMITMENT_LENGTH: Annotated[int, IntegerRange(48, 48)] = 48

BLS_FIELD_PADDING_LENGTH: Annotated[int, IntegerRange(16, 16)] = 16

BLS_PADDED_FIELD_LENGTH: Annotated[int, IntegerRange(64, 64)] = DOUBLE_WORD_BYTE_LENGTH

BLS_G1_POINT_LENGTH: Annotated[int, IntegerRange(128, 128)] = 128

BLS_G2_POINT_LENGTH: Annotated[int, IntegerRange(256, 256)] = 256

BLS_G2_FINAL_FIELD_OFFSET: Annotated[int, IntegerRange(192, 192)] = 192

BLS_G1_ADD_INPUT_LENGTH: Annotated[int, IntegerRange(256, 256)] = 256

BLS_G1_MSM_ITEM_LENGTH: Annotated[int, IntegerRange(160, 160)] = 160

BLS_G2_ADD_INPUT_LENGTH: Annotated[int, IntegerRange(512, 512)] = 512

BLS_G2_MSM_ITEM_LENGTH: Annotated[int, IntegerRange(288, 288)] = 288

BLS_PAIRING_ITEM_LENGTH: Annotated[int, IntegerRange(384, 384)] = 384

P256_INPUT_LENGTH: Annotated[int, IntegerRange(160, 160)] = 160

BN254_PAIRING_ITEM_LENGTH: Annotated[int, IntegerRange(192, 192)] = 192

PRECOMPILE_WORD_LENGTH: Annotated[int, IntegerRange(32, 32)] = WORD_BYTE_LENGTH

PRECOMPILE_DOUBLE_WORD_LENGTH: Annotated[int, IntegerRange(64, 64)] = DOUBLE_WORD_BYTE_LENGTH

PRECOMPILE_WORD_OFFSET: Annotated[int, IntegerRange(32, 32)] = 32

PRECOMPILE_DOUBLE_WORD_OFFSET: Annotated[int, IntegerRange(64, 64)] = 64

ECRECOVER_S_OFFSET: int = 96

TWO_COMPONENTS: Annotated[int, IntegerRange(2, 2)] = 2

BLS_G2_POINT_OFFSET: Annotated[int, IntegerRange(128, 128)] = 128

PRECOMPILE_ADDRESS_1: address = Bytes20(word_to_address(u256(1)))

PRECOMPILE_ADDRESS_2: address = Bytes20(word_to_address(u256(2)))

PRECOMPILE_ADDRESS_3: address = Bytes20(word_to_address(u256(3)))

PRECOMPILE_ADDRESS_4: address = Bytes20(word_to_address(u256(4)))

PRECOMPILE_ADDRESS_5: address = Bytes20(word_to_address(u256(5)))

PRECOMPILE_ADDRESS_6: address = Bytes20(word_to_address(u256(6)))

PRECOMPILE_ADDRESS_7: address = Bytes20(word_to_address(u256(7)))

PRECOMPILE_ADDRESS_8: address = Bytes20(word_to_address(u256(8)))

PRECOMPILE_ADDRESS_9: address = Bytes20(word_to_address(u256(9)))

PRECOMPILE_ADDRESS_10: address = Bytes20(word_to_address(u256(10)))

PRECOMPILE_ADDRESS_11: address = Bytes20(word_to_address(u256(11)))

PRECOMPILE_ADDRESS_12: address = Bytes20(word_to_address(u256(12)))

PRECOMPILE_ADDRESS_13: address = Bytes20(word_to_address(u256(13)))

PRECOMPILE_ADDRESS_14: address = Bytes20(word_to_address(u256(14)))

PRECOMPILE_ADDRESS_15: address = Bytes20(word_to_address(u256(15)))

PRECOMPILE_ADDRESS_16: address = Bytes20(word_to_address(u256(16)))

PRECOMPILE_ADDRESS_17: address = Bytes20(word_to_address(u256(17)))

PRECOMPILE_ADDRESS_256: address = Bytes20(word_to_address(u256(256)))
