# Generated by Sail's Python backend. Do not edit by hand.
# Sail source: evm/transaction.sail
from __future__ import annotations

from .._runtime import (
    Bits,
    Bytes20,
    IntegerRange,
    SailMatchFailure,
    SailReturn,
    SailThrown,
    Uint,
    Unsigned,
    sail_ediv_int,
    sail_range,
    sail_vector_access,
)
from copy import deepcopy
from dataclasses import dataclass, replace
from typing import Annotated
from pydantic import ConfigDict, model_validator
from pydantic.dataclasses import dataclass as pydantic_dataclass
from typing_extensions import Self
from evm.HostContract import (
    authorization_tracker_commit as _host_authorization_tracker_commit,
    authorization_tracker_delegation_set as _host_authorization_tracker_delegation_set,
    authorization_tracker_originally_delegated as _host_authorization_tracker_originally_delegated,
    authorization_tracker_reset as _host_authorization_tracker_reset,
    authorization_tracker_seen as _host_authorization_tracker_seen,
    stack_reset as _host_stack_reset,
)
from evm._sail.vector import neq_bits
from evm.prelude import (
    address,
    word,
    word_to_address,
    word_add_word,
    word_sub_word,
    word_is_zero,
    word_nonzero,
    word_ule,
    ZERO_WORD,
    ZERO_ADDRESS,
)
from evm.primitives.quantities import (
    account_nonce,
    excess_blob_gas,
    frame_depth,
    transaction_blob_gas,
    word_to_account_nonce,
    word_of_chain_identifier,
    precompile_id_to_address,
)
from evm.primitives.gas import (
    block_gas,
    block_gas_limit,
    gas_cost,
    gas_refund,
    receipt_cumulative_gas,
    transaction_state_gas_delta,
    STATE_GAS_SPILL_ZERO,
    GAS_ZERO,
    GAS_REFUND_ZERO,
    FRAME_STATE_GAS_DELTA_ZERO,
    STATE_GAS_DELTA_ZERO,
)
from evm.primitives.bytes import (
    InputCalldata,
    stateless_input_slice,
    EMPTY_CALLDATA,
)
from evm.exceptions import (
    BlockError,
    ExceptionKind,
    InvalidBlock,
)
from evm.evm.halt import (
    HaltReturn,
    Halted,
    Running,
)
from evm.primitives.code import (
    CodeSlice,
    EMPTY_CODE_SLICE,
    EMPTY_CODE,
)
from evm.primitives.rlp import RlpCursor
from evm.host.region_access import (
    output_byte,
    slice_count_nonzero,
)
from evm.primitives.crypto import KECCAK_EMPTY
from evm.primitives.fork import (
    Homestead,
    Berlin,
    London,
    Shanghai,
    Cancun,
    Prague,
    Amsterdam,
)
from evm.primitives.chain_config import ProtocolProfile
from evm.primitives.tx import (
    Authorization,
    AuthorizationListRef,
    Receipt,
    Transaction,
    TransactionInputSlice,
    TxType,
    transaction_calldata_cost,
    transaction_calldata_floor_cost,
    tx_is_access_list,
    tx_is_dynamic_fee,
    tx_is_blob,
    tx_is_set_code,
)
from evm.primitives.evm import (
    Message,
    TransactionGasAllowance,
    TransactionGasAllowanceFields,
    TransactionGasAllowanceFieldsValidity,
    TxFrameResult,
    TxValidity,
    tx_env,
)
from evm.host.code import (
    code_db_insert,
    code_db_intern_input,
    code_db_intern_output,
    code_db_resolve,
)
from evm.lib.rlp.rlp import (
    rlp_decode_list,
    rlp_decode_item,
    rlp_cursor_advance,
    rlp_cursor_expect_end,
    rlp_decode_word,
)
from evm.lib.tx import (
    tx_sig_v_valid,
    tx_y_parity,
    tx_auth_valid,
)
from evm.lib.rlp.tx import decode_authorization
from evm.kernel.environment import (
    k_coinbase,
    k_create_addr,
)
from evm.kernel.storage import (
    k_access_account,
    k_slot_is_warm,
)
from evm.kernel.logs import read_logs
from evm.kernel.accounts import (
    k_aload,
    k_get_balance,
    k_get_nonce,
    k_account_exists,
    k_account_is_empty,
    k_account_occupied,
    k_transfer,
    k_bump_nonce,
    k_add_balance,
    k_sub_balance,
    k_clear_storage,
)
from evm.kernel.code import (
    k_code_key,
    k_deploy_code,
    k_set_delegation,
    k_clear_code,
    k_deleg_target,
)
from evm.kernel.selfdestruct import k_mark_created
from evm.kernel.lifecycle import (
    k_state_checkpoint,
    k_set_tx,
    k_tx_reset,
    k_tx_merge,
    k_revert,
)
from evm.evm.machine import (
    validated_refund_add,
    conserved_gas_add,
    frame_state_gas_used,
    exc_halt,
    is_running,
    returndata_clear,
    memory_reset,
)
from evm.evm.gas import (
    protocol_word,
    blob_base_fee,
    deployed_code_size_allowed,
    initcode_size_allowed,
    charge,
    charge_state_gas,
    charge_deployment_state_gas,
    gas_sub_or_oog,
    account_cost,
    code_deployment_execution_cost,
    code_deployment_state_cost,
    precompile_gas,
    transaction_initcode_gas,
    G_amsterdam_account_write,
    G_amsterdam_state_new_account,
    G_amsterdam_state_auth_base,
)
from evm.evm.precompiles import (
    precompile_active_at_fork,
    precompile_number,
    run_precompile_slice,
)
from evm.evm.interpreter import (
    interpret,
    frame_succeeded,
    executable_code,
)
from evm.kernel import environment
from evm.evm import machine

@dataclass(slots=True)
class IntrinsicGasCost:
    execution: gas_cost
    state: gas_cost
    calldata_floor: gas_cost

@dataclass(slots=True)
class TransactionCosts:
    intrinsic_execution: gas_cost
    intrinsic_state: gas_cost
    calldata_floor: gas_cost
    blob_gas: transaction_blob_gas
    blob_fee: word
    upfront: word

def transaction_initcode_slice(input: TransactionInputSlice) -> CodeSlice:
    return code_db_intern_input(stateless_input_slice(input.off, input.len))

@pydantic_dataclass(config=ConfigDict(strict=True, validate_assignment=True, revalidate_instances="always", arbitrary_types_allowed=True), slots=True, kw_only=True)
class TxUpfrontResult:
    authorization_refund: gas_refund
    create_target_prestate_empty: bool

    @model_validator(mode="after")
    def validate(self) -> Self:
        if not (((-(199 * ((2 ** 64) - 1))) <= int(self.authorization_refund) <= (199 * ((2 ** 64) - 1)))):
            raise ValueError("TxUpfrontResult.authorization_refund violates Sail type range(- (199 * (2 ^ 64 - 1)), (199 * (2 ^ 64 - 1)))")
        return self

def calldata_cost(input: TransactionInputSlice) -> transaction_calldata_cost:
    nonzeroes = slice_count_nonzero(input)
    input_len = input.len
    if (int(nonzeroes) <= int(input_len)):
        zeroes = (int(input_len) - int(nonzeroes))
        return transaction_calldata_cost((int((int(G_txdatazero) * int(zeroes))) + int((int(G_txdatanonzero) * int(nonzeroes)))))
    else:
        raise SailThrown(InvalidBlock(BlockError.ExecutionInvalid))

def calldata_tokens(input: TransactionInputSlice) -> Uint:
    nonzeroes = slice_count_nonzero(input)
    input_len = input.len
    if (int(nonzeroes) <= int(input_len)):
        zeroes = (int(input_len) - int(nonzeroes))
    else:
        raise SailThrown(InvalidBlock(BlockError.ExecutionInvalid))
    return Uint((int(zeroes) + int((4 * int(nonzeroes)))))

def legacy_intrinsic_gas(tx: Transaction) -> receipt_cumulative_gas:
    data_cost = calldata_cost(tx.input_src)
    input = tx.input_src
    input_len = input.len
    address_cost = (int(G_access_list_address) * int(tx.access_list.address_count))
    slot_cost = (int(G_access_list_storage_key) * int(tx.access_list.slot_count))
    auth_cost = (int(PER_EMPTY_ACCOUNT) * int(tx.authorizations.count))
    common = (int((int((int((int(data_cost) + int(G_transaction))) + int(address_cost))) + int(slot_cost))) + int(auth_cost))
    if tx.is_create:
        return Uint((int((int(common) + int(G_txcreate))) + int(transaction_initcode_gas(input_len))))
    else:
        return Uint(common)

def legacy_calldata_floor(input: TransactionInputSlice) -> transaction_calldata_floor_cost:
    nonzeroes = slice_count_nonzero(input)
    input_len = input.len
    if (int(nonzeroes) <= int(input_len)):
        zeroes = (int(input_len) - int(nonzeroes))
        return transaction_calldata_floor_cost((int((int((10 * int(zeroes))) + int((40 * int(nonzeroes))))) + int(G_transaction)))
    else:
        raise SailThrown(InvalidBlock(BlockError.ExecutionInvalid))

class amsterdam_recipient_cost(Unsigned):
    LOWER = 0
    UPPER = 12756

    def _in_range(self, value: int) -> bool:
        return self.LOWER <= value <= self.UPPER

def amsterdam_recipient_execution_cost(tx: Transaction) -> amsterdam_recipient_cost:
    if tx.is_create:
        if word_nonzero(tx.value):
            return amsterdam_recipient_cost((int(AMSTERDAM_CREATE_ACCESS) + int(AMSTERDAM_TRANSFER_LOG_COST)))
        else:
            return amsterdam_recipient_cost(AMSTERDAM_CREATE_ACCESS)
    else:
        if ((tx.recipient) != (tx.sender)):
            if word_nonzero(tx.value):
                return amsterdam_recipient_cost((int((int(AMSTERDAM_COLD_ACCOUNT_ACCESS) + int(AMSTERDAM_TX_VALUE_COST))) + int(AMSTERDAM_TRANSFER_LOG_COST)))
            else:
                return amsterdam_recipient_cost(AMSTERDAM_COLD_ACCOUNT_ACCESS)
        else:
            return amsterdam_recipient_cost(0)

def intrinsic_gas(tx: Transaction) -> IntrinsicGasCost:
    execution_profile = environment.k_execution_profile
    profile = execution_profile.protocol
    if (int(profile.fork) < int(Amsterdam)):
        return IntrinsicGasCost(execution=Uint(legacy_intrinsic_gas(tx)), state=Uint(0), calldata_floor=Uint(legacy_calldata_floor(tx.input_src)))
    else:
        input = tx.input_src
        recipient = amsterdam_recipient_execution_cost(tx)
        address_count = tx.access_list.address_count
        slot_count = tx.access_list.slot_count
        access_execution = (int((int((int((int(AMSTERDAM_ACCESS_LIST_ADDRESS) * int(address_count))) + int((int(AMSTERDAM_ACCESS_LIST_SLOT) * int(slot_count))))) + int((int(AMSTERDAM_ACCESS_LIST_ADDRESS_FLOOR) * int(address_count))))) + int((int(AMSTERDAM_ACCESS_LIST_SLOT_FLOOR) * int(slot_count))))
        authorization_execution = (int(AMSTERDAM_AUTH_BASE) * int(tx.authorizations.count))
        if tx.is_create:
            create_execution = transaction_initcode_gas(input.len)
        else:
            create_execution = 0
        execution = (int((int((int((int((int(calldata_cost(tx.input_src)) + int(AMSTERDAM_TX_BASE))) + int(recipient))) + int(access_execution))) + int(authorization_execution))) + int(create_execution))
        input_length = input.len
        floor = (int((int((int((int((int(AMSTERDAM_CALLDATA_FLOOR_BYTE) * int(input_length))) + int(AMSTERDAM_TX_BASE))) + int(recipient))) + int((int(AMSTERDAM_ACCESS_LIST_ADDRESS_FLOOR) * int(address_count))))) + int((int(AMSTERDAM_ACCESS_LIST_SLOT_FLOOR) * int(slot_count))))
        return IntrinsicGasCost(execution=Uint(execution), state=Uint(0), calldata_floor=Uint(floor))

def transaction_blob_fee(blob_price: int, blob_gas: int) -> int:
    return (int(blob_price) * int(blob_gas))

def transaction_upfront_cost(max_fee: int, gas_limit: int, value: int, max_blob_fee: int, blob_gas: int) -> int:
    return (int((int((int(max_fee) * int(gas_limit))) + int(value))) + int((int(max_blob_fee) * int(blob_gas))))

def transaction_costs(profile: ProtocolProfile, tx: Transaction, gas_limit: block_gas, excess_blob_gas: excess_blob_gas) -> TransactionCosts:
    intrinsic = intrinsic_gas(tx)
    blob_gas = (int((1 << 17)) * int(tx.blob_hashes.count))
    if ((blob_gas) == (0)):
        blob_fee_value = 0
    else:
        blob_price = blob_base_fee(profile, excess_blob_gas)
        if (int(blob_price) <= int(tx.max_blob_fee)):
            blob_fee_value = transaction_blob_fee(blob_price, blob_gas)
        else:
            raise SailThrown(InvalidBlock(BlockError.ExecutionInvalid))
    upfront_value = transaction_upfront_cost(tx.max_fee, gas_limit, tx.value, tx.max_blob_fee, blob_gas)
    if (((int(blob_fee_value) < int((1 << 256)))) & ((int(upfront_value) < int((1 << 256))))):
        return TransactionCosts(intrinsic_execution=Uint(intrinsic.execution), intrinsic_state=Uint(intrinsic.state), calldata_floor=Uint(intrinsic.calldata_floor), blob_gas=blob_gas, blob_fee=word(protocol_word(blob_fee_value)), upfront=word(protocol_word(upfront_value)))
    else:
        raise SailThrown(InvalidBlock(BlockError.ExecutionInvalid))

def validated_word_product(value: word, factor: int) -> word:
    product = (int(value) * int(factor))
    if (int(product) < int((1 << 256))):
        return word(protocol_word(product))
    else:
        raise SailThrown(InvalidBlock(BlockError.ExecutionInvalid))

def validated_gas_add(left_gas: receipt_cumulative_gas, right_gas: receipt_cumulative_gas) -> receipt_cumulative_gas:
    return Uint(conserved_gas_add(left_gas, right_gas))

def validated_gas_sub(left: int, right: int) -> Uint:
    if (int(right) <= int(left)):
        return Uint((int(left) - int(right)))
    else:
        raise SailThrown(InvalidBlock(BlockError.ExecutionInvalid))

def transaction_gas_allowance_fields(value: int, _total_limit: int, regular_limit: int) -> TransactionGasAllowanceFields:
    if (int(value) < int(regular_limit)):
        regular = value
    else:
        regular = regular_limit
    return TransactionGasAllowanceFields(validity=TransactionGasAllowanceFieldsValidity(total=int(value), regular=(int(value) if (int(value) < int(regular_limit)) else int(regular_limit))), total=int(value), regular=int(regular))

def transaction_gas_allowance(value: int, total_limit: int, regular_limit: int) -> TransactionGasAllowance:
    if (int(total_limit) < int(value)):
        raise SailThrown(InvalidBlock(BlockError.ExecutionInvalid))
    else:
        return transaction_gas_allowance_fields(value, total_limit, regular_limit)

def transaction_initial_gas(allowance: TransactionGasAllowanceFields, intrinsic_execution: int, intrinsic_state: int) -> tuple[receipt_cumulative_gas, receipt_cumulative_gas]:
    if (int(allowance.total) < int(intrinsic_execution)):
        raise SailThrown(InvalidBlock(BlockError.ExecutionInvalid))
    else:
        after_execution = (int(allowance.total) - int(intrinsic_execution))
        if (int(after_execution) < int(intrinsic_state)):
            raise SailThrown(InvalidBlock(BlockError.ExecutionInvalid))
        else:
            if (int(allowance.regular) < int(intrinsic_execution)):
                raise SailThrown(InvalidBlock(BlockError.ExecutionInvalid))
            else:
                available = (int(after_execution) - int(intrinsic_state))
                regular_budget = (int(allowance.regular) - int(intrinsic_execution))
                if (int(available) < int(regular_budget)):
                    return (available, GAS_ZERO)
                else:
                    return (regular_budget, (int(available) - int(regular_budget)))

def process_auth(au: Authorization) -> gas_refund:
    refund = GAS_REFUND_ZERO
    authority = au.authority
    if ((au.valid_sig) & (((word_is_zero(au.chain_id)) | (((au.chain_id) == (word_of_chain_identifier(environment.k_chain_id))))))):
        k_access_account(authority)
        (is_deleg, _) = k_deleg_target(authority)
        if ((((((k_code_key(authority)) == (KECCAK_EMPTY))) | (is_deleg))) & (((k_get_nonce(authority)) == (au.nonce)))):
            existed = k_account_exists(authority)
            if ((au.address) == (ZERO_ADDRESS)):
                k_clear_code(authority)
            else:
                k_set_delegation(authority, au.address)
            k_bump_nonce(authority)
            if existed:
                refund = (int(PER_EMPTY_ACCOUNT) - int(PER_AUTH_BASE))
    return refund

def process_auth_cursor(cursor: RlpCursor) -> gas_refund:
    if ((cursor.len) == (0)):
        return GAS_REFUND_ZERO
    else:
        sail_tuple = rlp_decode_item(cursor)
        next = rlp_cursor_advance(cursor, sail_tuple.source.len)
        return validated_refund_add(process_auth(decode_authorization(sail_tuple)), process_auth_cursor(next))

def process_auth_list(authorizations: AuthorizationListRef) -> gas_refund:
    encoded = authorizations.encoded
    return process_auth_cursor(encoded)

def process_amsterdam_auth(au: Authorization, sender: address, current_target: address, transfers_value: bool) -> None:
    authority = au.authority
    if ((au.valid_sig) & (((word_is_zero(au.chain_id)) | (((au.chain_id) == (word_of_chain_identifier(environment.k_chain_id))))))):
        k_access_account(authority)
        (currently_delegated, _) = k_deleg_target(authority)
        if ((((((k_code_key(authority)) == (KECCAK_EMPTY))) | (currently_delegated))) & (((k_get_nonce(authority)) == (au.nonce)))):
            seen = _host_authorization_tracker_seen(authority)
            if seen:
                delegated_before_tx = _host_authorization_tracker_originally_delegated(authority)
            else:
                delegated_before_tx = currently_delegated
            already_written = ((seen) | (((((authority) == (sender))) | (((transfers_value) & (((authority) == (current_target))))))))
            if (not (k_account_exists(authority))):
                charge_state_gas(G_amsterdam_state_new_account)
            if ((is_running()) & ((not (already_written)))):
                charge(G_amsterdam_account_write)
            if ((is_running()) & (((((au.address) != (ZERO_ADDRESS))) & ((((not (delegated_before_tx))) & ((not (_host_authorization_tracker_delegation_set(authority))))))))):
                charge_state_gas(G_amsterdam_state_auth_base)
            if is_running():
                if ((au.address) == (ZERO_ADDRESS)):
                    k_clear_code(authority)
                else:
                    k_set_delegation(authority, au.address)
                k_bump_nonce(authority)
                return _host_authorization_tracker_commit(authority, (((not (seen))) & (currently_delegated)), ((au.address) != (ZERO_ADDRESS)))
            else:
                return None
        else:
            return None
    else:
        return None

def process_amsterdam_auth_cursor(cursor: RlpCursor, sender: address, current_target: address, transfers_value: bool) -> None:
    if ((cursor.len) == (0)):
        return None
    else:
        sail_tuple = rlp_decode_item(cursor)
        next = rlp_cursor_advance(cursor, sail_tuple.source.len)
        process_amsterdam_auth(decode_authorization(sail_tuple), sender, current_target, transfers_value)
        if is_running():
            return process_amsterdam_auth_cursor(next, sender, current_target, transfers_value)
        else:
            return None

def warm_access_list_keys(cursor: RlpCursor, addr: address) -> None:
    if ((cursor.len) == (0)):
        return None
    else:
        key = rlp_decode_item(cursor)
        next = rlp_cursor_advance(cursor, key.source.len)
        k_slot_is_warm(addr, rlp_decode_word(key))
        return warm_access_list_keys(next, addr)

def warm_access_list(cursor: RlpCursor) -> None:
    if ((cursor.len) == (0)):
        return None
    else:
        entry = rlp_decode_item(cursor)
        next = rlp_cursor_advance(cursor, entry.source.len)
        fields = rlp_decode_list(entry)
        addr_f = rlp_decode_item(fields)
        fields = rlp_cursor_advance(fields, addr_f.source.len)
        keys_f = rlp_decode_item(fields)
        fields = rlp_cursor_advance(fields, keys_f.source.len)
        rlp_cursor_expect_end(fields)
        addr = word_to_address(rlp_decode_word(addr_f))
        k_access_account(addr)
        warm_access_list_keys(rlp_decode_list(keys_f), addr)
        return warm_access_list(next)

def prewarm(tx: Transaction) -> None:
    execution_profile = environment.k_execution_profile
    profile = execution_profile.protocol
    k_access_account(tx.sender)
    if tx.is_create:
        False
    else:
        k_access_account(tx.recipient)
    if (int(profile.fork) >= int(Shanghai)):
        k_access_account(k_coinbase())
    precompile_addresses = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17]
    for i in sail_range(0, 16, 1, True):
        p = sail_vector_access(precompile_addresses, i, False)
        if precompile_active_at_fork(p):
            k_access_account(precompile_id_to_address(p))
    if precompile_active_at_fork(256):
        k_access_account(precompile_id_to_address(256))
    access_list = tx.access_list.encoded
    return warm_access_list(access_list)

def eff_gas_price_for(base_fee: word, max_fee: word, max_priority_fee: word) -> tuple[word, word]:
    if word_ule(max_fee, base_fee):
        price = max_fee
    else:
        available_priority = word_sub_word(max_fee, base_fee)
        if word_ule(max_priority_fee, available_priority):
            price = word_add_word(base_fee, max_priority_fee)
        else:
            price = max_fee
    if word_ule(base_fee, price):
        priority = word_sub_word(price, base_fee)
    else:
        priority = ZERO_WORD
    return (price, priority)

def check_transaction_validity(tx: Transaction, allowance: TransactionGasAllowance) -> TxValidity:
    execution_profile = environment.k_execution_profile
    profile = execution_profile.protocol
    if (not (tx_sig_v_valid(environment.k_chain_id, tx.tx_type, tx.sig_v))):
        raise SailThrown(InvalidBlock(BlockError.InvalidSignature))
    parity = tx_y_parity(tx.tx_type, tx.sig_v)
    if (not (tx_auth_valid(tx.sender, tx.signing_hash, parity, tx.sig_r, tx.sig_s))):
        raise SailThrown(InvalidBlock(BlockError.InvalidSignature))
    gas_limit = allowance.total
    (eff_gas_price, eff_priority_fee) = eff_gas_price_for(environment.k_header.base_fee, tx.max_fee, tx.max_priority_fee)
    sender = tx.sender
    input = tx.input_src
    input_len = input.len
    nonce_before = k_get_nonce(sender)
    costs = transaction_costs(profile, tx, gas_limit, environment.k_header.excess_blob_gas)
    match word_to_account_nonce(tx.nonce):
        case (nonce as _sail_some_value_1) if _sail_some_value_1 is not None:
            nonce = nonce
        case None:
            raise SailThrown(InvalidBlock(BlockError.ExecutionInvalid))
        case _:
            raise SailMatchFailure("no Sail match clause applied")
    if ((nonce) != (nonce_before)):
        raise SailThrown(InvalidBlock(BlockError.ExecutionInvalid))
    (sender_deleg, _) = k_deleg_target(sender)
    if tx_is_blob(tx.tx_type):
        if (((int(profile.fork) < int(Cancun))) | (((((tx.blob_hashes.count) == (0))) | (tx.is_create)))):
            raise SailThrown(InvalidBlock(BlockError.ExecutionInvalid))
    if (((int(profile.fork) >= int(Prague))) & ((int(gas_limit) < int(costs.calldata_floor)))):
        raise SailThrown(InvalidBlock(BlockError.ExecutionInvalid))
    if (not (word_ule(costs.upfront, k_get_balance(sender)))):
        raise SailThrown(InvalidBlock(BlockError.ExecutionInvalid))
    if (not (((((k_code_key(sender)) == (KECCAK_EMPTY))) | (sender_deleg)))):
        raise SailThrown(InvalidBlock(BlockError.ExecutionInvalid))
    if (int(allowance.regular) < int(costs.calldata_floor)):
        raise SailThrown(InvalidBlock(BlockError.ExecutionInvalid))
    if (not (word_ule(environment.k_header.base_fee, tx.max_fee))):
        raise SailThrown(InvalidBlock(BlockError.ExecutionInvalid))
    if ((tx.is_create) & ((not (initcode_size_allowed(input_len))))):
        raise SailThrown(InvalidBlock(BlockError.ExecutionInvalid))
    if (not (word_ule(tx.max_priority_fee, tx.max_fee))):
        raise SailThrown(InvalidBlock(BlockError.ExecutionInvalid))
    if ((tx_is_access_list(tx.tx_type)) & ((int(profile.fork) < int(Berlin)))):
        raise SailThrown(InvalidBlock(BlockError.ExecutionInvalid))
    if ((tx_is_dynamic_fee(tx.tx_type)) & ((int(profile.fork) < int(London)))):
        raise SailThrown(InvalidBlock(BlockError.ExecutionInvalid))
    if ((tx_is_set_code(tx.tx_type)) & (tx.is_create)):
        raise SailThrown(InvalidBlock(BlockError.ExecutionInvalid))
    if ((tx_is_set_code(tx.tx_type)) & (((tx.authorizations.count) == (0)))):
        raise SailThrown(InvalidBlock(BlockError.ExecutionInvalid))
    if ((tx_is_set_code(tx.tx_type)) & ((int(profile.fork) < int(Prague)))):
        raise SailThrown(InvalidBlock(BlockError.ExecutionInvalid))
    match tx.tx_type:
        case TxType.LegacyTx:
            _sail_value_0 = False
        case _:
            _sail_value_0 = ((tx.chain_id) != (environment.k_chain_id))
    if _sail_value_0:
        raise SailThrown(InvalidBlock(BlockError.ExecutionInvalid))
    if ((nonce_before) == ((int((1 << 64)) - 1))):
        raise SailThrown(InvalidBlock(BlockError.ExecutionInvalid))
    (initial_execution_gas, initial_state_gas) = transaction_initial_gas(allowance, costs.intrinsic_execution, costs.intrinsic_state)
    return TxValidity(sender=Bytes20(sender), nonce_before=account_nonce(nonce_before), gas_limit=block_gas_limit(gas_limit), initial_execution_gas=Uint(initial_execution_gas), initial_state_gas=Uint(initial_state_gas), intrinsic_execution_gas=Uint(costs.intrinsic_execution), intrinsic_state_gas=Uint(costs.intrinsic_state), calldata_floor=Uint(costs.calldata_floor), blob_fee=word(costs.blob_fee), gas_price=word(eff_gas_price), priority_fee=word(eff_priority_fee))

def apply_transaction_upfront_effects(tx: Transaction, v: TxValidity) -> TxUpfrontResult:
    execution_profile = environment.k_execution_profile
    profile = execution_profile.protocol
    if (((int(profile.fork) >= int(Amsterdam))) & (tx.is_create)):
        create_target_prestate_empty = (not (k_account_exists(k_create_addr(v.sender, v.nonce_before))))
    else:
        create_target_prestate_empty = False
    k_sub_balance(v.sender, validated_word_product(v.gas_price, v.gas_limit))
    if word_nonzero(v.blob_fee):
        k_sub_balance(v.sender, v.blob_fee)
    k_bump_nonce(v.sender)
    prewarm(tx)
    if (int(profile.fork) < int(Amsterdam)):
        authorization_refund = process_auth_list(tx.authorizations)
    else:
        authorization_refund = GAS_REFUND_ZERO
    return TxUpfrontResult(authorization_refund=authorization_refund, create_target_prestate_empty=create_target_prestate_empty)

def enter_transaction_frame(v: TxValidity) -> None:
    machine.pc = 0
    machine.call_depth = 0
    machine.gas_remaining = Uint(v.initial_execution_gas)
    machine.state_gas_remaining = Uint(v.initial_state_gas)
    machine.state_gas_spilled = STATE_GAS_SPILL_ZERO
    machine.message = Message(caller=Bytes20(ZERO_ADDRESS), address=Bytes20(ZERO_ADDRESS), code_address=Bytes20(ZERO_ADDRESS), value=word(ZERO_WORD), state_gas_reservoir=Uint(machine.state_gas_remaining), is_static=False, depth=frame_depth(0))
    _host_stack_reset()
    memory_reset()
    returndata_clear()
    machine.calldata = EMPTY_CALLDATA
    machine.frame_code = EMPTY_CODE
    machine.frame_refund = GAS_REFUND_ZERO
    machine.frame_status = Running(None)
    return None

def prepare_amsterdam_transaction_dispatch(tx: Transaction, v: TxValidity, upfront: TxUpfrontResult) -> bool:
    execution_profile = environment.k_execution_profile
    profile = execution_profile.protocol
    if tx.is_create:
        current_target = k_create_addr(v.sender, v.nonce_before)
    else:
        current_target = tx.recipient
    machine.message = Message(caller=Bytes20(v.sender), address=Bytes20(current_target), code_address=Bytes20(current_target), value=word(tx.value), state_gas_reservoir=Uint(machine.state_gas_remaining), is_static=False, depth=frame_depth(0))
    if tx.is_create:
        if upfront.create_target_prestate_empty:
            charge_state_gas(G_amsterdam_state_new_account)
        if is_running():
            machine.frame_code = code_db_resolve(code_db_insert(transaction_initcode_slice(tx.input_src), profile.fork))
        return False
    else:
        machine.calldata = InputCalldata(tx.input_src)
        if ((word_nonzero(tx.value)) & (k_account_is_empty(tx.recipient))):
            charge_state_gas(G_amsterdam_state_new_account)
        delegated = False
        delegate = ZERO_ADDRESS
        if is_running():
            (is_delegated, target) = k_deleg_target(tx.recipient)
            delegated = is_delegated
            delegate = Bytes20(target)
            if delegated:
                warm = k_access_account(delegate)
                charge(account_cost(warm))
        if is_running():
            if delegated:
                machine.message = replace(deepcopy(machine.message), code_address=Bytes20(delegate))
            machine.frame_code = executable_code(tx.recipient, delegated, delegate)
        return delegated

def run_create_transaction_frame(tx: Transaction, sender: address, nonce_before: account_nonce) -> None:
    execution_profile = environment.k_execution_profile
    profile = execution_profile.protocol
    new_addr = k_create_addr(sender, nonce_before)
    k_access_account(new_addr)
    if k_account_occupied(new_addr):
        return exc_halt(ExceptionKind.AddressCollision)
    else:
        k_mark_created(new_addr)
        k_clear_storage(new_addr)
        k_bump_nonce(new_addr)
        if word_nonzero(tx.value):
            k_transfer(sender, new_addr, tx.value)
        if (int(profile.fork) < int(Amsterdam)):
            machine.message = Message(caller=Bytes20(sender), address=Bytes20(new_addr), code_address=Bytes20(new_addr), value=word(tx.value), state_gas_reservoir=Uint(machine.state_gas_remaining), is_static=False, depth=frame_depth(0))
            machine.frame_code = code_db_resolve(code_db_insert(transaction_initcode_slice(tx.input_src), profile.fork))
        deployed_code = interpret()
        if frame_succeeded():
            dep_len = deployed_code.len
            deployed_length = dep_len
            if ((deployed_code_size_allowed(deployed_length)) & ((((int(profile.fork) < int(London))) | (((((deployed_length) == (0))) | (neq_bits(output_byte(deployed_code, 0), Bits(8, 0b11101111)))))))):
                match code_deployment_execution_cost(dep_len, machine.gas_remaining):
                    case (execution_deposit as _sail_some_value_2) if _sail_some_value_2 is not None:
                        machine.gas_remaining = Uint(gas_sub_or_oog(machine.gas_remaining, execution_deposit))
                        charge_deployment_state_gas(code_deployment_state_cost(dep_len))
                        if frame_succeeded():
                            return k_deploy_code(new_addr, code_db_intern_output(deployed_code))
                        else:
                            return None
                    case None:
                        if (int(profile.fork) < int(Homestead)):
                            machine.gas_remaining = GAS_ZERO
                            return k_deploy_code(new_addr, EMPTY_CODE_SLICE)
                        else:
                            return exc_halt(ExceptionKind.OutOfGas)
                    case _:
                        raise SailMatchFailure("no Sail match clause applied")
            else:
                return exc_halt(ExceptionKind.OutOfGas)
        else:
            return None

def run_call_transaction_frame(tx: Transaction, sender: address, delegated: bool) -> None:
    execution_profile = environment.k_execution_profile
    profile = execution_profile.protocol
    k_aload(tx.recipient)
    if word_nonzero(tx.value):
        k_transfer(sender, tx.recipient, tx.value)
    selected_precompile = precompile_number(tx.recipient)
    if (((not (delegated))) & (((selected_precompile) != (0)))):
        number = selected_precompile
        input_src = tx.input_src
        precompile_input = InputCalldata(input_src)
        match precompile_gas(number, precompile_input, machine.gas_remaining):
            case (used as _sail_some_value_3) if _sail_some_value_3 is not None:
                result = run_precompile_slice(number, precompile_input)
                if result.success:
                    machine.gas_remaining = Uint(gas_sub_or_oog(machine.gas_remaining, used))
                    if is_running():
                        machine.frame_status = Halted(HaltReturn(result.output))
                        return None
                    else:
                        return None
                else:
                    return exc_halt(ExceptionKind.OutOfGas)
            case _:
                return exc_halt(ExceptionKind.OutOfGas)
    else:
        if (int(profile.fork) < int(Amsterdam)):
            machine.calldata = InputCalldata(tx.input_src)
            machine.message = Message(caller=Bytes20(sender), address=Bytes20(tx.recipient), code_address=Bytes20(tx.recipient), value=word(tx.value), state_gas_reservoir=Uint(machine.state_gas_remaining), is_static=False, depth=frame_depth(0))
            (tx_deleg, tx_dtgt) = k_deleg_target(tx.recipient)
            if tx_deleg:
                k_access_account(tx_dtgt)
                k_aload(tx_dtgt)
            machine.frame_code = executable_code(tx.recipient, tx_deleg, tx_dtgt)
        interpret()
        return None

def run_legacy_transaction_frame(tx: Transaction, v: TxValidity) -> TxFrameResult:
    checkpoint = k_state_checkpoint()
    enter_transaction_frame(v)
    if tx.is_create:
        run_create_transaction_frame(tx, v.sender, v.nonce_before)
    else:
        run_call_transaction_frame(tx, v.sender, False)
    success = frame_succeeded()
    if (not (success)):
        k_revert(checkpoint)
    return TxFrameResult(success=success, execution_gas_remaining=Uint(machine.gas_remaining), state_gas_remaining=Uint(machine.state_gas_remaining), state_gas_used=frame_state_gas_used(), refund=(machine.frame_refund if success else GAS_REFUND_ZERO))

def run_amsterdam_transaction_frame(tx: Transaction, v: TxValidity, upfront: TxUpfrontResult) -> TxFrameResult:
    try:
        enter_transaction_frame(v)
        preparation_checkpoint = k_state_checkpoint()
        preparation_reservoir = machine.state_gas_remaining
        if tx.is_create:
            current_target = k_create_addr(v.sender, v.nonce_before)
        else:
            current_target = tx.recipient
        _host_authorization_tracker_reset(tx.authorizations.count)
        authorizations = tx.authorizations.encoded
        process_amsterdam_auth_cursor(authorizations, v.sender, current_target, word_nonzero(tx.value))
        authorization_state_gas = FRAME_STATE_GAS_DELTA_ZERO
        delegated = False
        if is_running():
            authorization_state_gas = frame_state_gas_used()
            machine.message = replace(deepcopy(machine.message), state_gas_reservoir=Uint(machine.state_gas_remaining))
            machine.state_gas_spilled = STATE_GAS_SPILL_ZERO
            delegated = prepare_amsterdam_transaction_dispatch(tx, v, upfront)
        if (not (is_running())):
            k_revert(preparation_checkpoint)
            machine.message = replace(deepcopy(machine.message), state_gas_reservoir=Uint(preparation_reservoir))
            machine.state_gas_remaining = preparation_reservoir
            machine.state_gas_spilled = STATE_GAS_SPILL_ZERO
            raise SailReturn(TxFrameResult(success=False, execution_gas_remaining=Uint(machine.gas_remaining), state_gas_remaining=Uint(machine.state_gas_remaining), state_gas_used=STATE_GAS_DELTA_ZERO, refund=GAS_REFUND_ZERO))
        execution_checkpoint = k_state_checkpoint()
        if tx.is_create:
            run_create_transaction_frame(tx, v.sender, v.nonce_before)
        else:
            run_call_transaction_frame(tx, v.sender, delegated)
        success = frame_succeeded()
        if (not (success)):
            k_revert(execution_checkpoint)
        return TxFrameResult(success=success, execution_gas_remaining=Uint(machine.gas_remaining), state_gas_remaining=Uint(machine.state_gas_remaining), state_gas_used=(int(authorization_state_gas) + int(frame_state_gas_used())), refund=(machine.frame_refund if success else GAS_REFUND_ZERO))
    except SailReturn as _sail_return:
        return _sail_return.value

def run_transaction_frame(tx: Transaction, v: TxValidity, upfront: TxUpfrontResult) -> TxFrameResult:
    execution_profile = environment.k_execution_profile
    profile = execution_profile.protocol
    if (int(profile.fork) >= int(Amsterdam)):
        return run_amsterdam_transaction_frame(tx, v, upfront)
    else:
        return run_legacy_transaction_frame(tx, v)

def capped_transaction_refund(total: gas_refund, cap: int) -> Uint:
    if (int(total) <= 0):
        return Uint(0)
    else:
        if (int(total) <= int(cap)):
            return Uint(total)
        else:
            return Uint(cap)

def admitted_transaction_state_gas(value: transaction_state_gas_delta) -> receipt_cumulative_gas:
    if (int(value) <= 0):
        return Uint(GAS_ZERO)
    else:
        if (int(value) <= int((int((1 << 64)) - 1))):
            return Uint(value)
        else:
            raise SailThrown(InvalidBlock(BlockError.ExecutionInvalid))

def settle_transaction(tx: Transaction, v: TxValidity, authorization_refund: gas_refund, fr: TxFrameResult) -> Receipt:
    execution_profile = environment.k_execution_profile
    profile = execution_profile.protocol
    gas_left0 = validated_gas_add(fr.execution_gas_remaining, fr.state_gas_remaining)
    gas_used0 = validated_gas_sub(v.gas_limit, gas_left0)
    refund_quotient = profile.refund_divisor
    refund_cap = sail_ediv_int(gas_used0, refund_quotient)
    total_refund = validated_refund_add(authorization_refund, fr.refund)
    refund = capped_transaction_refund(total_refund, refund_cap)
    gas_left1 = validated_gas_add(gas_left0, refund)
    gas_used1 = validated_gas_sub(v.gas_limit, gas_left1)
    if (int(profile.fork) >= int(Prague)):
        floor_cost = v.calldata_floor
        tx_limit = v.gas_limit
        if (int(floor_cost) <= int(tx_limit)):
            floor = floor_cost
        else:
            raise SailThrown(InvalidBlock(BlockError.ExecutionInvalid))
    else:
        floor = 0
    if (int(gas_used1) < int(floor)):
        gas_used = floor
    else:
        gas_used = gas_used1
    gas_left = validated_gas_sub(v.gas_limit, gas_used)
    raw_state_gas = (int(fr.state_gas_used) + int(v.intrinsic_state_gas))
    tx_state_gas = admitted_transaction_state_gas(raw_state_gas)
    execution_before_floor = GAS_ZERO
    if (int(tx_state_gas) <= int(gas_used0)):
        reduced_execution_gas = validated_gas_sub(gas_used0, tx_state_gas)
        execution_before_floor = Uint(reduced_execution_gas)
    if (int(profile.fork) >= int(Amsterdam)):
        if (int(execution_before_floor) < int(floor)):
            execution_gas = floor
        else:
            execution_gas = execution_before_floor
    else:
        execution_gas = gas_used
    if (int(profile.fork) >= int(Amsterdam)):
        state_gas = tx_state_gas
    else:
        state_gas = GAS_ZERO
    k_add_balance(v.sender, validated_word_product(v.gas_price, gas_left))
    k_add_balance(k_coinbase(), validated_word_product(v.priority_fee, gas_used))
    k_tx_merge()
    logs = read_logs()
    return Receipt(tx_type=tx.tx_type, success=fr.success, gas_used=Uint(gas_used), execution_gas=Uint(execution_gas), state_gas=Uint(state_gas), logs=logs)

def process_transaction(tx: Transaction, allowance: TransactionGasAllowance) -> Receipt:
    k_tx_reset()
    validity = check_transaction_validity(tx, allowance)
    k_set_tx(tx_env(tx.sender, validity.gas_price, tx.blob_hashes))
    upfront = apply_transaction_upfront_effects(tx, validity)
    frame_result = run_transaction_frame(tx, validity, upfront)
    receipt = settle_transaction(tx, validity, upfront.authorization_refund, frame_result)
    return receipt

G_transaction: Annotated[int, IntegerRange(21000, 21000)] = 21000

G_txcreate: Annotated[int, IntegerRange(32000, 32000)] = 32000

G_txdatazero: Annotated[int, IntegerRange(4, 4)] = 4

G_txdatanonzero: Annotated[int, IntegerRange(16, 16)] = 16

G_access_list_address: Annotated[int, IntegerRange(2400, 2400)] = 2400

G_access_list_storage_key: Annotated[int, IntegerRange(1900, 1900)] = 1900

PER_AUTH_BASE: Annotated[int, IntegerRange(12500, 12500)] = 12500

PER_EMPTY_ACCOUNT: Annotated[int, IntegerRange(25000, 25000)] = 25000

AMSTERDAM_TX_BASE: Annotated[int, IntegerRange(12000, 12000)] = 12000

AMSTERDAM_CREATE_ACCESS: Annotated[int, IntegerRange(11000, 11000)] = 11000

AMSTERDAM_COLD_ACCOUNT_ACCESS: Annotated[int, IntegerRange(3000, 3000)] = 3000

AMSTERDAM_TX_VALUE_COST: Annotated[int, IntegerRange(4244, 4244)] = 4244

AMSTERDAM_TRANSFER_LOG_COST: Annotated[int, IntegerRange(1756, 1756)] = 1756

AMSTERDAM_ACCESS_LIST_ADDRESS: Annotated[int, IntegerRange(3000, 3000)] = 3000

AMSTERDAM_ACCESS_LIST_SLOT: Annotated[int, IntegerRange(3000, 3000)] = 3000

AMSTERDAM_ACCESS_LIST_ADDRESS_FLOOR: Annotated[int, IntegerRange(1280, 1280)] = 1280

AMSTERDAM_ACCESS_LIST_SLOT_FLOOR: Annotated[int, IntegerRange(2048, 2048)] = 2048

AMSTERDAM_AUTH_BASE: Annotated[int, IntegerRange(7816, 7816)] = 7816

AMSTERDAM_CALLDATA_FLOOR_BYTE: Annotated[int, IntegerRange(64, 64)] = 64
