# Generated by Sail's Python backend. Do not edit by hand.
# Sail source: lib/mpt/indexed.sail
from __future__ import annotations

from ..._runtime import (
    Bits,
    SailMatchFailure,
    SailThrown,
    Uint,
    Unsigned,
)
from pydantic import ConfigDict, model_validator
from pydantic.dataclasses import dataclass as pydantic_dataclass
from typing_extensions import Self
from evm.exceptions import (
    BlockError,
    InvalidBlock,
)
from evm.lib.mpt.primitives import (
    TriePath,
    path_empty,
    path_append_byte,
)

@pydantic_dataclass(config=ConfigDict(strict=True, arbitrary_types_allowed=True), frozen=True, slots=True, kw_only=True)
class RlpIndexItemValidity:
    maximum: int

    @model_validator(mode="after")
    def validate(self) -> Self:
        if not (((0 < self.maximum) and (self.maximum <= (2 ** 20)))):
            raise ValueError("RlpIndexItemValidity violates Sail constraint rlp_index_valid_maximum('maximum)")
        return self

@pydantic_dataclass(config=ConfigDict(strict=True, validate_assignment=True, revalidate_instances="always", arbitrary_types_allowed=True), slots=True, kw_only=True)
class RlpIndexItem:
    validity: RlpIndexItemValidity
    index: Uint
    key: TriePath

    @model_validator(mode="after")
    def validate(self) -> Self:
        if not ((0 <= int(self.index) <= (self.validity.maximum - 1))):
            raise ValueError("RlpIndexItem.index violates Sail type range(0, ('maximum - 1))")
        return self

@pydantic_dataclass(config=ConfigDict(strict=True, arbitrary_types_allowed=True), frozen=True, slots=True, kw_only=True)
class RlpIndexCursorValidity:
    maximum: int

    @model_validator(mode="after")
    def validate(self) -> Self:
        if not (((0 < self.maximum) and (self.maximum <= (2 ** 20)))):
            raise ValueError("RlpIndexCursorValidity violates Sail constraint rlp_index_valid_maximum('maximum)")
        return self

@pydantic_dataclass(config=ConfigDict(strict=True, validate_assignment=True, revalidate_instances="always", arbitrary_types_allowed=True), slots=True, kw_only=True)
class RlpIndexCursor:
    validity: RlpIndexCursorValidity
    count: Uint
    position: Uint
    current: RlpIndexItem | None

    @model_validator(mode="after")
    def validate(self) -> Self:
        if not ((0 <= int(self.count) <= self.validity.maximum)):
            raise ValueError("RlpIndexCursor.count violates Sail type range(0, 'maximum)")
        if not ((0 <= int(self.position) <= self.validity.maximum)):
            raise ValueError("RlpIndexCursor.position violates Sail type range(0, 'maximum)")
        return self

class rlp_index_byte_width(Unsigned):
    LOWER = 1
    UPPER = 8

    def _in_range(self, value: int) -> bool:
        return self.LOWER <= value <= self.UPPER

class rlp_index(Unsigned):
    LOWER = 0
    UPPER = 1048575

    def _in_range(self, value: int) -> bool:
        return self.LOWER <= value <= self.UPPER

def rlp_index_encoded_width(value: rlp_index) -> rlp_index_byte_width:
    if (int(value) < 256):
        return rlp_index_byte_width(1)
    else:
        if (int(value) < 65536):
            return rlp_index_byte_width(2)
        else:
            if (int(value) < 16777216):
                return rlp_index_byte_width(3)
            else:
                if (int(value) < 4294967296):
                    return rlp_index_byte_width(4)
                else:
                    if (int(value) < 1099511627776):
                        return rlp_index_byte_width(5)
                    else:
                        if (int(value) < 281474976710656):
                            return rlp_index_byte_width(6)
                        else:
                            if (int(value) < 72057594037927936):
                                return rlp_index_byte_width(7)
                            else:
                                return rlp_index_byte_width(8)

def trie_index_key(index: rlp_index) -> TriePath:
    if ((index) == (0)):
        return path_append_byte(path_empty(), Bits(8, 0b10000000))
    else:
        if (int(index) <= 127):
            return path_append_byte(path_empty(), Bits(8, int(index) >> 0))
        else:
            width = rlp_index_encoded_width(index)
            path = path_append_byte(path_empty(), Bits(8, int((128 + int(width))) >> 0))
            remaining = width
            while True:
                if not (((remaining) != (0))):
                    break
                current_remaining = remaining
                if (0 < int(current_remaining)):
                    byte_offset = (int(current_remaining) - 1)
                else:
                    raise SailThrown(InvalidBlock(BlockError.WitnessDeficient))
                shift = (int(byte_offset) * 8)
                path = path_append_byte(path, Bits(8, int(index) >> int(shift)))
                remaining = byte_offset
            return path

def rlp_index_at_position(cursor: RlpIndexCursor) -> Uint:
    count = cursor.count
    position = cursor.position
    if (int(position) < int(count)):
        rest = (int(count) - 1)
        if (int(rest) < 127):
            single_count = rest
        else:
            single_count = 127
        if (int(position) < int(single_count)):
            return Uint((int(position) + 1))
        else:
            if ((position) == (single_count)):
                return Uint(0)
            else:
                return Uint(position)
    else:
        raise SailThrown(InvalidBlock(BlockError.WitnessDeficient))

def rlp_index_cursor(count: Uint, _sail_implicit_maximum: int) -> RlpIndexCursor:
    cursor = RlpIndexCursor(validity=RlpIndexCursorValidity(maximum=int(_sail_implicit_maximum)), count=Uint(count), position=Uint(0), current=None)
    if ((count) != (0)):
        index = rlp_index_at_position(cursor)
        cursor.current = RlpIndexItem(validity=RlpIndexItemValidity(maximum=int(_sail_implicit_maximum)), index=Uint(index), key=trie_index_key(index))
    return cursor

def rlp_index_cursor_empty(cursor: RlpIndexCursor) -> bool:
    match cursor.current:
        case None:
            return True
        case (_ as _sail_some_value_0) if _sail_some_value_0 is not None:
            return False
        case _:
            raise SailMatchFailure("no Sail match clause applied")

def rlp_index_cursor_peek(cursor: RlpIndexCursor) -> RlpIndexItem:
    match cursor.current:
        case (item as _sail_some_value_1) if _sail_some_value_1 is not None:
            return item
        case None:
            raise SailThrown(InvalidBlock(BlockError.WitnessDeficient))
        case _:
            raise SailMatchFailure("no Sail match clause applied")

def rlp_index_cursor_advance(cursor: RlpIndexCursor) -> RlpIndexCursor:
    count = cursor.count
    position = cursor.position
    if (int(position) < int(count)):
        next = RlpIndexCursor(validity=RlpIndexCursorValidity(maximum=cursor.validity.maximum), count=Uint(count), position=Uint((int(position) + 1)), current=None)
        if (int(next.position) < int(count)):
            index = rlp_index_at_position(next)
            next.current = RlpIndexItem(validity=RlpIndexItemValidity(maximum=cursor.validity.maximum), index=Uint(index), key=trie_index_key(index))
        return next
    else:
        raise SailThrown(InvalidBlock(BlockError.WitnessDeficient))

def rlp_index_cursor_pop(cursor: RlpIndexCursor) -> tuple[RlpIndexItem, RlpIndexCursor]:
    item = rlp_index_cursor_peek(cursor)
    return (item, rlp_index_cursor_advance(cursor))
