// TEMPLATE — compile the Sail EVM model core for the zkVM RV64 target and link
// it into the guest. Untested here; needs the zkVM SDK's target + sysroot.
//
// The model core is the SAME C that the spike target builds, minus the
// spike-only harness (start.S, htif.c, zkvm_io.c, zkvm_input_data.c): the ere
// SDK runtime provides the entry, allocator, read_input and write_output.
fn main() {
    let ffi = "../../ffi";
    let rt  = "../runtime";
    let mut b = cc::Build::new();
    b.flag("-DERE_GUEST").flag("-ffreestanding").flag("-fno-builtin")
     .include(rt).include(format!("{ffi}"))
     // model core (generated by `sail -c` + the sailfix runtime):
     .file("generated/zkvm_block.c")        // sail -c zkvm_block.sail (committed by build)
     .file("../runtime/sailfix/sail.c")
     .file(format!("{ffi}/host_crypto.c"))
     .file(format!("{ffi}/precompiles.c"))
     .file(format!("{ffi}/returndata.c"))
     .file(format!("{ffi}/memory.c")).file(format!("{ffi}/transient_storage.c"))
     .file(format!("{ffi}/state_db.c"))
     .file(format!("{ffi}/stack.c"))
     .file(format!("{ffi}/code_db.c"))
     .file(format!("{ffi}/trie_node_db.c"))
     // Crypto/precompiles live behind explicit host_crypto/precompiles adapters;
     // the zkVM environment supplies the proven native crypto/precompile surface.
     // (The portable-C reference ffi/zkvm_accelerators.c has been removed; the single
     // crypto source is the Rust accel-host, served as proven precompiles.)
     .file(format!("{rt}/zkvm_input.c"))             // -DERE_GUEST: read_input source + buffered output
     .file("ere_bridge.c");
    b.compile("evmsail_core");
}
