# Generated by Sail's Python backend. Do not edit by hand.
# Sail source: lib/rlp/decoding.sail
from __future__ import annotations

from ..._runtime import (
    BitWidth,
    Bits,
    SailThrown,
    U64,
    Uint,
    sail_tmod_int,
    sail_vector_access,
)
from typing import Annotated
from evm._sail.vector import neq_bits
from evm.prelude import word
from evm.primitives.quantities import (
    code_length,
    ssz_uint,
)
from evm.primitives.bytes import (
    ScratchSlice,
    ScratchSliceFields,
    StatelessInputSlice,
    StatelessInputSliceFields,
    stateless_input_sub_slice,
    scratch_sub_slice,
    stateless_input_slice_suffix,
    scratch_slice_suffix,
)
from evm.exceptions import (
    BlockError,
    InvalidBlock,
)
from evm.primitives.rlp import (
    RlpCursor,
    RlpFieldRef,
    RlpFieldRefValidity,
    RlpInvalidValue,
    RlpOk,
    RlpResult,
    ScratchRlpCursor,
    ScratchRlpFieldRef,
    ScratchRlpFieldRefValidity,
)
from evm.host.region_access import (
    stateless_input_slice_byte,
    scratch_byte,
    stateless_input_slice_load_n,
    scratch_slice_load_n,
)
from evm.lib.rlp.encoding import (
    rlp_nat_length_byte,
    rlp_length_word,
    rlp_minimal_word_len,
    RLP_SHORT_LENGTH_LIMIT,
    RLP_WORD_LENGTH_LIMIT,
    RLP_UINT64_LENGTH_LIMIT,
)

def rlp_uint64_append(_width: int, prefix: int, next: Annotated[Bits, BitWidth(8)]) -> Uint:
    return Uint((int((int(prefix) * 256)) + int(next)))

def rlp_uint64_width(content: StatelessInputSlice, width: int) -> Uint:
    if ((width) == (0)):
        return Uint(0)
    else:
        return Uint(rlp_uint64_append(width, rlp_uint64_width(content, (int(width) - 1)), stateless_input_slice_byte(content, (int(width) - 1))))

def rlp_ref_hdr(b: StatelessInputSlice) -> tuple[bool, code_length, U64]:
    source_len = b.len
    if ((source_len) == (0)):
        raise SailThrown(InvalidBlock(BlockError.RlpDecode))
    h = int(stateless_input_slice_byte(b, 0))
    if (int(h) < 128):
        return (False, 0, 1)
    else:
        if (int(h) < 184):
            return (False, 1, (int(h) - 128))
        else:
            if (int(h) < 192):
                length_width = (int(h) - 183)
                if (int((int(source_len) - 1)) < int(length_width)):
                    raise SailThrown(InvalidBlock(BlockError.RlpDecode))
                length_bytes = stateless_input_sub_slice(b, 1, length_width)
                return (False, (1 + int(length_width)), rlp_uint64_width(length_bytes, length_width))
            else:
                if (int(h) < 248):
                    return (True, 1, (int(h) - 192))
                else:
                    length_width = (int(h) - 247)
                    if (int((int(source_len) - 1)) < int(length_width)):
                        raise SailThrown(InvalidBlock(BlockError.RlpDecode))
                    length_bytes = stateless_input_sub_slice(b, 1, length_width)
                    return (True, (1 + int(length_width)), rlp_uint64_width(length_bytes, length_width))

def rlp_decode_list(f: RlpFieldRef) -> StatelessInputSliceFields:
    if f.is_list:
        return stateless_input_sub_slice(f.source, (int(f.source.len) - int(f.content_len)), f.content_len)
    else:
        raise SailThrown(InvalidBlock(BlockError.RlpDecode))

def rlp_decode_item(cursor: RlpCursor) -> RlpFieldRef:
    if ((cursor.len) == (0)):
        raise SailThrown(InvalidBlock(BlockError.RlpDecode))
    (is_list, content_off, content_len_value) = rlp_ref_hdr(cursor)
    content_len = content_len_value
    if (int(cursor.len) < int(content_off)):
        raise SailThrown(InvalidBlock(BlockError.RlpDecode))
    if (int((int(cursor.len) - int(content_off))) < int(content_len)):
        raise SailThrown(InvalidBlock(BlockError.RlpDecode))
    full_len = (int(content_off) + int(content_len))
    if (((0 < int(full_len))) & ((int(full_len) <= int(cursor.len)))):
        field_source = stateless_input_sub_slice(cursor, 0, full_len)
        field = RlpFieldRef(validity=RlpFieldRefValidity(source_off=cursor.validity.off, source_len=int(full_len), content_len=int(content_len)), source=field_source, is_list=is_list, content_len=int(content_len))
        return field
    else:
        raise SailThrown(InvalidBlock(BlockError.RlpDecode))

def rlp_cursor_advance(cursor: RlpCursor, consumed: int) -> StatelessInputSliceFields:
    return stateless_input_slice_suffix(cursor, consumed)

def rlp_cursor_expect_end(cursor: RlpCursor) -> None:
    if ((cursor.len) == (0)):
        return None
    else:
        raise SailThrown(InvalidBlock(BlockError.RlpDecode))

def rlp_single_ref(item: StatelessInputSliceFields) -> RlpFieldRef:
    item_length = item.len
    if ((item_length) == (0)):
        raise SailThrown(InvalidBlock(BlockError.RlpDecode))
    else:
        (is_list, content_off, content_len_value) = rlp_ref_hdr(item)
        content_len = content_len_value
        if (int(content_off) > int(item_length)):
            raise SailThrown(InvalidBlock(BlockError.RlpDecode))
        if ((content_len) != ((int(item_length) - int(content_off)))):
            raise SailThrown(InvalidBlock(BlockError.RlpDecode))
        field = RlpFieldRef(validity=RlpFieldRefValidity(source_off=item.validity.off, source_len=item.validity.len, content_len=int(content_len)), source=item, is_list=is_list, content_len=int(content_len))
        return field

def rlp_node_cursor(node: StatelessInputSlice) -> RlpCursor:
    if ((node.len) == (0)):
        raise SailThrown(InvalidBlock(BlockError.RlpDecode))
    else:
        return rlp_decode_list(rlp_single_ref(node))

def rlp_item_content(f: RlpFieldRef) -> StatelessInputSlice:
    return stateless_input_sub_slice(f.source, (int(f.source.len) - int(f.content_len)), f.content_len)

def scratch_rlp_uint64_width(content: ScratchSlice, width: int) -> Uint:
    if ((width) == (0)):
        return Uint(0)
    else:
        return Uint(rlp_uint64_append(width, scratch_rlp_uint64_width(content, (int(width) - 1)), scratch_byte(content, (int(width) - 1))))

def scratch_rlp_ref_hdr(b: ScratchSlice) -> tuple[bool, code_length, U64]:
    source_len = b.len
    if ((source_len) == (0)):
        raise SailThrown(InvalidBlock(BlockError.RlpDecode))
    h = int(scratch_byte(b, 0))
    if (int(h) < 128):
        return (False, 0, 1)
    else:
        if (int(h) < 184):
            return (False, 1, (int(h) - 128))
        else:
            if (int(h) < 192):
                length_width = (int(h) - 183)
                if (int((int(source_len) - 1)) < int(length_width)):
                    raise SailThrown(InvalidBlock(BlockError.RlpDecode))
                length_bytes = scratch_sub_slice(b, 1, length_width)
                return (False, (1 + int(length_width)), scratch_rlp_uint64_width(length_bytes, length_width))
            else:
                if (int(h) < 248):
                    return (True, 1, (int(h) - 192))
                else:
                    length_width = (int(h) - 247)
                    if (int((int(source_len) - 1)) < int(length_width)):
                        raise SailThrown(InvalidBlock(BlockError.RlpDecode))
                    length_bytes = scratch_sub_slice(b, 1, length_width)
                    return (True, (1 + int(length_width)), scratch_rlp_uint64_width(length_bytes, length_width))

def scratch_rlp_decode_list(f: ScratchRlpFieldRef) -> ScratchSliceFields:
    if f.is_list:
        return scratch_sub_slice(f.source, (int(f.source.len) - int(f.content_len)), f.content_len)
    else:
        raise SailThrown(InvalidBlock(BlockError.RlpDecode))

def scratch_rlp_decode_item(cursor: ScratchRlpCursor) -> ScratchRlpFieldRef:
    if ((cursor.len) == (0)):
        raise SailThrown(InvalidBlock(BlockError.RlpDecode))
    (is_list, content_off, content_len_value) = scratch_rlp_ref_hdr(cursor)
    content_len = content_len_value
    if (int(cursor.len) < int(content_off)):
        raise SailThrown(InvalidBlock(BlockError.RlpDecode))
    if (int((int(cursor.len) - int(content_off))) < int(content_len)):
        raise SailThrown(InvalidBlock(BlockError.RlpDecode))
    full_len = (int(content_off) + int(content_len))
    if (((0 < int(full_len))) & ((int(full_len) <= int(cursor.len)))):
        field_source = scratch_sub_slice(cursor, 0, full_len)
        field = ScratchRlpFieldRef(validity=ScratchRlpFieldRefValidity(source_off=cursor.validity.off, source_len=int(full_len), content_len=int(content_len)), source=field_source, is_list=is_list, content_len=int(content_len))
        return field
    else:
        raise SailThrown(InvalidBlock(BlockError.RlpDecode))

def scratch_rlp_cursor_advance(cursor: ScratchRlpCursor, consumed: int) -> ScratchSliceFields:
    return scratch_slice_suffix(cursor, consumed)

def scratch_rlp_cursor_expect_end(cursor: ScratchRlpCursor) -> None:
    if ((cursor.len) == (0)):
        return None
    else:
        raise SailThrown(InvalidBlock(BlockError.RlpDecode))

def scratch_rlp_single_ref(item: ScratchSliceFields) -> ScratchRlpFieldRef:
    item_length = item.len
    if ((item_length) == (0)):
        raise SailThrown(InvalidBlock(BlockError.RlpDecode))
    else:
        (is_list, content_off, content_len_value) = scratch_rlp_ref_hdr(item)
        content_len = content_len_value
        if (int(content_off) > int(item_length)):
            raise SailThrown(InvalidBlock(BlockError.RlpDecode))
        if ((content_len) != ((int(item_length) - int(content_off)))):
            raise SailThrown(InvalidBlock(BlockError.RlpDecode))
        field = ScratchRlpFieldRef(validity=ScratchRlpFieldRefValidity(source_off=item.validity.off, source_len=item.validity.len, content_len=int(content_len)), source=item, is_list=is_list, content_len=int(content_len))
        return field

def scratch_rlp_node_cursor(node: ScratchSlice) -> ScratchRlpCursor:
    return scratch_rlp_decode_list(scratch_rlp_single_ref(node))

def scratch_rlp_item_content(f: ScratchRlpFieldRef) -> ScratchSlice:
    return scratch_sub_slice(f.source, (int(f.source.len) - int(f.content_len)), f.content_len)

def scratch_rlp_decode_word(f: ScratchRlpFieldRef) -> word:
    n = f.content_len
    if ((f.is_list) | ((int(RLP_WORD_LENGTH_LIMIT) < int(n)))):
        raise SailThrown(InvalidBlock(BlockError.RlpDecode))
    else:
        return word(scratch_slice_load_n(f.source, (int(f.source.len) - int(n)), n))

def rlp_ref_framing_canonical(f: RlpFieldRef) -> bool:
    n = f.content_len
    payload_length = n
    full_length = f.source.len
    full_offset = 0
    content_offset = (int(full_length) - int(payload_length))
    source = f.source
    source_length = source.len
    if ((full_length) == (0)):
        return False
    else:
        if f.is_list:
            if (int(n) <= int(RLP_SHORT_LENGTH_LIMIT)):
                return ((((full_length) == ((int(payload_length) + 1)))) & (((stateless_input_slice_byte(f.source, 0)) == (((Bits(8, 0b11000000)) + (rlp_nat_length_byte(n)))))))
            else:
                length_word = rlp_length_word(n)
                length_width = rlp_minimal_word_len(length_word)
                return ((((full_length) == ((int((1 + int(length_width))) + int(payload_length))))) & (((((stateless_input_slice_byte(f.source, 0)) == (((Bits(8, 0b11110111)) + (rlp_nat_length_byte(length_width)))))) & ((((stateless_input_slice_load_n(f.source, (int(full_offset) + 1), length_width)) == (length_word)) if (int(full_offset) < int(source_length)) else False)))))
        else:
            if ((payload_length) == (0)):
                return ((((full_length) == (1))) & (((stateless_input_slice_byte(f.source, 0)) == (Bits(8, 0b10000000)))))
            else:
                first = stateless_input_slice_byte(f.source, content_offset)
                if ((((payload_length) == (1))) & (((sail_vector_access(first, 7, False)) == (Bits(1, 0b0))))):
                    return ((((full_length) == (1))) & (((stateless_input_slice_byte(f.source, 0)) == (first))))
                else:
                    if (int(n) <= int(RLP_SHORT_LENGTH_LIMIT)):
                        return ((((full_length) == ((int(payload_length) + 1)))) & (((stateless_input_slice_byte(f.source, 0)) == (((Bits(8, 0b10000000)) + (rlp_nat_length_byte(n)))))))
                    else:
                        length_word = rlp_length_word(n)
                        length_width = rlp_minimal_word_len(length_word)
                        return ((((full_length) == ((int((1 + int(length_width))) + int(payload_length))))) & (((((stateless_input_slice_byte(f.source, 0)) == (((Bits(8, 0b10110111)) + (rlp_nat_length_byte(length_width)))))) & ((((stateless_input_slice_load_n(f.source, (int(full_offset) + 1), length_width)) == (length_word)) if (int(full_offset) < int(source_length)) else False)))))

def rlp_ref_bytes_canonical(f: RlpFieldRef) -> bool:
    return (((not (f.is_list))) & (rlp_ref_framing_canonical(f)))

def rlp_item_uint_canonical(f: RlpFieldRef) -> bool:
    if (not (rlp_ref_bytes_canonical(f))):
        return False
    else:
        return ((((f.content_len) == (0))) | (neq_bits(stateless_input_slice_byte(f.source, (int(f.source.len) - int(f.content_len))), Bits(8, 0b00000000))))

def rlp_decode_word(f: RlpFieldRef) -> word:
    n = f.content_len
    if ((f.is_list) | ((int(RLP_WORD_LENGTH_LIMIT) < int(n)))):
        raise SailThrown(InvalidBlock(BlockError.RlpDecode))
    else:
        return word(stateless_input_slice_load_n(f.source, (int(f.source.len) - int(n)), n))

def rlp_decode_u256(f: RlpFieldRef) -> word:
    if rlp_item_uint_canonical(f):
        return word(rlp_decode_word(f))
    else:
        raise SailThrown(InvalidBlock(BlockError.RlpDecode))

def rlp_decode_uint64(f: RlpFieldRef) -> ssz_uint:
    if (((not (rlp_item_uint_canonical(f)))) | ((int(RLP_UINT64_LENGTH_LIMIT) < int(f.content_len)))):
        raise SailThrown(InvalidBlock(BlockError.RlpDecode))
    content_length = f.content_len
    content = rlp_item_content(f)
    width = sail_tmod_int(content_length, 9)
    return ssz_uint(rlp_uint64_width(content, width))

def rlp_decode_bool(field: RlpFieldRef) -> RlpResult:
    value = rlp_decode_uint64(field)
    match value:
        case 0:
            return RlpOk(False)
        case 1:
            return RlpOk(True)
        case _:
            return RlpInvalidValue(None)
