# Generated by Sail's Python backend. Do not edit by hand.
# Sail source: lib/ssz/ssz.sail
from __future__ import annotations

from ..._runtime import (
    Bits,
    Bytes20,
    Bytes32,
    IntegerRange,
    SailThrown,
    sail_range,
    sail_vector_init,
    sail_vector_update,
)
from typing import Annotated
from evm.prelude import (
    address,
    hash,
    word,
    word_to_hash,
    word_to_address,
    word_add_word,
    word_mul_word,
    WORD_ZERO,
)
from evm.primitives.quantities import (
    code_length,
    ssz_offset,
    ssz_uint,
)
from evm.primitives.bytes import (
    ScratchSlice,
    StatelessInputSlice,
    ADDRESS_BYTE_LENGTH,
)
from evm.exceptions import (
    BlockError,
    InvalidBlock,
)
from evm.host.region_access import (
    stateless_input_slice_byte,
    scratch_byte,
    stateless_input_slice_load,
    stateless_input_slice_load_n,
)
from evm.primitives.block import LogsBloom

def ssz_field_offset(base: int, delta: int) -> int:
    return (int(base) + int(delta))

def scratch_field_offset(base: int, delta: int) -> int:
    return (int(base) + int(delta))

def ssz_u32_at(input: StatelessInputSlice, offset: int) -> ssz_offset:
    b0 = (stateless_input_slice_byte(input, offset)).zero_extend(32)
    b1 = (stateless_input_slice_byte(input, ssz_field_offset(offset, 1))).zero_extend(32)
    b2 = (stateless_input_slice_byte(input, ssz_field_offset(offset, 2))).zero_extend(32)
    b3 = (stateless_input_slice_byte(input, ssz_field_offset(offset, 3))).zero_extend(32)
    return ssz_offset(int(((b0) | (((((b1) << 8)) | (((((b2) << 16)) | (((b3) << 24)))))))))

def ssz_u32(input: StatelessInputSlice, offset: int) -> ssz_offset:
    return ssz_offset(ssz_u32_at(input, offset))

def ssz_u32_in_slice(input: StatelessInputSlice, offset: ssz_offset) -> ssz_offset:
    if (((int(offset) <= int(input.len))) & ((4 <= int((int(input.len) - int(offset)))))):
        return ssz_offset(ssz_u32_at(input, offset))
    else:
        raise SailThrown(InvalidBlock(BlockError.InvalidConfig))

def ssz_offset_to_source_pointer(value: ssz_offset) -> code_length:
    return code_length(value)

def decode_ssz_uint(input: StatelessInputSlice, offset: int) -> ssz_uint:
    return ssz_uint((int((int((int((int((int((int((int(stateless_input_slice_byte(input, offset)) + int((int(stateless_input_slice_byte(input, ssz_field_offset(offset, 1))) * int((1 << 8)))))) + int((int(stateless_input_slice_byte(input, ssz_field_offset(offset, 2))) * int((1 << 16)))))) + int((int(stateless_input_slice_byte(input, ssz_field_offset(offset, 3))) * int((1 << 24)))))) + int((int(stateless_input_slice_byte(input, ssz_field_offset(offset, 4))) * int((1 << 32)))))) + int((int(stateless_input_slice_byte(input, ssz_field_offset(offset, 5))) * int((1 << 40)))))) + int((int(stateless_input_slice_byte(input, ssz_field_offset(offset, 6))) * int((1 << 48)))))) + int((int(stateless_input_slice_byte(input, ssz_field_offset(offset, 7))) * int((1 << 56))))))

def decode_scratch_uint(input: ScratchSlice, offset: int) -> ssz_uint:
    return ssz_uint((int((int((int((int((int((int((int(scratch_byte(input, offset)) + int((int(scratch_byte(input, scratch_field_offset(offset, 1))) * int((1 << 8)))))) + int((int(scratch_byte(input, scratch_field_offset(offset, 2))) * int((1 << 16)))))) + int((int(scratch_byte(input, scratch_field_offset(offset, 3))) * int((1 << 24)))))) + int((int(scratch_byte(input, scratch_field_offset(offset, 4))) * int((1 << 32)))))) + int((int(scratch_byte(input, scratch_field_offset(offset, 5))) * int((1 << 40)))))) + int((int(scratch_byte(input, scratch_field_offset(offset, 6))) * int((1 << 48)))))) + int((int(scratch_byte(input, scratch_field_offset(offset, 7))) * int((1 << 56))))))

def ssz_addr(input: StatelessInputSlice, offset: int) -> address:
    return Bytes20(word_to_address(stateless_input_slice_load_n(input, offset, ADDRESS_BYTE_LENGTH)))

def ssz_bytes32(input: StatelessInputSlice, offset: int) -> hash:
    return Bytes32(word_to_hash(stateless_input_slice_load(input, offset)))

def ssz_logs_bloom_index(index: int) -> int:
    return (255 - int(index))

def ssz_logs_bloom(input: StatelessInputSlice, offset: int) -> LogsBloom:
    out = sail_vector_init(256, Bits(8, 0b00000000))
    for k in sail_range(0, 255, 1, True):
        out = sail_vector_update(out, ssz_logs_bloom_index(k), stateless_input_slice_byte(input, ssz_field_offset(offset, k)), False)
    return out

def ssz_u256_index(index: int) -> int:
    return (31 - int(index))

def ssz_u256(input: StatelessInputSlice, offset: int) -> word:
    result = WORD_ZERO
    for k in sail_range(0, 31, 1, True):
        result = word(word_add_word(word_mul_word(result, 256), int(stateless_input_slice_byte(input, ssz_field_offset(offset, ssz_u256_index(k))))))
    return word(result)

SSZ_OFF_BYTES: Annotated[int, IntegerRange(4, 4)] = 4

SSZ_UINT_BYTES: Annotated[int, IntegerRange(8, 8)] = 8
