# Generated by Sail's Python backend. Do not edit by hand.
# Sail source: lib/ssz/stateless_input.sail
from __future__ import annotations

from ..._runtime import (
    BitWidth,
    Bits,
    BoundedUint,
    Bytes32,
    IntegerRange,
    SailThrown,
    Uint,
    Unsigned,
    sail_ediv_int,
    sail_tdiv_int,
    sail_tmod_int,
)
from dataclasses import dataclass
from typing import Annotated, TypeAlias
from evm.HostContract import (
    ancestor_hash_write as _host_ancestor_hash_write,
    nodedb_insert as _host_nodedb_insert,
    nodedb_reset as _host_nodedb_reset,
    scratch_sha256 as _host_scratch_sha256,
    stateless_input_keccak256 as _host_stateless_input_keccak256,
)
from evm._sail.vector import neq_bits
from evm.prelude import (
    address,
    hash,
    word,
    hash_to_word,
    word_to_hash,
    ZERO_WORD,
    ZERO_HASH,
)
from evm.primitives.quantities import (
    blob_gas_used,
    block_number,
    block_timestamp,
    chain_identifier,
    excess_blob_gas,
    slot_number,
    source_length,
    source_pointer,
    ssz_offset,
    ssz_offset_index,
    validator_index,
    withdrawal_amount,
    withdrawal_index,
)
from evm.primitives.gas import (
    block_gas,
    block_gas_limit,
)
from evm.primitives.bytes import (
    StatelessInputSlice,
    StatelessInputSliceAtLeast,
    StatelessInputSliceAtMost,
    StatelessInputSliceFields,
    stateless_input_sub_slice,
    stateless_input_slice_suffix,
    WORD_BYTE_LENGTH,
)
from evm.exceptions import (
    BlockError,
    InvalidBlock,
)
from evm.primitives.ssz import (
    BoundedSszListCursor,
    BoundedSszListCursorValidity,
    BoundedSszListRef,
    BoundedSszListRefValidity,
    TransactionListRef,
    WithdrawalListRef,
    WitnessCodeListCursor,
    WitnessCodeListRef,
    WitnessHeaderListCursor,
    WitnessHeaderListRef,
    WitnessNodeListCursor,
    WitnessNodeListRef,
)
from evm.primitives.rlp import RlpCursor
from evm.host.region_access import stateless_input_slice_byte
from evm.kernel.scratch import (
    scratch_length_add,
    scratch_reserve,
    scratch_push_byte,
    stateless_input_scratch_push_slice,
    scratch_finish,
    scratch_rewind,
)
from evm.primitives.fork import Cancun
from evm.primitives.chain_config import (
    ChainConfig,
    ProtocolProfile,
    execution_profile_for,
    schema_protocol_profile_forwards,
    schema_protocol_profile_forwards_matches,
)
from evm.primitives.tx import Transaction
from evm.primitives.block import (
    Block,
    BlockBody,
    BlockHeader,
    ExecutionPayload,
    Withdrawal,
)
from evm.primitives.stateless_input import (
    StatelessInput,
    WitnessContext,
)
from evm.host.code import (
    code_db_insert,
    code_db_intern_input,
)
from evm.lib.ssz.ssz import (
    ssz_field_offset,
    ssz_u32,
    ssz_u32_in_slice,
    ssz_offset_to_source_pointer,
    decode_ssz_uint,
    ssz_addr,
    ssz_bytes32,
    ssz_u256,
    SSZ_OFF_BYTES,
    SSZ_UINT_BYTES,
)
from evm.lib.rlp.decoding import (
    rlp_decode_item,
    rlp_cursor_advance,
    rlp_node_cursor,
    rlp_decode_word,
    rlp_decode_u256,
    rlp_decode_uint64,
)
from evm.lib.rlp.codecs.transactions import rlp_decode_tx
from evm.kernel.lifecycle import k_set_header
from evm.kernel import environment

def ssz_offset_table_position(index: ssz_offset_index) -> ssz_offset:
    return ssz_offset((int(index) * 4))

def ssz_list_cursor(items: BoundedSszListRef) -> BoundedSszListCursor:
    bytes = items.bytes
    if ((items.count) != (0)):
        current = ssz_offset_to_source_pointer(ssz_u32(bytes, 0))
    else:
        current = bytes.len
    return BoundedSszListCursor(validity=BoundedSszListCursorValidity(maximum=items.validity.maximum), items=items, index=Uint(0), current=source_pointer(current))

def ssz_list_cursor_empty(cursor: BoundedSszListCursor) -> bool:
    return (int(cursor.items.count) <= int(cursor.index))

def ssz_list_pop(cursor: BoundedSszListCursor) -> tuple[StatelessInputSlice, BoundedSszListCursor]:
    count = cursor.items.count
    index = cursor.index
    if (int(count) <= int(index)):
        raise SailThrown(InvalidBlock(BlockError.InvalidConfig))
    next_index = (int(index) + 1)
    items = cursor.items
    bytes = items.bytes
    nat = bytes.len
    if (int(next_index) < int(items.count)):
        next = ssz_offset_to_source_pointer(ssz_u32_in_slice(bytes, ssz_offset_table_position(next_index)))
    else:
        next = nat
    current_value = cursor.current
    next_value = next
    if (int(current_value) <= int(next_value)):
        if (int(next_value) <= int(nat)):
            item_length = (int(next_value) - int(current_value))
            if ((((items.max_item_length) != (0))) & ((int(items.max_item_length) < int(item_length)))):
                raise SailThrown(InvalidBlock(BlockError.InvalidConfig))
            item = stateless_input_sub_slice(bytes, current_value, item_length)
            return (item, BoundedSszListCursor(validity=BoundedSszListCursorValidity(maximum=cursor.validity.maximum), items=items, index=Uint(next_index), current=source_pointer(next)))
        else:
            raise SailThrown(InvalidBlock(BlockError.InvalidConfig))
    else:
        raise SailThrown(InvalidBlock(BlockError.InvalidConfig))

def ssz_list_at(items: BoundedSszListRef, index: int) -> StatelessInputSlice:
    bytes = items.bytes
    count = items.count
    if (int(count) <= int(index)):
        raise SailThrown(InvalidBlock(BlockError.InvalidConfig))
    next_index = (int(index) + 1)
    start = ssz_offset_to_source_pointer(ssz_u32_in_slice(bytes, ssz_offset_table_position(index)))
    if (int(next_index) < int(items.count)):
        stop = ssz_offset_to_source_pointer(ssz_u32_in_slice(bytes, ssz_offset_table_position(next_index)))
    else:
        stop = bytes.len
    start_value = start
    stop_value = stop
    items_length = bytes.len
    if (int(start_value) <= int(stop_value)):
        if (int(stop_value) <= int(items_length)):
            item_length = (int(stop_value) - int(start_value))
            if ((((items.max_item_length) != (0))) & ((int(items.max_item_length) < int(item_length)))):
                raise SailThrown(InvalidBlock(BlockError.InvalidConfig))
            return stateless_input_sub_slice(bytes, start, item_length)
        else:
            raise SailThrown(InvalidBlock(BlockError.InvalidConfig))
    else:
        raise SailThrown(InvalidBlock(BlockError.InvalidConfig))

def ssz_fixed_list_at(items: BoundedSszListRef, index: int, item_size: int) -> StatelessInputSliceFields:
    bytes = items.bytes
    if (int(items.count) <= int(index)):
        raise SailThrown(InvalidBlock(BlockError.InvalidConfig))
    width_value = item_size
    offset_value = (int(index) * int(width_value))
    items_length = bytes.len
    if (int((int(offset_value) + int(width_value))) <= int(items_length)):
        return stateless_input_sub_slice(bytes, offset_value, width_value)
    else:
        raise SailThrown(InvalidBlock(BlockError.InvalidConfig))

def ssz_fixed_list_pop(items: BoundedSszListRef, item_size: int) -> tuple[StatelessInputSliceFields, BoundedSszListRef]:
    bytes = items.bytes
    items_length = bytes.len
    width = item_size
    count = items.count
    if ((count) == (0)):
        raise SailThrown(InvalidBlock(BlockError.InvalidConfig))
    if (int(items_length) < int(width)):
        raise SailThrown(InvalidBlock(BlockError.InvalidConfig))
    item = stateless_input_sub_slice(bytes, 0, item_size)
    rest = BoundedSszListRef(validity=BoundedSszListRefValidity(maximum=items.validity.maximum), bytes=stateless_input_slice_suffix(bytes, width), count=Uint((int(count) - 1)), max_item_length=source_length(items.max_item_length))
    return (item, rest)

@dataclass(slots=True)
class StatelessInputRef:
    protocol: ProtocolProfile
    new_payload_request: StatelessInputSlice
    execution_payload: StatelessInputSliceAtLeast
    versioned_hashes: StatelessInputSlice
    deposits: StatelessInputSlice
    withdrawal_requests: StatelessInputSlice
    consolidation_requests: StatelessInputSlice
    builder_deposit_requests: StatelessInputSlice
    builder_exit_requests: StatelessInputSlice
    extra_data: StatelessInputSliceAtMost
    transactions: TransactionListRef
    withdrawals: WithdrawalListRef
    block_access_list: StatelessInputSliceAtMost
    witness_state: WitnessNodeListRef
    witness_codes: WitnessCodeListRef
    witness_headers: WitnessHeaderListRef
    chain_config: StatelessInputSlice
    public_keys: StatelessInputSlice

def ssz_container_bytes(bytes: StatelessInputSlice, minimum: int) -> StatelessInputSliceFields:
    fields = bytes
    if (int(minimum) <= int(fields.len)):
        return fields
    else:
        raise SailThrown(InvalidBlock(BlockError.InvalidConfig))

@dataclass(slots=True)
class SszContainerCursor:
    bytes: StatelessInputSlice
    current: source_pointer

def ssz_container_cursor(bytes: StatelessInputSliceFields, fixed_length: int) -> SszContainerCursor:
    return SszContainerCursor(bytes=bytes, current=source_pointer(fixed_length))

def ssz_take(cursor: SszContainerCursor, stop: ssz_offset) -> tuple[StatelessInputSlice, SszContainerCursor]:
    current_value = cursor.current
    bytes = cursor.bytes
    container_length = bytes.len
    if (((int(current_value) <= int(stop))) & ((int(stop) <= int(container_length)))):
        stop_pointer = stop
        span_length = (int(stop) - int(current_value))
        span = stateless_input_sub_slice(bytes, current_value, span_length)
        return (span, SszContainerCursor(bytes=bytes, current=source_pointer(stop_pointer)))
    else:
        raise SailThrown(InvalidBlock(BlockError.InvalidConfig))

def ssz_finish(cursor: SszContainerCursor) -> StatelessInputSlice:
    current_value = cursor.current
    bytes = cursor.bytes
    container_length = bytes.len
    if (int(current_value) <= int(container_length)):
        remaining = (int(container_length) - int(current_value))
        return stateless_input_sub_slice(bytes, current_value, remaining)
    else:
        raise SailThrown(InvalidBlock(BlockError.InvalidConfig))

def ssz_bounded_variable_list_ref(bytes: StatelessInputSlice, maximum_count: int, maximum_item_length: int) -> BoundedSszListRef:
    span = bytes.len
    if ((span) == (0)):
        raw_count = 0
    else:
        if (int(span) < int(SSZ_OFF_BYTES)):
            raise SailThrown(InvalidBlock(BlockError.InvalidConfig))
        first_offset = ssz_u32(bytes, 0)
        count = sail_tdiv_int(first_offset, 4)
        if ((((sail_tmod_int(first_offset, 4)) != (0))) | (((((count) == (0))) | ((int(first_offset) > int(span)))))):
            raise SailThrown(InvalidBlock(BlockError.InvalidConfig))
        raw_count = count
    if (int(maximum_count) < int(raw_count)):
        raise SailThrown(InvalidBlock(BlockError.InvalidConfig))
    count = raw_count
    return BoundedSszListRef(validity=BoundedSszListRefValidity(maximum=int(maximum_count)), bytes=bytes, count=Uint(count), max_item_length=source_length(maximum_item_length))

def ssz_bounded_fixed_list_ref(bytes: StatelessInputSlice, item_size: int, maximum_count: int) -> BoundedSszListRef:
    width = item_size
    if ((width) == (0)):
        raise SailThrown(InvalidBlock(BlockError.InvalidConfig))
    span = bytes.len
    raw_count = sail_ediv_int(span, width)
    if ((span) != ((int(raw_count) * int(width)))):
        raise SailThrown(InvalidBlock(BlockError.InvalidConfig))
    if (int(maximum_count) < int(raw_count)):
        raise SailThrown(InvalidBlock(BlockError.InvalidConfig))
    count = raw_count
    return BoundedSszListRef(validity=BoundedSszListRefValidity(maximum=int(maximum_count)), bytes=bytes, count=Uint(count), max_item_length=source_length(item_size))

def decode_stateless_input_ref(input: StatelessInputSlice) -> StatelessInputRef:
    input_fields = input
    input_length = input_fields.len
    fixed_length = STATELESS_INPUT_FIXED_LENGTH
    body_offset_value = SSZ_BODY
    if (int(input_length) < int(fixed_length)):
        raise SailThrown(InvalidBlock(BlockError.InvalidConfig))
    if neq_bits(stateless_input_slice_byte(input_fields, 1), Bits(8, 0b00000001)):
        raise SailThrown(InvalidBlock(BlockError.InvalidConfig))
    schema_fork = stateless_input_slice_byte(input_fields, 0)
    if (not (schema_protocol_profile_forwards_matches(schema_fork))):
        raise SailThrown(InvalidBlock(BlockError.InvalidConfig))
    protocol = schema_protocol_profile_forwards(schema_fork)
    body_bytes = stateless_input_slice_suffix(input_fields, body_offset_value)
    body = ssz_container_bytes(body_bytes, STATELESS_INPUT_BODY_FIXED_LENGTH)
    container_start = 0
    new_payload_request_offset = ssz_u32(body, ssz_field_offset(container_start, IN_NPR_OFF))
    witness_offset = ssz_u32(body, ssz_field_offset(container_start, IN_WITNESS_OFF))
    chain_config_offset = ssz_u32(body, ssz_field_offset(container_start, IN_CHAIN_CONFIG_OFF))
    public_keys_offset = ssz_u32(body, ssz_field_offset(container_start, IN_PUBLIC_KEYS_OFF))
    body_fixed_length = STATELESS_INPUT_BODY_FIXED_LENGTH
    if ((new_payload_request_offset) != (body_fixed_length)):
        raise SailThrown(InvalidBlock(BlockError.InvalidConfig))
    body_cursor = ssz_container_cursor(body, STATELESS_INPUT_BODY_FIXED_LENGTH)
    (new_payload_request_bytes, body_after_payload_request) = ssz_take(body_cursor, witness_offset)
    new_payload_request = ssz_container_bytes(new_payload_request_bytes, NEW_PAYLOAD_REQUEST_FIXED_LENGTH)
    (execution_witness_bytes, body_after_witness) = ssz_take(body_after_payload_request, chain_config_offset)
    execution_witness = ssz_container_bytes(execution_witness_bytes, EXECUTION_WITNESS_FIXED_LENGTH)
    (chain_config, body_after_chain_config) = ssz_take(body_after_witness, public_keys_offset)
    public_keys = ssz_finish(body_after_chain_config)
    npr_start = 0
    payload_offset = ssz_u32(new_payload_request, ssz_field_offset(npr_start, NPR_PAYLOAD_OFF))
    versioned_hashes_offset = ssz_u32(new_payload_request, ssz_field_offset(npr_start, NPR_VHASHES_OFF))
    requests_offset = ssz_u32(new_payload_request, ssz_field_offset(npr_start, NPR_REQUESTS_OFF))
    npr_fixed_length = NEW_PAYLOAD_REQUEST_FIXED_LENGTH
    if ((payload_offset) != (npr_fixed_length)):
        raise SailThrown(InvalidBlock(BlockError.InvalidConfig))
    npr_cursor = ssz_container_cursor(new_payload_request, NEW_PAYLOAD_REQUEST_FIXED_LENGTH)
    (execution_payload_bytes, npr_after_payload) = ssz_take(npr_cursor, versioned_hashes_offset)
    (versioned_hashes, npr_after_versioned_hashes) = ssz_take(npr_after_payload, requests_offset)
    execution_requests_bytes = ssz_finish(npr_after_versioned_hashes)
    execution_requests = ssz_container_bytes(execution_requests_bytes, EXECUTION_REQUESTS_FIXED_LENGTH)
    execution_payload = ssz_container_bytes(execution_payload_bytes, EXECUTION_PAYLOAD_FIXED_LENGTH)
    payload_start = 0
    extra_data_offset = ssz_u32(execution_payload, ssz_field_offset(payload_start, PL_EXTRA_OFF))
    transactions_offset = ssz_u32(execution_payload, ssz_field_offset(payload_start, PL_TXS_OFF))
    withdrawals_offset = ssz_u32(execution_payload, ssz_field_offset(payload_start, PL_WDS_OFF))
    block_access_list_offset = ssz_u32(execution_payload, ssz_field_offset(payload_start, PL_BAL_OFF))
    payload_fixed_length = EXECUTION_PAYLOAD_FIXED_LENGTH
    if ((extra_data_offset) != (payload_fixed_length)):
        raise SailThrown(InvalidBlock(BlockError.InvalidConfig))
    payload_cursor = ssz_container_cursor(execution_payload, EXECUTION_PAYLOAD_FIXED_LENGTH)
    (extra_data_bytes, payload_after_extra_data) = ssz_take(payload_cursor, transactions_offset)
    (transaction_bytes, payload_after_transactions) = ssz_take(payload_after_extra_data, withdrawals_offset)
    transactions = ssz_bounded_variable_list_ref(transaction_bytes, MAX_TRANSACTIONS_PER_PAYLOAD, MAX_TRANSACTION_LENGTH)
    (withdrawal_bytes, payload_after_withdrawals) = ssz_take(payload_after_transactions, block_access_list_offset)
    withdrawals = ssz_bounded_fixed_list_ref(withdrawal_bytes, WD_SIZE, MAX_WITHDRAWALS_PER_PAYLOAD)
    block_access_list_bytes = ssz_finish(payload_after_withdrawals)
    if (int(extra_data_bytes.len) <= int(MAX_EXTRA_DATA_LENGTH)):
        extra_data = extra_data_bytes
    else:
        raise SailThrown(InvalidBlock(BlockError.InvalidConfig))
    if (int(block_access_list_bytes.len) <= int(MAX_BLOCK_ACCESS_LIST_LENGTH)):
        block_access_list = block_access_list_bytes
    else:
        raise SailThrown(InvalidBlock(BlockError.InvalidConfig))
    requests_start = 0
    deposits_offset = ssz_u32(execution_requests, ssz_field_offset(requests_start, REQ_DEPOSITS_OFF))
    withdrawal_requests_offset = ssz_u32(execution_requests, ssz_field_offset(requests_start, REQ_WITHDRAWALS_OFF))
    consolidation_requests_offset = ssz_u32(execution_requests, ssz_field_offset(requests_start, REQ_CONSOLIDATIONS_OFF))
    builder_deposit_requests_offset = ssz_u32(execution_requests, ssz_field_offset(requests_start, REQ_BUILDER_DEPOSITS_OFF))
    builder_exit_requests_offset = ssz_u32(execution_requests, ssz_field_offset(requests_start, REQ_BUILDER_EXITS_OFF))
    requests_fixed_length = EXECUTION_REQUESTS_FIXED_LENGTH
    if ((deposits_offset) != (requests_fixed_length)):
        raise SailThrown(InvalidBlock(BlockError.InvalidConfig))
    requests_cursor = ssz_container_cursor(execution_requests, EXECUTION_REQUESTS_FIXED_LENGTH)
    (deposits, requests_after_deposits) = ssz_take(requests_cursor, withdrawal_requests_offset)
    (withdrawal_requests, requests_after_withdrawals) = ssz_take(requests_after_deposits, consolidation_requests_offset)
    (consolidation_requests, requests_after_consolidations) = ssz_take(requests_after_withdrawals, builder_deposit_requests_offset)
    (builder_deposit_requests, requests_after_builder_deposits) = ssz_take(requests_after_consolidations, builder_exit_requests_offset)
    builder_exit_requests = ssz_finish(requests_after_builder_deposits)
    witness_start = 0
    witness_state_offset = ssz_u32(execution_witness, ssz_field_offset(witness_start, WIT_STATE_OFF))
    witness_codes_offset = ssz_u32(execution_witness, ssz_field_offset(witness_start, WIT_CODES_OFF))
    witness_headers_offset = ssz_u32(execution_witness, ssz_field_offset(witness_start, WIT_HEADERS_OFF))
    witness_fixed_length = EXECUTION_WITNESS_FIXED_LENGTH
    if ((witness_state_offset) != (witness_fixed_length)):
        raise SailThrown(InvalidBlock(BlockError.InvalidConfig))
    witness_cursor = ssz_container_cursor(execution_witness, EXECUTION_WITNESS_FIXED_LENGTH)
    (witness_state_bytes, witness_after_state) = ssz_take(witness_cursor, witness_codes_offset)
    witness_state = ssz_bounded_variable_list_ref(witness_state_bytes, MAX_WITNESS_NODES, MAX_WITNESS_NODE_LENGTH)
    (witness_code_bytes, witness_after_codes) = ssz_take(witness_after_state, witness_headers_offset)
    witness_codes = ssz_bounded_variable_list_ref(witness_code_bytes, MAX_WITNESS_CODES, MAX_WITNESS_CODE_LENGTH)
    witness_headers = ssz_bounded_variable_list_ref(ssz_finish(witness_after_codes), MAX_WITNESS_HEADERS, MAX_WITNESS_HEADER_LENGTH)
    public_key_bytes = public_keys.len
    public_key_length = PUBLIC_KEY_LENGTH
    public_key_count = sail_ediv_int(public_key_bytes, public_key_length)
    if ((public_key_bytes) != ((int(public_key_count) * int(public_key_length)))):
        raise SailThrown(InvalidBlock(BlockError.InvalidConfig))
    if (int(MAX_PUBLIC_KEYS) < int(public_key_count)):
        raise SailThrown(InvalidBlock(BlockError.InvalidConfig))
    ssz_bounded_fixed_list_ref(versioned_hashes, WORD_BYTE_LENGTH, MAX_BLOB_COMMITMENTS_PER_BLOCK)
    return StatelessInputRef(protocol=protocol, new_payload_request=new_payload_request, execution_payload=execution_payload, versioned_hashes=versioned_hashes, deposits=deposits, withdrawal_requests=withdrawal_requests, consolidation_requests=consolidation_requests, builder_deposit_requests=builder_deposit_requests, builder_exit_requests=builder_exit_requests, extra_data=extra_data, transactions=transactions, withdrawals=withdrawals, block_access_list=block_access_list, witness_state=witness_state, witness_codes=witness_codes, witness_headers=witness_headers, chain_config=chain_config, public_keys=public_keys)

def sha256_request_digest(request_type: Annotated[Bits, BitWidth(8)], s: StatelessInputSlice) -> hash:
    mark = scratch_reserve(scratch_length_add(1, s.len))
    scratch_push_byte(request_type)
    stateless_input_scratch_push_slice(s)
    digest = _host_scratch_sha256(scratch_finish(mark))
    scratch_rewind(mark)
    return Bytes32(digest)

def index_witness_nodes_cursor(cursor: WitnessNodeListCursor) -> None:
    if ssz_list_cursor_empty(cursor):
        return None
    else:
        (node, next) = ssz_list_pop(cursor)
        _host_nodedb_insert(_host_stateless_input_keccak256(node), node.bytes, node.len)
        return index_witness_nodes_cursor(next)

def index_witness_nodes(nodes: WitnessNodeListRef) -> None:
    return index_witness_nodes_cursor(ssz_list_cursor(nodes))

def index_witness_codes_cursor(cursor: WitnessCodeListCursor) -> None:
    execution_profile = environment.k_execution_profile
    profile = execution_profile.protocol
    if ssz_list_cursor_empty(cursor):
        return None
    else:
        (code, next) = ssz_list_pop(cursor)
        code_length = code.len
        if (int(MAX_WITNESS_CODE_LENGTH) < int(code_length)):
            raise SailThrown(InvalidBlock(BlockError.InvalidConfig))
        executable = code_db_intern_input(code)
        code_db_insert(executable, profile.fork)
        return index_witness_codes_cursor(next)

def index_witness_codes(codes: WitnessCodeListRef) -> None:
    return index_witness_codes_cursor(ssz_list_cursor(codes))

_ParentHeaderFields_blob_gas_used_type: TypeAlias = blob_gas_used
_ParentHeaderFields_excess_blob_gas_type: TypeAlias = excess_blob_gas
@dataclass(slots=True)
class ParentHeaderFields:
    parent_hash: hash
    state_root: hash
    base_fee: word
    blob_gas_used: _ParentHeaderFields_blob_gas_used_type
    excess_blob_gas: _ParentHeaderFields_excess_blob_gas_type
    have_parent: bool
    have_state: bool
    have_base_fee: bool
    have_blob_gas: bool
    have_excess_blob_gas: bool

class parent_header_field_cursor(Unsigned):
    LOWER = 0
    UPPER = 19

    def _in_range(self, value: int) -> bool:
        return self.LOWER <= value <= self.UPPER

def next_parent_header_field(index: parent_header_field_cursor) -> parent_header_field_cursor:
    if (int(index) < 19):
        return parent_header_field_cursor((int(index) + 1))
    else:
        return parent_header_field_cursor(19)

def decode_parent_header_fields(cursor: RlpCursor, field_index: parent_header_field_cursor, fields: ParentHeaderFields) -> ParentHeaderFields:
    if ((cursor.len) == (0)):
        return fields
    else:
        field = rlp_decode_item(cursor)
        next = rlp_cursor_advance(cursor, field.source.len)
        decoded = fields
        if ((field_index) == (0)):
            decoded.parent_hash = Bytes32(word_to_hash(rlp_decode_word(field)))
            decoded.have_parent = True
        else:
            if ((field_index) == (3)):
                decoded.state_root = Bytes32(word_to_hash(rlp_decode_word(field)))
                decoded.have_state = True
            else:
                if ((field_index) == (15)):
                    decoded.base_fee = word(rlp_decode_u256(field))
                    decoded.have_base_fee = True
                else:
                    if ((field_index) == (17)):
                        value = rlp_decode_uint64(field)
                        count = sail_ediv_int(value, (1 << 17))
                        execution_profile = environment.k_execution_profile
                        profile = execution_profile.protocol
                        if (((int(count) <= int(profile.blob_schedule.max))) & (((value) == ((int((1 << 17)) * int(count)))))):
                            decoded.blob_gas_used = (int((1 << 17)) * int(count))
                            decoded.have_blob_gas = True
                        else:
                            raise SailThrown(InvalidBlock(BlockError.RlpDecode))
                    else:
                        if ((field_index) == (18)):
                            value = rlp_decode_uint64(field)
                            execution_profile = environment.k_execution_profile
                            profile = execution_profile.protocol
                            limit = profile.excess_blob_gas_limit
                            if (int(value) <= int(limit)):
                                decoded.excess_blob_gas = excess_blob_gas(value)
                                decoded.have_excess_blob_gas = True
                            else:
                                raise SailThrown(InvalidBlock(BlockError.RlpDecode))
        return decode_parent_header_fields(next, next_parent_header_field(field_index), decoded)

@dataclass(slots=True)
class WitnessHeaderIndex:
    cursor: WitnessHeaderListCursor
    previous_hash: hash
    valid: bool
    parent_state_root: hash
    parent_base_fee_per_gas: word
    parent_blob_gas_used: blob_gas_used
    parent_excess_blob_gas: excess_blob_gas
    parent_fields_valid: bool

def index_witness_header_cursor(state: WitnessHeaderIndex) -> WitnessHeaderIndex:
    execution_profile = environment.k_execution_profile
    profile = execution_profile.protocol
    if ssz_list_cursor_empty(state.cursor):
        return state
    else:
        index = state.cursor.index
        (header, next) = ssz_list_pop(state.cursor)
        is_last = ((next.index) == (state.cursor.items.count))
        result = state
        result.cursor = next
        if ((((index) != (0))) | (is_last)):
            fields = rlp_node_cursor(header)
            decoded = decode_parent_header_fields(fields, 0, EMPTY_PARENT_HEADER_FIELDS)
            if ((((index) != (0))) & ((((not (decoded.have_parent))) | (((decoded.parent_hash) != (state.previous_hash)))))):
                result.valid = False
            if is_last:
                result.parent_state_root = Bytes32(decoded.state_root)
                result.parent_base_fee_per_gas = word(decoded.base_fee)
                result.parent_blob_gas_used = decoded.blob_gas_used
                result.parent_excess_blob_gas = excess_blob_gas(decoded.excess_blob_gas)
                result.parent_fields_valid = ((decoded.have_state) & ((((((int(profile.fork) < int(Cancun))) | (decoded.have_base_fee))) & ((((int(profile.fork) < int(Cancun))) | (((decoded.have_blob_gas) == (decoded.have_excess_blob_gas))))))))
        current_hash = _host_stateless_input_keccak256(header)
        result.previous_hash = Bytes32(current_hash)
        header_count = state.cursor.items.count
        next_index = next.index
        if (int(next_index) <= int(header_count)):
            distance = (int(header_count) - int(next_index))
        else:
            raise SailThrown(InvalidBlock(BlockError.WitnessDeficient))
        if (int(distance) < 256):
            ancestor = distance
            _host_ancestor_hash_write(ancestor, current_hash)
        return index_witness_header_cursor(result)

def index_witness_headers(headers: WitnessHeaderListRef) -> WitnessContext:
    indexed = index_witness_header_cursor(WitnessHeaderIndex(cursor=ssz_list_cursor(headers), previous_hash=hash(ZERO_HASH), valid=((headers.count) != (0)), parent_state_root=hash(ZERO_HASH), parent_base_fee_per_gas=word(ZERO_WORD), parent_blob_gas_used=0, parent_excess_blob_gas=excess_blob_gas(0), parent_fields_valid=False))
    environment.k_n_headers = BoundedUint[0, 256](headers.count)
    if (not (indexed.valid)):
        raise SailThrown(InvalidBlock(BlockError.WitnessDeficient))
    if (not (indexed.parent_fields_valid)):
        raise SailThrown(InvalidBlock(BlockError.RlpDecode))
    return WitnessContext(parent_hash=hash(indexed.previous_hash), parent_state_root=hash(indexed.parent_state_root), parent_base_fee_per_gas=word(indexed.parent_base_fee_per_gas), parent_blob_gas_used=indexed.parent_blob_gas_used, parent_excess_blob_gas=excess_blob_gas(indexed.parent_excess_blob_gas))

def decode_payload_blob_gas_used(payload: StatelessInputSlice, profile: ProtocolProfile) -> blob_gas_used:
    value = decode_ssz_uint(payload, PL_BLOB_GAS_USED)
    count = sail_ediv_int(value, (1 << 17))
    if (((int(count) <= int(profile.blob_schedule.max))) & (((value) == ((int((1 << 17)) * int(count)))))):
        return (int((1 << 17)) * int(count))
    else:
        raise SailThrown(InvalidBlock(BlockError.InvalidBlobGasUsed))

def decode_payload_excess_blob_gas(payload: StatelessInputSlice, profile: ProtocolProfile) -> excess_blob_gas:
    value = decode_ssz_uint(payload, PL_EXCESS_BLOB_GAS)
    limit = profile.excess_blob_gas_limit
    if (int(value) <= int(limit)):
        return excess_blob_gas(value)
    else:
        raise SailThrown(InvalidBlock(BlockError.InvalidExcessBlobGas))

def decode_block_header_ssz(input_ref: StatelessInputRef) -> BlockHeader:
    payload = input_ref.execution_payload
    gas_limit_value = decode_ssz_uint(payload, PL_GAS_LIMIT)
    gas_used_value = decode_ssz_uint(payload, PL_GAS_USED)
    return BlockHeader(number=block_number(decode_ssz_uint(payload, PL_BLOCK_NUMBER)), timestamp=block_timestamp(decode_ssz_uint(payload, PL_TIMESTAMP)), gas_limit=block_gas_limit(gas_limit_value), gas_used=block_gas(gas_used_value), prev_randao=word(hash_to_word(ssz_bytes32(payload, PL_PREV_RANDAO))), base_fee=word(ssz_u256(payload, PL_BASE_FEE)), blob_gas_used=decode_payload_blob_gas_used(payload, input_ref.protocol), excess_blob_gas=excess_blob_gas(decode_payload_excess_blob_gas(payload, input_ref.protocol)), state_root=hash(ssz_bytes32(payload, PL_STATE_ROOT)), receipts_root=hash(ssz_bytes32(payload, PL_RECEIPTS_ROOT)), logs_bloom=stateless_input_sub_slice(payload, PL_LOGS_BLOOM, 256), fee_recipient=address(ssz_addr(payload, PL_FEE_RECIPIENT)), parent_hash=hash(ssz_bytes32(payload, 0)), parent_beacon_block_root=hash(ssz_bytes32(input_ref.new_payload_request, NPR_BEACON_ROOT)), slot_number=slot_number(decode_ssz_uint(payload, PL_SLOT_NUMBER)), extra_data=input_ref.extra_data)

def decode_withdrawal(withdrawal: StatelessInputSlice) -> Withdrawal:
    return Withdrawal(index=withdrawal_index(decode_ssz_uint(withdrawal, WD_INDEX)), validator_index=validator_index(decode_ssz_uint(withdrawal, WD_VALIDATOR_INDEX)), address=address(ssz_addr(withdrawal, WD_ADDRESS)), amount=withdrawal_amount(decode_ssz_uint(withdrawal, WD_AMOUNT)))

def decode_chain_config(cc: StatelessInputSlice, number: withdrawal_amount, timestamp: withdrawal_amount) -> ChainConfig:
    cc_length = cc.len
    header_length = CHAIN_CONFIG_HEADER_LENGTH
    minimum_length = CHAIN_CONFIG_MIN_LENGTH
    if (int(cc_length) < int(header_length)):
        raise SailThrown(InvalidBlock(BlockError.InvalidConfig))
    f_offset = ssz_u32(cc, CC_ACTIVE_FORK_OFF)
    if ((((f_offset) != (12))) | ((int(cc_length) < int(minimum_length)))):
        raise SailThrown(InvalidBlock(BlockError.InvalidConfig))
    f = 12
    activation_offset = ssz_u32(cc, ssz_field_offset(f, FC_ACTIVATION_OFF))
    if ((activation_offset) != (4)):
        raise SailThrown(InvalidBlock(BlockError.InvalidConfig))
    activation_start = 16
    activation_fixed_end = 24
    a = 16
    block_number_offset = ssz_u32(cc, ssz_field_offset(a, FA_BLOCK_NUMBER_OFF))
    timestamp_offset = ssz_u32(cc, ssz_field_offset(a, FA_TIMESTAMP_OFF))
    if (((int(block_number_offset) > int((int(cc_length) - int(activation_start))))) | ((int(timestamp_offset) > int((int(cc_length) - int(activation_start)))))):
        raise SailThrown(InvalidBlock(BlockError.InvalidConfig))
    block_number_start = (int(activation_start) + int(block_number_offset))
    timestamp_start = (int(activation_start) + int(timestamp_offset))
    if ((activation_fixed_end) != (block_number_start)):
        raise SailThrown(InvalidBlock(BlockError.InvalidConfig))
    if (int(timestamp_start) < int(block_number_start)):
        raise SailThrown(InvalidBlock(BlockError.InvalidConfig))
    if (int(cc_length) < int(timestamp_start)):
        raise SailThrown(InvalidBlock(BlockError.InvalidConfig))
    bn_length = (int(timestamp_start) - int(block_number_start))
    ts_length = (int(cc_length) - int(timestamp_start))
    if ((((((bn_length) != (0))) & (((bn_length) != (SSZ_UINT_BYTES))))) | (((((ts_length) != (0))) & (((ts_length) != (SSZ_UINT_BYTES)))))):
        raise SailThrown(InvalidBlock(BlockError.InvalidConfig))
    if ((((bn_length) == (0))) & (((ts_length) == (0)))):
        raise SailThrown(InvalidBlock(BlockError.InvalidConfig))
    if ((bn_length) == (SSZ_UINT_BYTES)):
        activation_block = decode_ssz_uint(cc, block_number_start)
        if (int(number) < int(activation_block)):
            raise SailThrown(InvalidBlock(BlockError.InvalidConfig))
    if ((ts_length) == (SSZ_UINT_BYTES)):
        activation_timestamp = decode_ssz_uint(cc, timestamp_start)
        if (int(timestamp) < int(activation_timestamp)):
            raise SailThrown(InvalidBlock(BlockError.InvalidConfig))
    return ChainConfig(chain_id=chain_identifier(decode_ssz_uint(cc, CC_CHAIN_ID)))

def decode_stateless_input(input_ref: StatelessInputRef) -> StatelessInput:
    payload = input_ref.execution_payload
    header = decode_block_header_ssz(input_ref)
    chain_config = decode_chain_config(input_ref.chain_config, header.number, header.timestamp)
    k_set_header(header)
    environment.k_chain_id = chain_identifier(chain_config.chain_id)
    environment.k_execution_profile = execution_profile_for(input_ref.protocol, header.gas_limit)
    return StatelessInput(payload=ExecutionPayload(expected_block_hash=hash(ssz_bytes32(input_ref.execution_payload, PL_BLOCK_HASH)), block=Block(header=header, body=BlockBody(transactions=input_ref.transactions, withdrawals=input_ref.withdrawals, block_access_list=input_ref.block_access_list))), chain_config=chain_config)

def index_execution_witness(input_ref: StatelessInputRef) -> WitnessContext:
    _host_nodedb_reset()
    index_witness_nodes(input_ref.witness_state)
    index_witness_codes(input_ref.witness_codes)
    witness = index_witness_headers(input_ref.witness_headers)
    environment.k_parent_state_root = Bytes32(witness.parent_state_root)
    return witness

def decode_transaction(transaction: StatelessInputSliceFields, public_key: StatelessInputSliceFields) -> Transaction:
    execution_profile = environment.k_execution_profile
    profile = execution_profile.protocol
    if (int(transaction.len) <= int((1 << 30))):
        return rlp_decode_tx(transaction, public_key, profile.transaction_blob_limit)
    else:
        raise SailThrown(InvalidBlock(BlockError.InvalidConfig))

SSZ_BODY: Annotated[int, IntegerRange(2, 2)] = 2

IN_NPR_OFF: Annotated[int, IntegerRange(0, 0)] = 0

IN_WITNESS_OFF: Annotated[int, IntegerRange(4, 4)] = 4

IN_CHAIN_CONFIG_OFF: Annotated[int, IntegerRange(8, 8)] = 8

IN_PUBLIC_KEYS_OFF: Annotated[int, IntegerRange(12, 12)] = 12

NPR_PAYLOAD_OFF: Annotated[int, IntegerRange(0, 0)] = 0

NPR_VHASHES_OFF: Annotated[int, IntegerRange(4, 4)] = 4

NPR_BEACON_ROOT: Annotated[int, IntegerRange(8, 8)] = 8

NPR_REQUESTS_OFF: Annotated[int, IntegerRange(40, 40)] = 40

REQ_DEPOSITS_OFF: Annotated[int, IntegerRange(0, 0)] = 0

REQ_WITHDRAWALS_OFF: Annotated[int, IntegerRange(4, 4)] = 4

REQ_CONSOLIDATIONS_OFF: Annotated[int, IntegerRange(8, 8)] = 8

REQ_BUILDER_DEPOSITS_OFF: Annotated[int, IntegerRange(12, 12)] = 12

REQ_BUILDER_EXITS_OFF: Annotated[int, IntegerRange(16, 16)] = 16

PL_FEE_RECIPIENT: Annotated[int, IntegerRange(32, 32)] = 32

PL_STATE_ROOT: Annotated[int, IntegerRange(52, 52)] = 52

PL_RECEIPTS_ROOT: Annotated[int, IntegerRange(84, 84)] = 84

PL_LOGS_BLOOM: Annotated[int, IntegerRange(116, 116)] = 116

PL_PREV_RANDAO: Annotated[int, IntegerRange(372, 372)] = 372

PL_BLOCK_NUMBER: Annotated[int, IntegerRange(404, 404)] = 404

PL_GAS_LIMIT: Annotated[int, IntegerRange(412, 412)] = 412

PL_GAS_USED: Annotated[int, IntegerRange(420, 420)] = 420

PL_TIMESTAMP: Annotated[int, IntegerRange(428, 428)] = 428

PL_EXTRA_OFF: Annotated[int, IntegerRange(436, 436)] = 436

PL_BASE_FEE: Annotated[int, IntegerRange(440, 440)] = 440

PL_BLOCK_HASH: Annotated[int, IntegerRange(472, 472)] = 472

PL_TXS_OFF: Annotated[int, IntegerRange(504, 504)] = 504

PL_WDS_OFF: Annotated[int, IntegerRange(508, 508)] = 508

PL_BLOB_GAS_USED: Annotated[int, IntegerRange(512, 512)] = 512

PL_EXCESS_BLOB_GAS: Annotated[int, IntegerRange(520, 520)] = 520

PL_BAL_OFF: Annotated[int, IntegerRange(528, 528)] = 528

PL_SLOT_NUMBER: Annotated[int, IntegerRange(532, 532)] = 532

WD_SIZE: Annotated[int, IntegerRange(44, 44)] = 44

WD_INDEX: Annotated[int, IntegerRange(0, 0)] = 0

WD_VALIDATOR_INDEX: Annotated[int, IntegerRange(8, 8)] = 8

WD_ADDRESS: Annotated[int, IntegerRange(16, 16)] = 16

WD_AMOUNT: Annotated[int, IntegerRange(36, 36)] = 36

CC_CHAIN_ID: Annotated[int, IntegerRange(0, 0)] = 0

CC_ACTIVE_FORK_OFF: Annotated[int, IntegerRange(8, 8)] = 8

FC_ACTIVATION_OFF: Annotated[int, IntegerRange(0, 0)] = 0

FA_BLOCK_NUMBER_OFF: Annotated[int, IntegerRange(0, 0)] = 0

FA_TIMESTAMP_OFF: Annotated[int, IntegerRange(4, 4)] = 4

WIT_STATE_OFF: Annotated[int, IntegerRange(0, 0)] = 0

WIT_CODES_OFF: Annotated[int, IntegerRange(4, 4)] = 4

WIT_HEADERS_OFF: Annotated[int, IntegerRange(8, 8)] = 8

STATELESS_INPUT_FIXED_LENGTH: Annotated[int, IntegerRange(18, 18)] = 18

STATELESS_INPUT_BODY_FIXED_LENGTH: Annotated[int, IntegerRange(16, 16)] = 16

NEW_PAYLOAD_REQUEST_FIXED_LENGTH: Annotated[int, IntegerRange(44, 44)] = 44

EXECUTION_PAYLOAD_FIXED_LENGTH: Annotated[int, IntegerRange(540, 540)] = 540

EXECUTION_REQUESTS_FIXED_LENGTH: Annotated[int, IntegerRange(20, 20)] = 20

EXECUTION_WITNESS_FIXED_LENGTH: Annotated[int, IntegerRange(12, 12)] = 12

PUBLIC_KEY_LENGTH: Annotated[int, IntegerRange(65, 65)] = 65

CHAIN_CONFIG_HEADER_LENGTH: Annotated[int, IntegerRange(12, 12)] = 12

CHAIN_CONFIG_MIN_LENGTH: Annotated[int, IntegerRange(24, 24)] = 24

MAX_EXTRA_DATA_LENGTH: int = (1 << 5)

MAX_TRANSACTION_LENGTH: int = (1 << 30)

MAX_TRANSACTIONS_PER_PAYLOAD: int = (1 << 20)

MAX_WITHDRAWALS_PER_PAYLOAD: int = (1 << 4)

MAX_BLOCK_ACCESS_LIST_LENGTH: int = (1 << 30)

MAX_BLOB_COMMITMENTS_PER_BLOCK: int = (1 << 12)

MAX_WITNESS_NODES: int = (1 << 22)

MAX_WITNESS_NODE_LENGTH: int = (1 << 10)

MAX_WITNESS_CODES: int = (1 << 18)

MAX_WITNESS_CODE_LENGTH: int = (1 << 16)

MAX_WITNESS_HEADERS: int = (1 << 8)

MAX_WITNESS_HEADER_LENGTH: int = (1 << 10)

MAX_PUBLIC_KEYS: int = (1 << 15)

EMPTY_PARENT_HEADER_FIELDS: ParentHeaderFields = ParentHeaderFields(parent_hash=hash(ZERO_HASH), state_root=hash(ZERO_HASH), base_fee=word(ZERO_WORD), blob_gas_used=0, excess_blob_gas=excess_blob_gas(0), have_parent=False, have_state=False, have_base_fee=False, have_blob_gas=False, have_excess_blob_gas=False)
