# Generated by Sail's Python backend. Do not edit by hand.
# Sail source: primitives/account.sail
from __future__ import annotations

from dataclasses import dataclass
from evm.prelude import (
    address,
    hash,
    word,
    ZERO_WORD,
)
from evm.primitives.quantities import account_nonce
from evm.primitives.crypto import (
    KECCAK_EMPTY,
    EMPTY_TRIE_ROOT,
)

@dataclass(slots=True)
class AccountInfo:
    nonce: account_nonce
    balance: word
    code_hash: hash
    storage_root: hash

@dataclass(slots=True)
class Account:
    info: AccountInfo
    present: bool
    storage_cleared: bool
    created: bool
    selfdestructed: bool

@dataclass(slots=True)
class StorageValue:
    curr: word
    orig: word

class StorageTxLookup:
    pass

@dataclass(frozen=True, slots=True)
class StorageTxHit(StorageTxLookup):
    value: StorageValue

@dataclass(frozen=True, slots=True)
class StorageTxCleared(StorageTxLookup):
    value: None = None

@dataclass(frozen=True, slots=True)
class StorageTxMiss(StorageTxLookup):
    value: None = None

@dataclass(slots=True)
class StorageKey:
    addr: address
    slot: word

@dataclass(slots=True)
class StorageEntry:
    key: StorageKey
    value: StorageValue

@dataclass(slots=True)
class AcctValue:
    curr: Account
    orig: Account

@dataclass(slots=True)
class AcctEntry:
    addr: address
    value: AcctValue

@dataclass(slots=True)
class StorageTrieEntry:
    entry: StorageEntry
    address_hash: hash
    slot_hash: hash

@dataclass(slots=True)
class AcctTrieEntry:
    entry: AcctEntry
    address_hash: hash

def account_from_info(info: AccountInfo) -> Account:
    return Account(info=info, present=True, storage_cleared=False, created=False, selfdestructed=False)

EMPTY_ACCOUNT_INFO: AccountInfo = AccountInfo(nonce=account_nonce(0), balance=word(ZERO_WORD), code_hash=hash(KECCAK_EMPTY), storage_root=hash(EMPTY_TRIE_ROOT))

EMPTY_ACCOUNT: Account = Account(info=EMPTY_ACCOUNT_INFO, present=False, storage_cleared=True, created=False, selfdestructed=False)
