# Generated by Sail's Python backend. Do not edit by hand.
# Sail source: primitives/evm.sail
from __future__ import annotations

from .._runtime import (
    Bytes20,
    Uint,
    UintEnum,
)
from dataclasses import dataclass
from typing import TypeAlias
from pydantic import ConfigDict, model_validator
from pydantic.dataclasses import dataclass as pydantic_dataclass
from typing_extensions import Self
from evm.prelude import (
    address,
    word,
    ZERO_WORD,
    ZERO_ADDRESS,
)
from evm.primitives.quantities import (
    account_nonce,
    code_pointer,
    frame_depth,
    journal_checkpoint,
    memory_length,
    memory_pointer,
)
from evm.primitives.gas import (
    block_gas_limit,
    gas,
    gas_cost,
    gas_refund,
    state_gas_delta,
    state_gas_spill,
    GAS_ZERO,
)
from evm.primitives.bytes import (
    CalldataSlice,
    MemorySlice,
)
from evm.evm.halt import FrameStatus
from evm.primitives.code import Code
from evm.primitives.tx import BlobHashesFields

@pydantic_dataclass(config=ConfigDict(strict=True, arbitrary_types_allowed=True), frozen=True, slots=True, kw_only=True)
class TxEnvFieldsValidity:
    blob_limit: int

    @model_validator(mode="after")
    def validate(self) -> Self:
        if not (((self.blob_limit == 0) or ((self.blob_limit == 6) or (self.blob_limit == 9)))):
            raise ValueError("TxEnvFieldsValidity violates Sail constraint transaction_blob_limit_value('blob_limit)")
        return self

@pydantic_dataclass(config=ConfigDict(strict=True, validate_assignment=True, revalidate_instances="always", arbitrary_types_allowed=True), slots=True, kw_only=True)
class TxEnvFields:
    validity: TxEnvFieldsValidity
    origin: address
    gas_price: word
    blob_hashes: BlobHashesFields

TxEnv: TypeAlias = TxEnvFields

def tx_env(origin: address, gas_price: word, blob_hashes: BlobHashesFields) -> TxEnvFields:
    return TxEnvFields(validity=TxEnvFieldsValidity(blob_limit=blob_hashes.validity.limit), origin=Bytes20(origin), gas_price=word(gas_price), blob_hashes=blob_hashes)

@pydantic_dataclass(config=ConfigDict(strict=True, arbitrary_types_allowed=True), frozen=True, slots=True, kw_only=True)
class TransactionGasAllowanceFieldsValidity:
    total: int
    regular: int

    @model_validator(mode="after")
    def validate(self) -> Self:
        if not (((0 <= self.regular) and ((self.regular <= self.total) and (self.total <= ((2 ** 64) - 1))))):
            raise ValueError("TransactionGasAllowanceFieldsValidity violates Sail constraint (0 <= 'regular & ('regular <= 'total & 'total <= block_gas_limit_bound))")
        return self

@pydantic_dataclass(config=ConfigDict(strict=True, validate_assignment=True, revalidate_instances="always", arbitrary_types_allowed=True), slots=True, kw_only=True)
class TransactionGasAllowanceFields:
    validity: TransactionGasAllowanceFieldsValidity
    total: int
    regular: int

    @model_validator(mode="after")
    def validate(self) -> Self:
        if not ((int(self.total) == self.validity.total)):
            raise ValueError("TransactionGasAllowanceFields.total violates Sail type int('total)")
        if not ((int(self.regular) == self.validity.regular)):
            raise ValueError("TransactionGasAllowanceFields.regular violates Sail type int('regular)")
        return self

TransactionGasAllowance: TypeAlias = TransactionGasAllowanceFields

@dataclass(slots=True)
class TxValidity:
    sender: address
    nonce_before: account_nonce
    gas_limit: block_gas_limit
    initial_execution_gas: gas
    initial_state_gas: gas
    intrinsic_execution_gas: gas_cost
    intrinsic_state_gas: gas_cost
    calldata_floor: gas_cost
    blob_fee: word
    gas_price: word
    priority_fee: word

@pydantic_dataclass(config=ConfigDict(strict=True, validate_assignment=True, revalidate_instances="always", arbitrary_types_allowed=True), slots=True, kw_only=True)
class TxFrameResult:
    success: bool
    execution_gas_remaining: gas
    state_gas_remaining: gas
    state_gas_used: state_gas_delta
    refund: gas_refund

    @model_validator(mode="after")
    def validate(self) -> Self:
        if not (((-(199 * ((2 ** 64) - 1))) <= int(self.refund) <= (199 * ((2 ** 64) - 1)))):
            raise ValueError("TxFrameResult.refund violates Sail type range(- (199 * (2 ^ 64 - 1)), (199 * (2 ^ 64 - 1)))")
        return self

class CallKind(UintEnum):
    Call = Uint(0)
    CallCode = Uint(1)
    DelegateCall = Uint(2)
    StaticCall = Uint(3)

_Message_address_type: TypeAlias = address
@dataclass(slots=True)
class Message:
    caller: _Message_address_type
    code_address: _Message_address_type
    address: _Message_address_type
    value: word
    state_gas_reservoir: gas
    is_static: bool
    depth: frame_depth

@pydantic_dataclass(config=ConfigDict(strict=True, validate_assignment=True, revalidate_instances="always", arbitrary_types_allowed=True), slots=True, kw_only=True)
class FrameCheckpoint:
    state: journal_checkpoint
    pc: code_pointer
    gas_remaining: gas
    state_gas_remaining: gas
    state_gas_spilled: state_gas_spill
    refund: gas_refund
    status: FrameStatus
    message: Message
    call_depth: frame_depth
    code: Code
    calldata: CalldataSlice
    memory: MemorySlice

    @model_validator(mode="after")
    def validate(self) -> Self:
        if not (((-(199 * ((2 ** 64) - 1))) <= int(self.refund) <= (199 * ((2 ** 64) - 1)))):
            raise ValueError("FrameCheckpoint.refund violates Sail type range(- (199 * (2 ^ 64 - 1)), (199 * (2 ^ 64 - 1)))")
        return self

@dataclass(slots=True)
class CallContinuation:
    checkpoint: FrameCheckpoint
    return_offset: memory_pointer
    return_length: memory_length
    new_account_charged: bool

_CreateContinuation_address_type: TypeAlias = address
@dataclass(slots=True)
class CreateContinuation:
    checkpoint: FrameCheckpoint
    address: _CreateContinuation_address_type
    new_account_charged: bool

class FrameContinuation:
    pass

@dataclass(frozen=True, slots=True)
class Empty(FrameContinuation):
    value: None = None

@dataclass(frozen=True, slots=True)
class ResumeCall(FrameContinuation):
    value: CallContinuation

@dataclass(frozen=True, slots=True)
class ResumeCreate(FrameContinuation):
    value: CreateContinuation

DEFAULT_MESSAGE: Message = Message(caller=Bytes20(ZERO_ADDRESS), address=Bytes20(ZERO_ADDRESS), code_address=Bytes20(ZERO_ADDRESS), value=word(ZERO_WORD), state_gas_reservoir=Uint(GAS_ZERO), is_static=False, depth=frame_depth(0))
