# Generated by Sail's Python backend. Do not edit by hand.
# Sail source: primitives/fork.sail
from __future__ import annotations

from .._runtime import (
    IntegerRange,
    Unsigned,
)
from typing import Annotated

class Fork(Unsigned):
    LOWER = 0
    UPPER = 16

    def _in_range(self, value: int) -> bool:
        return self.LOWER <= value <= self.UPPER

Frontier: Annotated[int, IntegerRange(0, 0)] = 0

Homestead: Annotated[int, IntegerRange(1, 1)] = 1

Byzantium: Annotated[int, IntegerRange(2, 2)] = 2

Constantinople: Annotated[int, IntegerRange(3, 3)] = 3

Istanbul: Annotated[int, IntegerRange(4, 4)] = 4

Berlin: Annotated[int, IntegerRange(5, 5)] = 5

London: Annotated[int, IntegerRange(6, 6)] = 6

ArrowGlacier: Annotated[int, IntegerRange(7, 7)] = 7

GrayGlacier: Annotated[int, IntegerRange(8, 8)] = 8

Paris: Annotated[int, IntegerRange(9, 9)] = 9

Shanghai: Annotated[int, IntegerRange(10, 10)] = 10

Cancun: Annotated[int, IntegerRange(11, 11)] = 11

Prague: Annotated[int, IntegerRange(12, 12)] = 12

Osaka: Annotated[int, IntegerRange(13, 13)] = 13

BPO1: Annotated[int, IntegerRange(14, 14)] = 14

BPO2: Annotated[int, IntegerRange(15, 15)] = 15

Amsterdam: Annotated[int, IntegerRange(16, 16)] = 16
