# Generated by Sail's Python backend. Do not edit by hand.
# Sail source: primitives/stateless_input.sail
from __future__ import annotations

from dataclasses import dataclass
from evm.prelude import (
    hash,
    word,
)
from evm.primitives.quantities import (
    blob_gas_used,
    excess_blob_gas,
)
from evm.primitives.chain_config import ChainConfig
from evm.primitives.block import ExecutionPayload

@dataclass(slots=True)
class StatelessInput:
    payload: ExecutionPayload
    chain_config: ChainConfig

@dataclass(slots=True)
class WitnessContext:
    parent_hash: hash
    parent_state_root: hash
    parent_base_fee_per_gas: word
    parent_blob_gas_used: blob_gas_used
    parent_excess_blob_gas: excess_blob_gas
