# Generated by Sail's Python backend. Do not edit by hand.
# Sail source: primitives/tx.sail
from __future__ import annotations

from .._runtime import (
    BitWidth,
    Bits,
    SailError,
    SailExit,
    SailMatchFailure,
    Uint,
    UintEnum,
    Unsigned,
)
from dataclasses import dataclass
from typing import Annotated, TypeAlias
from pydantic import ConfigDict, model_validator
from pydantic.dataclasses import dataclass as pydantic_dataclass
from typing_extensions import Self
from evm.prelude import (
    address,
    hash,
    word,
)
from evm.primitives.quantities import (
    account_nonce,
    chain_identifier,
    transaction_blob_count,
)
from evm.primitives.gas import (
    gas,
    transaction_gas,
)
from evm.primitives.bytes import (
    StatelessInputSlice,
    StatelessInputSliceFields,
    EMPTY_STATELESS_INPUT_SLICE,
)

class TxType(UintEnum):
    LegacyTx = Uint(0)
    AccessListTx = Uint(1)
    FeeMarketTx = Uint(2)
    BlobTx = Uint(3)
    SetCodeTx = Uint(4)

_Authorization_address_type: TypeAlias = address
@dataclass(slots=True)
class Authorization:
    valid_sig: bool
    authority: _Authorization_address_type
    address: _Authorization_address_type
    nonce: account_nonce
    chain_id: word

@pydantic_dataclass(config=ConfigDict(strict=True, arbitrary_types_allowed=True), frozen=True, slots=True, kw_only=True)
class BlobHashesFieldsValidity:
    limit: int

    @model_validator(mode="after")
    def validate(self) -> Self:
        if not (((self.limit == 0) or ((self.limit == 6) or (self.limit == 9)))):
            raise ValueError("BlobHashesFieldsValidity violates Sail constraint transaction_blob_limit_value('limit)")
        return self

@pydantic_dataclass(config=ConfigDict(strict=True, validate_assignment=True, revalidate_instances="always", arbitrary_types_allowed=True), slots=True, kw_only=True)
class BlobHashesFields:
    validity: BlobHashesFieldsValidity
    bytes: StatelessInputSlice
    count: transaction_blob_count

    @model_validator(mode="after")
    def validate(self) -> Self:
        if not ((0 <= int(self.count) <= self.validity.limit)):
            raise ValueError("BlobHashesFields.count violates Sail type range(0, 'limit)")
        return self

class transaction_item_count(Unsigned):
    LOWER = 0
    UPPER = 1073741824

    def _in_range(self, value: int) -> bool:
        return self.LOWER <= value <= self.UPPER

@dataclass(slots=True)
class AccessListRef:
    encoded: StatelessInputSlice
    address_count: transaction_item_count
    slot_count: transaction_item_count

@dataclass(slots=True)
class AuthorizationListRef:
    encoded: StatelessInputSlice
    count: transaction_item_count

class transaction_byte_length(Unsigned):
    LOWER = 0
    UPPER = 1073741824

    def _in_range(self, value: int) -> bool:
        return self.LOWER <= value <= self.UPPER

class transaction_calldata_cost(Unsigned):
    LOWER = 0
    UPPER = 17179869184

    def _in_range(self, value: int) -> bool:
        return self.LOWER <= value <= self.UPPER

class transaction_calldata_floor_cost(Unsigned):
    LOWER = 0
    UPPER = 42949693960

    def _in_range(self, value: int) -> bool:
        return self.LOWER <= value <= self.UPPER

transaction_initcode_cost: TypeAlias = Uint

@pydantic_dataclass(config=ConfigDict(strict=True, arbitrary_types_allowed=True), frozen=True, slots=True, kw_only=True)
class TransactionFieldsValidity:
    blob_limit: int

    @model_validator(mode="after")
    def validate(self) -> Self:
        if not (((self.blob_limit == 0) or ((self.blob_limit == 6) or (self.blob_limit == 9)))):
            raise ValueError("TransactionFieldsValidity violates Sail constraint transaction_blob_limit_value('blob_limit)")
        return self

@pydantic_dataclass(config=ConfigDict(strict=True, validate_assignment=True, revalidate_instances="always", arbitrary_types_allowed=True), slots=True, kw_only=True)
class TransactionFields:
    validity: TransactionFieldsValidity
    tx_type: TxType
    sender: address
    nonce: word
    chain_id: chain_identifier
    gas_limit: transaction_gas
    is_create: bool
    recipient: address
    value: word
    raw: StatelessInputSlice
    input_src: TransactionInputSlice
    access_list: AccessListRef
    max_fee: word
    max_blob_fee: word
    max_priority_fee: word
    authorizations: AuthorizationListRef
    blob_hashes: BlobHashesFields
    pubkey: StatelessInputSlice
    signing_hash: hash
    sig_v: word
    sig_r: word
    sig_s: word

Transaction: TypeAlias = TransactionFields

class LogTopics:
    pass

@dataclass(frozen=True, slots=True)
class LogTopics0(LogTopics):
    value: None = None

@dataclass(frozen=True, slots=True)
class LogTopics1(LogTopics):
    value: word

@dataclass(frozen=True, slots=True)
class LogTopics2(LogTopics):
    value: tuple[word, word]

@dataclass(frozen=True, slots=True)
class LogTopics3(LogTopics):
    value: tuple[word, word, word]

@dataclass(frozen=True, slots=True)
class LogTopics4(LogTopics):
    value: tuple[word, word, word, word]

log_store_index: TypeAlias = Uint

def log_store_index_increment(value: log_store_index) -> log_store_index:
    if (int(value) < int((int((1 << 64)) - 1))):
        return log_store_index((int(value) + 1))
    else:
        if not (False):
            raise SailError("log store index overflow")
        raise SailExit(None)

def log_store_index_add(left: log_store_index, right: log_store_index) -> log_store_index:
    if (int(right) <= int((int((int((1 << 64)) - 1)) - int(left)))):
        return log_store_index((int(left) + int(right)))
    else:
        if not (False):
            raise SailError("log store index overflow")
        raise SailExit(None)

@dataclass(slots=True)
class LogSeriesRef:
    start: log_store_index
    count: log_store_index

@dataclass(slots=True)
class Receipt:
    tx_type: TxType
    success: bool
    gas_used: gas
    execution_gas: gas
    state_gas: gas
    logs: LogSeriesRef

def tx_type_byte(t: TxType) -> Annotated[Bits, BitWidth(8)]:
    match t:
        case TxType.LegacyTx:
            return Bits(8, 0b00000000)
        case TxType.AccessListTx:
            return Bits(8, 0b00000001)
        case TxType.FeeMarketTx:
            return Bits(8, 0b00000010)
        case TxType.BlobTx:
            return Bits(8, 0b00000011)
        case TxType.SetCodeTx:
            return Bits(8, 0b00000100)
        case _:
            raise SailMatchFailure("no Sail match clause applied")

def tx_is_access_list(t: TxType) -> bool:
    match t:
        case TxType.AccessListTx:
            return True
        case _:
            return False

def tx_is_dynamic_fee(t: TxType) -> bool:
    match t:
        case TxType.FeeMarketTx:
            return True
        case TxType.BlobTx:
            return True
        case TxType.SetCodeTx:
            return True
        case _:
            return False

def tx_is_blob(t: TxType) -> bool:
    match t:
        case TxType.BlobTx:
            return True
        case _:
            return False

def tx_is_set_code(t: TxType) -> bool:
    match t:
        case TxType.SetCodeTx:
            return True
        case _:
            return False

TransactionInputSlice: TypeAlias = StatelessInputSliceFields

EMPTY_BLOB_HASHES: BlobHashesFields = BlobHashesFields(validity=BlobHashesFieldsValidity(limit=0), bytes=EMPTY_STATELESS_INPUT_SLICE, count=Uint(0))

EMPTY_ACCESS_LIST_REF: AccessListRef = AccessListRef(encoded=EMPTY_STATELESS_INPUT_SLICE, address_count=transaction_item_count(0), slot_count=transaction_item_count(0))

EMPTY_AUTHORIZATION_LIST_REF: AuthorizationListRef = AuthorizationListRef(encoded=EMPTY_STATELESS_INPUT_SLICE, count=transaction_item_count(0))
