name = "evm"
defaultTargets = ["Evm"]
moreLeanArgs = ["--tstack=400000"]

[[lean_lib]]
name = "Evm"
leanOptions.weak.linter.style.nameCheck = false
moreLeancArgs= ["-fbracket-depth=500"]

[[require]]
name = "Sail"
path = ".lake/packages/Sail"


[[lean_exe]]
name = "run"
root = "Evm"
