# Generated by Sail's Python backend. Do not edit by hand.
# Sail source: lib/rlp/codecs/receipts.sail
from __future__ import annotations

from ...._runtime import (
    Bits,
    SailThrown,
)
from evm.HostContract import (
    log_address as _host_log_address,
    log_topic as _host_log_topic,
    log_topics_count as _host_log_topics_count,
)
from evm._sail.vector import neq_bits
from evm.primitives.quantities import word_of_nat_byte_count
from evm.primitives.bytes import (
    ScratchSlice,
    EIGHT_BYTE_LENGTH,
)
from evm.exceptions import (
    BlockError,
    InvalidBlock,
)
from evm.kernel.scratch import (
    scratch_length_add,
    scratch_reserve,
    scratch_push_byte,
    scratch_push_fixed_bytes_256,
)
from evm.primitives.tx import (
    LogSeriesRef,
    Receipt,
    log_store_index,
    tx_envelope_type_forwards,
    log_store_index_increment,
    log_store_index_add,
)
from evm.primitives.block import LogsBloom
from evm.lib.rlp.encoding import (
    rlp_scratch_length,
    rlp_scratch_small_length,
    rlp_scratch_length_add,
    rlp_length_prefix_len,
    rlp_uint_word_size,
    rlp_word_size,
    rlp_addr_size,
    rlp_scratch_list_size,
    rlp_log_scratch_slice_size,
    rlp_write_string_prefix,
    rlp_write_list_prefix,
    rlp_write_log_data_slice,
    rlp_write_uint_word,
    rlp_write_word,
    rlp_write_addr,
    rlp_encoder_begin,
    rlp_encoder_finish,
)
from evm.kernel.logs import (
    read_log_data,
    LOGS_BLOOM_BYTE_LENGTH,
)

def topics_rlp_content_size(index: log_store_index) -> rlp_scratch_length:
    size = 0
    topic = 0
    topic_count = _host_log_topics_count(index)
    while True:
        if not ((int(topic) < int(topic_count))):
            break
        size = rlp_scratch_length(rlp_scratch_length_add(size, rlp_scratch_small_length(rlp_word_size())))
        topic = log_store_index(log_store_index_increment(topic))
    return rlp_scratch_length(size)

def topics_rlp_size(index: log_store_index) -> rlp_scratch_length:
    return rlp_scratch_length(rlp_scratch_list_size(topics_rlp_content_size(index)))

def log_entry_rlp_content_size(index: log_store_index) -> rlp_scratch_length:
    address_length = rlp_scratch_small_length(rlp_addr_size())
    topics_length = topics_rlp_size(index)
    data_length = rlp_log_scratch_slice_size(read_log_data(index))
    return rlp_scratch_length(rlp_scratch_length_add(rlp_scratch_length_add(address_length, topics_length), data_length))

def log_entry_rlp_size(index: log_store_index) -> rlp_scratch_length:
    return rlp_scratch_length(rlp_scratch_list_size(log_entry_rlp_content_size(index)))

def logs_rlp_content_size(logs: LogSeriesRef) -> rlp_scratch_length:
    size = 0
    offset = 0
    while True:
        if not ((int(offset) < int(logs.count))):
            break
        size = rlp_scratch_length(rlp_scratch_length_add(size, log_entry_rlp_size(log_store_index_add(logs.start, offset))))
        offset = log_store_index(log_store_index_increment(offset))
    return rlp_scratch_length(size)

def logs_rlp_size(logs: LogSeriesRef) -> rlp_scratch_length:
    return rlp_scratch_length(rlp_scratch_list_size(logs_rlp_content_size(logs)))

def rlp_write_topics(index: log_store_index) -> None:
    rlp_write_list_prefix(topics_rlp_content_size(index))
    topic = 0
    topic_count = _host_log_topics_count(index)
    while True:
        if not ((int(topic) < int(topic_count))):
            break
        rlp_write_word(_host_log_topic(index, topic))
        topic = log_store_index(log_store_index_increment(topic))
    return None

def rlp_write_log_entry(index: log_store_index) -> None:
    rlp_write_list_prefix(log_entry_rlp_content_size(index))
    rlp_write_addr(_host_log_address(index))
    rlp_write_topics(index)
    return rlp_write_log_data_slice(read_log_data(index))

def rlp_write_logs(logs: LogSeriesRef) -> None:
    rlp_write_list_prefix(logs_rlp_content_size(logs))
    offset = 0
    while True:
        if not ((int(offset) < int(logs.count))):
            break
        rlp_write_log_entry(log_store_index_add(logs.start, offset))
        offset = log_store_index(log_store_index_increment(offset))
    return None

def rlp_write_logs_bloom(bloom: LogsBloom) -> None:
    rlp_write_string_prefix(LOGS_BLOOM_BYTE_LENGTH, Bits(8, 0b00000000))
    return scratch_push_fixed_bytes_256(bloom)

def receipt_write_logs_bloom(_receipt: Receipt, bloom: LogsBloom) -> None:
    return rlp_write_logs_bloom(bloom)

def receipt_payload_content_size(r: Receipt, cumulative_gas_used: int) -> rlp_scratch_length:
    if r.success:
        status = 1
    else:
        status = 0
    status_length = rlp_scratch_small_length(rlp_uint_word_size(status))
    gas_word = word_of_nat_byte_count(cumulative_gas_used)
    gas_length = rlp_scratch_small_length(rlp_uint_word_size(gas_word))
    bloom_length = rlp_scratch_length_add(LOGS_BLOOM_BYTE_LENGTH, rlp_scratch_small_length(rlp_length_prefix_len(LOGS_BLOOM_BYTE_LENGTH)))
    logs_length = logs_rlp_size(r.logs)
    fixed_length = rlp_scratch_length_add(status_length, gas_length)
    return rlp_scratch_length(rlp_scratch_length_add(rlp_scratch_length_add(fixed_length, bloom_length), logs_length))

def receipt_encoded_length(r: Receipt, cumulative_gas_used: int) -> rlp_scratch_length:
    content_len = receipt_payload_content_size(r, cumulative_gas_used)
    envelope_type = tx_envelope_type_forwards(r.tx_type)
    typed = neq_bits(envelope_type, Bits(8, 0b00000000))
    payload_len = rlp_scratch_list_size(content_len)
    if typed:
        return rlp_scratch_length(rlp_scratch_length_add(payload_len, 1))
    else:
        return rlp_scratch_length(payload_len)

def receipt_write_encoded(r: Receipt, cumulative_gas_used: int, bloom: LogsBloom) -> None:
    if r.success:
        status = 1
    else:
        status = 0
    content_len = receipt_payload_content_size(r, cumulative_gas_used)
    envelope_type = tx_envelope_type_forwards(r.tx_type)
    typed = neq_bits(envelope_type, Bits(8, 0b00000000))
    if typed:
        scratch_push_byte(envelope_type)
    rlp_write_list_prefix(content_len)
    rlp_write_uint_word(status)
    rlp_write_uint_word(cumulative_gas_used)
    receipt_write_logs_bloom(r, bloom)
    return rlp_write_logs(r.logs)

def receipt_encoded(r: Receipt, cumulative_gas_used: int, bloom: LogsBloom) -> ScratchSlice:
    encoded_len = receipt_encoded_length(r, cumulative_gas_used)
    encoder = rlp_encoder_begin(encoded_len)
    receipt_write_encoded(r, cumulative_gas_used, bloom)
    return rlp_encoder_finish(encoder)

def receipt_record_write_length(value: int) -> None:
    scratch_push_byte(Bits(8, int(value) >> 0))
    scratch_push_byte(Bits(8, int(value) >> 8))
    scratch_push_byte(Bits(8, int(value) >> 16))
    scratch_push_byte(Bits(8, int(value) >> 24))
    scratch_push_byte(Bits(8, int(value) >> 32))
    scratch_push_byte(Bits(8, int(value) >> 40))
    scratch_push_byte(Bits(8, int(value) >> 48))
    return scratch_push_byte(Bits(8, int(value) >> 56))

def receipt_record_append(r: Receipt, cumulative_gas_used: int, bloom: LogsBloom) -> None:
    encoded_len = receipt_encoded_length(r, cumulative_gas_used)
    if (int((int((1 << 64)) - 1)) < int(encoded_len)):
        raise SailThrown(InvalidBlock(BlockError.RlpDecode))
    record_len = scratch_length_add(EIGHT_BYTE_LENGTH, encoded_len)
    _record_start = scratch_reserve(record_len)
    receipt_record_write_length(encoded_len)
    encoder = rlp_encoder_begin(encoded_len)
    receipt_write_encoded(r, cumulative_gas_used, bloom)
    _encoded = rlp_encoder_finish(encoder)
    return None
