# Generated by Sail's Python backend. Do not edit by hand.
# Sail source: lib/rlp/codecs/withdrawals.sail
from __future__ import annotations

from ...._runtime import (
    SailThrown,
    sail_tmod_int,
)
from evm.primitives.bytes import (
    ScratchSlice,
    StatelessInputSliceFields,
    stateless_input_sub_slice,
    ADDRESS_BYTE_LENGTH,
)
from evm.exceptions import (
    BlockError,
    InvalidBlock,
)
from evm.lib.ssz.ssz import decode_ssz_uint
from evm.lib.rlp.encoding import (
    rlp_input_slice_size,
    rlp_uint_word_size,
    rlp_list_size,
    rlp_write_list_prefix,
    rlp_write_input_slice,
    rlp_write_uint_word,
    rlp_encoder_begin,
    rlp_encoder_finish,
)
from evm.lib.ssz.stateless_input import (
    WD_INDEX,
    WD_VALIDATOR_INDEX,
    WD_ADDRESS,
    WD_AMOUNT,
)

def withdrawal_rlp(withdrawal: StatelessInputSliceFields) -> ScratchSlice:
    index = decode_ssz_uint(withdrawal, WD_INDEX)
    validator_index = decode_ssz_uint(withdrawal, WD_VALIDATOR_INDEX)
    address = stateless_input_sub_slice(withdrawal, WD_ADDRESS, ADDRESS_BYTE_LENGTH)
    amount = decode_ssz_uint(withdrawal, WD_AMOUNT)
    index_length = rlp_uint_word_size(index)
    validator_index_length = rlp_uint_word_size(validator_index)
    address_length = rlp_input_slice_size(address)
    amount_length = rlp_uint_word_size(amount)
    content_length = (int((int((int(index_length) + int(validator_index_length))) + int(address_length))) + int(amount_length))
    if (48 < int(content_length)):
        raise SailThrown(InvalidBlock(BlockError.RlpDecode))
    bounded_content_length = sail_tmod_int(content_length, 49)
    content_len = bounded_content_length
    encoder = rlp_encoder_begin(rlp_list_size(content_len))
    rlp_write_list_prefix(content_len)
    rlp_write_uint_word(index)
    rlp_write_uint_word(validator_index)
    rlp_write_input_slice(address)
    rlp_write_uint_word(amount)
    return rlp_encoder_finish(encoder)
