# Generated by Sail's Python backend. Do not edit by hand.
# Sail source: lib/rlp/codecs/transactions.sail
from __future__ import annotations

from ...._runtime import (
    Bits,
    IntegerRange,
    SailMatchFailure,
    Uint,
    sail_ediv_int,
    sail_vector_subrange,
)
from typing import Annotated
from pydantic import ConfigDict, model_validator
from pydantic.dataclasses import dataclass as pydantic_dataclass
from typing_extensions import Self
from evm.HostContract import (
    stateless_input_keccak256 as _host_stateless_input_keccak256,
)
from evm._sail.vector import neq_bits
from evm.prelude import (
    AddressResult,
    address,
    hash,
    word,
    hash_to_word,
    word_to_address,
    word_ult,
    word_ule,
    ZERO_WORD,
    ZERO_ADDRESS,
)
from evm.primitives.quantities import (
    account_nonce,
    chain_identifier,
    transaction_blob_count,
    word_of_account_nonce,
)
from evm.primitives.gas import (
    block_gas,
    transaction_gas,
)
from evm.primitives.bytes import (
    StatelessInputSlice,
    StatelessInputSliceFields,
    stateless_input_slice,
    stateless_input_sub_slice,
    WORD_BYTE_LENGTH,
)
from evm.exceptions import (
    FatalError,
    fatal_error,
)
from evm.primitives.rlp import (
    RlpCursor,
    RlpFieldRef,
    RlpInvalidValue,
    RlpOk,
)
from evm.host.region_access import stateless_input_slice_byte
from evm.primitives.crypto import (
    ecrecover_addr,
    SECP_N_FULL,
    SECP_N_HALF,
)
from evm.primitives.account import StorageKey
from evm.primitives.tx import (
    AccessListRef,
    Authorization,
    AuthorizationListRef,
    BlobHashesFields,
    BlobHashesFieldsValidity,
    PreparedAuthorizationList,
    TransactionFields,
    TransactionFieldsValidity,
    TransactionInputSlice,
    TxType,
    prepared_authorization_count,
    transaction_byte_length,
    transaction_item_count,
    authorization_list_ref,
    pack_transaction,
    EMPTY_BLOB_HASHES,
    EMPTY_ACCESS_LIST_REF,
    EMPTY_AUTHORIZATION_LIST_REF,
)
from evm.lib.rlp.decoding import (
    rlp_decode_list,
    rlp_decode_item,
    rlp_cursor_advance,
    rlp_cursor_expect_end,
    rlp_node_cursor,
    rlp_item_content,
    rlp_decode_word,
    rlp_decode_u256,
    rlp_decode_uint64,
    rlp_decode_bool,
)
from evm.lib.rlp.codecs.transaction_signing import (
    tx_signing_hash,
    auth_signing_hash,
    PUBLIC_KEY_BODY_LENGTH,
)

@pydantic_dataclass(config=ConfigDict(strict=True, arbitrary_types_allowed=True), frozen=True, slots=True, kw_only=True)
class AccessListDecodeValidity:
    address_bound: int
    slot_bound: int

    @model_validator(mode="after")
    def validate(self) -> Self:
        if not ((((0 <= self.address_bound) and (self.address_bound <= ((2 ** 32) - 1))) and ((0 <= self.slot_bound) and (self.slot_bound <= ((2 ** 32) - 1))))):
            raise ValueError("AccessListDecodeValidity violates Sail constraint (source_valid_length('address_bound) & source_valid_length('slot_bound))")
        return self

@pydantic_dataclass(config=ConfigDict(strict=True, validate_assignment=True, revalidate_instances="always", arbitrary_types_allowed=True), slots=True, kw_only=True)
class AccessListDecode:
    validity: AccessListDecodeValidity
    address_count: Uint
    slot_count: Uint

    @model_validator(mode="after")
    def validate(self) -> Self:
        if not ((0 <= int(self.address_count) <= self.validity.address_bound)):
            raise ValueError("AccessListDecode.address_count violates Sail type range(0, 'address_bound)")
        if not ((0 <= int(self.slot_count) <= self.validity.slot_bound)):
            raise ValueError("AccessListDecode.slot_count violates Sail type range(0, 'slot_bound)")
        return self

def transaction_rlp_content(f: RlpFieldRef) -> StatelessInputSlice:
    content = rlp_item_content(f)
    return stateless_input_slice(content.bytes, content.len)

def decode_access_list_keys(cursor: RlpCursor, addr: address, tail: AccessListDecode) -> AccessListDecode:
    if ((cursor.len) == (0)):
        return AccessListDecode(validity=AccessListDecodeValidity(address_bound=tail.validity.address_bound, slot_bound=(tail.validity.slot_bound + cursor.validity.len)), address_count=Uint(tail.address_count), slot_count=Uint(tail.slot_count))
    else:
        key = rlp_decode_item(cursor)
        next = rlp_cursor_advance(cursor, key.source.len)
        StorageKey(addr=address(addr), slot=word(rlp_decode_word(key)))
        result = decode_access_list_keys(next, addr, tail)
        return AccessListDecode(validity=AccessListDecodeValidity(address_bound=tail.validity.address_bound, slot_bound=(tail.validity.slot_bound + cursor.validity.len)), address_count=Uint(result.address_count), slot_count=Uint((int(result.slot_count) + 1)))

def decode_access_list_entries(cursor: RlpCursor) -> AccessListDecode:
    if ((cursor.len) == (0)):
        return EMPTY_ACCESS_LIST_DECODE
    else:
        entry = rlp_decode_item(cursor)
        next = rlp_cursor_advance(cursor, entry.source.len)
        entry_fields = rlp_decode_list(entry)
        addr_f = rlp_decode_item(entry_fields)
        entry_fields = rlp_cursor_advance(entry_fields, addr_f.source.len)
        keys_f = rlp_decode_item(entry_fields)
        entry_fields = rlp_cursor_advance(entry_fields, keys_f.source.len)
        rlp_cursor_expect_end(entry_fields)
        address_word = rlp_decode_word(addr_f)
        addr = word_to_address(address_word)
        tail = decode_access_list_entries(next)
        keys = rlp_decode_list(keys_f)
        result = decode_access_list_keys(keys, addr, tail)
        return AccessListDecode(validity=AccessListDecodeValidity(address_bound=cursor.validity.len, slot_bound=cursor.validity.len), address_count=Uint((int(result.address_count) + 1)), slot_count=Uint(result.slot_count))

def decode_access_list(f: RlpFieldRef) -> AccessListRef:
    if (int(f.source.len) <= int((1 << 30))):
        entries = rlp_decode_list(f)
        decoded = decode_access_list_entries(entries)
        return AccessListRef(encoded=transaction_rlp_content(f), address_count=transaction_item_count(decoded.address_count), slot_count=transaction_item_count(decoded.slot_count))
    else:
        return fatal_error(FatalError.RlpDecode)

def decode_blob_hash_items(cursor: RlpCursor, limit: int, count: transaction_blob_count) -> transaction_blob_count:
    if ((cursor.len) == (0)):
        return transaction_blob_count(count)
    else:
        item = rlp_decode_item(cursor)
        next = rlp_cursor_advance(cursor, item.source.len)
        item_prefix = stateless_input_slice_byte(item.source, 0)
        if ((item.is_list) | (((((item.source.len) != (BLOB_HASH_RLP_LENGTH))) | (((((item.content_len) != (BLOB_HASH_LENGTH))) | (neq_bits(item_prefix, Bits(8, 0b10100000)))))))):
            fatal_error(FatalError.RlpDecode)
        version = stateless_input_slice_byte(item.source, 1)
        if neq_bits(version, Bits(8, 0b00000001)):
            fatal_error(FatalError.ExecutionInvalid)
        if (int(count) < int(limit)):
            return transaction_blob_count(decode_blob_hash_items(next, limit, (int(count) + 1)))
        else:
            return transaction_blob_count(fatal_error(FatalError.RlpDecode))

def decode_blob_hashes(f: RlpFieldRef, limit: int) -> BlobHashesFields:
    bytes = transaction_rlp_content(f)
    items = rlp_decode_list(f)
    count = decode_blob_hash_items(items, limit, 0)
    return BlobHashesFields(validity=BlobHashesFieldsValidity(limit=int(limit)), bytes=bytes, count=transaction_blob_count(count))

def validate_auth_tuples(cursor: RlpCursor, count: transaction_byte_length) -> transaction_byte_length:
    if ((cursor.len) == (0)):
        return transaction_byte_length(count)
    else:
        sail_tuple = rlp_decode_item(cursor)
        next = rlp_cursor_advance(cursor, sail_tuple.source.len)
        rlp_decode_list(sail_tuple)
        if (int(count) < int((1 << 30))):
            return transaction_byte_length(validate_auth_tuples(next, (int(count) + 1)))
        else:
            return transaction_byte_length(fatal_error(FatalError.RlpDecode))

def decode_auth_list(f: RlpFieldRef) -> AuthorizationListRef:
    if (int(f.source.len) <= int((1 << 30))):
        content = transaction_rlp_content(f)
        tuples = rlp_decode_list(f)
        count = validate_auth_tuples(tuples, 0)
        return authorization_list_ref(content, count)
    else:
        return fatal_error(FatalError.RlpDecode)

def decode_authorization(sail_tuple: RlpFieldRef) -> Authorization:
    fields = rlp_decode_list(sail_tuple)
    chain_f = rlp_decode_item(fields)
    fields = rlp_cursor_advance(fields, chain_f.source.len)
    addr_f = rlp_decode_item(fields)
    fields = rlp_cursor_advance(fields, addr_f.source.len)
    nonce_f = rlp_decode_item(fields)
    fields = rlp_cursor_advance(fields, nonce_f.source.len)
    y_f = rlp_decode_item(fields)
    fields = rlp_cursor_advance(fields, y_f.source.len)
    y = rlp_decode_bool(y_f)
    r_f = rlp_decode_item(fields)
    fields = rlp_cursor_advance(fields, r_f.source.len)
    s_f = rlp_decode_item(fields)
    fields = rlp_cursor_advance(fields, s_f.source.len)
    rlp_cursor_expect_end(fields)
    chain_id = rlp_decode_u256(chain_f)
    auth_nonce = rlp_decode_uint64(nonce_f)
    r = rlp_decode_u256(r_f)
    s = rlp_decode_u256(s_f)
    address_word = rlp_decode_word(addr_f)
    auth_addr = word_to_address(address_word)
    signing_hash = auth_signing_hash(chain_id, auth_addr, auth_nonce)
    match y:
        case RlpOk(False):
            recovered = ecrecover_addr(signing_hash, 0, r, s)
        case RlpOk(True):
            recovered = ecrecover_addr(signing_hash, 1, r, s)
        case RlpInvalidValue(None):
            recovered = AddressResult(success=False, address=address(ZERO_ADDRESS))
        case _:
            raise SailMatchFailure("no Sail match clause applied")
    return Authorization(valid_sig=((recovered.success) & (((word_ult(ZERO_WORD, r)) & (((word_ult(r, SECP_N_FULL)) & (((word_ult(ZERO_WORD, s)) & (((word_ule(s, SECP_N_HALF)) & (((auth_nonce) != ((int((1 << 64)) - 1))))))))))))), authority=address(recovered.address), address=address(auth_addr), nonce=account_nonce(auth_nonce), chain_id=word(chain_id))

def prepare_authorization_entries(cursor: RlpCursor, count: prepared_authorization_count) -> list[Authorization]:
    if ((count) == (0)):
        if ((cursor.len) != (0)):
            fatal_error(FatalError.RlpDecode)
        return []
    else:
        if ((cursor.len) == (0)):
            fatal_error(FatalError.RlpDecode)
        sail_tuple = rlp_decode_item(cursor)
        next = rlp_cursor_advance(cursor, sail_tuple.source.len)
        authorization = decode_authorization(sail_tuple)
        return [authorization, *prepare_authorization_entries(next, (int(count) - 1))]

def prepare_authorizations(authorizations: AuthorizationListRef) -> PreparedAuthorizationList:
    if (int(authorizations.count) <= int(sail_ediv_int((1 << 24), 7816))):
        encoded = authorizations.encoded
        entries = prepare_authorization_entries(encoded, authorizations.count)
        return PreparedAuthorizationList(entries=entries, count=prepared_authorization_count(authorizations.count))
    else:
        return fatal_error(FatalError.ExecutionInvalid)

def prepared_authorization_head(authorizations: PreparedAuthorizationList) -> Authorization:
    match authorizations.entries:
        case [authorization, *_]:
            return authorization
        case []:
            return fatal_error(FatalError.ExecutionInvalid)

def prepared_authorization_tail(authorizations: PreparedAuthorizationList, count: int) -> PreparedAuthorizationList:
    match authorizations.entries:
        case [_, *entries]:
            return PreparedAuthorizationList(entries=entries, count=prepared_authorization_count((int(count) - 1)))
        case []:
            return fatal_error(FatalError.ExecutionInvalid)

def tx_input_span(data: RlpFieldRef) -> TransactionInputSlice:
    content = transaction_rlp_content(data)
    if (int(content.len) <= int((1 << 30))):
        return content
    else:
        return fatal_error(FatalError.RlpDecode)

def tx_sig_span(first: RlpFieldRef, signature: RlpFieldRef) -> StatelessInputSlice:
    start = first.source.bytes
    stop = signature.source.bytes
    start_offset = start
    stop_offset = stop
    if (int(stop_offset) < int(start_offset)):
        return fatal_error(FatalError.RlpDecode)
    else:
        return stateless_input_slice(start_offset, (int(stop_offset) - int(start_offset)))

def rlp_decode_gas(f: RlpFieldRef) -> block_gas:
    return block_gas(rlp_decode_uint64(f))

def decode_legacy_tx(tx: TransactionInputSlice, pubkey: StatelessInputSlice, sender: address, fields: RlpCursor) -> TransactionFields:
    nonce_f = rlp_decode_item(fields)
    fields = rlp_cursor_advance(fields, nonce_f.source.len)
    gp_f = rlp_decode_item(fields)
    fields = rlp_cursor_advance(fields, gp_f.source.len)
    gas_f = rlp_decode_item(fields)
    fields = rlp_cursor_advance(fields, gas_f.source.len)
    to_f = rlp_decode_item(fields)
    fields = rlp_cursor_advance(fields, to_f.source.len)
    value_f = rlp_decode_item(fields)
    fields = rlp_cursor_advance(fields, value_f.source.len)
    data_f = rlp_decode_item(fields)
    fields = rlp_cursor_advance(fields, data_f.source.len)
    v_f = rlp_decode_item(fields)
    fields = rlp_cursor_advance(fields, v_f.source.len)
    r_f = rlp_decode_item(fields)
    fields = rlp_cursor_advance(fields, r_f.source.len)
    s_f = rlp_decode_item(fields)
    fields = rlp_cursor_advance(fields, s_f.source.len)
    rlp_cursor_expect_end(fields)
    v = rlp_decode_word(v_f)
    gp = rlp_decode_u256(gp_f)
    recipient_word = rlp_decode_word(to_f)
    recipient = word_to_address(recipient_word)
    signing_span = tx_sig_span(nonce_f, v_f)
    signing_hash = tx_signing_hash(TxType.LegacyTx, signing_span, v)
    return TransactionFields(validity=TransactionFieldsValidity(blob_limit=0), tx_type=TxType.LegacyTx, sender=address(sender), raw=tx, nonce=word(rlp_decode_u256(nonce_f)), chain_id=chain_identifier(0), gas_limit=transaction_gas(rlp_decode_gas(gas_f)), is_create=((to_f.content_len) == (0)), recipient=address(recipient), value=word(rlp_decode_u256(value_f)), input_src=tx_input_span(data_f), access_list=EMPTY_ACCESS_LIST_REF, max_fee=word(gp), max_blob_fee=word(ZERO_WORD), max_priority_fee=word(gp), authorizations=EMPTY_AUTHORIZATION_LIST_REF, blob_hashes=EMPTY_BLOB_HASHES, pubkey=pubkey, signing_hash=hash(signing_hash), sig_v=word(v), sig_r=word(rlp_decode_u256(r_f)), sig_s=word(rlp_decode_u256(s_f)))

def decode_access_list_tx(tx: TransactionInputSlice, pubkey: StatelessInputSlice, sender: address, fields: RlpCursor) -> TransactionFields:
    chain_f = rlp_decode_item(fields)
    fields = rlp_cursor_advance(fields, chain_f.source.len)
    nonce_f = rlp_decode_item(fields)
    fields = rlp_cursor_advance(fields, nonce_f.source.len)
    gp_f = rlp_decode_item(fields)
    fields = rlp_cursor_advance(fields, gp_f.source.len)
    gas_f = rlp_decode_item(fields)
    fields = rlp_cursor_advance(fields, gas_f.source.len)
    to_f = rlp_decode_item(fields)
    fields = rlp_cursor_advance(fields, to_f.source.len)
    value_f = rlp_decode_item(fields)
    fields = rlp_cursor_advance(fields, value_f.source.len)
    data_f = rlp_decode_item(fields)
    fields = rlp_cursor_advance(fields, data_f.source.len)
    al_f = rlp_decode_item(fields)
    fields = rlp_cursor_advance(fields, al_f.source.len)
    v_f = rlp_decode_item(fields)
    fields = rlp_cursor_advance(fields, v_f.source.len)
    r_f = rlp_decode_item(fields)
    fields = rlp_cursor_advance(fields, r_f.source.len)
    s_f = rlp_decode_item(fields)
    fields = rlp_cursor_advance(fields, s_f.source.len)
    rlp_cursor_expect_end(fields)
    v = rlp_decode_word(v_f)
    gp = rlp_decode_u256(gp_f)
    access_list = decode_access_list(al_f)
    recipient_word = rlp_decode_word(to_f)
    recipient = word_to_address(recipient_word)
    signing_span = tx_sig_span(chain_f, v_f)
    signing_hash = tx_signing_hash(TxType.AccessListTx, signing_span, v)
    return TransactionFields(validity=TransactionFieldsValidity(blob_limit=0), tx_type=TxType.AccessListTx, sender=address(sender), raw=tx, nonce=word(rlp_decode_u256(nonce_f)), chain_id=chain_identifier(rlp_decode_uint64(chain_f)), gas_limit=transaction_gas(rlp_decode_gas(gas_f)), is_create=((to_f.content_len) == (0)), recipient=address(recipient), value=word(rlp_decode_u256(value_f)), input_src=tx_input_span(data_f), access_list=access_list, max_fee=word(gp), max_blob_fee=word(ZERO_WORD), max_priority_fee=word(gp), authorizations=EMPTY_AUTHORIZATION_LIST_REF, blob_hashes=EMPTY_BLOB_HASHES, pubkey=pubkey, signing_hash=hash(signing_hash), sig_v=word(v), sig_r=word(rlp_decode_u256(r_f)), sig_s=word(rlp_decode_u256(s_f)))

def decode_fee_market_tx(tx: TransactionInputSlice, pubkey: StatelessInputSlice, sender: address, fields: RlpCursor) -> TransactionFields:
    chain_f = rlp_decode_item(fields)
    fields = rlp_cursor_advance(fields, chain_f.source.len)
    nonce_f = rlp_decode_item(fields)
    fields = rlp_cursor_advance(fields, nonce_f.source.len)
    mp_f = rlp_decode_item(fields)
    fields = rlp_cursor_advance(fields, mp_f.source.len)
    mf_f = rlp_decode_item(fields)
    fields = rlp_cursor_advance(fields, mf_f.source.len)
    gas_f = rlp_decode_item(fields)
    fields = rlp_cursor_advance(fields, gas_f.source.len)
    to_f = rlp_decode_item(fields)
    fields = rlp_cursor_advance(fields, to_f.source.len)
    value_f = rlp_decode_item(fields)
    fields = rlp_cursor_advance(fields, value_f.source.len)
    data_f = rlp_decode_item(fields)
    fields = rlp_cursor_advance(fields, data_f.source.len)
    al_f = rlp_decode_item(fields)
    fields = rlp_cursor_advance(fields, al_f.source.len)
    v_f = rlp_decode_item(fields)
    fields = rlp_cursor_advance(fields, v_f.source.len)
    r_f = rlp_decode_item(fields)
    fields = rlp_cursor_advance(fields, r_f.source.len)
    s_f = rlp_decode_item(fields)
    fields = rlp_cursor_advance(fields, s_f.source.len)
    rlp_cursor_expect_end(fields)
    v = rlp_decode_word(v_f)
    access_list = decode_access_list(al_f)
    recipient_word = rlp_decode_word(to_f)
    recipient = word_to_address(recipient_word)
    signing_span = tx_sig_span(chain_f, v_f)
    signing_hash = tx_signing_hash(TxType.FeeMarketTx, signing_span, v)
    return TransactionFields(validity=TransactionFieldsValidity(blob_limit=0), tx_type=TxType.FeeMarketTx, sender=address(sender), raw=tx, nonce=word(rlp_decode_u256(nonce_f)), chain_id=chain_identifier(rlp_decode_uint64(chain_f)), gas_limit=transaction_gas(rlp_decode_gas(gas_f)), is_create=((to_f.content_len) == (0)), recipient=address(recipient), value=word(rlp_decode_u256(value_f)), input_src=tx_input_span(data_f), access_list=access_list, max_fee=word(rlp_decode_u256(mf_f)), max_blob_fee=word(ZERO_WORD), max_priority_fee=word(rlp_decode_u256(mp_f)), authorizations=EMPTY_AUTHORIZATION_LIST_REF, blob_hashes=EMPTY_BLOB_HASHES, pubkey=pubkey, signing_hash=hash(signing_hash), sig_v=word(v), sig_r=word(rlp_decode_u256(r_f)), sig_s=word(rlp_decode_u256(s_f)))

def decode_blob_tx(tx: TransactionInputSlice, pubkey: StatelessInputSlice, blob_limit: int, sender: address, fields: RlpCursor) -> TransactionFields:
    chain_f = rlp_decode_item(fields)
    fields = rlp_cursor_advance(fields, chain_f.source.len)
    nonce_f = rlp_decode_item(fields)
    fields = rlp_cursor_advance(fields, nonce_f.source.len)
    mp_f = rlp_decode_item(fields)
    fields = rlp_cursor_advance(fields, mp_f.source.len)
    mf_f = rlp_decode_item(fields)
    fields = rlp_cursor_advance(fields, mf_f.source.len)
    gas_f = rlp_decode_item(fields)
    fields = rlp_cursor_advance(fields, gas_f.source.len)
    to_f = rlp_decode_item(fields)
    fields = rlp_cursor_advance(fields, to_f.source.len)
    value_f = rlp_decode_item(fields)
    fields = rlp_cursor_advance(fields, value_f.source.len)
    data_f = rlp_decode_item(fields)
    fields = rlp_cursor_advance(fields, data_f.source.len)
    al_f = rlp_decode_item(fields)
    fields = rlp_cursor_advance(fields, al_f.source.len)
    mbf_f = rlp_decode_item(fields)
    fields = rlp_cursor_advance(fields, mbf_f.source.len)
    bh_f = rlp_decode_item(fields)
    fields = rlp_cursor_advance(fields, bh_f.source.len)
    v_f = rlp_decode_item(fields)
    fields = rlp_cursor_advance(fields, v_f.source.len)
    r_f = rlp_decode_item(fields)
    fields = rlp_cursor_advance(fields, r_f.source.len)
    s_f = rlp_decode_item(fields)
    fields = rlp_cursor_advance(fields, s_f.source.len)
    rlp_cursor_expect_end(fields)
    v = rlp_decode_word(v_f)
    access_list = decode_access_list(al_f)
    blob_hashes = decode_blob_hashes(bh_f, blob_limit)
    recipient_word = rlp_decode_word(to_f)
    recipient = word_to_address(recipient_word)
    signing_span = tx_sig_span(chain_f, v_f)
    signing_hash = tx_signing_hash(TxType.BlobTx, signing_span, v)
    return TransactionFields(validity=TransactionFieldsValidity(blob_limit=int(blob_limit)), tx_type=TxType.BlobTx, sender=address(sender), raw=tx, nonce=word(rlp_decode_u256(nonce_f)), chain_id=chain_identifier(rlp_decode_uint64(chain_f)), gas_limit=transaction_gas(rlp_decode_gas(gas_f)), is_create=((to_f.content_len) == (0)), recipient=address(recipient), value=word(rlp_decode_u256(value_f)), input_src=tx_input_span(data_f), access_list=access_list, max_fee=word(rlp_decode_u256(mf_f)), max_blob_fee=word(rlp_decode_u256(mbf_f)), max_priority_fee=word(rlp_decode_u256(mp_f)), authorizations=EMPTY_AUTHORIZATION_LIST_REF, blob_hashes=blob_hashes, pubkey=pubkey, signing_hash=hash(signing_hash), sig_v=word(v), sig_r=word(rlp_decode_u256(r_f)), sig_s=word(rlp_decode_u256(s_f)))

def decode_set_code_tx(tx: TransactionInputSlice, pubkey: StatelessInputSlice, sender: address, fields: RlpCursor) -> TransactionFields:
    chain_f = rlp_decode_item(fields)
    fields = rlp_cursor_advance(fields, chain_f.source.len)
    nonce_f = rlp_decode_item(fields)
    fields = rlp_cursor_advance(fields, nonce_f.source.len)
    mp_f = rlp_decode_item(fields)
    fields = rlp_cursor_advance(fields, mp_f.source.len)
    mf_f = rlp_decode_item(fields)
    fields = rlp_cursor_advance(fields, mf_f.source.len)
    gas_f = rlp_decode_item(fields)
    fields = rlp_cursor_advance(fields, gas_f.source.len)
    to_f = rlp_decode_item(fields)
    fields = rlp_cursor_advance(fields, to_f.source.len)
    value_f = rlp_decode_item(fields)
    fields = rlp_cursor_advance(fields, value_f.source.len)
    data_f = rlp_decode_item(fields)
    fields = rlp_cursor_advance(fields, data_f.source.len)
    al_f = rlp_decode_item(fields)
    fields = rlp_cursor_advance(fields, al_f.source.len)
    auth_f = rlp_decode_item(fields)
    fields = rlp_cursor_advance(fields, auth_f.source.len)
    v_f = rlp_decode_item(fields)
    fields = rlp_cursor_advance(fields, v_f.source.len)
    r_f = rlp_decode_item(fields)
    fields = rlp_cursor_advance(fields, r_f.source.len)
    s_f = rlp_decode_item(fields)
    fields = rlp_cursor_advance(fields, s_f.source.len)
    rlp_cursor_expect_end(fields)
    v = rlp_decode_word(v_f)
    access_list = decode_access_list(al_f)
    authorizations = decode_auth_list(auth_f)
    decoded_nonce = rlp_decode_uint64(nonce_f)
    nonce = word_of_account_nonce(decoded_nonce)
    recipient_word = rlp_decode_word(to_f)
    recipient = word_to_address(recipient_word)
    signing_span = tx_sig_span(chain_f, v_f)
    signing_hash = tx_signing_hash(TxType.SetCodeTx, signing_span, v)
    return TransactionFields(validity=TransactionFieldsValidity(blob_limit=0), tx_type=TxType.SetCodeTx, sender=address(sender), raw=tx, nonce=word(nonce), chain_id=chain_identifier(rlp_decode_uint64(chain_f)), gas_limit=transaction_gas(rlp_decode_gas(gas_f)), is_create=((to_f.content_len) == (0)), recipient=address(recipient), value=word(rlp_decode_u256(value_f)), input_src=tx_input_span(data_f), access_list=access_list, max_fee=word(rlp_decode_u256(mf_f)), max_blob_fee=word(ZERO_WORD), max_priority_fee=word(rlp_decode_u256(mp_f)), authorizations=authorizations, blob_hashes=EMPTY_BLOB_HASHES, pubkey=pubkey, signing_hash=hash(signing_hash), sig_v=word(v), sig_r=word(rlp_decode_u256(r_f)), sig_s=word(rlp_decode_u256(s_f)))

def rlp_decode_tx(tx: StatelessInputSliceFields, pubkey: StatelessInputSliceFields, blob_limit: int) -> TransactionFields:
    public_key_body = stateless_input_sub_slice(pubkey, 1, PUBLIC_KEY_BODY_LENGTH)
    public_key_hash = _host_stateless_input_keccak256(public_key_body)
    public_key_word = hash_to_word(public_key_hash)
    sender = word_to_address(public_key_word)
    tx_length = tx.len
    if ((tx_length) == (0)):
        b0 = fatal_error(FatalError.RlpDecode)
    else:
        b0 = stateless_input_slice_byte(tx, 0)
    if ((sail_vector_subrange(b0, 7, 6, False)) == (Bits(2, 0b11))):
        ttype = Bits(8, 0b00000000)
    else:
        ttype = b0
    typed = neq_bits(ttype, Bits(8, 0b00000000))
    if typed:
        if (1 <= int(tx_length)):
            payload = stateless_input_sub_slice(tx, 1, (int(tx_length) - 1))
        else:
            payload = fatal_error(FatalError.RlpDecode)
    else:
        payload = tx
    payload_input = payload
    fields = rlp_node_cursor(payload_input)
    match ttype:
        case _sail_bits_pattern_0 if _sail_bits_pattern_0 == Bits(8, 0b00000000):
            tx_type = TxType.LegacyTx
        case _sail_bits_pattern_1 if _sail_bits_pattern_1 == Bits(8, 0b00000001):
            tx_type = TxType.AccessListTx
        case _sail_bits_pattern_2 if _sail_bits_pattern_2 == Bits(8, 0b00000010):
            tx_type = TxType.FeeMarketTx
        case _sail_bits_pattern_3 if _sail_bits_pattern_3 == Bits(8, 0b00000011):
            tx_type = TxType.BlobTx
        case _sail_bits_pattern_4 if _sail_bits_pattern_4 == Bits(8, 0b00000100):
            tx_type = TxType.SetCodeTx
        case _:
            tx_type = fatal_error(FatalError.RlpDecode)
    match tx_type:
        case TxType.LegacyTx:
            decoded = decode_legacy_tx(tx, pubkey, sender, fields)
            return pack_transaction(decoded)
        case TxType.AccessListTx:
            decoded = decode_access_list_tx(tx, pubkey, sender, fields)
            return pack_transaction(decoded)
        case TxType.FeeMarketTx:
            decoded = decode_fee_market_tx(tx, pubkey, sender, fields)
            return pack_transaction(decoded)
        case TxType.BlobTx:
            decoded = decode_blob_tx(tx, pubkey, blob_limit, sender, fields)
            return pack_transaction(decoded)
        case TxType.SetCodeTx:
            decoded = decode_set_code_tx(tx, pubkey, sender, fields)
            return pack_transaction(decoded)
        case _:
            raise SailMatchFailure("no Sail match clause applied")

EMPTY_ACCESS_LIST_DECODE: AccessListDecode = AccessListDecode(validity=AccessListDecodeValidity(address_bound=0, slot_bound=0), address_count=Uint(0), slot_count=Uint(0))

BLOB_HASH_RLP_LENGTH: Annotated[int, IntegerRange(33, 33)] = 33

BLOB_HASH_LENGTH: Annotated[int, IntegerRange(32, 32)] = WORD_BYTE_LENGTH
