# Generated by Sail's Python backend. Do not edit by hand.
# Sail source: lib/rlp/codecs/transaction_signing.sail
from __future__ import annotations

from ...._runtime import (
    Bits,
    Bytes32,
    IntegerRange,
)
from typing import Annotated
from evm.HostContract import (
    scratch_keccak256 as _host_scratch_keccak256,
)
from evm._sail.vector import neq_bits
from evm.prelude import (
    address,
    hash,
    word,
    word_sub_word,
    word_ule,
    word_div_word,
    ZERO_WORD,
)
from evm.primitives.quantities import account_nonce
from evm.primitives.bytes import (
    StatelessInputSlice,
    DOUBLE_WORD_BYTE_LENGTH,
)
from evm.exceptions import (
    FatalError,
    fatal_error,
)
from evm.kernel.scratch import (
    scratch_push_byte,
    stateless_input_scratch_push_slice,
)
from evm.primitives.tx import (
    TxType,
    tx_envelope_type,
)
from evm.lib.rlp.encoding import (
    rlp_length_prefix_len,
    rlp_uint_word_size,
    rlp_addr_size,
    rlp_list_size,
    rlp_write_list_prefix,
    rlp_write_uint_word,
    rlp_write_addr,
    rlp_encoder_begin,
    rlp_encoder_finish,
    rlp_encoder_rewind,
)

def legacy_sig_chain_id(v: word) -> word:
    adjusted_v = word_sub_word(v, 35)
    return word(word_div_word(adjusted_v, 2))

def tx_signing_hash(t: TxType, content_src: StatelessInputSlice, v: word) -> hash:
    tb = tx_envelope_type(t)
    eip155 = ((((tb) == (Bits(8, 0b00000000)))) & (word_ule(35, v)))
    if eip155:
        chain_id = legacy_sig_chain_id(v)
    else:
        chain_id = ZERO_WORD
    if eip155:
        chain_id_length = rlp_uint_word_size(chain_id)
        suffix_length = LEGACY_SIGNATURE_SUFFIX_LENGTH
        suffix_len = (int(chain_id_length) + int(suffix_length))
    else:
        suffix_len = 0
    if (int(content_src.len) <= int((1 << 30))):
        content_length = content_src.len
    else:
        content_length = fatal_error(FatalError.RlpDecode)
    suffix_length = suffix_len
    content_len = (int(content_length) + int(suffix_length))
    prefix_len = rlp_length_prefix_len(content_len)
    if ((tb) == (Bits(8, 0b00000000))):
        type_len = 0
    else:
        type_len = 1
    preimage_len = (int((int(type_len) + int(prefix_len))) + int(content_len))
    encoder = rlp_encoder_begin(preimage_len)
    if neq_bits(tb, Bits(8, 0b00000000)):
        scratch_push_byte(tb)
    rlp_write_list_prefix(content_len)
    stateless_input_scratch_push_slice(content_src)
    if eip155:
        rlp_write_uint_word(chain_id)
        scratch_push_byte(Bits(8, 0b10000000))
        scratch_push_byte(Bits(8, 0b10000000))
    preimage = rlp_encoder_finish(encoder)
    signing_hash = _host_scratch_keccak256(preimage)
    rlp_encoder_rewind(encoder)
    return Bytes32(signing_hash)

def auth_signing_hash(chain_id: word, addr: address, nonce: account_nonce) -> hash:
    chain_id_length = rlp_uint_word_size(chain_id)
    address_length = rlp_addr_size()
    nonce_length = rlp_uint_word_size(nonce)
    content_len = (int((int(chain_id_length) + int(address_length))) + int(nonce_length))
    preimage_len = (1 + int(rlp_list_size(content_len)))
    encoder = rlp_encoder_begin(preimage_len)
    scratch_push_byte(Bits(8, 0b00000101))
    rlp_write_list_prefix(content_len)
    rlp_write_uint_word(chain_id)
    rlp_write_addr(addr)
    rlp_write_uint_word(nonce)
    encoded = rlp_encoder_finish(encoder)
    signing_hash = _host_scratch_keccak256(encoded)
    rlp_encoder_rewind(encoder)
    return Bytes32(signing_hash)

LEGACY_SIGNATURE_SUFFIX_LENGTH: Annotated[int, IntegerRange(2, 2)] = 2

PUBLIC_KEY_BODY_LENGTH: Annotated[int, IntegerRange(64, 64)] = DOUBLE_WORD_BYTE_LENGTH
