# Generated by Sail's Python backend. Do not edit by hand.
# Sail source: primitives/crypto.sail
from __future__ import annotations

from .._runtime import (
    Bits,
    Bytes32,
    SailMatchFailure,
)
from evm.HostContract import (
    host_ecrecover as _host_host_ecrecover,
    memory_keccak256 as _host_memory_keccak256,
    memory_sha256 as _host_memory_sha256,
    stateless_input_keccak256 as _host_stateless_input_keccak256,
    stateless_input_sha256 as _host_stateless_input_sha256,
)
from evm.prelude import (
    AddressResult,
    hash,
    word,
    word_from_bits,
    hash_from_bits,
)
from evm.primitives.quantities import y_parity
from evm.primitives.bytes import (
    CalldataSlice,
    InputCalldata,
    MemoryCalldata,
)

def calldata_keccak256(input: CalldataSlice) -> hash:
    match input:
        case InputCalldata(bytes):
            return Bytes32(_host_stateless_input_keccak256(bytes))
        case MemoryCalldata(bytes):
            return Bytes32(_host_memory_keccak256(bytes))
        case _:
            raise SailMatchFailure("no Sail match clause applied")

def calldata_sha256(input: CalldataSlice) -> hash:
    match input:
        case InputCalldata(bytes):
            return Bytes32(_host_stateless_input_sha256(bytes))
        case MemoryCalldata(bytes):
            return Bytes32(_host_memory_sha256(bytes))
        case _:
            raise SailMatchFailure("no Sail match clause applied")

def ecrecover_addr(h: hash, yparity: y_parity, r: word, s: word) -> AddressResult:
    return _host_host_ecrecover(h, yparity, r, s)

KECCAK_EMPTY: hash = Bytes32(hash_from_bits(Bits(256, 0b1100010111010010010001100000000110000110111101110010001100111100100100100111111001111101101100101101110011000111000000111100000011100101000000001011011001010011110010101000001000100111001110110111101111111010110110000000010001011101100001011010010001110000)))

EMPTY_TRIE_ROOT: hash = Bytes32(hash_from_bits(Bits(256, 0b0101011011101000000111110001011100011011110011000101010110100110111111111000001101000101111001101001001011000000111110000110111001011011010010001110000000011011100110010110110010101101110000000000000101100010001011111011010111100011011000111011010000100001)))

SECP_N_FULL: int = word_from_bits(Bits(256, 0b1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111010111010101011101101110011100110101011110100100010100000001110111011111111010010010111101000110011010000001101100100000101000001))

SECP_N_HALF: int = word_from_bits(Bits(256, 0b0111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111101011101010101110110111001110011010101111010010001010000000111011101111111101001001011110100011001101000000110110010000010100000))
