# Generated by Sail's Python backend. Do not edit by hand.
# Sail source: _sail/generic_equality.sail
from __future__ import annotations

from typing import Any

def neq_anything(x: Any, y: Any) -> bool:
    return (not (((y) == (x))))
