# Generated by Sail's Python backend. Do not edit by hand.
# Sail source: lib/state_trie.sail
from __future__ import annotations

from .._runtime import (
    Bytes32,
    SailMatchFailure,
)
from evm.HostContract import (
    acct_block_iter_begin as _host_acct_block_iter_begin,
    acct_block_iter_next as _host_acct_block_iter_next,
    storage_block_iter_begin as _host_storage_block_iter_begin,
    storage_block_iter_next as _host_storage_block_iter_next,
)
from evm.prelude import (
    address,
    hash,
    word,
    word_is_zero,
    ZERO_WORD,
)
from evm.primitives.crypto import EMPTY_TRIE_ROOT
from evm.primitives.account import (
    Account,
    AcctBlockIterExhausted,
    AcctBlockIterRow,
    AcctTrieEntry,
    AcctValue,
    StorageBlockIterExhausted,
    StorageBlockIterRow,
    StorageTrieEntry,
    StorageValue,
    account_from_info,
    EMPTY_ACCOUNT,
)
from evm.lib.rlp.decoding import (
    rlp_single_ref,
    rlp_decode_u256,
)
from evm.lib.mpt.primitives import path_new
from evm.lib.mpt.updates import (
    ChangedAccountTrieUpdates,
    StorageTrieUpdates,
    TrieDelete,
    TriePut,
)
from evm.lib.rlp.codecs.state import (
    decode_state_account,
    encode_storage_value,
    encode_state_account,
)
from evm.kernel import environment
from evm.kernel import accounts
from evm.lib.mpt import updates as lib_mpt_updates
from evm.lib.mpt import trie

def stateless_account_by_key(root: hash, address_hash: hash) -> Account:
    path = path_new(address_hash, 64)
    value = trie.trie_lookup(root, path)
    if ((value.len) == (0)):
        return EMPTY_ACCOUNT
    else:
        account_info = decode_state_account(value)
        return account_from_info(account_info)

def stateless_storage_by_key(root: hash, slot_hash: hash) -> word:
    path = path_new(slot_hash, 64)
    value = trie.trie_lookup(root, path)
    if ((value.len) == (0)):
        return word(ZERO_WORD)
    else:
        encoded_value = rlp_single_ref(value)
        return word(rlp_decode_u256(encoded_value))

def storage_value_changed(value: StorageValue) -> bool:
    return (not (((value.curr) == (value.orig))))

def account_value_changed(value: AcctValue) -> bool:
    return (((not (((value.curr.info.nonce) == (value.orig.info.nonce))))) | ((((not (((value.curr.info.balance) == (value.orig.info.balance))))) | ((((not (((value.curr.info.storage_root) == (value.orig.info.storage_root))))) | ((((not (((value.curr.info.code_hash) == (value.orig.info.code_hash))))) | ((((not (((value.curr.present) == (value.orig.present))))) | ((not (((value.curr.storage_cleared) == (value.orig.storage_cleared))))))))))))))

def storage_update(trie_entry: StorageTrieEntry) -> lib_mpt_updates.TrieUpdate:
    entry = trie_entry.entry
    key = path_new(trie_entry.slot_hash, 64)
    value_is_zero = word_is_zero(entry.value.curr)
    if value_is_zero:
        change = TrieDelete(None)
    else:
        encoded_value = encode_storage_value(entry.value.curr)
        change = TriePut(encoded_value)
    return lib_mpt_updates.TrieUpdate(key=key, change=change)

def account_update(trie_entry: AcctTrieEntry, storage_root: hash) -> lib_mpt_updates.TrieUpdate:
    entry = trie_entry.entry
    current = entry.value.curr
    key = path_new(trie_entry.address_hash, 64)
    account_absent = (not (current.present))
    account_empty = accounts.account_info_empty(current.info)
    if ((account_absent) | (account_empty)):
        return lib_mpt_updates.TrieUpdate(key=key, change=TrieDelete(None))
    else:
        encoded_account = encode_state_account(current.info, storage_root)
        return lib_mpt_updates.TrieUpdate(key=key, change=TriePut(encoded_account))

def next_storage_trie_update(addr: address) -> lib_mpt_updates.TrieUpdateFetch:
    searching = True
    result = lib_mpt_updates.TrieUpdateFetch(available=False, update=lib_mpt_updates.EMPTY_TRIE_UPDATE)
    while True:
        if not (searching):
            break
        iterator_item = _host_storage_block_iter_next(addr)
        match iterator_item:
            case StorageBlockIterRow(trie_entry):
                changed = storage_value_changed(trie_entry.entry.value)
                if changed:
                    result = lib_mpt_updates.TrieUpdateFetch(available=True, update=storage_update(trie_entry))
                    searching = False
            case StorageBlockIterExhausted(_):
                searching = False
            case _:
                raise SailMatchFailure("no Sail match clause applied")
    return result

def account_trie_update(trie_entry: AcctTrieEntry) -> tuple[lib_mpt_updates.TrieUpdate, bool]:
    entry = trie_entry.entry
    current = entry.value.curr
    _host_storage_block_iter_begin(entry.addr)
    storage_source = StorageTrieUpdates(entry.addr)
    storage_updates = lib_mpt_updates.trie_updates_begin(storage_source)
    no_storage_changes = lib_mpt_updates.updates_empty(storage_updates)
    storage_changed = (not (no_storage_changes))
    if current.storage_cleared:
        base_storage_root = EMPTY_TRIE_ROOT
    else:
        base_storage_root = current.info.storage_root
    account_empty = accounts.account_info_empty(current.info)
    account_nonempty = (not (account_empty))
    if ((current.present) & (((account_nonempty) & (storage_changed)))):
        storage_root = trie.trie_root_cursor(base_storage_root, storage_updates).root
    else:
        storage_root = base_storage_root
    update = account_update(trie_entry, storage_root)
    persisted_account_changed = account_value_changed(entry.value)
    return (update, ((persisted_account_changed) | (storage_changed)))

def next_changed_account_trie_update() -> lib_mpt_updates.TrieUpdateFetch:
    searching = True
    result = lib_mpt_updates.TrieUpdateFetch(available=False, update=lib_mpt_updates.EMPTY_TRIE_UPDATE)
    while True:
        if not (searching):
            break
        iterator_item = _host_acct_block_iter_next()
        match iterator_item:
            case AcctBlockIterRow(entry):
                (update, changed) = account_trie_update(entry)
                if changed:
                    result = lib_mpt_updates.TrieUpdateFetch(available=True, update=update)
                    searching = False
            case AcctBlockIterExhausted(_):
                searching = False
            case _:
                raise SailMatchFailure("no Sail match clause applied")
    return result

def trie_update_source_next(source: lib_mpt_updates.TrieUpdateSource) -> lib_mpt_updates.TrieUpdateFetch:
    match source:
        case StorageTrieUpdates(addr):
            return next_storage_trie_update(addr)
        case ChangedAccountTrieUpdates(None):
            return next_changed_account_trie_update()
        case _:
            raise SailMatchFailure("no Sail match clause applied")

def compute_state_root() -> hash:
    _host_acct_block_iter_begin()
    updates = ChangedAccountTrieUpdates(None)
    return Bytes32(trie.trie_root(environment.k_parent_state_root, updates).root)
