# Generated by Sail's Python backend. Do not edit by hand.
# Sail source: lib/address.sail
from __future__ import annotations

from .._runtime import (
    Bits,
    Bytes20,
)
from evm.HostContract import (
    scratch_keccak256 as _host_scratch_keccak256,
)
from evm.prelude import (
    address,
    hash,
    word,
    hash_to_word,
    word_to_hash,
    word_to_address,
)
from evm.primitives.bytes import WORD_BYTE_LENGTH
from evm.kernel.scratch import (
    scratch_reserve,
    scratch_push_byte,
    scratch_push_address,
    scratch_push_b256,
    scratch_finish,
    scratch_rewind,
)

def create2_address(sender: address, salt: word, init_hash: hash) -> address:
    mark = scratch_reserve(85)
    scratch_push_byte(Bits(8, 0b11111111))
    scratch_push_address(sender)
    scratch_push_b256(word_to_hash(salt), WORD_BYTE_LENGTH)
    scratch_push_b256(init_hash, WORD_BYTE_LENGTH)
    digest = _host_scratch_keccak256(scratch_finish(mark))
    scratch_rewind(mark)
    return Bytes20(word_to_address(hash_to_word(digest)))
