# Generated by Sail's Python backend. Do not edit by hand.
# Sail source: lib/state_trie.sail
from __future__ import annotations

from .._runtime import (
    Bytes32,
    SailMatchFailure,
)
from evm.HostContract import (
    acct_block_iter_begin as _host_acct_block_iter_begin,
    acct_block_iter_next as _host_acct_block_iter_next,
    storage_block_iter_begin as _host_storage_block_iter_begin,
    storage_block_iter_next as _host_storage_block_iter_next,
)
from evm.prelude import (
    address,
    hash,
    word,
    word_is_zero,
    ZERO_WORD,
)
from evm.primitives.crypto import EMPTY_TRIE_ROOT
from evm.primitives.account import (
    AccountInfo,
    AcctTrieEntry,
    AcctValue,
    StorageTrieEntry,
    StorageValue,
)
from evm.lib.rlp.decoding import (
    rlp_single_ref,
    rlp_decode_u256,
)
from evm.lib.mpt.primitives import path_new
from evm.lib.mpt.updates import (
    ChangedAccountTrieUpdates,
    StorageTrieUpdates,
    TrieDelete,
    TriePut,
)
from evm.lib.rlp.codecs.state import (
    decode_state_account,
    encode_storage_value,
    encode_state_account,
)
from evm.kernel import environment
from evm.kernel import accounts
from evm.lib.mpt import updates
from evm.lib.mpt import trie

def stateless_account_by_key(root: hash, address_hash: hash) -> AccountInfo | None:
    value = trie.trie_lookup(root, path_new(address_hash, 64))
    if ((value.len) == (0)):
        return None
    else:
        return decode_state_account(value)

def stateless_storage_by_key(root: hash, slot_hash: hash) -> word:
    value = trie.trie_lookup(root, path_new(slot_hash, 64))
    if ((value.len) == (0)):
        return word(ZERO_WORD)
    else:
        return word(rlp_decode_u256(rlp_single_ref(value)))

def storage_value_changed(value: StorageValue) -> bool:
    return (not (((value.curr) == (value.orig))))

def account_value_changed(value: AcctValue) -> bool:
    return (((not (((value.curr.info.nonce) == (value.orig.info.nonce))))) | ((((not (((value.curr.info.balance) == (value.orig.info.balance))))) | ((((not (((value.curr.info.storage_root) == (value.orig.info.storage_root))))) | ((((not (((value.curr.info.code_hash) == (value.orig.info.code_hash))))) | ((((not (((value.curr.present) == (value.orig.present))))) | ((not (((value.curr.storage_cleared) == (value.orig.storage_cleared))))))))))))))

def storage_update(trie_entry: StorageTrieEntry) -> updates.TrieUpdate:
    entry = trie_entry.entry
    key = path_new(trie_entry.slot_hash, 64)
    if word_is_zero(entry.value.curr):
        change = TrieDelete(None)
    else:
        change = TriePut(encode_storage_value(entry.value.curr))
    return updates.TrieUpdate(key=key, change=change)

def account_update(trie_entry: AcctTrieEntry, storage_root: hash) -> updates.TrieUpdate:
    entry = trie_entry.entry
    current = entry.value.curr
    key = path_new(trie_entry.address_hash, 64)
    if (((not (current.present))) | (accounts.account_info_empty(current.info))):
        return updates.TrieUpdate(key=key, change=TrieDelete(None))
    else:
        return updates.TrieUpdate(key=key, change=TriePut(encode_state_account(current.info, storage_root)))

def next_changed_storage_entry(addr: address) -> StorageTrieEntry | None:
    searching = True
    result = None
    while True:
        if not (searching):
            break
        match _host_storage_block_iter_next(addr):
            case (trie_entry as _sail_some_value_0) if _sail_some_value_0 is not None:
                if storage_value_changed(trie_entry.entry.value):
                    result = trie_entry
                    searching = False
            case None:
                searching = False
            case _:
                raise SailMatchFailure("no Sail match clause applied")
    return result

def next_storage_trie_update(addr: address) -> updates.TrieUpdate | None:
    match next_changed_storage_entry(addr):
        case (entry as _sail_some_value_1) if _sail_some_value_1 is not None:
            return storage_update(entry)
        case None:
            return None
        case _:
            raise SailMatchFailure("no Sail match clause applied")

def account_trie_update(trie_entry: AcctTrieEntry) -> tuple[updates.TrieUpdate, bool]:
    entry = trie_entry.entry
    current = entry.value.curr
    _host_storage_block_iter_begin(entry.addr)
    storage_updates = updates.trie_updates_begin(StorageTrieUpdates(entry.addr))
    storage_changed = (not (updates.updates_empty(storage_updates)))
    if current.storage_cleared:
        base_storage_root = EMPTY_TRIE_ROOT
    else:
        base_storage_root = current.info.storage_root
    if (((not (current.present))) | (accounts.account_info_empty(current.info))):
        storage_root = base_storage_root
    else:
        if storage_changed:
            storage_root = trie.trie_root_cursor(base_storage_root, storage_updates).root
        else:
            storage_root = base_storage_root
    return (account_update(trie_entry, storage_root), ((account_value_changed(entry.value)) | (storage_changed)))

def next_changed_account_trie_update() -> updates.TrieUpdate | None:
    searching = True
    result = None
    while True:
        if not (searching):
            break
        match _host_acct_block_iter_next():
            case (entry as _sail_some_value_2) if _sail_some_value_2 is not None:
                (update, changed) = account_trie_update(entry)
                if changed:
                    result = update
                    searching = False
            case None:
                searching = False
            case _:
                raise SailMatchFailure("no Sail match clause applied")
    return result

def trie_update_source_next(source: updates.TrieUpdateSource) -> updates.TrieUpdate | None:
    match source:
        case StorageTrieUpdates(addr):
            return next_storage_trie_update(addr)
        case ChangedAccountTrieUpdates(None):
            return next_changed_account_trie_update()
        case _:
            raise SailMatchFailure("no Sail match clause applied")

def compute_state_root() -> hash:
    _host_acct_block_iter_begin()
    return Bytes32(trie.trie_root(environment.k_parent_state_root, ChangedAccountTrieUpdates(None)).root)
