/* zkVM binding of the SSZ byte-source (sail/lib/ssz/ssz.sail)
 * to the private input (read_input's buffer). Pulls in keccak too so a single
 * `sail -c --c-include zkvm_input.h` covers all guest externs. */
#ifndef EL_INPUT_H
#define EL_INPUT_H
#include "sail.h"
#include "byte_slice_glue.h"          /* generated ByteSlice extern boundary */
#include "host_crypto.h"              /* direct host hash helpers */
#include "precompiles.h"              /* staged precompile input/execution */
#include "output.h"                   /* frame/precompile output arena */
#include "scratch.h"                  /* executor scratch byte arena */
#include "memory.h"
#include "transient_storage.h"
#include "stack.h"
#include "code_db.h"
#include "kernel_state.h"
#include "trie_node_db.h"
#include "state_db.h"
uint64_t ssz_src_len(const unit u);                  /* unit -> bits(64) (byte count) */
uint64_t ssz_src_byte(uint64_t idx);                 /* u64 -> bits(8) */
uint64_t ssz_src_le(sail_int off, sail_int n);       /* (int,int) -> bits(64): n<=8 LE */
uint64_t ssz_src_be(sail_int off, sail_int n);       /* (int,int) -> bits(64): n<=8 BE */
const uint8_t *evmsail_stateless_input_ptr(uint64_t off, uint64_t len);
unit     el_emit_out(uint64_t b);                    /* bits(8) -> unit: write_output one byte */
unit evmsail_cycle_scope_start(uint64_t scope);
unit evmsail_cycle_scope_end(uint64_t scope);
/* journal boundary (ffi/journal_glue.c): whole JEntry values cross as the
 * generated struct zJEntry -- declared incomplete here (this header precedes
 * the generated type definitions in the model translation unit). */
struct zJEntry;
unit journal_push(struct zJEntry e);                 /* JEntry -> unit */
void journal_pop(struct zJEntry *rop, unit u);       /* unit -> JEntry */
struct zoptionzIRStorageValuezK;                     /* option(StorageValue) per-layer views */
struct zStorageKey;
struct zStorageEntry;
void storage_tx_get(struct zoptionzIRStorageValuezK *rop, struct zStorageKey key);
void storage_block_get(struct zoptionzIRStorageValuezK *rop, struct zStorageKey key);
unit storage_tx_update(struct zStorageEntry entry);
unit storage_block_put(struct zStorageEntry entry);
unit storage_block_cache(struct zStorageKey key, const lbits value);
struct zoptionzIRAccountzK;                          /* transaction Account view */
struct zAccount;
struct zAcctEntry;
void acct_tx_get(struct zoptionzIRAccountzK *rop, const lbits a);
void acct_block_get(struct zoptionzIRAccountzK *rop, const lbits a);
unit acct_tx_update(const lbits a, struct zAccount account);
unit acct_block_write(struct zAcctEntry entry);
unit acct_block_cache(const lbits a, struct zAccount account);
struct zoptionzIRStorageEntryzK;                     /* k_tx_merge drain pops */
struct zoptionzIRAcctEntryzK;
void storage_tx_pop(struct zoptionzIRStorageEntryzK *rop, unit u);
void acct_tx_pop(struct zoptionzIRAcctEntryzK *rop, unit u);
#endif
