# Generated by Sail's Python backend. Do not edit by hand.
# Sail source: lib/mpt/nodes.sail
from __future__ import annotations

from ..._runtime import (
    BoundedUint,
    Bytes32,
    IntegerRange,
    Unsigned,
    VectorLength,
)
from dataclasses import dataclass
from typing import Annotated, TypeAlias
from evm.HostContract import (
    scratch_keccak256 as _host_scratch_keccak256,
)
from evm.prelude import (
    b256,
    hash,
    word_to_hash,
)
from evm.primitives.bytes import (
    ScratchSlice,
    StatelessInputSlice,
    StatelessInputSliceAtMost,
    WORD_BYTE_LENGTH,
)
from evm.exceptions import (
    FatalError,
    fatal_error,
)
from evm.host.region_access import (
    stateless_input_slice_load,
    scratch_slice_load,
)
from evm.kernel.scratch import (
    scratch_begin,
    scratch_reserve,
    scratch_push_b256,
    scratch_finish,
    scratch_rewind,
)

@dataclass(slots=True)
class InlineNode:
    data: b256
    len: BoundedUint[0, 31]

class TrieLeafValue:
    pass

@dataclass(frozen=True, slots=True)
class InputTrieLeaf(TrieLeafValue):
    value: StatelessInputSlice

@dataclass(frozen=True, slots=True)
class ScratchTrieLeaf(TrieLeafValue):
    value: ScratchSlice

def inline_node_from_scratch_slice(bytes: ScratchSlice) -> InlineNode:
    length = bytes.len
    if (int(length) < int(MPT_HASH_LENGTH)):
        encoded = scratch_slice_load(bytes, 0)
        return InlineNode(data=b256(word_to_hash(encoded)), len=BoundedUint[0, 31](length))
    else:
        return fatal_error(FatalError.WitnessDeficient)

def inline_node_from_input_slice(bytes: StatelessInputSlice) -> InlineNode:
    length = bytes.len
    if (int(length) < int(MPT_HASH_LENGTH)):
        encoded = stateless_input_slice_load(bytes, 0)
        return InlineNode(data=b256(word_to_hash(encoded)), len=BoundedUint[0, 31](length))
    else:
        return fatal_error(FatalError.WitnessDeficient)

def inline_node_slice(node: InlineNode) -> ScratchSlice:
    start = scratch_reserve(node.len)
    scratch_push_b256(node.data, node.len)
    return scratch_finish(start)

def inline_node_hash(node: InlineNode) -> hash:
    mark = scratch_begin()
    encoded = inline_node_slice(node)
    digest = _host_scratch_keccak256(encoded)
    scratch_rewind(mark)
    return Bytes32(digest)

class NodeRef:
    pass

@dataclass(frozen=True, slots=True)
class EmptyRef(NodeRef):
    value: None = None

@dataclass(frozen=True, slots=True)
class InputInlineRef(NodeRef):
    value: StatelessInputSliceAtMost

@dataclass(frozen=True, slots=True)
class ScratchInlineRef(NodeRef):
    value: InlineNode

@dataclass(frozen=True, slots=True)
class HashRef(NodeRef):
    value: hash

BranchRefs: TypeAlias = Annotated[list[NodeRef], VectorLength(16)]

class branch_content_length(Unsigned):
    LOWER = 0
    UPPER = 529

    def _in_range(self, value: int) -> bool:
        return self.LOWER <= value <= self.UPPER

def branch_content_length_add(current: branch_content_length, addition: BoundedUint[0, 33]) -> branch_content_length:
    if (int(addition) <= int((529 - int(current)))):
        return branch_content_length((int(current) + int(addition)))
    else:
        return branch_content_length(fatal_error(FatalError.RlpDecode))

MPT_HASH_LENGTH: Annotated[int, IntegerRange(32, 32)] = WORD_BYTE_LENGTH
