# Generated by Sail's Python backend. Do not edit by hand.
# Sail source: lib/mpt/updates.sail
from __future__ import annotations

from ..._runtime import (
    BitWidth,
    Bits,
    BoundedUint,
    Bytes32,
    SailMatchFailure,
    sail_vector_init,
    sail_vector_update,
)
from copy import deepcopy
from dataclasses import dataclass, replace
from typing import Annotated
from pydantic import ConfigDict, model_validator
from pydantic.dataclasses import dataclass as pydantic_dataclass
from typing_extensions import Self
from evm.prelude import (
    address,
    hash,
)
from evm.primitives.bytes import (
    ScratchSlice,
    StatelessInputSlice,
)
from evm.exceptions import (
    FatalError,
    fatal_error,
)
from evm.primitives.crypto import EMPTY_TRIE_ROOT
from evm.lib.mpt.primitives import (
    TriePath,
    trie_path_cursor,
    trie_path_len,
    path_len,
    path_empty,
    path_single,
    path_concat,
    path_drop,
    path_prefix_of,
    common_prefix_length,
)
from evm.lib.mpt.nodes import (
    BranchRefs,
    EmptyRef,
    HashRef,
    InputTrieLeaf,
    NodeRef,
    ScratchTrieLeaf,
    TrieLeafValue,
)
from evm.lib.mpt.codec import (
    branch_mask,
    branch_mask_has,
    branch_mask_set,
    leaf_child_ref,
    branch_child_ref,
    trie_ref_to_root,
    node_db_lookup,
    merge_ext_node,
    merge_ext_ref,
)

class TrieChange:
    pass

@dataclass(frozen=True, slots=True)
class TriePut(TrieChange):
    value: ScratchSlice

@dataclass(frozen=True, slots=True)
class TrieDelete(TrieChange):
    value: None = None

@dataclass(slots=True)
class TrieUpdate:
    key: TriePath
    change: TrieChange

class TrieUpdateSource:
    pass

@dataclass(frozen=True, slots=True)
class StorageTrieUpdates(TrieUpdateSource):
    value: address

@dataclass(frozen=True, slots=True)
class ChangedAccountTrieUpdates(TrieUpdateSource):
    value: None = None

@dataclass(slots=True)
class TrieUpdateFetch:
    available: bool
    update: TrieUpdate

class TrieUpdateRelation:
    pass

@dataclass(frozen=True, slots=True)
class UpdateUnderPrefix(TrieUpdateRelation):
    value: TriePath

@dataclass(frozen=True, slots=True)
class UpdateBeyondPrefix(TrieUpdateRelation):
    value: trie_path_len

@dataclass(frozen=True, slots=True)
class UpdateSourceExhausted(TrieUpdateRelation):
    value: None = None

@dataclass(slots=True)
class TrieUpdateCursor:
    source: TrieUpdateSource
    current: TrieUpdate
    relation: TrieUpdateRelation

def trie_updates_begin(source: TrieUpdateSource) -> TrieUpdateCursor:
    from evm.lib import state_trie

    first = state_trie.trie_update_source_next(source)
    if first.available:
        relation = UpdateUnderPrefix(first.update.key)
    else:
        relation = UpdateSourceExhausted(None)
    return TrieUpdateCursor(source=source, current=first.update, relation=relation)

def updates_empty(updates: TrieUpdateCursor) -> bool:
    match updates.relation:
        case UpdateSourceExhausted(_):
            return True
        case _:
            return False

def trie_updates_pop(updates: TrieUpdateCursor) -> tuple[TrieUpdate, TrieUpdateCursor]:
    from evm.lib import state_trie

    match updates.relation:
        case UpdateSourceExhausted(_):
            return fatal_error(FatalError.WitnessDeficient)
        case _:
            current = updates.current
            successor = state_trie.trie_update_source_next(updates.source)
            if successor.available:
                common_prefix_len = common_prefix_length(current.key, successor.update.key)
                next = TrieUpdateCursor(source=updates.source, current=successor.update, relation=UpdateBeyondPrefix(common_prefix_len))
            else:
                next = TrieUpdateCursor(source=updates.source, current=EMPTY_TRIE_UPDATE, relation=UpdateSourceExhausted(None))
            return (current, next)

def trie_updates_rebase(updates: TrieUpdateCursor, prefix: TriePath) -> TrieUpdateCursor:
    prefix_len = path_len(prefix)
    match updates.relation:
        case UpdateSourceExhausted(_):
            return updates
        case UpdateUnderPrefix(_):
            return updates
        case UpdateBeyondPrefix(common_prefix_len):
            if (int(prefix_len) <= int(common_prefix_len)):
                path_postfix = path_drop(updates.current.key, prefix_len)
                return TrieUpdateCursor(source=updates.source, current=updates.current, relation=UpdateUnderPrefix(path_postfix))
            else:
                return updates
        case _:
            raise SailMatchFailure("no Sail match clause applied")

def trie_updates_descend(updates: TrieUpdateCursor) -> TrieUpdateCursor:
    match updates.relation:
        case UpdateUnderPrefix(path_postfix):
            postfix_len = path_len(path_postfix)
            if ((postfix_len) == (0)):
                return fatal_error(FatalError.WitnessDeficient)
            else:
                child_postfix = path_drop(path_postfix, 1)
                descended = updates
                descended.relation = UpdateUnderPrefix(child_postfix)
                return descended
        case UpdateBeyondPrefix(_):
            return fatal_error(FatalError.WitnessDeficient)
        case UpdateSourceExhausted(_):
            return fatal_error(FatalError.WitnessDeficient)
        case _:
            raise SailMatchFailure("no Sail match clause applied")

class TrieItemValue:
    pass

@dataclass(frozen=True, slots=True)
class EmptySubtree(TrieItemValue):
    value: None = None

@dataclass(frozen=True, slots=True)
class LeafItem(TrieItemValue):
    value: TrieLeafValue

@dataclass(frozen=True, slots=True)
class BranchItem(TrieItemValue):
    value: NodeRef

@dataclass(frozen=True, slots=True)
class SubtreeItem(TrieItemValue):
    value: NodeRef

@dataclass(slots=True)
class TrieItem:
    path: TriePath
    value: TrieItemValue

def trie_empty_subtree() -> TrieItem:
    return TrieItem(path=path_empty(), value=EmptySubtree(None))

def trie_leaf(path: TriePath, value: TrieLeafValue) -> TrieItem:
    return TrieItem(path=path, value=LeafItem(value))

def trie_input_leaf(path: TriePath, value: StatelessInputSlice) -> TrieItem:
    leaf_value = InputTrieLeaf(value)
    return trie_leaf(path, leaf_value)

def trie_scratch_leaf(path: TriePath, value: ScratchSlice) -> TrieItem:
    leaf_value = ScratchTrieLeaf(value)
    return trie_leaf(path, leaf_value)

def trie_branch(path: TriePath, childref: NodeRef) -> TrieItem:
    return TrieItem(path=path, value=BranchItem(childref))

def trie_subtree(path: TriePath, childref: NodeRef) -> TrieItem:
    return TrieItem(path=path, value=SubtreeItem(childref))

def trie_child_ref(it: TrieItem, depth: trie_path_cursor) -> NodeRef:
    suffix = path_drop(it.path, depth)
    suffix_len = path_len(suffix)
    match it.value:
        case EmptySubtree(None):
            return EmptyRef(None)
        case LeafItem(value):
            return leaf_child_ref(suffix, value)
        case BranchItem(subref):
            if ((suffix_len) == (0)):
                return subref
            else:
                return merge_ext_ref(suffix, subref)
        case SubtreeItem(subref):
            if ((suffix_len) == (0)):
                return subref
            else:
                match subref:
                    case HashRef(h):
                        node = node_db_lookup(h)
                        if ((node.len) == (0)):
                            return fatal_error(FatalError.WitnessDeficient)
                        else:
                            return merge_ext_node(suffix, node)
                    case _:
                        return merge_ext_ref(suffix, subref)
        case _:
            raise SailMatchFailure("no Sail match clause applied")

@pydantic_dataclass(config=ConfigDict(strict=True, validate_assignment=True, revalidate_instances="always", arbitrary_types_allowed=True), slots=True, kw_only=True)
class TrieChildren:
    mask: branch_mask
    children: BranchRefs
    only: TrieItem
    count: BoundedUint[0, 16]

    @model_validator(mode="after")
    def validate(self) -> Self:
        if not ((len(self.children) == 16)):
            raise ValueError("TrieChildren.children violates Sail type vector(16, NodeRef)")
        return self

def trie_children_empty() -> TrieChildren:
    empty_ref = EmptyRef(None)
    children = sail_vector_init(16, empty_ref)
    empty_subtree = trie_empty_subtree()
    return TrieChildren(mask=Bits(16, 0b0000000000000000), children=children, only=empty_subtree, count=BoundedUint[0, 16](0))

def trie_children_add(children: TrieChildren, prefix: TriePath, index: Annotated[Bits, BitWidth(4)], child: TrieItem) -> TrieChildren:
    match child.value:
        case EmptySubtree(None):
            return children
        case _:
            depth = path_len(prefix)
            child_count = children.count
            if (int(depth) < 64):
                child_depth = (int(depth) + 1)
            else:
                child_depth = fatal_error(FatalError.WitnessDeficient)
            if (int(child_count) < 16):
                next_child_count = (int(child_count) + 1)
            else:
                next_child_count = fatal_error(FatalError.WitnessDeficient)
            child_segment = path_single(index)
            child_prefix = path_concat(prefix, child_segment)
            path_below_child = path_prefix_of(child_prefix, child.path)
            path_outside_child = (not (path_below_child))
            if path_outside_child:
                fatal_error(FatalError.WitnessDeficient)
            child_already_present = branch_mask_has(children.mask, index)
            if child_already_present:
                fatal_error(FatalError.WitnessDeficient)
            updated = children
            updated.mask = branch_mask_set(updated.mask, index)
            updated = replace(deepcopy(updated), children=sail_vector_update(updated.children, int(index), trie_child_ref(child, child_depth), False))
            updated.only = child
            updated.count = BoundedUint[0, 16](next_child_count)
            return updated

def trie_children_finish(prefix: TriePath, children: TrieChildren) -> TrieItem:
    if ((children.count) == (0)):
        return TrieItem(path=prefix, value=EmptySubtree(None))
    else:
        if ((children.count) == (1)):
            return children.only
        else:
            branch_ref = branch_child_ref(children.mask, children.children)
            return trie_branch(prefix, branch_ref)

def trie_subtree_root(subtree: TrieItem) -> hash:
    match subtree.value:
        case EmptySubtree(None):
            return Bytes32(EMPTY_TRIE_ROOT)
        case _:
            root_ref = trie_child_ref(subtree, 0)
            return Bytes32(trie_ref_to_root(root_ref))

EMPTY_TRIE_UPDATE: TrieUpdate = TrieUpdate(key=path_empty(), change=TrieDelete(None))
