# Generated by Sail's Python backend. Do not edit by hand.
# Sail source: kernel/accounts.sail
from __future__ import annotations

from .._runtime import (
    SailReturn,
)
from copy import deepcopy
from dataclasses import replace
from evm.HostContract import (
    acct_block_cache as _host_acct_block_cache,
    acct_block_get as _host_acct_block_get,
    acct_tx_get as _host_acct_tx_get,
    acct_tx_set_balance as _host_acct_tx_set_balance,
    acct_tx_set_code_hash as _host_acct_tx_set_code_hash,
    acct_tx_set_nonce as _host_acct_tx_set_nonce,
    acct_tx_update as _host_acct_tx_update,
    bal_account_touch as _host_bal_account_touch,
    keccak256_address as _host_keccak256_address,
    storage_has_writes as _host_storage_has_writes,
    storage_tx_clear as _host_storage_tx_clear,
)
from evm._sail.flow import neq_bool
from evm.prelude import (
    address,
    hash,
    word,
    word_is_zero,
    alu_add,
    alu_sub,
)
from evm.primitives.quantities import account_nonce
from evm.exceptions import (
    FatalError,
    fatal_error,
)
from evm.primitives.crypto import (
    KECCAK_EMPTY,
    EMPTY_TRIE_ROOT,
)
from evm.primitives.account import (
    Account,
    AccountInfo,
    EMPTY_ACCOUNT_INFO,
)
from evm.kernel.logs import k_emit_transfer_log
from evm.kernel import environment
from evm.lib import state_trie

def account_info_changed(c: AccountInfo, o: AccountInfo) -> bool:
    return ((((c.nonce) != (o.nonce))) | (((((c.balance) != (o.balance))) | (((((c.code_hash) != (o.code_hash))) | (((c.storage_root) != (o.storage_root))))))))

def account_info_empty(info: AccountInfo) -> bool:
    return ((((info.code_hash) == (KECCAK_EMPTY))) & (((((info.nonce) == (0))) & (word_is_zero(info.balance)))))

def account_changed(c: Account, o: Account) -> bool:
    return ((account_info_changed(c.info, o.info)) | (((neq_bool(c.present, o.present)) | (neq_bool(c.storage_cleared, o.storage_cleared)))))

def account_set_info(acc: Account, info: AccountInfo) -> Account:
    empty = account_info_empty(info)
    if empty:
        return replace(deepcopy(acc), info=replace(deepcopy(EMPTY_ACCOUNT_INFO), storage_root=hash(acc.info.storage_root)), present=False, storage_cleared=True)
    else:
        return replace(deepcopy(acc), info=info, present=True)

def account_clear_storage(acc: Account) -> Account:
    return replace(deepcopy(acc), storage_cleared=True)

def account_delete(acc: Account) -> Account:
    return replace(deepcopy(acc), info=replace(deepcopy(EMPTY_ACCOUNT_INFO), storage_root=hash(acc.info.storage_root)), present=False, storage_cleared=True)

def account_clear_preserving_balance(acc: Account) -> Account:
    cleared_storage = account_clear_storage(acc)
    return account_set_info(cleared_storage, replace(deepcopy(acc.info), nonce=account_nonce(0), code_hash=hash(KECCAK_EMPTY)))

def store_account(a: address, v: Account) -> None:
    return _host_acct_tx_update(a, v)

def store_account_info(a: address, acc: Account, info: AccountInfo) -> None:
    empty = account_info_empty(info)
    if empty:
        _host_storage_tx_clear(a)
    next = account_set_info(acc, info)
    if ((((next.info.storage_root) != (acc.info.storage_root))) | (((neq_bool(next.present, acc.present)) | (neq_bool(next.storage_cleared, acc.storage_cleared))))):
        return store_account(a, next)
    else:
        if ((next.info.balance) != (acc.info.balance)):
            _host_acct_tx_set_balance(a, next.info.balance)
        if ((next.info.nonce) != (acc.info.nonce)):
            _host_acct_tx_set_nonce(a, next.info.nonce)
        if ((next.info.code_hash) != (acc.info.code_hash)):
            return _host_acct_tx_set_code_hash(a, next.info.code_hash)
        else:
            return None

def k_aload(a: address) -> Account:
    try:
        tx_account = _host_acct_tx_get(a)
        if tx_account.found:
            raise SailReturn(tx_account.account)
        _host_bal_account_touch(a)
        block_account = _host_acct_block_get(a)
        if block_account.found:
            raise SailReturn(block_account.account)
        address_hash = _host_keccak256_address(a)
        account = state_trie.stateless_account_by_key(environment.k_parent_state_root, address_hash)
        _host_acct_block_cache(a, address_hash, account)
        return account
    except SailReturn as _sail_return:
        return _sail_return.value

def k_get_balance(a: address) -> word:
    return word(k_aload(a).info.balance)

def k_get_nonce(a: address) -> account_nonce:
    return account_nonce(k_aload(a).info.nonce)

def k_account_exists(a: address) -> bool:
    return k_aload(a).present

def k_account_is_empty(a: address) -> bool:
    account = k_aload(a)
    return account_info_empty(account.info)

def k_account_occupied(a: address) -> bool:
    acc = k_aload(a)
    info = acc.info
    anchored_storage = (((not (acc.storage_cleared))) & (((info.storage_root) != (EMPTY_TRIE_ROOT))))
    if ((((info.code_hash) != (KECCAK_EMPTY))) | (((((info.nonce) != (0))) | (anchored_storage)))):
        return True
    else:
        return _host_storage_has_writes(a)

def k_transfer(src: address, dst: address, v: word) -> None:
    try:
        src_acc = k_aload(src)
        dst_acc = k_aload(dst)
        value_is_zero = word_is_zero(v)
        if ((value_is_zero) | (((src) == (dst)))):
            raise SailReturn(None)
        source_balance = alu_sub(src_acc.info.balance, v)
        store_account_info(src, src_acc, replace(deepcopy(src_acc.info), balance=word(source_balance)))
        destination_balance = alu_add(dst_acc.info.balance, v)
        store_account_info(dst, dst_acc, replace(deepcopy(dst_acc.info), balance=word(destination_balance)))
        return k_emit_transfer_log(src, dst, v)
    except SailReturn as _sail_return:
        return _sail_return.value

def k_bump_nonce(a: address) -> None:
    cur = k_aload(a)
    nonce = cur.info.nonce
    if (int(nonce) < int((int((1 << 64)) - 1))):
        return store_account_info(a, cur, replace(deepcopy(cur.info), nonce=account_nonce((int(nonce) + 1))))
    else:
        return fatal_error(FatalError.ExecutionInvalid)

def k_add_balance(a: address, v: int) -> None:
    cur = k_aload(a)
    value_is_zero = word_is_zero(v)
    value_is_nonzero = (not (value_is_zero))
    if value_is_nonzero:
        balance = alu_add(cur.info.balance, v)
        return store_account_info(a, cur, replace(deepcopy(cur.info), balance=word(balance)))
    else:
        return None

def k_sub_balance(a: address, v: word) -> None:
    cur = k_aload(a)
    value_is_zero = word_is_zero(v)
    value_is_nonzero = (not (value_is_zero))
    if value_is_nonzero:
        balance = alu_sub(cur.info.balance, v)
        return store_account_info(a, cur, replace(deepcopy(cur.info), balance=word(balance)))
    else:
        return None

def k_clear_storage(a: address) -> None:
    cur = k_aload(a)
    _host_storage_tx_clear(a)
    cleared = account_clear_storage(cur)
    return store_account(a, cleared)
