(*Generated by Sail from io_contracts.*)


From stdpp Require Import base countable pretty.
Require Import SailStdpp.Base.
Require Import SailStdpp.Real.

Import ListNotations.
Open Scope string.
Open Scope bool.
Open Scope Z.

Definition bit : Type := mword 1.

Definition bits (n : Z) : Type := mword n.

Definition byte : Type := bits 8.

Inductive word :=
| U256 : bits 256 -> word.
Arguments word : clear implicits.

Definition sail_word_encode (x : word) := match x with U256 x' => encode (0, encode x') end.
Definition sail_word_decode x : option word := match decode x with
  | Some (0, x') => U256 <$> decode x'
  | _ => None end.
Lemma sail_word_decode_encode : forall (x : word), sail_word_decode (sail_word_encode x)  = Some x.
Proof.
  unfold sail_word_decode, sail_word_encode;
  intros [x]; rewrite !decode_encode; reflexivity.
Qed.

#[export]
Instance Decidable_eq_word : EqDecision word := decode_encode_eq_dec sail_word_encode
  sail_word_decode sail_word_decode_encode .

#[export]
Instance Countable_word : Countable word := {|
  encode := sail_word_encode;
  decode := sail_word_decode;
  decode_encode := sail_word_decode_encode
|}.
#[export]
Instance dummy_word : Inhabited (word) := { inhabitant := U256 inhabitant }.

Inductive address_typ :=
| Address : vec byte 20 -> address_typ.
Arguments address_typ : clear implicits.

Definition sail_address_typ_encode (x : address_typ) := match x with
  | Address x' => encode (0, encode x') end.
Definition sail_address_typ_decode x : option address_typ := match decode x with
  | Some (0, x') => Address <$> decode x'
  | _ => None end.
Lemma sail_address_typ_decode_encode : forall (x : address_typ), sail_address_typ_decode
  (sail_address_typ_encode x)  = Some x.
Proof.
  unfold sail_address_typ_decode, sail_address_typ_encode;
  intros [x]; rewrite !decode_encode; reflexivity.
Qed.

#[export]
Instance Decidable_eq_address_typ : EqDecision address_typ := decode_encode_eq_dec
  sail_address_typ_encode sail_address_typ_decode sail_address_typ_decode_encode .

#[export]
Instance Countable_address_typ : Countable address_typ := {|
  encode := sail_address_typ_encode;
  decode := sail_address_typ_decode;
  decode_encode := sail_address_typ_decode_encode
|}.
#[export]
Instance dummy_address_typ : Inhabited (address_typ) := { inhabitant := Address inhabitant }.

Inductive b256 :=
| B256 : vec byte 32 -> b256.
Arguments b256 : clear implicits.

Definition sail_b256_encode (x : b256) := match x with B256 x' => encode (0, encode x') end.
Definition sail_b256_decode x : option b256 := match decode x with
  | Some (0, x') => B256 <$> decode x'
  | _ => None end.
Lemma sail_b256_decode_encode : forall (x : b256), sail_b256_decode (sail_b256_encode x)  = Some x.
Proof.
  unfold sail_b256_decode, sail_b256_encode;
  intros [x]; rewrite !decode_encode; reflexivity.
Qed.

#[export]
Instance Decidable_eq_b256 : EqDecision b256 := decode_encode_eq_dec sail_b256_encode
  sail_b256_decode sail_b256_decode_encode .

#[export]
Instance Countable_b256 : Countable b256 := {|
  encode := sail_b256_encode;
  decode := sail_b256_decode;
  decode_encode := sail_b256_decode_encode
|}.
#[export]
Instance dummy_b256 : Inhabited (b256) := { inhabitant := B256 inhabitant }.

Definition hash : Type := b256.

Definition limb : Type := bits 64.

Record AddressResult := {
  AddressResult_success : bool;
  AddressResult_address : address_typ;
}.
Arguments AddressResult : clear implicits.
#[export]
Instance Decidable_eq_AddressResult : EqDecision AddressResult.
   intros [x0 x1].
   intros [y0 y1].
  cmp_record_field x0 y0.
  cmp_record_field x1 y1.
left; subst; reflexivity.
Defined.
#[export]
Instance Countable_AddressResult : Countable AddressResult.
refine {|
  encode x := encode (AddressResult_success x, AddressResult_address x);
  decode x := '(x0, x1) ← decode x;
              mret (Build_AddressResult x0 x1)
|}.
abstract (
  intros [x0 x1];
  rewrite decode_encode;
  reflexivity).
Defined.

Notation "{[ r 'with' 'AddressResult_success' := e ]}" :=
  match r with Build_AddressResult _ (_ as f1) => Build_AddressResult e f1 end (at level 1).
Notation "{[ r 'with' 'AddressResult_address' := e ]}" :=
  match r with Build_AddressResult (_ as f0) _ => Build_AddressResult f0 e end (at level 1).
#[export]
Instance dummy_AddressResult : Inhabited (AddressResult) := {
  inhabitant := {| AddressResult_success := inhabitant; AddressResult_address := inhabitant
|} }.


Record LimbDivMod := {
  LimbDivMod_quotient : limb;
  LimbDivMod_remainder : limb;
}.
Arguments LimbDivMod : clear implicits.
#[export]
Instance Decidable_eq_LimbDivMod : EqDecision LimbDivMod.
   intros [x0 x1].
   intros [y0 y1].
  cmp_record_field x0 y0.
  cmp_record_field x1 y1.
left; subst; reflexivity.
Defined.
#[export]
Instance Countable_LimbDivMod : Countable LimbDivMod.
refine {|
  encode x := encode (LimbDivMod_quotient x, LimbDivMod_remainder x);
  decode x := '(x0, x1) ← decode x;
              mret (Build_LimbDivMod x0 x1)
|}.
abstract (
  intros [x0 x1];
  rewrite decode_encode;
  reflexivity).
Defined.

Notation "{[ r 'with' 'LimbDivMod_quotient' := e ]}" :=
  match r with Build_LimbDivMod _ (_ as f1) => Build_LimbDivMod e f1 end (at level 1).
Notation "{[ r 'with' 'LimbDivMod_remainder' := e ]}" :=
  match r with Build_LimbDivMod (_ as f0) _ => Build_LimbDivMod f0 e end (at level 1).
#[export]
Instance dummy_LimbDivMod : Inhabited (LimbDivMod) := {
  inhabitant := {| LimbDivMod_quotient := inhabitant; LimbDivMod_remainder := inhabitant
|} }.


Record WordDivMod := {
  WordDivMod_quotient : word;
  WordDivMod_remainder : word;
}.
Arguments WordDivMod : clear implicits.
#[export]
Instance Decidable_eq_WordDivMod : EqDecision WordDivMod.
   intros [x0 x1].
   intros [y0 y1].
  cmp_record_field x0 y0.
  cmp_record_field x1 y1.
left; subst; reflexivity.
Defined.
#[export]
Instance Countable_WordDivMod : Countable WordDivMod.
refine {|
  encode x := encode (WordDivMod_quotient x, WordDivMod_remainder x);
  decode x := '(x0, x1) ← decode x;
              mret (Build_WordDivMod x0 x1)
|}.
abstract (
  intros [x0 x1];
  rewrite decode_encode;
  reflexivity).
Defined.

Notation "{[ r 'with' 'WordDivMod_quotient' := e ]}" :=
  match r with Build_WordDivMod _ (_ as f1) => Build_WordDivMod e f1 end (at level 1).
Notation "{[ r 'with' 'WordDivMod_remainder' := e ]}" :=
  match r with Build_WordDivMod (_ as f0) _ => Build_WordDivMod f0 e end (at level 1).
#[export]
Instance dummy_WordDivMod : Inhabited (WordDivMod) := {
  inhabitant := {| WordDivMod_quotient := inhabitant; WordDivMod_remainder := inhabitant
|} }.


Definition limb_bit_count : Type := Z.

Definition word_bit_count : Type := Z.






Variant register : Type :=

.

Definition type_of_register (r : register) : Type :=
  match r with

  end.

Instance Decidable_eq_register : EqDecision register := fun r _ => match r with end.

Instance Countable_register : Countable register := {|
  encode _ := 1%positive;
  decode _ := None;
  decode_encode (r : register) := match r with end
|}.

Definition register_transport {P : Type -> Type} {r r' : register} :
  r = r' -> P (type_of_register r) -> P (type_of_register r') :=
  match r, r' with
  end.

Lemma register_transport_sound {P} {r : register} (e : r = r) (p : P (type_of_register r)) : register_transport e p = p.
Proof.
  destruct r.
Qed.


Definition register_beq (r r' : register) : bool :=
  match r, r' with

  | _, _ => false
  end.

Lemma register_beq_refl (r : register) : register_beq r r = true.
destruct r; simpl; autorewrite with register_beq_refls; reflexivity.
Qed.

Definition register_eq_cast (P : Type -> Type) (r r' : register) : P (type_of_register r) -> option (P (type_of_register r')) :=
  match r, r' with

  | _, _ => fun _ => None
  end.

Definition register_list : list (string * register) := List.concat [

].

Definition string_of_register (r : register) : string :=
  match List.find (fun '(_s, r') => register_beq r r') register_list with
  | Some (s, _r) => s
  | None => "<impossible>"
  end.

Instance Pretty_register : Pretty register :=
  fun reg => string_of_register reg.

Definition register_of_string (s : string) : option register :=
  match List.find (fun '(s', _r) => String.eqb s s') register_list with
  | Some (_s, r) => Some r
  | None => None
  end.

Lemma string_of_register_roundtrip (r : register) :
  register_of_string (string_of_register r) = Some r.
case r; intro r'; destruct r'; reflexivity.
Qed.

#[export] Instance string_of_register_inj : Inj (=) (=) string_of_register.
Proof.
  intros r r' H.
  specialize (string_of_register_roundtrip r) as H1.
  specialize (string_of_register_roundtrip r') as H2.
  rewrite H in H1.
  rewrite H2 in H1.
  congruence.
Qed.
#[export] Hint Extern 1 (register _) => assumption : typeclass_instances.
#[export] Instance Decidable_eq_register_values `(r : register) : EqDecision (type_of_register r) | 100 :=
match r with

end.
#[export] Instance Inhabited_register_values `(r : register) : Inhabited (type_of_register r) | 100 :=
  match r with

end.
#[export] Instance Countable_register_values `(r : register) : Countable (type_of_register r) | 100.
refine {|
  encode := match r with

  end;
  decode := match r with

  end;
|}.
abstract (destruct r; apply decode_encode).
Defined.



(* Definitions to support the lifting to the sequential monad *)
Record regstate := {

}.


Definition init_regstate : regstate := Build_regstate

.

Definition register_lookup (reg : register) (rs : regstate) : type_of_register reg :=
  match reg with

  end.

Definition register_set (reg : register) : type_of_register reg -> regstate -> regstate :=
  match reg with

  end.

Lemma register_lookup_set (r : register) regs v: register_lookup r (register_set r v regs) = v.
destruct regs, r; simpl; autorewrite with register_beq_refls; reflexivity.
Qed.

Lemma irrelevant_register_set (r r' : register) regs v:
  register_beq r r' = false ->
  register_lookup r (register_set r' v regs) = register_lookup r regs.
destruct regs, r, r'; simpl; intro EQ; rewrite ?EQ; reflexivity.
Qed.

Arguments register_set : simpl never.
Arguments register_lookup : simpl never.

Definition register_accessors : register_accessors regstate register type_of_register := (@register_lookup, @register_set).


(* Instantiate library definitions with types. *)

Definition read_reg {E} := @read_reg register type_of_register E.
Definition write_reg {E} := @write_reg register type_of_register E.
Definition MR r a := @monadR register type_of_register a r unit.
Definition M a := @monad register type_of_register a unit.
Definition returnM {A:Type} := @returnm register type_of_register A unit.
Definition returnR {A:Type} (R:Type) := @returnm register type_of_register A (R + unit).
Definition register_ref := @register_ref register type_of_register.