(*Generated by Sail from schema_prefix.*)


From stdpp Require Import base countable pretty.
Require Import SailStdpp.Base.
Require Import SailStdpp.Real.

Import ListNotations.
Open Scope string.
Open Scope bool.
Open Scope Z.

Definition bit : Type := mword 1.

Definition bits (n : Z) : Type := mword n.

Definition word : Type := bits 256.

Definition address : Type := bits 160.

Definition hash : Type := bits 256.

Definition byte : Type := bits 8.

Definition limb : Type := bits 64.

Record LimbDivMod := {
  LimbDivMod_quotient : limb;
  LimbDivMod_remainder : limb;
}.
Arguments LimbDivMod : clear implicits.
#[export]
Instance Decidable_eq_LimbDivMod : EqDecision LimbDivMod.
   intros [x0 x1].
   intros [y0 y1].
  cmp_record_field x0 y0.
  cmp_record_field x1 y1.
left; subst; reflexivity.
Defined.
#[export]
Instance Countable_LimbDivMod : Countable LimbDivMod.
refine {|
  encode x := encode (LimbDivMod_quotient x, LimbDivMod_remainder x);
  decode x := '(x0, x1) ← decode x;
              mret (Build_LimbDivMod x0 x1)
|}.
abstract (
  intros [x0 x1];
  rewrite decode_encode;
  reflexivity).
Defined.

Notation "{[ r 'with' 'LimbDivMod_quotient' := e ]}" :=
  match r with Build_LimbDivMod _ (_ as f1) => Build_LimbDivMod e f1 end (at level 1).
Notation "{[ r 'with' 'LimbDivMod_remainder' := e ]}" :=
  match r with Build_LimbDivMod (_ as f0) _ => Build_LimbDivMod f0 e end (at level 1).
#[export]
Instance dummy_LimbDivMod : Inhabited (LimbDivMod) := {
  inhabitant := {| LimbDivMod_quotient := inhabitant; LimbDivMod_remainder := inhabitant
|} }.


Record WordDivMod := {
  WordDivMod_quotient : word;
  WordDivMod_remainder : word;
}.
Arguments WordDivMod : clear implicits.
#[export]
Instance Decidable_eq_WordDivMod : EqDecision WordDivMod.
   intros [x0 x1].
   intros [y0 y1].
  cmp_record_field x0 y0.
  cmp_record_field x1 y1.
left; subst; reflexivity.
Defined.
#[export]
Instance Countable_WordDivMod : Countable WordDivMod.
refine {|
  encode x := encode (WordDivMod_quotient x, WordDivMod_remainder x);
  decode x := '(x0, x1) ← decode x;
              mret (Build_WordDivMod x0 x1)
|}.
abstract (
  intros [x0 x1];
  rewrite decode_encode;
  reflexivity).
Defined.

Notation "{[ r 'with' 'WordDivMod_quotient' := e ]}" :=
  match r with Build_WordDivMod _ (_ as f1) => Build_WordDivMod e f1 end (at level 1).
Notation "{[ r 'with' 'WordDivMod_remainder' := e ]}" :=
  match r with Build_WordDivMod (_ as f0) _ => Build_WordDivMod f0 e end (at level 1).
#[export]
Instance dummy_WordDivMod : Inhabited (WordDivMod) := {
  inhabitant := {| WordDivMod_quotient := inhabitant; WordDivMod_remainder := inhabitant
|} }.


Definition limb_bit_count : Type := Z.

Definition word_bit_count : Type := Z.






Variant register : Type :=

.

Definition type_of_register (r : register) : Type :=
  match r with

  end.

Instance Decidable_eq_register : EqDecision register := fun r _ => match r with end.

Instance Countable_register : Countable register := {|
  encode _ := 1%positive;
  decode _ := None;
  decode_encode (r : register) := match r with end
|}.

Definition register_transport {P : Type -> Type} {r r' : register} :
  r = r' -> P (type_of_register r) -> P (type_of_register r') :=
  match r, r' with
  end.

Lemma register_transport_sound {P} {r : register} (e : r = r) (p : P (type_of_register r)) : register_transport e p = p.
Proof.
  destruct r.
Qed.


Definition register_beq (r r' : register) : bool :=
  match r, r' with

  | _, _ => false
  end.

Lemma register_beq_refl (r : register) : register_beq r r = true.
destruct r; simpl; autorewrite with register_beq_refls; reflexivity.
Qed.

Definition register_eq_cast (P : Type -> Type) (r r' : register) : P (type_of_register r) -> option (P (type_of_register r')) :=
  match r, r' with

  | _, _ => fun _ => None
  end.

Definition register_list : list (string * register) := List.concat [

].

Definition string_of_register (r : register) : string :=
  match List.find (fun '(_s, r') => register_beq r r') register_list with
  | Some (s, _r) => s
  | None => "<impossible>"
  end.

Instance Pretty_register : Pretty register :=
  fun reg => string_of_register reg.

Definition register_of_string (s : string) : option register :=
  match List.find (fun '(s', _r) => String.eqb s s') register_list with
  | Some (_s, r) => Some r
  | None => None
  end.

Lemma string_of_register_roundtrip (r : register) :
  register_of_string (string_of_register r) = Some r.
case r; intro r'; destruct r'; reflexivity.
Qed.

#[export] Instance string_of_register_inj : Inj (=) (=) string_of_register.
Proof.
  intros r r' H.
  specialize (string_of_register_roundtrip r) as H1.
  specialize (string_of_register_roundtrip r') as H2.
  rewrite H in H1.
  rewrite H2 in H1.
  congruence.
Qed.
#[export] Hint Extern 1 (register _) => assumption : typeclass_instances.
#[export] Instance Decidable_eq_register_values `(r : register) : EqDecision (type_of_register r) | 100 :=
match r with

end.
#[export] Instance Inhabited_register_values `(r : register) : Inhabited (type_of_register r) | 100 :=
  match r with

end.
#[export] Instance Countable_register_values `(r : register) : Countable (type_of_register r) | 100.
refine {|
  encode := match r with

  end;
  decode := match r with

  end;
|}.
abstract (destruct r; apply decode_encode).
Defined.



(* Definitions to support the lifting to the sequential monad *)
Record regstate := {

}.


Definition init_regstate : regstate := Build_regstate

.

Definition register_lookup (reg : register) (rs : regstate) : type_of_register reg :=
  match reg with

  end.

Definition register_set (reg : register) : type_of_register reg -> regstate -> regstate :=
  match reg with

  end.

Lemma register_lookup_set (r : register) regs v: register_lookup r (register_set r v regs) = v.
destruct regs, r; simpl; autorewrite with register_beq_refls; reflexivity.
Qed.

Lemma irrelevant_register_set (r r' : register) regs v:
  register_beq r r' = false ->
  register_lookup r (register_set r' v regs) = register_lookup r regs.
destruct regs, r, r'; simpl; intro EQ; rewrite ?EQ; reflexivity.
Qed.

Arguments register_set : simpl never.
Arguments register_lookup : simpl never.

Definition register_accessors : register_accessors regstate register type_of_register := (@register_lookup, @register_set).


(* Instantiate library definitions with types. *)

Definition read_reg {E} := @read_reg register type_of_register E.
Definition write_reg {E} := @write_reg register type_of_register E.
Definition MR r a := @monadR register type_of_register a r unit.
Definition M a := @monad register type_of_register a unit.
Definition returnM {A:Type} := @returnm register type_of_register A unit.
Definition returnR {A:Type} (R:Type) := @returnm register type_of_register A (R + unit).
Definition register_ref := @register_ref register type_of_register.