# Generated by Sail's Python backend. Do not edit by hand.
# Sail source: kernel/environment.sail
from __future__ import annotations

from .._runtime import (
    BoundedUint,
    Bytes20,
    Bytes32,
    SailMatchFailure,
    SailThrown,
    Uint,
    UintEnum,
)
from evm.HostContract import (
    ancestor_hash_read as _host_ancestor_hash_read,
)
from evm.prelude import (
    address,
    hash,
    word,
    u256,
    address_to_word,
    ZERO_WORD,
    ZERO_ADDRESS,
    ZERO_HASH,
)
from evm.primitives.quantities import (
    account_nonce,
    ancestor_hash_count,
    block_number,
    block_timestamp,
    chain_identifier,
    excess_blob_gas,
    slot_number,
    word_of_slot_number,
    word_of_block_number,
    word_of_block_timestamp,
    word_of_chain_identifier,
)
from evm.primitives.gas import (
    block_gas,
    block_gas_limit,
)
from evm.primitives.bytes import (
    stateless_input_slice,
    WORD_BYTE_LENGTH,
    EMPTY_STATELESS_INPUT_SLICE,
)
from evm.exceptions import (
    BlockError,
    InvalidBlock,
)
from evm.primitives.ssz import block_access_index
from evm.host.region_access import stateless_input_slice_load_n
from evm.primitives.chain_config import (
    ExecutionProfile,
    DEFAULT_EXECUTION_PROFILE,
)
from evm.primitives.tx import EMPTY_BLOB_HASHES
from evm.primitives.block import BlockHeader
from evm.primitives.evm import (
    TxEnv,
    TxEnvFields,
    TxEnvFieldsValidity,
)
from evm.lib.rlp.codecs.address import create_address
from evm.lib.address import create2_address

class EnvField(UintEnum):
    F_Number = Uint(0)
    F_Timestamp = Uint(1)
    F_Coinbase = Uint(2)
    F_BaseFee = Uint(3)
    F_ChainId = Uint(4)
    F_GasLimit = Uint(5)
    F_PrevRandao = Uint(6)
    F_Origin = Uint(7)
    F_GasPrice = Uint(8)
    F_SlotNumber = Uint(9)

def k_env(f: EnvField) -> word:
    active_tx = k_tx
    match f:
        case EnvField.F_Number:
            return word(u256(word_of_block_number(k_header.number)))
        case EnvField.F_Timestamp:
            return word(u256(word_of_block_timestamp(k_header.timestamp)))
        case EnvField.F_Coinbase:
            return word(address_to_word(k_header.fee_recipient))
        case EnvField.F_BaseFee:
            return word(k_header.base_fee)
        case EnvField.F_ChainId:
            return word(u256(word_of_chain_identifier(k_chain_id)))
        case EnvField.F_GasLimit:
            return word(u256(k_header.gas_limit))
        case EnvField.F_PrevRandao:
            return word(k_header.prev_randao)
        case EnvField.F_Origin:
            return word(address_to_word(active_tx.origin))
        case EnvField.F_GasPrice:
            return word(active_tx.gas_price)
        case EnvField.F_SlotNumber:
            return word(u256(word_of_slot_number(k_header.slot_number)))
        case _:
            raise SailMatchFailure("no Sail match clause applied")

def k_coinbase() -> address:
    return Bytes20(k_header.fee_recipient)

def blockhash_word_distance(current: int, number: int) -> BoundedUint[1, 115792089237316195423570985008687907853269984665640564039457584007913129639935]:
    return BoundedUint[1, 115792089237316195423570985008687907853269984665640564039457584007913129639935]((int(current) - int(number)))

def k_blockhash(number_word: word) -> hash:
    current = k_header.number
    current_word = u256(word_of_block_number(current))
    if (int(number_word) < int(current_word)):
        distance_word = blockhash_word_distance(current_word, number_word)
        if (int(distance_word) <= 256):
            distance = distance_word
            if (int(k_n_headers) < int(distance)):
                raise SailThrown(InvalidBlock(BlockError.WitnessDeficient))
            else:
                index = (int(distance) - 1)
                return Bytes32(_host_ancestor_hash_read(index))
        else:
            return Bytes32(ZERO_HASH)
    else:
        return Bytes32(ZERO_HASH)

def k_blobhash(index_word: word) -> word:
    active_tx = k_tx
    count = active_tx.blob_hashes.count
    if (int(index_word) < int(count)):
        index = index_word
        offset = (int((33 * int(index))) + 1)
        return word(stateless_input_slice_load_n(active_tx.blob_hashes.bytes, offset, WORD_BYTE_LENGTH))
    else:
        return word(ZERO_WORD)

def k_create_addr(a: address, nonce: account_nonce) -> address:
    return Bytes20(create_address(a, nonce))

def k_create2_addr(a: address, salt: word, inithash: hash) -> address:
    return Bytes20(create2_address(a, salt, inithash))

k_parent_state_root: hash = ZERO_HASH

k_n_headers: ancestor_hash_count = 0

k_chain_id: chain_identifier = 1

k_execution_profile: ExecutionProfile = DEFAULT_EXECUTION_PROFILE

k_header: BlockHeader = BlockHeader(number=block_number(0), timestamp=block_timestamp(0), extra_data=EMPTY_STATELESS_INPUT_SLICE, gas_limit=block_gas_limit(0), gas_used=block_gas(0), prev_randao=word(ZERO_WORD), base_fee=word(ZERO_WORD), blob_gas_used=0, excess_blob_gas=excess_blob_gas(0), state_root=hash(ZERO_HASH), receipts_root=hash(ZERO_HASH), logs_bloom=stateless_input_slice(0, 256), fee_recipient=address(ZERO_ADDRESS), parent_hash=hash(ZERO_HASH), parent_beacon_block_root=hash(ZERO_HASH), slot_number=slot_number(0))

k_tx: TxEnv = TxEnvFields(validity=TxEnvFieldsValidity(blob_limit=0), origin=address(ZERO_ADDRESS), gas_price=word(ZERO_WORD), blob_hashes=EMPTY_BLOB_HASHES)

k_current_transaction_epoch: block_access_index = 0

def _reset_registers() -> None:
    global k_parent_state_root, k_n_headers, k_chain_id, k_execution_profile, k_header, k_tx, k_current_transaction_epoch
    k_parent_state_root = ZERO_HASH
    k_n_headers = 0
    k_chain_id = 1
    k_execution_profile = DEFAULT_EXECUTION_PROFILE
    k_header = BlockHeader(number=block_number(0), timestamp=block_timestamp(0), extra_data=EMPTY_STATELESS_INPUT_SLICE, gas_limit=block_gas_limit(0), gas_used=block_gas(0), prev_randao=word(ZERO_WORD), base_fee=word(ZERO_WORD), blob_gas_used=0, excess_blob_gas=excess_blob_gas(0), state_root=hash(ZERO_HASH), receipts_root=hash(ZERO_HASH), logs_bloom=stateless_input_slice(0, 256), fee_recipient=address(ZERO_ADDRESS), parent_hash=hash(ZERO_HASH), parent_beacon_block_root=hash(ZERO_HASH), slot_number=slot_number(0))
    k_tx = TxEnvFields(validity=TxEnvFieldsValidity(blob_limit=0), origin=address(ZERO_ADDRESS), gas_price=word(ZERO_WORD), blob_hashes=EMPTY_BLOB_HASHES)
    k_current_transaction_epoch = 0
    return None
