# Generated by Sail's Python backend. Do not edit by hand.
# Sail source: kernel/lifecycle.sail
from __future__ import annotations

from .._runtime import (
    Bytes20,
    SailMatchFailure,
    Uint,
)
from copy import deepcopy
from dataclasses import replace
from evm.HostContract import (
    acct_block_get as _host_acct_block_get,
    acct_block_write as _host_acct_block_write,
    acct_tx_pop as _host_acct_tx_pop,
    acct_tx_reset as _host_acct_tx_reset,
    bal_balance_change as _host_bal_balance_change,
    bal_code_change as _host_bal_code_change,
    bal_nonce_change as _host_bal_nonce_change,
    bal_storage_change as _host_bal_storage_change,
    logs_tx_reset as _host_logs_tx_reset,
    state_checkpoint as _host_state_checkpoint,
    state_checkpoint_reset as _host_state_checkpoint_reset,
    state_revert as _host_state_revert,
    storage_block_clear as _host_storage_block_clear,
    storage_block_put as _host_storage_block_put,
    storage_tx_clear as _host_storage_tx_clear,
    storage_tx_pop as _host_storage_tx_pop,
    storage_tx_reset as _host_storage_tx_reset,
    transient_reset as _host_transient_reset,
    warm_reset as _host_warm_reset,
)
from evm.primitives.quantities import code_chunk_index
from evm.primitives.fork import (
    Cancun,
    Amsterdam,
)
from evm.primitives.account import (
    Account,
    AcctEntry,
    AcctValue,
)
from evm.primitives.block import BlockHeader
from evm.primitives.evm import TxEnv
from evm.kernel.accounts import (
    account_changed,
    account_delete,
    account_clear_preserving_balance,
)
from evm.kernel import environment

def k_state_checkpoint() -> code_chunk_index:
    return Uint(_host_state_checkpoint())

def k_set_header(h: BlockHeader) -> None:
    environment.k_header = h
    return None

def k_set_tx(env: TxEnv) -> None:
    environment.k_tx = env
    return None

def k_tx_reset() -> None:
    _host_acct_tx_reset()
    _host_storage_tx_reset()
    _host_warm_reset()
    _host_transient_reset()
    _host_logs_tx_reset()
    return _host_state_checkpoint_reset()

def account_deleted_at_tx_end(acc: Account) -> bool:
    execution_profile = environment.k_execution_profile
    profile = execution_profile.protocol
    return ((acc.selfdestructed) & ((((int(profile.fork) < int(Cancun))) | (acc.created))))

def k_tx_merge() -> None:
    execution_profile = environment.k_execution_profile
    profile = execution_profile.protocol
    more = True
    while True:
        if not (more):
            break
        match _host_acct_tx_pop():
            case (e as _sail_some_value_2) if _sail_some_value_2 is not None:
                curr = e.value.curr
                deleted = account_deleted_at_tx_end(curr)
                if deleted:
                    if (int(profile.fork) >= int(Amsterdam)):
                        curr = account_clear_preserving_balance(curr)
                    else:
                        curr = account_delete(curr)
                    _host_storage_tx_clear(e.addr)
                if ((deleted) | (((curr.storage_cleared) & ((not (e.value.orig.storage_cleared)))))):
                    _host_storage_block_clear(e.addr)
                if ((curr.info.nonce) != (e.value.orig.info.nonce)):
                    _host_bal_nonce_change(environment.k_block_access_index, e.addr, curr.info.nonce)
                if ((curr.info.balance) != (e.value.orig.info.balance)):
                    _host_bal_balance_change(environment.k_block_access_index, e.addr, curr.info.balance)
                if ((curr.info.code_hash) != (e.value.orig.info.code_hash)):
                    _host_bal_code_change(environment.k_block_access_index, e.addr, curr.info.code_hash)
                curr = replace(deepcopy(curr), created=False, selfdestructed=False)
                if account_changed(curr, e.value.orig):
                    _host_acct_block_write(AcctEntry(addr=Bytes20(e.addr), value=AcctValue(curr=curr, orig=e.value.orig)))
            case None:
                more = False
            case _:
                raise SailMatchFailure("no Sail match clause applied")
    more = True
    while True:
        if not (more):
            break
        match _host_storage_tx_pop():
            case (e as _sail_some_value_0) if _sail_some_value_0 is not None:
                match _host_acct_block_get(e.key.addr):
                    case (acc as _sail_some_value_1) if _sail_some_value_1 is not None:
                        if ((acc.present) & (((e.value.curr) != (e.value.orig)))):
                            _host_bal_storage_change(environment.k_block_access_index, e.key.addr, e.key.slot, e.value.curr)
                            _host_storage_block_put(e)
                    case None:
                        pass
                    case _:
                        raise SailMatchFailure("no Sail match clause applied")
            case None:
                more = False
            case _:
                raise SailMatchFailure("no Sail match clause applied")
    _host_acct_tx_reset()
    return _host_storage_tx_reset()

def k_revert(checkpoint: code_chunk_index) -> None:
    return _host_state_revert(checkpoint)
