# Generated by Sail's Python backend. Do not edit by hand.
# Sail source: kernel/storage.sail
from __future__ import annotations

from .._runtime import (
    Bytes20,
    SailMatchFailure,
    SailReturn,
)
from evm.HostContract import (
    bal_storage_read as _host_bal_storage_read,
    keccak256_word as _host_keccak256_word,
    storage_block_cache as _host_storage_block_cache,
    storage_block_get as _host_storage_block_get,
    storage_tx_get as _host_storage_tx_get,
    storage_tx_update as _host_storage_tx_update,
    transient_load as _host_transient_load,
    transient_store as _host_transient_store,
    warm_addr_touch as _host_warm_addr_touch,
    warm_slot_touch as _host_warm_slot_touch,
)
from evm.prelude import (
    address,
    word,
    ZERO_WORD,
)
from evm.primitives.account import (
    StorageEntry,
    StorageKey,
    StorageTxCleared,
    StorageTxHit,
    StorageTxMiss,
    StorageValue,
)
from evm.kernel.accounts import k_aload
from evm.lib.state_trie import stateless_storage_by_key

def storage_key(a: address, s: word) -> StorageKey:
    return StorageKey(addr=Bytes20(a), slot=word(s))

def k_access_account(a: address) -> bool:
    return _host_warm_addr_touch(a)

def k_slot_is_warm(a: address, s: word) -> bool:
    return _host_warm_slot_touch(a, s)

def k_sload(a: address, s: word) -> StorageValue:
    try:
        key = storage_key(a, s)
        tx_value = _host_storage_tx_get(key)
        match tx_value:
            case StorageTxHit(value):
                raise SailReturn(value)
            case StorageTxCleared(_):
                _host_bal_storage_read(a, s)
                raise SailReturn(StorageValue(curr=word(ZERO_WORD), orig=word(ZERO_WORD)))
            case StorageTxMiss(_):
                _host_bal_storage_read(a, s)
            case _:
                raise SailMatchFailure("no Sail match clause applied")
        block_value = _host_storage_block_get(key)
        match block_value:
            case (entry as _sail_some_value_0) if _sail_some_value_0 is not None:
                raise SailReturn(StorageValue(curr=word(entry.curr), orig=word(entry.curr)))
            case None:
                pass
            case _:
                raise SailMatchFailure("no Sail match clause applied")
        acc = k_aload(a)
        slot_hash = _host_keccak256_word(s)
        if acc.storage_cleared:
            value = ZERO_WORD
        else:
            value = stateless_storage_by_key(acc.info.storage_root, slot_hash)
        _host_storage_block_cache(key, slot_hash, value)
        return StorageValue(curr=word(value), orig=word(value))
    except SailReturn as _sail_return:
        return _sail_return.value

def k_sstore(a: address, s: word, v: StorageValue) -> None:
    return _host_storage_tx_update(StorageEntry(key=storage_key(a, s), value=v))

def k_tload(a: address, s: word) -> word:
    return word(_host_transient_load(a, s))

def k_tstore(a: address, s: word, v: word) -> None:
    return _host_transient_store(a, s, v)
