# Generated by Sail's Python backend. Do not edit by hand.
# Sail source: kernel/selfdestruct.sail
from __future__ import annotations

from .._runtime import (
    SailReturn,
)
from copy import deepcopy
from dataclasses import replace
from src.prelude import (
    address,
    word,
    word_is_zero,
    ZERO_WORD,
)
from src.kernel.accounts import (
    store_account,
    store_account_info,
    k_aload,
)

def k_selfdestruct(a: address) -> None:
    cur = k_aload(a)
    active = (not (cur.selfdestructed))
    if active:
        return store_account(a, replace(deepcopy(cur), selfdestructed=True))
    else:
        return None

def k_is_selfdestructed(a: address) -> bool:
    return k_aload(a).selfdestructed

def k_mark_created(a: address) -> None:
    cur = k_aload(a)
    return store_account(a, replace(deepcopy(cur), created=True))

def k_was_created(a: address) -> bool:
    return k_aload(a).created

def k_zero_balance(a: address) -> None:
    try:
        cur = k_aload(a)
        balance_is_zero = word_is_zero(cur.info.balance)
        if balance_is_zero:
            raise SailReturn(None)
        return store_account_info(a, cur, replace(deepcopy(cur.info), balance=word(ZERO_WORD)))
    except SailReturn as _sail_return:
        return _sail_return.value
