# Generated by Sail's Python backend. Do not edit by hand.
# Sail source: primitives/gas.sail
from __future__ import annotations

from .._runtime import (
    IntegerRange,
    Uint,
    Unsigned,
)
from dataclasses import dataclass
from typing import Annotated, TypeAlias

gas: TypeAlias = Uint

transaction_gas: TypeAlias = Uint

gas_cost: TypeAlias = Uint

memory_required_endpoint: TypeAlias = Uint

memory_expansion_charge: TypeAlias = Uint

@dataclass(slots=True)
class GasCharge:
    affordable: bool
    cost: gas_cost

def gas_charge(cost: transaction_state_gas_used) -> GasCharge:
    return GasCharge(affordable=True, cost=gas_cost(cost))

modexp_factor: TypeAlias = Uint

modexp_product: TypeAlias = Uint

modexp_osaka_extra: TypeAlias = Uint

modexp_pre_osaka_extra: TypeAlias = Uint

bls_msm_coefficient: TypeAlias = Uint

bls_msm_product: TypeAlias = Uint

bls_msm_tail_product: TypeAlias = Uint

linear_gas_variable_product: TypeAlias = Uint

linear_gas_product: TypeAlias = Uint

class transaction_execution_gas(Unsigned):
    LOWER = 0
    UPPER = 16777216

    def _in_range(self, value: int) -> bool:
        return self.LOWER <= value <= self.UPPER

class state_gas_spill(Unsigned):
    LOWER = 0
    UPPER = 16777216

    def _in_range(self, value: int) -> bool:
        return self.LOWER <= value <= self.UPPER

block_gas_limit: TypeAlias = Uint

block_gas: TypeAlias = Uint

class receipt_cumulative_gas(Unsigned):
    LOWER = 0
    UPPER = 36893488147419103230

    def _in_range(self, value: int) -> bool:
        return self.LOWER <= value <= self.UPPER

class gas_constant(Unsigned):
    LOWER = 0
    UPPER = 45000

    def _in_range(self, value: int) -> bool:
        return self.LOWER <= value <= self.UPPER

gas_refund: TypeAlias = int

frame_state_gas_delta: TypeAlias = int

state_gas_delta: TypeAlias = int

transaction_state_gas_delta: TypeAlias = int

transaction_state_gas_used: TypeAlias = Uint

transaction_refund_divisor: TypeAlias = int

BLOCK_ACCESS_LIST_ITEM_GAS: Annotated[int, IntegerRange(2000, 2000)] = 2000

GAS_COST_ZERO: int = 0

GAS_CHARGE_UNAFFORDABLE: GasCharge = GasCharge(affordable=False, cost=gas_cost(GAS_COST_ZERO))

TRANSACTION_EXECUTION_GAS_LIMIT: Annotated[int, IntegerRange((2 ** 24), (2 ** 24))] = (1 << 24)

STATE_GAS_SPILL_ZERO: int = 0

STATE_GAS_SPILL_LIMIT: int = (1 << 24)

GAS_ZERO: int = 0

SYSTEM_CALL_GAS_LIMIT: Annotated[int, IntegerRange(30000000, 30000000)] = 30000000

GAS_CONSTANT_ZERO: int = 0

GAS_REFUND_ZERO: int = 0

FRAME_STATE_GAS_DELTA_ZERO: int = 0

STATE_GAS_DELTA_ZERO: int = 0
