# Generated by Sail's Python backend. Do not edit by hand.
# Sail source: primitives/rlp.sail
from __future__ import annotations

from dataclasses import dataclass
from typing import Any, TypeAlias
from pydantic import ConfigDict, model_validator
from pydantic.dataclasses import dataclass as pydantic_dataclass
from typing_extensions import Self
from src.primitives.bytes import (
    ScratchSliceFields,
    StatelessInputSliceFields,
)

@pydantic_dataclass(config=ConfigDict(strict=True, arbitrary_types_allowed=True), frozen=True, slots=True, kw_only=True)
class RlpFieldRefValidity:
    source_off: int
    source_len: int
    content_len: int

    @model_validator(mode="after")
    def validate(self) -> Self:
        if not ((((0 <= self.source_off) and ((0 <= self.source_len) and ((self.source_off + self.source_len) <= ((2 ** 32) - 1)))) and ((0 <= self.content_len) and (self.content_len <= self.source_len)))):
            raise ValueError("RlpFieldRefValidity violates Sail constraint rlp_field_ref_valid('source_off, 'source_len, 'content_len)")
        return self

@pydantic_dataclass(config=ConfigDict(strict=True, validate_assignment=True, revalidate_instances="always", arbitrary_types_allowed=True), slots=True, kw_only=True)
class RlpFieldRef:
    validity: RlpFieldRefValidity
    source: RlpCursor
    is_list: bool
    content_len: int

    @model_validator(mode="after")
    def validate(self) -> Self:
        if not ((int(self.content_len) == self.validity.content_len)):
            raise ValueError("RlpFieldRef.content_len violates Sail type int('content_len)")
        return self

@pydantic_dataclass(config=ConfigDict(strict=True, arbitrary_types_allowed=True), frozen=True, slots=True, kw_only=True)
class ScratchRlpFieldRefValidity:
    source_off: int
    source_len: int
    content_len: int

    @model_validator(mode="after")
    def validate(self) -> Self:
        if not ((((0 <= self.source_off) and ((0 <= self.source_len) and ((self.source_off + self.source_len) <= ((2 ** 32) - 1)))) and ((0 <= self.content_len) and (self.content_len <= self.source_len)))):
            raise ValueError("ScratchRlpFieldRefValidity violates Sail constraint rlp_field_ref_valid('source_off, 'source_len, 'content_len)")
        return self

@pydantic_dataclass(config=ConfigDict(strict=True, validate_assignment=True, revalidate_instances="always", arbitrary_types_allowed=True), slots=True, kw_only=True)
class ScratchRlpFieldRef:
    validity: ScratchRlpFieldRefValidity
    source: ScratchRlpCursor
    is_list: bool
    content_len: int

    @model_validator(mode="after")
    def validate(self) -> Self:
        if not ((int(self.content_len) == self.validity.content_len)):
            raise ValueError("ScratchRlpFieldRef.content_len violates Sail type int('content_len)")
        return self

class RlpResult:
    # Sail type parameters: ...
    pass

@dataclass(frozen=True, slots=True)
class RlpOk(RlpResult):
    value: Any

@dataclass(frozen=True, slots=True)
class RlpInvalidValue(RlpResult):
    value: None = None

RlpCursor: TypeAlias = StatelessInputSliceFields

ScratchRlpCursor: TypeAlias = ScratchSliceFields
