# Generated by Sail's Python backend. Do not edit by hand.
# Sail source: lib/tx.sail
from __future__ import annotations

from .._runtime import (
    SailMatchFailure,
)
from src.prelude import (
    address,
    hash,
    word,
    word_and,
    word_ult,
    word_ule,
    WORD_ZERO,
    WORD_ONE,
)
from src.primitives.quantities import (
    chain_identifier,
    y_parity,
    word_of_chain_identifier,
)
from src.exceptions import (
    FatalError,
    fatal_error,
)
from src.primitives.crypto import (
    ecrecover_addr,
    SECP_N_HALF,
)
from src.primitives.tx import TxSignatureScheme
from src.lib.rlp.codecs.transaction_signing import legacy_sig_chain_id

def tx_signature_parity(chain_id: chain_identifier, scheme: TxSignatureScheme, v: word) -> y_parity:
    match scheme:
        case TxSignatureScheme.LegacySignature:
            eip155_v = word_ule(35, v)
            signature_chain_id = legacy_sig_chain_id(v)
            expected_chain_id = word_of_chain_identifier(chain_id)
            if ((((v) == (27))) | (((((v) == (28))) | (((eip155_v) & (((signature_chain_id) == (expected_chain_id)))))))):
                parity_bit = word_and(v, WORD_ONE)
                if ((parity_bit) == (WORD_ONE)):
                    return y_parity(0)
                else:
                    return y_parity(1)
            else:
                return y_parity(fatal_error(FatalError.InvalidSignature))
        case TxSignatureScheme.TypedSignature:
            if ((v) == (WORD_ZERO)):
                return y_parity(0)
            else:
                if ((v) == (WORD_ONE)):
                    return y_parity(1)
                else:
                    return y_parity(fatal_error(FatalError.InvalidSignature))
        case _:
            raise SailMatchFailure("no Sail match clause applied")

def tx_auth_valid(sender: address, h: hash, parity: y_parity, r: word, s: word) -> bool:
    high_s = word_ult(SECP_N_HALF, s)
    if high_s:
        return False
    else:
        (recovered, recovered_sender) = ecrecover_addr(h, parity, r, s)
        return ((recovered) & (((recovered_sender) == (sender))))
