# Generated by Sail's Python backend. Do not edit by hand.
# Sail source: lib/rlp/codecs/block_access_list.sail
from __future__ import annotations

from ...._runtime import (
    SailReturn,
)
from src.prelude import word
from src.primitives.quantities import ssz_uint
from src.primitives.bytes import (
    StatelessInputSlice,
    StatelessInputSliceFields,
)
from src.exceptions import (
    FatalError,
    fatal_error,
)
from src.primitives.rlp import (
    RlpCursor,
    RlpFieldRef,
)
from src.lib.rlp.decoding import (
    rlp_decode_list,
    rlp_item_content,
    rlp_ref_framing_canonical,
    rlp_ref_bytes_canonical,
    rlp_item_uint_canonical,
    rlp_decode_word,
    rlp_decode_uint64,
)

def bal_ref_cursor(f: RlpFieldRef) -> StatelessInputSliceFields:
    framing_canonical = rlp_ref_framing_canonical(f)
    if ((f.is_list) & (framing_canonical)):
        return rlp_decode_list(f)
    else:
        return fatal_error(FatalError.InvalidBlockAccessList)

def bal_ref_bytes(f: RlpFieldRef) -> StatelessInputSlice:
    canonical = rlp_ref_bytes_canonical(f)
    if canonical:
        return rlp_item_content(f)
    else:
        return fatal_error(FatalError.InvalidBlockAccessList)

def bal_ref_word(f: RlpFieldRef) -> word:
    canonical = rlp_item_uint_canonical(f)
    if ((canonical) & ((int(f.content_len) <= 32))):
        return word(rlp_decode_word(f))
    else:
        return word(fatal_error(FatalError.InvalidBlockAccessList))

def bal_ref_uint64(f: RlpFieldRef) -> ssz_uint:
    canonical = rlp_item_uint_canonical(f)
    if ((canonical) & ((int(f.content_len) <= 8))):
        return ssz_uint(rlp_decode_uint64(f))
    else:
        return ssz_uint(fatal_error(FatalError.InvalidBlockAccessList))

def bal_expect_end(cursor: RlpCursor) -> None:
    try:
        if ((cursor.len) == (0)):
            raise SailReturn(None)
        return fatal_error(FatalError.InvalidBlockAccessList)
    except SailReturn as _sail_return:
        return _sail_return.value
