# Generated by Sail's Python backend. Do not edit by hand.
# Sail source: lib/rlp/codecs/block_header.sail
from __future__ import annotations

from ...._runtime import (
    Bits,
    Bytes32,
    sail_tmod_int,
)
from evm.HostContract import (
    scratch_keccak256 as _host_scratch_keccak256,
)
from src.prelude import (
    hash,
    hash_to_word,
    ZERO_WORD,
)
from src.primitives.bytes import EIGHT_BYTE_LENGTH
from src.exceptions import (
    FatalError,
    fatal_error,
)
from src.kernel.scratch import scratch_push_word_be
from src.primitives.fork import (
    London,
    Shanghai,
    Cancun,
    Prague,
    Amsterdam,
)
from src.primitives.block import (
    BlockHeader,
    logs_bloom_from_ref,
    EMPTY_OMMER_HASH,
)
from src.lib.rlp.encoding import (
    rlp_scratch_length,
    rlp_scratch_length_add,
    rlp_uint_word_size,
    rlp_word_size,
    rlp_addr_size,
    rlp_list_size,
    rlp_input_scratch_slice_size,
    rlp_write_string_prefix,
    rlp_write_list_prefix,
    rlp_write_input_slice,
    rlp_write_uint_word,
    rlp_write_word,
    rlp_write_addr,
    rlp_encoder_begin,
    rlp_encoder_finish,
    rlp_encoder_rewind,
)
from src.kernel.logs import LOGS_BLOOM_BYTE_LENGTH
from src.lib.rlp.codecs.receipts import rlp_write_logs_bloom
from src.kernel import environment

def block_header_hash(header: BlockHeader, transactions_root: hash, withdrawals_root: hash, requests_hash: hash, block_access_list_hash: hash) -> hash:
    execution_profile = environment.k_execution_profile
    profile = execution_profile.protocol
    word_length = rlp_word_size()
    address_length = rlp_addr_size()
    bloom_length = (3 + int(LOGS_BLOOM_BYTE_LENGTH))
    difficulty_length = rlp_uint_word_size(0)
    number_length = rlp_uint_word_size(header.number)
    gas_limit_length = rlp_uint_word_size(header.gas_limit)
    gas_used_length = rlp_uint_word_size(header.gas_used)
    timestamp_length = rlp_uint_word_size(header.timestamp)
    extra_data_length = rlp_input_scratch_slice_size(header.extra_data)
    nonce_length = (1 + int(EIGHT_BYTE_LENGTH))
    content_length = rlp_scratch_length_add((6 * int(word_length)), address_length)
    content_length = rlp_scratch_length(rlp_scratch_length_add(content_length, bloom_length))
    content_length = rlp_scratch_length(rlp_scratch_length_add(content_length, difficulty_length))
    content_length = rlp_scratch_length(rlp_scratch_length_add(content_length, number_length))
    content_length = rlp_scratch_length(rlp_scratch_length_add(content_length, gas_limit_length))
    content_length = rlp_scratch_length(rlp_scratch_length_add(content_length, gas_used_length))
    content_length = rlp_scratch_length(rlp_scratch_length_add(content_length, timestamp_length))
    content_length = rlp_scratch_length(rlp_scratch_length_add(content_length, extra_data_length))
    content_length = rlp_scratch_length(rlp_scratch_length_add(content_length, nonce_length))
    if (int(profile.fork) >= int(London)):
        field_length = rlp_uint_word_size(header.base_fee)
        content_length = rlp_scratch_length(rlp_scratch_length_add(content_length, field_length))
    if (int(profile.fork) >= int(Shanghai)):
        content_length = rlp_scratch_length(rlp_scratch_length_add(content_length, word_length))
    if (int(profile.fork) >= int(Cancun)):
        blob_gas_used_length = rlp_uint_word_size(header.blob_gas_used)
        excess_blob_gas_length = rlp_uint_word_size(header.excess_blob_gas)
        content_length = rlp_scratch_length(rlp_scratch_length_add(content_length, blob_gas_used_length))
        content_length = rlp_scratch_length(rlp_scratch_length_add(content_length, excess_blob_gas_length))
        content_length = rlp_scratch_length(rlp_scratch_length_add(content_length, word_length))
    if (int(profile.fork) >= int(Prague)):
        content_length = rlp_scratch_length(rlp_scratch_length_add(content_length, word_length))
    if (int(profile.fork) >= int(Amsterdam)):
        slot_number_length = rlp_uint_word_size(header.slot_number)
        content_length = rlp_scratch_length(rlp_scratch_length_add(content_length, word_length))
        content_length = rlp_scratch_length(rlp_scratch_length_add(content_length, slot_number_length))
    if (749 < int(content_length)):
        fatal_error(FatalError.RlpDecode)
    bounded_content_length = sail_tmod_int(content_length, 750)
    content_len = bounded_content_length
    encoded_length = rlp_list_size(content_len)
    encoder = rlp_encoder_begin(encoded_length)
    rlp_write_list_prefix(content_len)
    parent_hash = hash_to_word(header.parent_hash)
    rlp_write_word(parent_hash)
    ommer_hash = hash_to_word(EMPTY_OMMER_HASH)
    rlp_write_word(ommer_hash)
    rlp_write_addr(header.fee_recipient)
    state_root = hash_to_word(header.state_root)
    rlp_write_word(state_root)
    transactions_root_word = hash_to_word(transactions_root)
    rlp_write_word(transactions_root_word)
    receipts_root = hash_to_word(header.receipts_root)
    rlp_write_word(receipts_root)
    logs_bloom = logs_bloom_from_ref(header.logs_bloom)
    rlp_write_logs_bloom(logs_bloom)
    rlp_write_uint_word(0)
    rlp_write_uint_word(header.number)
    rlp_write_uint_word(header.gas_limit)
    rlp_write_uint_word(header.gas_used)
    rlp_write_uint_word(header.timestamp)
    rlp_write_input_slice(header.extra_data)
    rlp_write_word(header.prev_randao)
    rlp_write_string_prefix(EIGHT_BYTE_LENGTH, Bits(8, 0b00000000))
    scratch_push_word_be(ZERO_WORD, EIGHT_BYTE_LENGTH)
    if (int(profile.fork) >= int(London)):
        rlp_write_uint_word(header.base_fee)
    if (int(profile.fork) >= int(Shanghai)):
        withdrawals_root_word = hash_to_word(withdrawals_root)
        rlp_write_word(withdrawals_root_word)
    if (int(profile.fork) >= int(Cancun)):
        rlp_write_uint_word(header.blob_gas_used)
        rlp_write_uint_word(header.excess_blob_gas)
        parent_beacon_block_root = hash_to_word(header.parent_beacon_block_root)
        rlp_write_word(parent_beacon_block_root)
    if (int(profile.fork) >= int(Prague)):
        requests_hash_word = hash_to_word(requests_hash)
        rlp_write_word(requests_hash_word)
    if (int(profile.fork) >= int(Amsterdam)):
        block_access_list_hash_word = hash_to_word(block_access_list_hash)
        rlp_write_word(block_access_list_hash_word)
        rlp_write_uint_word(header.slot_number)
    encoded = rlp_encoder_finish(encoder)
    block_hash = _host_scratch_keccak256(encoded)
    rlp_encoder_rewind(encoder)
    return Bytes32(block_hash)
