# Generated by Sail's Python backend. Do not edit by hand.
# Sail source: executor/stateless.sail
from __future__ import annotations

from src.exceptions import (
    FatalError,
    fatal_error,
)
from src.kernel.scratch import scratch_reset
from src.primitives.fork import (
    Cancun,
    Amsterdam,
)
from src.primitives.block import Block
from src.lib.state_trie import compute_state_root
from src.host.debug_disabled import validation_debug_capture_block_gas
from src.lib.ssz.stateless_input import (
    StatelessInputRef,
    decode_stateless_input,
    index_execution_witness,
)
from src.executor.receipts import block_logs_bloom_matches
from src.executor.block_access_list import validate_block_access_list
from src.executor.block import (
    BlockExecutionResult,
    execute_block_body,
)
from src.executor.payload import validate_execution_payload
from src.kernel import environment

def validate_executed_block(block: Block, result: BlockExecutionResult) -> None:
    execution_profile = environment.k_execution_profile
    profile = execution_profile.protocol
    header = block.header
    validation_debug_capture_block_gas(result.header_gas_used, header.gas_used, result.execution_gas_used, result.state_gas_used)
    if ((result.header_gas_used) != (header.gas_used)):
        fatal_error(FatalError.InvalidGasUsed)
    if (((int(profile.fork) >= int(Cancun))) & (((result.blob_gas_used) != (header.blob_gas_used)))):
        fatal_error(FatalError.InvalidBlobGasUsed)
    poststate = compute_state_root()
    if ((poststate) != (header.state_root)):
        fatal_error(FatalError.InvalidStateRoot)
    if ((result.receipts_root) != (header.receipts_root)):
        fatal_error(FatalError.InvalidReceiptsRoot)
    logs_bloom_matches = block_logs_bloom_matches(result.logs, header.logs_bloom)
    logs_bloom_mismatch = (not (logs_bloom_matches))
    if logs_bloom_mismatch:
        fatal_error(FatalError.InvalidLogsBloom)
    if (int(profile.fork) >= int(Amsterdam)):
        return validate_block_access_list(block.body.block_access_list, execution_profile.gas.block_limit)
    else:
        return None

def verify_stateless_payload(input_ref: StatelessInputRef) -> None:
    scratch_reset()
    input = decode_stateless_input(input_ref)
    witness = index_execution_witness(input_ref)
    validate_execution_payload(input, input_ref, witness)
    block = input.payload.block
    result = execute_block_body(block.body, input_ref)
    return validate_executed_block(block, result)

VALIDATION_STAGE_DECODE_INPUT: int = 1

VALIDATION_STAGE_INDEX_WITNESS: int = 2

VALIDATION_STAGE_VALIDATE_PAYLOAD: int = 3

VALIDATION_STAGE_EXECUTE_BLOCK: int = 4

VALIDATION_STAGE_VALIDATE_RESULT: int = 5
