# Generated by Sail's Python backend. Do not edit by hand.
# Sail source: host/code.sail
from __future__ import annotations

from .._runtime import (
    Bits,
    Bytes32,
    SailError,
)
from evm.HostContract import (
    code_db_lookup as _host_code_db_lookup,
    code_db_store as _host_code_db_store,
    code_region_from_input as _host_code_region_from_input,
    code_region_from_memory as _host_code_region_from_memory,
    code_region_from_output as _host_code_region_from_output,
    jumpdest_table_alloc as _host_jumpdest_table_alloc,
    jumpdest_table_mark as _host_jumpdest_table_mark,
)
from evm.prelude import hash
from evm.primitives.bytes import (
    EvmMemorySlice,
    OutputSlice,
    StatelessInputSlice,
)
from evm.exceptions import (
    FatalError,
    fatal_error,
)
from evm.primitives.code import (
    Code,
    CodeSlice,
    jump_table_index,
    validated_code_slice,
    deep_stack_operation,
    deep_stack_operation_immediate_valid,
    analyzed_code,
    EMPTY_JUMP_TABLE,
    EMPTY_CODE,
)
from evm.host.region_access import code_slice_byte
from evm.primitives.crypto import KECCAK_EMPTY
from evm.primitives.fork import (
    Fork,
    Amsterdam,
)

def analyze_code_from(code: CodeSlice, fork: Fork, table: jump_table_index, pc: int) -> None:
    position = pc
    code_len = code.len
    if (int(position) < int(code_len)):
        opcode_ = code_slice_byte(code, position)
        if ((opcode_) == (Bits(8, 0b01011011))):
            marked = _host_jumpdest_table_mark(table, code_len, position)
            if not (marked):
                raise SailError("JUMPDEST mark")
        opcode_value = int(opcode_)
        if (((96 <= int(opcode_value))) & ((int(opcode_value) <= 127))):
            step = (int(opcode_value) - 94)
        else:
            if (int(fork) >= int(Amsterdam)):
                operation = deep_stack_operation(opcode_value)
                immediate = code_slice_byte(code, (int(position) + 1))
                immediate_valid = deep_stack_operation_immediate_valid(operation, immediate)
                if immediate_valid:
                    step = 2
                else:
                    step = 1
            else:
                step = 1
        if (int(step) < int((int(code_len) - int(position)))):
            added = (int(position) + int(step))
            return analyze_code_from(code, fork, table, added)
        else:
            return None
    else:
        return None

def analyze_code(code: CodeSlice, fork: Fork) -> jump_table_index:
    if ((code.len) == (0)):
        return jump_table_index(EMPTY_JUMP_TABLE)
    else:
        table = _host_jumpdest_table_alloc(code)
        if not (((table) != (EMPTY_JUMP_TABLE))):
            raise SailError("JUMPDEST table allocation")
        analyze_code_from(code, fork, table, 0)
        return jump_table_index(table)

def code_db_insert(code: CodeSlice, fork: Fork) -> hash:
    jumpdest_table = analyze_code(code, fork)
    analyzed = analyzed_code(code, jumpdest_table)
    return Bytes32(_host_code_db_store(analyzed))

def code_db_intern_input(bytes: StatelessInputSlice) -> CodeSlice:
    region = _host_code_region_from_input(bytes)
    return validated_code_slice(region)

def code_db_intern_memory(bytes: EvmMemorySlice) -> CodeSlice:
    region = _host_code_region_from_memory(bytes)
    return validated_code_slice(region)

def code_db_intern_output(bytes: OutputSlice) -> CodeSlice:
    region = _host_code_region_from_output(bytes)
    return validated_code_slice(region)

def code_db_resolve(code_hash: hash) -> Code:
    if ((code_hash) == (KECCAK_EMPTY)):
        return EMPTY_CODE
    else:
        code = _host_code_db_lookup(code_hash)
        if ((code.len) == (0)):
            return fatal_error(FatalError.WitnessDeficient)
        else:
            return code
