# Generated by Sail's Python backend. Do not edit by hand.
# Sail source: prelude.sail
from __future__ import annotations

from ._runtime import (
    BitWidth,
    Bits,
    BoundedUint,
    Bytes20,
    Bytes32,
    U256,
    U64,
    U8,
    Unsigned,
    sail_range,
    sail_tdiv_int,
    sail_tmod_int,
    sail_vector_access,
    sail_vector_append,
    sail_vector_init,
    sail_vector_update,
)
from dataclasses import dataclass
from typing import Annotated, TypeAlias
from evm._sail.flow import (
    bit,
    neq_bool,
)

byte: TypeAlias = Annotated[Bits, BitWidth(8)]

word: TypeAlias = U256

def u256(value: int) -> word:
    return word(value)

address: TypeAlias = Bytes20

def Address(bytes: address) -> address:
    return Bytes20(bytes)

b256: TypeAlias = Bytes32

def B256(bytes: hash) -> hash:
    return Bytes32(bytes)

hash: TypeAlias = Bytes32

_AddressResult_address_type: TypeAlias = address
@dataclass(slots=True)
class AddressResult:
    success: bool
    address: _AddressResult_address_type

class word_bit_count(Unsigned):
    LOWER = 0
    UPPER = 256

    def _in_range(self, value: int) -> bool:
        return self.LOWER <= value <= self.UPPER

def hash_to_word(bytes: hash) -> word:
    return word(int(sail_vector_append(sail_vector_access(bytes, 0, False), sail_vector_append(sail_vector_access(bytes, 1, False), sail_vector_append(sail_vector_access(bytes, 2, False), sail_vector_append(sail_vector_access(bytes, 3, False), sail_vector_append(sail_vector_access(bytes, 4, False), sail_vector_append(sail_vector_access(bytes, 5, False), sail_vector_append(sail_vector_access(bytes, 6, False), sail_vector_append(sail_vector_access(bytes, 7, False), sail_vector_append(sail_vector_access(bytes, 8, False), sail_vector_append(sail_vector_access(bytes, 9, False), sail_vector_append(sail_vector_access(bytes, 10, False), sail_vector_append(sail_vector_access(bytes, 11, False), sail_vector_append(sail_vector_access(bytes, 12, False), sail_vector_append(sail_vector_access(bytes, 13, False), sail_vector_append(sail_vector_access(bytes, 14, False), sail_vector_append(sail_vector_access(bytes, 15, False), sail_vector_append(sail_vector_access(bytes, 16, False), sail_vector_append(sail_vector_access(bytes, 17, False), sail_vector_append(sail_vector_access(bytes, 18, False), sail_vector_append(sail_vector_access(bytes, 19, False), sail_vector_append(sail_vector_access(bytes, 20, False), sail_vector_append(sail_vector_access(bytes, 21, False), sail_vector_append(sail_vector_access(bytes, 22, False), sail_vector_append(sail_vector_access(bytes, 23, False), sail_vector_append(sail_vector_access(bytes, 24, False), sail_vector_append(sail_vector_access(bytes, 25, False), sail_vector_append(sail_vector_access(bytes, 26, False), sail_vector_append(sail_vector_access(bytes, 27, False), sail_vector_append(sail_vector_access(bytes, 28, False), sail_vector_append(sail_vector_access(bytes, 29, False), sail_vector_append(sail_vector_access(bytes, 30, False), sail_vector_access(bytes, 31, False))))))))))))))))))))))))))))))))))

def word_to_hash(value: word) -> hash:
    result = B256(sail_vector_init(32, Bits(8, 0b00000000)))
    result = Bytes32(sail_vector_update(result, 0, Bits(8, int(value) >> 248), False))
    result = Bytes32(sail_vector_update(result, 1, Bits(8, int(value) >> 240), False))
    result = Bytes32(sail_vector_update(result, 2, Bits(8, int(value) >> 232), False))
    result = Bytes32(sail_vector_update(result, 3, Bits(8, int(value) >> 224), False))
    result = Bytes32(sail_vector_update(result, 4, Bits(8, int(value) >> 216), False))
    result = Bytes32(sail_vector_update(result, 5, Bits(8, int(value) >> 208), False))
    result = Bytes32(sail_vector_update(result, 6, Bits(8, int(value) >> 200), False))
    result = Bytes32(sail_vector_update(result, 7, Bits(8, int(value) >> 192), False))
    result = Bytes32(sail_vector_update(result, 8, Bits(8, int(value) >> 184), False))
    result = Bytes32(sail_vector_update(result, 9, Bits(8, int(value) >> 176), False))
    result = Bytes32(sail_vector_update(result, 10, Bits(8, int(value) >> 168), False))
    result = Bytes32(sail_vector_update(result, 11, Bits(8, int(value) >> 160), False))
    result = Bytes32(sail_vector_update(result, 12, Bits(8, int(value) >> 152), False))
    result = Bytes32(sail_vector_update(result, 13, Bits(8, int(value) >> 144), False))
    result = Bytes32(sail_vector_update(result, 14, Bits(8, int(value) >> 136), False))
    result = Bytes32(sail_vector_update(result, 15, Bits(8, int(value) >> 128), False))
    result = Bytes32(sail_vector_update(result, 16, Bits(8, int(value) >> 120), False))
    result = Bytes32(sail_vector_update(result, 17, Bits(8, int(value) >> 112), False))
    result = Bytes32(sail_vector_update(result, 18, Bits(8, int(value) >> 104), False))
    result = Bytes32(sail_vector_update(result, 19, Bits(8, int(value) >> 96), False))
    result = Bytes32(sail_vector_update(result, 20, Bits(8, int(value) >> 88), False))
    result = Bytes32(sail_vector_update(result, 21, Bits(8, int(value) >> 80), False))
    result = Bytes32(sail_vector_update(result, 22, Bits(8, int(value) >> 72), False))
    result = Bytes32(sail_vector_update(result, 23, Bits(8, int(value) >> 64), False))
    result = Bytes32(sail_vector_update(result, 24, Bits(8, int(value) >> 56), False))
    result = Bytes32(sail_vector_update(result, 25, Bits(8, int(value) >> 48), False))
    result = Bytes32(sail_vector_update(result, 26, Bits(8, int(value) >> 40), False))
    result = Bytes32(sail_vector_update(result, 27, Bits(8, int(value) >> 32), False))
    result = Bytes32(sail_vector_update(result, 28, Bits(8, int(value) >> 24), False))
    result = Bytes32(sail_vector_update(result, 29, Bits(8, int(value) >> 16), False))
    result = Bytes32(sail_vector_update(result, 30, Bits(8, int(value) >> 8), False))
    result = Bytes32(sail_vector_update(result, 31, Bits(8, int(value) >> 0), False))
    return Bytes32(result)

def word_to_address(value: word) -> address:
    result = Address(sail_vector_init(20, Bits(8, 0b00000000)))
    result = Bytes20(sail_vector_update(result, 0, Bits(8, int(value) >> 152), False))
    result = Bytes20(sail_vector_update(result, 1, Bits(8, int(value) >> 144), False))
    result = Bytes20(sail_vector_update(result, 2, Bits(8, int(value) >> 136), False))
    result = Bytes20(sail_vector_update(result, 3, Bits(8, int(value) >> 128), False))
    result = Bytes20(sail_vector_update(result, 4, Bits(8, int(value) >> 120), False))
    result = Bytes20(sail_vector_update(result, 5, Bits(8, int(value) >> 112), False))
    result = Bytes20(sail_vector_update(result, 6, Bits(8, int(value) >> 104), False))
    result = Bytes20(sail_vector_update(result, 7, Bits(8, int(value) >> 96), False))
    result = Bytes20(sail_vector_update(result, 8, Bits(8, int(value) >> 88), False))
    result = Bytes20(sail_vector_update(result, 9, Bits(8, int(value) >> 80), False))
    result = Bytes20(sail_vector_update(result, 10, Bits(8, int(value) >> 72), False))
    result = Bytes20(sail_vector_update(result, 11, Bits(8, int(value) >> 64), False))
    result = Bytes20(sail_vector_update(result, 12, Bits(8, int(value) >> 56), False))
    result = Bytes20(sail_vector_update(result, 13, Bits(8, int(value) >> 48), False))
    result = Bytes20(sail_vector_update(result, 14, Bits(8, int(value) >> 40), False))
    result = Bytes20(sail_vector_update(result, 15, Bits(8, int(value) >> 32), False))
    result = Bytes20(sail_vector_update(result, 16, Bits(8, int(value) >> 24), False))
    result = Bytes20(sail_vector_update(result, 17, Bits(8, int(value) >> 16), False))
    result = Bytes20(sail_vector_update(result, 18, Bits(8, int(value) >> 8), False))
    result = Bytes20(sail_vector_update(result, 19, Bits(8, int(value) >> 0), False))
    return Bytes20(result)

def word_add_word(left: int, right: int) -> word:
    return word(u256(sail_tmod_int((int(left) + int(right)), (1 << 256))))

def word_sub_word(left: int, right: int) -> word:
    if (int(right) <= int(left)):
        return word((int(left) - int(right)))
    else:
        maximum = (int((1 << 256)) - 1)
        return word((int((int(maximum) - int((int(right) - int(left))))) + 1))

def word_and(left: word, right: word) -> word:
    return word(u256(int(((Bits(256, int(left) >> 0)) & (Bits(256, int(right) >> 0))))))

def word_or(left: word, right: word) -> word:
    return word(u256(int(((Bits(256, int(left) >> 0)) | (Bits(256, int(right) >> 0))))))

def word_xor(left: word, right: word) -> word:
    return word(u256(int(((Bits(256, int(left) >> 0)) ^ (Bits(256, int(right) >> 0))))))

def word_not(value: word) -> word:
    return word(u256(int((~(Bits(256, int(value) >> 0))))))

def word_bit(value: word, index: U8) -> bit:
    return sail_vector_access(Bits(256, int(value) >> 0), index, False)

def word_low_byte(value: int) -> Annotated[Bits, BitWidth(8)]:
    return Bits(8, int(value) >> 0)

def word_shift_right_one(value: word) -> word:
    return word(u256(sail_tdiv_int(value, 2)))

def word_of_bool(b: bool) -> word:
    if b:
        return word(WORD_ONE)
    else:
        return word(WORD_ZERO)

def word_is_zero(w: int) -> bool:
    return ((w) == (WORD_ZERO))

def word_nonzero(w: int) -> bool:
    return (not (word_is_zero(w)))

def word_ult(a: int, b: int) -> bool:
    return (int(a) < int(b))

def word_ule(a: int, b: int) -> bool:
    return (not (word_ult(b, a)))

def u64_bit_length(value: U64) -> BoundedUint[0, 64]:
    leading = (Bits(64, int(value) >> 0)).count_leading_zeros()
    return BoundedUint[0, 64]((64 - int(leading)))

def word_bit_length(value: int) -> word_bit_count:
    limb3 = int(Bits(64, int(value) >> 192))
    if ((limb3) != (0)):
        return word_bit_count((192 + int(u64_bit_length(limb3))))
    else:
        limb2 = int(Bits(64, int(value) >> 128))
        if ((limb2) != (0)):
            return word_bit_count((128 + int(u64_bit_length(limb2))))
        else:
            limb1 = int(Bits(64, int(value) >> 64))
            if ((limb1) != (0)):
                return word_bit_count((64 + int(u64_bit_length(limb1))))
            else:
                return word_bit_count(u64_bit_length(int(Bits(64, int(value) >> 0))))

def word_mul_word(a: int, b: int) -> int:
    return sail_tmod_int((int(a) * int(b)), (1 << 256))

def word_div_word(dividend: int, divisor: int) -> word:
    if ((divisor) == (0)):
        return word(WORD_ZERO)
    else:
        return word(u256(sail_tdiv_int(dividend, divisor)))

def word_mod_word(dividend: int, divisor: int) -> word:
    if ((divisor) == (0)):
        return word(WORD_ZERO)
    else:
        return word(u256(sail_tmod_int(dividend, divisor)))

def word_greater_than_word(left: int, right: int) -> bool:
    return (int(left) > int(right))

def word_shift_left(value: word, amount: word_bit_count) -> word:
    return word(u256(int(((Bits(256, int(value) >> 0)) << int(amount)))))

def word_shift_right(value: word, amount: word_bit_count) -> word:
    return word(int(((Bits(256, int(value) >> 0)) >> int(amount))))

def word_byte_length(value: int) -> BoundedUint[0, 32]:
    bit_length = word_bit_length(value)
    if ((bit_length) == (0)):
        return BoundedUint[0, 32](0)
    else:
        return BoundedUint[0, 32](sail_tdiv_int((int(bit_length) + 7), 8))

def word_arithmetic_shift_right(value: word, amount: word_bit_count) -> word:
    shifted = word_shift_right(value, amount)
    if ((word_bit(value, 255)) == (Bits(1, 0b1))):
        sign_fill = word_shift_left(WORD_ALL_ONES, (256 - int(amount)))
        return word(word_or(shifted, sign_fill))
    else:
        return word(shifted)

def address_to_word(bytes: address) -> word:
    return word(int(sail_vector_append(sail_vector_access(bytes, 0, False), sail_vector_append(sail_vector_access(bytes, 1, False), sail_vector_append(sail_vector_access(bytes, 2, False), sail_vector_append(sail_vector_access(bytes, 3, False), sail_vector_append(sail_vector_access(bytes, 4, False), sail_vector_append(sail_vector_access(bytes, 5, False), sail_vector_append(sail_vector_access(bytes, 6, False), sail_vector_append(sail_vector_access(bytes, 7, False), sail_vector_append(sail_vector_access(bytes, 8, False), sail_vector_append(sail_vector_access(bytes, 9, False), sail_vector_append(sail_vector_access(bytes, 10, False), sail_vector_append(sail_vector_access(bytes, 11, False), sail_vector_append(sail_vector_access(bytes, 12, False), sail_vector_append(sail_vector_access(bytes, 13, False), sail_vector_append(sail_vector_access(bytes, 14, False), sail_vector_append(sail_vector_access(bytes, 15, False), sail_vector_append(sail_vector_access(bytes, 16, False), sail_vector_append(sail_vector_access(bytes, 17, False), sail_vector_append(sail_vector_access(bytes, 18, False), sail_vector_access(bytes, 19, False))))))))))))))))))))))

def word_negate(value: word) -> word:
    return word(word_sub_word(WORD_ZERO, value))

def word_abs(value: word) -> word:
    if ((word_bit(value, 255)) == (Bits(1, 0b1))):
        return word(word_negate(value))
    else:
        return word(value)

def word_slt(a: word, b: word) -> bool:
    a_neg = ((word_bit(a, 255)) == (Bits(1, 0b1)))
    b_neg = ((word_bit(b, 255)) == (Bits(1, 0b1)))
    if a_neg:
        if b_neg:
            return word_ult(a, b)
        else:
            return True
    else:
        if b_neg:
            return False
        else:
            return word_ult(a, b)

def alu_add(a: word, b: int) -> word:
    return word(word_add_word(a, b))

def alu_sub(a: word, b: word) -> word:
    return word(word_sub_word(a, b))

def alu_mul(a: int, b: int) -> int:
    return word_mul_word(a, b)

def alu_div(a: word, b: word) -> word:
    return word(word_div_word(a, b))

def alu_mod(a: word, b: word) -> word:
    return word(word_mod_word(a, b))

def alu_sdiv(a: word, b: word) -> word:
    if word_is_zero(b):
        return word(WORD_ZERO)
    else:
        quotient = word_div_word(word_abs(a), word_abs(b))
        if neq_bool(((word_bit(a, 255)) == (Bits(1, 0b1))), ((word_bit(b, 255)) == (Bits(1, 0b1)))):
            return word(word_negate(quotient))
        else:
            return word(quotient)

def alu_smod(a: word, b: word) -> word:
    if word_is_zero(b):
        return word(WORD_ZERO)
    else:
        remainder = word_mod_word(word_abs(a), word_abs(b))
        if ((word_bit(a, 255)) == (Bits(1, 0b1))):
            return word(word_negate(remainder))
        else:
            return word(remainder)

def alu_addmod(a: int, b: int, n: int) -> word:
    if ((n) == (0)):
        return word(WORD_ZERO)
    else:
        return word(u256(sail_tmod_int((int(a) + int(b)), n)))

def alu_mulmod(a: int, b: int, n: int) -> word:
    if ((n) == (0)):
        return word(WORD_ZERO)
    else:
        return word(u256(sail_tmod_int((int(a) * int(b)), n)))

def alu_exp(base: word, exponent: word) -> word:
    result = WORD_ONE
    b = base
    e = exponent
    for _step in sail_range(0, 255, 1, True):
        if ((word_bit(e, 0)) == (Bits(1, 0b1))):
            result = word_mul_word(result, b)
        b = word_mul_word(b, b)
        e = word(word_shift_right_one(e))
    return word(result)

def alu_signextend(byte_index: word, value: word) -> word:
    if (int(byte_index) < 32):
        index = byte_index
        width = (int((int(index) * 8)) + 8)
        sign_shift = (int((int(index) * 8)) + 7)
        sign_set = ((word_and(word_shift_right(value, sign_shift), WORD_ONE)) == (WORD_ONE))
        low_mask = word_sub_word(word_shift_left(WORD_ONE, width), WORD_ONE)
        if sign_set:
            return word(word_or(word_and(value, low_mask), word_not(low_mask)))
        else:
            return word(word_and(value, low_mask))
    else:
        return word(value)

def alu_lt(a: word, b: word) -> word:
    return word(word_of_bool(word_ult(a, b)))

def alu_gt(a: word, b: word) -> word:
    return word(word_of_bool(word_ult(b, a)))

def alu_slt(a: word, b: word) -> word:
    return word(word_of_bool(word_slt(a, b)))

def alu_sgt(a: word, b: word) -> word:
    return word(word_of_bool(word_slt(b, a)))

def alu_eq(a: word, b: word) -> word:
    return word(word_of_bool(((a) == (b))))

def alu_iszero(a: word) -> word:
    return word(word_of_bool(word_is_zero(a)))

def alu_and(a: word, b: word) -> word:
    return word(word_and(a, b))

def alu_or(a: word, b: word) -> word:
    return word(word_or(a, b))

def alu_xor(a: word, b: word) -> word:
    return word(word_xor(a, b))

def alu_not(a: word) -> word:
    return word(word_not(a))

def alu_byte(i: word, x: word) -> word:
    if (int(i) < 32):
        index = i
        shift = (int((31 - int(index))) * 8)
        return word(int(word_low_byte(word_shift_right(x, shift))))
    else:
        return word(WORD_ZERO)

def alu_shl(shift_amt: word, v: word) -> word:
    if (int(shift_amt) < 256):
        return word(word_shift_left(v, shift_amt))
    else:
        return word(WORD_ZERO)

def alu_shr(shift_amt: word, v: word) -> word:
    if (int(shift_amt) < 256):
        return word(word_shift_right(v, shift_amt))
    else:
        return word(WORD_ZERO)

def alu_sar(shift_amt: word, v: word) -> word:
    if (int(shift_amt) < 256):
        return word(word_arithmetic_shift_right(v, shift_amt))
    else:
        if ((word_bit(v, 255)) == (Bits(1, 0b1))):
            return word(WORD_ALL_ONES)
        else:
            return word(WORD_ZERO)

def alu_clz(x: word) -> word:
    return word(u256((256 - int(word_bit_length(x)))))

ZERO_WORD: int = u256(int(Bits(256, 0b0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000)))

ZERO_ADDRESS: address = Bytes20(Address(sail_vector_init(20, Bits(8, 0b00000000))))

ZERO_HASH: hash = Bytes32(B256(sail_vector_init(32, Bits(8, 0b00000000))))

WORD_ZERO: int = u256(int(Bits(256, 0b0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000)))

WORD_ONE: int = u256(int(Bits(256, 0b0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001)))

WORD_ALL_ONES: int = u256(int(Bits(256, 0b1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111)))

WORD_SIGN_BIT: int = u256(int(Bits(256, 0b1000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000)))
