# Generated by Sail's Python backend. Do not edit by hand.
# Sail source: evm/precompiles.sail
from __future__ import annotations

from .._runtime import (
    Bits,
    Bytes20,
    Bytes32,
    IntegerRange,
    SailMatchFailure,
    sail_ediv_int,
    sail_tmod_int,
    sail_vector_update,
)
from dataclasses import dataclass
from typing import Annotated
from evm.HostContract import (
    accelerator_blake2f as _host_accelerator_blake2f,
    accelerator_bls_g1_add as _host_accelerator_bls_g1_add,
    accelerator_bls_g1_msm as _host_accelerator_bls_g1_msm,
    accelerator_bls_g2_add as _host_accelerator_bls_g2_add,
    accelerator_bls_g2_msm as _host_accelerator_bls_g2_msm,
    accelerator_bls_map_fp2_to_g2 as _host_accelerator_bls_map_fp2_to_g2,
    accelerator_bls_map_fp_to_g1 as _host_accelerator_bls_map_fp_to_g1,
    accelerator_bls_pairing as _host_accelerator_bls_pairing,
    accelerator_bn254_add as _host_accelerator_bn254_add,
    accelerator_bn254_mul as _host_accelerator_bn254_mul,
    accelerator_bn254_pairing as _host_accelerator_bn254_pairing,
    accelerator_kzg_point_evaluation as _host_accelerator_kzg_point_evaluation,
    accelerator_modexp as _host_accelerator_modexp,
    accelerator_p256_verify as _host_accelerator_p256_verify,
    accelerator_ripemd160 as _host_accelerator_ripemd160,
)
from evm._sail.vector import neq_bits
from evm.prelude import (
    address,
    u256,
    hash_to_word,
    word_from_bits,
    word_to_hash,
    address_from_nat,
    address_to_word,
    WORD_ZERO,
    WORD_ONE,
)
from evm.primitives.quantities import (
    PrecompileId,
    precompile_id,
)
from evm.primitives.bytes import (
    CalldataSlice,
    OutputSlice,
    calldata_slice_length,
    calldata_sub_slice,
    WORD_BYTE_LENGTH,
    DOUBLE_WORD_BYTE_LENGTH,
    EMPTY_OUTPUT_SLICE,
)
from evm.host.accelerators import pairing_check_result
from evm.host.region_access import (
    calldata_slice_byte,
    slice_strided_zero,
    calldata_slice_load,
)
from evm.primitives.crypto import (
    calldata_sha256,
    ecrecover_addr,
)
from evm.primitives.fork import (
    Byzantium,
    Istanbul,
    Cancun,
    Prague,
    Osaka,
)
from evm.host.output import (
    output_buffer_slice,
    freeze_calldata_output,
    output_buffer_word,
    output_buffer_words,
)
from evm.evm.gas import (
    pc_word,
    pc_blake2_rounds,
)
from evm.kernel import environment

@dataclass(slots=True)
class PrecompileResult:
    success: bool
    output: OutputSlice

def precompile_success(output: OutputSlice) -> PrecompileResult:
    return PrecompileResult(success=True, output=output)

def precompile_failure() -> PrecompileResult:
    return PrecompileResult(success=False, output=EMPTY_OUTPUT_SLICE)

def accelerator_result(success: bool, output_len: int) -> PrecompileResult:
    if success:
        output = output_buffer_slice(output_len)
        return precompile_success(output)
    else:
        return precompile_failure()

def copied_result(data: CalldataSlice) -> PrecompileResult:
    output = freeze_calldata_output(data)
    input_length = calldata_slice_length(data)
    if ((output.len) == (input_length)):
        return precompile_success(output)
    else:
        return precompile_failure()

def boolean_result(value: bool) -> PrecompileResult:
    if value:
        result_word = WORD_ONE
    else:
        result_word = WORD_ZERO
    output = output_buffer_word(result_word)
    return precompile_success(output)

def precompile_active_at_fork(n: precompile_id) -> bool:
    execution_profile = environment.k_execution_profile
    profile = execution_profile.protocol
    match n:
        case PrecompileId.NotPrecompile:
            return False
        case PrecompileId.Ecrecover:
            return True
        case PrecompileId.Sha256:
            return True
        case PrecompileId.Ripemd160:
            return True
        case PrecompileId.Identity:
            return True
        case PrecompileId.Modexp:
            return (int(profile.fork) >= int(Byzantium))
        case PrecompileId.Bn254Add:
            return (int(profile.fork) >= int(Byzantium))
        case PrecompileId.Bn254Mul:
            return (int(profile.fork) >= int(Byzantium))
        case PrecompileId.Bn254Pairing:
            return (int(profile.fork) >= int(Byzantium))
        case PrecompileId.Blake2f:
            return (int(profile.fork) >= int(Istanbul))
        case PrecompileId.KzgPointEvaluation:
            return (int(profile.fork) >= int(Cancun))
        case PrecompileId.BlsG1Add:
            return (int(profile.fork) >= int(Prague))
        case PrecompileId.BlsG1Msm:
            return (int(profile.fork) >= int(Prague))
        case PrecompileId.BlsG2Add:
            return (int(profile.fork) >= int(Prague))
        case PrecompileId.BlsG2Msm:
            return (int(profile.fork) >= int(Prague))
        case PrecompileId.BlsPairing:
            return (int(profile.fork) >= int(Prague))
        case PrecompileId.BlsMapFpToG1:
            return (int(profile.fork) >= int(Prague))
        case PrecompileId.BlsMapFp2ToG2:
            return (int(profile.fork) >= int(Prague))
        case PrecompileId.P256Verify:
            return (int(profile.fork) >= int(Osaka))
        case _:
            raise SailMatchFailure("no Sail match clause applied")

def precompile_id_if_active(candidate: precompile_id) -> precompile_id:
    active = precompile_active_at_fork(candidate)
    if active:
        return candidate
    else:
        return PrecompileId.NotPrecompile

def precompile_id_for_address(bytes: address) -> precompile_id:
    match bytes:
        case _ if ((bytes) == (PRECOMPILE_ADDRESS_1)):
            return precompile_id_if_active(PrecompileId.Ecrecover)
        case _ if ((bytes) == (PRECOMPILE_ADDRESS_2)):
            return precompile_id_if_active(PrecompileId.Sha256)
        case _ if ((bytes) == (PRECOMPILE_ADDRESS_3)):
            return precompile_id_if_active(PrecompileId.Ripemd160)
        case _ if ((bytes) == (PRECOMPILE_ADDRESS_4)):
            return precompile_id_if_active(PrecompileId.Identity)
        case _ if ((bytes) == (PRECOMPILE_ADDRESS_5)):
            return precompile_id_if_active(PrecompileId.Modexp)
        case _ if ((bytes) == (PRECOMPILE_ADDRESS_6)):
            return precompile_id_if_active(PrecompileId.Bn254Add)
        case _ if ((bytes) == (PRECOMPILE_ADDRESS_7)):
            return precompile_id_if_active(PrecompileId.Bn254Mul)
        case _ if ((bytes) == (PRECOMPILE_ADDRESS_8)):
            return precompile_id_if_active(PrecompileId.Bn254Pairing)
        case _ if ((bytes) == (PRECOMPILE_ADDRESS_9)):
            return precompile_id_if_active(PrecompileId.Blake2f)
        case _ if ((bytes) == (PRECOMPILE_ADDRESS_10)):
            return precompile_id_if_active(PrecompileId.KzgPointEvaluation)
        case _ if ((bytes) == (PRECOMPILE_ADDRESS_11)):
            return precompile_id_if_active(PrecompileId.BlsG1Add)
        case _ if ((bytes) == (PRECOMPILE_ADDRESS_12)):
            return precompile_id_if_active(PrecompileId.BlsG1Msm)
        case _ if ((bytes) == (PRECOMPILE_ADDRESS_13)):
            return precompile_id_if_active(PrecompileId.BlsG2Add)
        case _ if ((bytes) == (PRECOMPILE_ADDRESS_14)):
            return precompile_id_if_active(PrecompileId.BlsG2Msm)
        case _ if ((bytes) == (PRECOMPILE_ADDRESS_15)):
            return precompile_id_if_active(PrecompileId.BlsPairing)
        case _ if ((bytes) == (PRECOMPILE_ADDRESS_16)):
            return precompile_id_if_active(PrecompileId.BlsMapFpToG1)
        case _ if ((bytes) == (PRECOMPILE_ADDRESS_17)):
            return precompile_id_if_active(PrecompileId.BlsMapFp2ToG2)
        case _ if ((bytes) == (PRECOMPILE_ADDRESS_256)):
            return precompile_id_if_active(PrecompileId.P256Verify)
        case _:
            return PrecompileId.NotPrecompile

def run_ecrecover(input: CalldataSlice) -> PrecompileResult:
    v = calldata_slice_load(input, PRECOMPILE_WORD_OFFSET)
    v_27 = u256(27)
    v_28 = u256(28)
    valid_v = ((((v) == (v_27))) | (((v) == (v_28))))
    if valid_v:
        if ((v) == (v_27)):
            parity = 0
        else:
            parity = 1
        message_word = calldata_slice_load(input, 0)
        message_hash = word_to_hash(message_word)
        r = calldata_slice_load(input, PRECOMPILE_DOUBLE_WORD_OFFSET)
        s = calldata_slice_load(input, ECRECOVER_S_OFFSET)
        (recovered, address_) = ecrecover_addr(message_hash, parity, r, s)
        if recovered:
            address_word = address_to_word(address_)
            output = output_buffer_word(address_word)
            return precompile_success(output)
        else:
            return precompile_success(EMPTY_OUTPUT_SLICE)
    else:
        return precompile_success(EMPTY_OUTPUT_SLICE)

def run_sha256(input: CalldataSlice) -> PrecompileResult:
    digest = calldata_sha256(input)
    digest_word = hash_to_word(digest)
    output = output_buffer_word(digest_word)
    return precompile_success(output)

def run_ripemd160(input: CalldataSlice) -> PrecompileResult:
    success = _host_accelerator_ripemd160(input)
    return accelerator_result(success, PRECOMPILE_WORD_LENGTH)

def run_modexp(input: CalldataSlice) -> PrecompileResult:
    base_len = pc_word(input, 0, 32)
    exponent_len = pc_word(input, 32, 32)
    modulus_len = pc_word(input, 64, 32)
    if ((modulus_len) == (0)):
        return precompile_success(EMPTY_OUTPUT_SLICE)
    else:
        if (((int(ACCELERATOR_INPUT_MAX) < int(base_len))) | ((((int(ACCELERATOR_INPUT_MAX) < int(exponent_len))) | ((int(ACCELERATOR_INPUT_MAX) < int(modulus_len)))))):
            return precompile_failure()
        else:
            bounded_base = base_len
            bounded_exponent = exponent_len
            bounded_modulus = modulus_len
            input_end = (int((int((96 + int(bounded_base))) + int(bounded_exponent))) + int(bounded_modulus))
            if (int(ACCELERATOR_INPUT_MAX) < int(input_end)):
                return precompile_failure()
            else:
                success = _host_accelerator_modexp(input, bounded_base, bounded_exponent, bounded_modulus)
                return accelerator_result(success, bounded_modulus)

def pairing_result(result: pairing_check_result) -> PrecompileResult:
    if (int(result) < 2):
        return precompile_failure()
    else:
        parity = sail_tmod_int(result, 2)
        return boolean_result(((parity) == (1)))

def run_blake2f(input: CalldataSlice) -> PrecompileResult:
    final_byte = calldata_slice_byte(input, BLAKE2F_FINAL_BLOCK_OFFSET)
    input_length = calldata_slice_length(input)
    if ((((input_length) != (BLAKE2F_INPUT_LENGTH))) | (((neq_bits(final_byte, Bits(8, 0b00000000))) & (neq_bits(final_byte, Bits(8, 0b00000001)))))):
        return precompile_failure()
    else:
        if ((final_byte) == (Bits(8, 0b00000000))):
            final_block = 0
        else:
            final_block = 1
        rounds = pc_blake2_rounds(input)
        success = _host_accelerator_blake2f(input, rounds, final_block)
        return accelerator_result(success, BLAKE2F_OUTPUT_LENGTH)

def kzg_versioned_hash_matches(input: CalldataSlice) -> bool:
    commitment = calldata_sub_slice(input, KZG_COMMITMENT_OFFSET, KZG_COMMITMENT_LENGTH)
    commitment_hash = calldata_sha256(commitment)
    expected = commitment_hash
    expected = Bytes32(sail_vector_update(expected, 0, Bits(8, 0b00000001), False))
    claimed_word = calldata_slice_load(input, 0)
    claimed_hash = word_to_hash(claimed_word)
    return ((claimed_hash) == (expected))

def run_kzg_point_evaluation(input: CalldataSlice) -> PrecompileResult:
    input_length = calldata_slice_length(input)
    if ((input_length) != (KZG_INPUT_LENGTH)):
        return precompile_failure()
    else:
        versioned_hash_matches = kzg_versioned_hash_matches(input)
        invalid_versioned_hash = (not (versioned_hash_matches))
        if invalid_versioned_hash:
            return precompile_failure()
        else:
            valid_proof = _host_accelerator_kzg_point_evaluation(input)
            if valid_proof:
                output = output_buffer_words(FIELD_ELEMENTS_PER_BLOB, BLS_MODULUS)
                return precompile_success(output)
            else:
                return precompile_failure()

def bls_g1_padding(input: CalldataSlice, base: int, stride: int, count: int) -> bool:
    return ((slice_strided_zero(input, base, stride, BLS_FIELD_PADDING_LENGTH, count)) & (slice_strided_zero(input, (int(base) + int(BLS_PADDED_FIELD_LENGTH)), stride, BLS_FIELD_PADDING_LENGTH, count)))

def bls_g2_padding(input: CalldataSlice, base: int, stride: int, count: int) -> bool:
    return ((slice_strided_zero(input, base, stride, BLS_FIELD_PADDING_LENGTH, count)) & (((slice_strided_zero(input, (int(base) + int(BLS_PADDED_FIELD_LENGTH)), stride, BLS_FIELD_PADDING_LENGTH, count)) & (((slice_strided_zero(input, (int(base) + int(BLS_G1_POINT_LENGTH)), stride, BLS_FIELD_PADDING_LENGTH, count)) & (slice_strided_zero(input, (int(base) + int(BLS_G2_FINAL_FIELD_OFFSET)), stride, BLS_FIELD_PADDING_LENGTH, count)))))))

def run_bls_g1_add(input: CalldataSlice) -> PrecompileResult:
    input_length = calldata_slice_length(input)
    if ((input_length) != (BLS_G1_ADD_INPUT_LENGTH)):
        return precompile_failure()
    else:
        valid_padding = bls_g1_padding(input, 0, BLS_G1_POINT_LENGTH, TWO_COMPONENTS)
        invalid_padding = (not (valid_padding))
        if invalid_padding:
            return precompile_failure()
        else:
            success = _host_accelerator_bls_g1_add(input)
            return accelerator_result(success, BLS_G1_POINT_LENGTH)

def run_bls_g1_msm(input: CalldataSlice) -> PrecompileResult:
    length = calldata_slice_length(input)
    item_length = BLS_G1_MSM_ITEM_LENGTH
    pairs = sail_ediv_int(length, item_length)
    if ((((length) == (0))) | (((length) != ((int(pairs) * int(item_length)))))):
        return precompile_failure()
    else:
        valid_padding = bls_g1_padding(input, 0, BLS_G1_MSM_ITEM_LENGTH, pairs)
        invalid_padding = (not (valid_padding))
        if invalid_padding:
            return precompile_failure()
        else:
            success = _host_accelerator_bls_g1_msm(input)
            return accelerator_result(success, BLS_G1_POINT_LENGTH)

def run_bls_g2_add(input: CalldataSlice) -> PrecompileResult:
    input_length = calldata_slice_length(input)
    if ((input_length) != (BLS_G2_ADD_INPUT_LENGTH)):
        return precompile_failure()
    else:
        valid_padding = bls_g2_padding(input, 0, BLS_G2_POINT_LENGTH, TWO_COMPONENTS)
        invalid_padding = (not (valid_padding))
        if invalid_padding:
            return precompile_failure()
        else:
            success = _host_accelerator_bls_g2_add(input)
            return accelerator_result(success, BLS_G2_POINT_LENGTH)

def run_bls_g2_msm(input: CalldataSlice) -> PrecompileResult:
    length = calldata_slice_length(input)
    item_length = BLS_G2_MSM_ITEM_LENGTH
    pairs = sail_ediv_int(length, item_length)
    if ((((length) == (0))) | (((length) != ((int(pairs) * int(item_length)))))):
        return precompile_failure()
    else:
        valid_padding = bls_g2_padding(input, 0, BLS_G2_MSM_ITEM_LENGTH, pairs)
        invalid_padding = (not (valid_padding))
        if invalid_padding:
            return precompile_failure()
        else:
            success = _host_accelerator_bls_g2_msm(input)
            return accelerator_result(success, BLS_G2_POINT_LENGTH)

def run_bls_pairing(input: CalldataSlice) -> PrecompileResult:
    length = calldata_slice_length(input)
    item_length = BLS_PAIRING_ITEM_LENGTH
    pairs = sail_ediv_int(length, item_length)
    if ((((length) == (0))) | (((length) != ((int(pairs) * int(item_length)))))):
        return precompile_failure()
    else:
        pair_count = pairs
        valid_g1_padding = bls_g1_padding(input, 0, BLS_PAIRING_ITEM_LENGTH, pair_count)
        valid_g2_padding = bls_g2_padding(input, BLS_G2_POINT_OFFSET, BLS_PAIRING_ITEM_LENGTH, pair_count)
        if ((valid_g1_padding) & (valid_g2_padding)):
            result = _host_accelerator_bls_pairing(input)
            return pairing_result(result)
        else:
            return precompile_failure()

def run_bls_map_fp_to_g1(input: CalldataSlice) -> PrecompileResult:
    input_length = calldata_slice_length(input)
    if ((input_length) != (BLS_PADDED_FIELD_LENGTH)):
        return precompile_failure()
    else:
        valid_padding = slice_strided_zero(input, 0, BLS_PADDED_FIELD_LENGTH, BLS_FIELD_PADDING_LENGTH, 1)
        invalid_padding = (not (valid_padding))
        if invalid_padding:
            return precompile_failure()
        else:
            success = _host_accelerator_bls_map_fp_to_g1(input)
            return accelerator_result(success, BLS_G1_POINT_LENGTH)

def run_bls_map_fp2_to_g2(input: CalldataSlice) -> PrecompileResult:
    input_length = calldata_slice_length(input)
    if ((input_length) != (BLS_G1_POINT_LENGTH)):
        return precompile_failure()
    else:
        valid_padding = slice_strided_zero(input, 0, BLS_PADDED_FIELD_LENGTH, BLS_FIELD_PADDING_LENGTH, TWO_COMPONENTS)
        invalid_padding = (not (valid_padding))
        if invalid_padding:
            return precompile_failure()
        else:
            success = _host_accelerator_bls_map_fp2_to_g2(input)
            return accelerator_result(success, BLS_G2_POINT_LENGTH)

def run_p256_verify(input: CalldataSlice) -> PrecompileResult:
    input_length = calldata_slice_length(input)
    if ((input_length) == (P256_INPUT_LENGTH)):
        verified = _host_accelerator_p256_verify(input)
    else:
        verified = False
    if verified:
        output = output_buffer_word(WORD_ONE)
        return precompile_success(output)
    else:
        return precompile_success(EMPTY_OUTPUT_SLICE)

def run_precompile_slice(num: precompile_id, input: CalldataSlice) -> PrecompileResult:
    match num:
        case PrecompileId.NotPrecompile:
            return precompile_failure()
        case PrecompileId.Ecrecover:
            return run_ecrecover(input)
        case PrecompileId.Sha256:
            return run_sha256(input)
        case PrecompileId.Ripemd160:
            return run_ripemd160(input)
        case PrecompileId.Identity:
            return copied_result(input)
        case PrecompileId.Modexp:
            return run_modexp(input)
        case PrecompileId.Bn254Add:
            success = _host_accelerator_bn254_add(input)
            return accelerator_result(success, PRECOMPILE_DOUBLE_WORD_LENGTH)
        case PrecompileId.Bn254Mul:
            success = _host_accelerator_bn254_mul(input)
            return accelerator_result(success, PRECOMPILE_DOUBLE_WORD_LENGTH)
        case PrecompileId.Bn254Pairing:
            input_length = calldata_slice_length(input)
            item_length = BN254_PAIRING_ITEM_LENGTH
            if ((input_length) == ((int(sail_ediv_int(input_length, item_length)) * int(item_length)))):
                result = _host_accelerator_bn254_pairing(input)
                return pairing_result(result)
            else:
                return precompile_failure()
        case PrecompileId.Blake2f:
            return run_blake2f(input)
        case PrecompileId.KzgPointEvaluation:
            return run_kzg_point_evaluation(input)
        case PrecompileId.BlsG1Add:
            return run_bls_g1_add(input)
        case PrecompileId.BlsG1Msm:
            return run_bls_g1_msm(input)
        case PrecompileId.BlsG2Add:
            return run_bls_g2_add(input)
        case PrecompileId.BlsG2Msm:
            return run_bls_g2_msm(input)
        case PrecompileId.BlsPairing:
            return run_bls_pairing(input)
        case PrecompileId.BlsMapFpToG1:
            return run_bls_map_fp_to_g1(input)
        case PrecompileId.BlsMapFp2ToG2:
            return run_bls_map_fp2_to_g2(input)
        case PrecompileId.P256Verify:
            return run_p256_verify(input)
        case _:
            raise SailMatchFailure("no Sail match clause applied")

ACCELERATOR_INPUT_MAX: Annotated[int, IntegerRange(2097152, 2097152)] = 2097152

FIELD_ELEMENTS_PER_BLOB: int = word_from_bits(Bits(256, 0b0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001000000000000))

BLS_MODULUS: int = word_from_bits(Bits(256, 0b0111001111101101101001110101001100101001100111010111110101001000001100110011100111011000000010000000100110100001110110000000010101010011101111011010010000000010111111111111111001011011111111101111111111111111111111111111111100000000000000000000000000000001))

BLAKE2F_INPUT_LENGTH: Annotated[int, IntegerRange(213, 213)] = 213

BLAKE2F_FINAL_BLOCK_OFFSET: Annotated[int, IntegerRange(212, 212)] = 212

BLAKE2F_OUTPUT_LENGTH: Annotated[int, IntegerRange(64, 64)] = DOUBLE_WORD_BYTE_LENGTH

KZG_INPUT_LENGTH: Annotated[int, IntegerRange(192, 192)] = 192

KZG_COMMITMENT_OFFSET: Annotated[int, IntegerRange(96, 96)] = 96

KZG_COMMITMENT_LENGTH: Annotated[int, IntegerRange(48, 48)] = 48

BLS_FIELD_PADDING_LENGTH: Annotated[int, IntegerRange(16, 16)] = 16

BLS_PADDED_FIELD_LENGTH: Annotated[int, IntegerRange(64, 64)] = DOUBLE_WORD_BYTE_LENGTH

BLS_G1_POINT_LENGTH: Annotated[int, IntegerRange(128, 128)] = 128

BLS_G2_POINT_LENGTH: Annotated[int, IntegerRange(256, 256)] = 256

BLS_G2_FINAL_FIELD_OFFSET: Annotated[int, IntegerRange(192, 192)] = 192

BLS_G1_ADD_INPUT_LENGTH: Annotated[int, IntegerRange(256, 256)] = 256

BLS_G1_MSM_ITEM_LENGTH: Annotated[int, IntegerRange(160, 160)] = 160

BLS_G2_ADD_INPUT_LENGTH: Annotated[int, IntegerRange(512, 512)] = 512

BLS_G2_MSM_ITEM_LENGTH: Annotated[int, IntegerRange(288, 288)] = 288

BLS_PAIRING_ITEM_LENGTH: Annotated[int, IntegerRange(384, 384)] = 384

P256_INPUT_LENGTH: Annotated[int, IntegerRange(160, 160)] = 160

BN254_PAIRING_ITEM_LENGTH: Annotated[int, IntegerRange(192, 192)] = 192

PRECOMPILE_WORD_LENGTH: Annotated[int, IntegerRange(32, 32)] = WORD_BYTE_LENGTH

PRECOMPILE_DOUBLE_WORD_LENGTH: Annotated[int, IntegerRange(64, 64)] = DOUBLE_WORD_BYTE_LENGTH

PRECOMPILE_WORD_OFFSET: Annotated[int, IntegerRange(32, 32)] = 32

PRECOMPILE_DOUBLE_WORD_OFFSET: Annotated[int, IntegerRange(64, 64)] = 64

ECRECOVER_S_OFFSET: int = 96

TWO_COMPONENTS: Annotated[int, IntegerRange(2, 2)] = 2

BLS_G2_POINT_OFFSET: Annotated[int, IntegerRange(128, 128)] = 128

PRECOMPILE_ADDRESS_1: address = Bytes20(address_from_nat(1))

PRECOMPILE_ADDRESS_2: address = Bytes20(address_from_nat(2))

PRECOMPILE_ADDRESS_3: address = Bytes20(address_from_nat(3))

PRECOMPILE_ADDRESS_4: address = Bytes20(address_from_nat(4))

PRECOMPILE_ADDRESS_5: address = Bytes20(address_from_nat(5))

PRECOMPILE_ADDRESS_6: address = Bytes20(address_from_nat(6))

PRECOMPILE_ADDRESS_7: address = Bytes20(address_from_nat(7))

PRECOMPILE_ADDRESS_8: address = Bytes20(address_from_nat(8))

PRECOMPILE_ADDRESS_9: address = Bytes20(address_from_nat(9))

PRECOMPILE_ADDRESS_10: address = Bytes20(address_from_nat(10))

PRECOMPILE_ADDRESS_11: address = Bytes20(address_from_nat(11))

PRECOMPILE_ADDRESS_12: address = Bytes20(address_from_nat(12))

PRECOMPILE_ADDRESS_13: address = Bytes20(address_from_nat(13))

PRECOMPILE_ADDRESS_14: address = Bytes20(address_from_nat(14))

PRECOMPILE_ADDRESS_15: address = Bytes20(address_from_nat(15))

PRECOMPILE_ADDRESS_16: address = Bytes20(address_from_nat(16))

PRECOMPILE_ADDRESS_17: address = Bytes20(address_from_nat(17))

PRECOMPILE_ADDRESS_256: address = Bytes20(address_from_nat(256))
